/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <CorePDF/CorePDF-Structs.h>
#import <CorePDF/CPGraphicObject.h>


@interface CPCompoundGraphic : CPGraphicObject {
}
- (id)initWithGraphicObjects:(id)graphicObjects withRenderedBounds:(CGRect)renderedBounds;	// 0x7df9
- (void)accept:(id)accept;	// 0x7e69
@end
