/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <CorePDF/CorePDF-Structs.h>
#import <CorePDF/CPDisposable.h>



@interface CPFontInfo : NSObject <CPDisposable> {
	CFDataRef fontData;	// 4 = 0x4
	char *dataPtr;	// 8 = 0x8
	unsigned offset;	// 12 = 0xc
	unsigned fontDataLength;	// 16 = 0x10
	BOOL valid;	// 20 = 0x14
}
- (id)initWithFontData:(CFDataRef)fontData;	// 0x3b7b1
- (void)dispose;	// 0x3b83d
- (void)finalize;	// 0x3b865
- (void)dealloc;	// 0x3ba55
- (unsigned char)readByte;	// 0x3b661
- (unsigned)readUnsignedLong;	// 0x3b6b1
- (int)readLong;	// 0x3b6fd
- (float)readFloat;	// 0x3b70d
- (CGRect)readRect;	// 0x3b725
- (BOOL)getDescriptor:(XXStruct_FvSZlC *)descriptor;	// 0x3b8f9
- (int)kernUnitsPerEm;	// 0x3b76d
- (CFDataRef)createKernData;	// 0x3b8a5
@end
