/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */



@class NSMutableArray;

@interface CPTextLineMerge : NSObject {
	NSMutableArray *avail;	// 4 = 0x4
}
- (BOOL)fits:(id)fits into:(id)into;	// 0x3491d
- (void)addInterval:(id)interval to:(id)to;	// 0x34ac5
- (void)mergeColumn:(id)column;	// 0x351ed
- (void)mergeLinesInInterval:(id)interval from:(id)from;	// 0x34c61
- (void)mergeByColumn:(id)column;	// 0x35651
- (void)eliminate:(id)eliminate;	// 0x34d4d
- (BOOL)hasOverlappingLines;	// 0x35315
- (void)makeOverlappingLinesTo:(id)to;	// 0x35411
- (void)removeOverlapping:(id)overlapping;	// 0x34df9
- (unsigned)countOverlapsOfLineAtIndex:(unsigned)index in:(id)anIn;	// 0x3554d
- (void)detachDropCaps:(id)caps to:(id)to;	// 0x34e6d
- (id)findLineFor:(id)aFor in:(id)anIn;	// 0x35889
- (float)averageHeight:(id)height;	// 0x35999
- (void)dropCaps:(id)caps to:(id)to;	// 0x35a51
- (void)mergeLinesIn:(id)anIn;	// 0x34ffd
@end
