/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <CorePDF/CorePDF-Structs.h>

#import <CorePDF/NSCopying.h>

@class CPZoneBorder;

@interface CPZoneBorderIntersection : NSObject <NSCopying> {
	CGRect intersectionRect;	// 4 = 0x4
	CPZoneBorder *intersectingBorder;	// 20 = 0x14
	BOOL forwardVector;	// 24 = 0x18
	BOOL backwardVector;	// 25 = 0x19
}
@property(assign) CGRect intersectionRect;	// G=0x48101; S=0x480dd; converted property
@property(retain) CPZoneBorder *intersectingBorder;	// G=0x48135; S=0x48125; converted property
@property(assign) BOOL forwardVector;	// G=0x48155; S=0x48145; converted property
@property(assign) BOOL backwardVector;	// G=0x48175; S=0x48165; converted property
- (id)copyWithZone:(NSZone *)zone;	// 0x4a331
// converted property setter: - (void)setIntersectionRect:(CGRect)rect;	// 0x480dd
// converted property getter: - (CGRect)intersectionRect;	// 0x48101
// converted property setter: - (void)setIntersectingBorder:(id)border;	// 0x48125
// converted property getter: - (id)intersectingBorder;	// 0x48135
// converted property setter: - (void)setForwardVector:(BOOL)vector;	// 0x48145
// converted property getter: - (BOOL)forwardVector;	// 0x48155
// converted property setter: - (void)setBackwardVector:(BOOL)vector;	// 0x48165
// converted property getter: - (BOOL)backwardVector;	// 0x48175
- (int)comparePositionLengthwise:(id)lengthwise;	// 0x4a281
@end
