/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
 */

#import <CorePDF/CorePDF-Structs.h>
#import <CorePDF/CPRegion.h>
#import <CorePDF/CPGraphicUser.h>

@class NSMutableArray, NSArray, CPCharSequence, CPZoneProfile;

@interface CPZone : CPRegion <CPGraphicUser> {
	NSMutableArray *zoneBorders;	// 68 = 0x44
	CGPoint *outerVertices;	// 72 = 0x48
	CGPoint *swollenOuterVertices;	// 76 = 0x4c
	double area;	// 80 = 0x50
	BOOL isStraddleZone;	// 88 = 0x58
	CPZoneProfile *zoneProfile;	// 92 = 0x5c
	NSArray *leftGuides;	// 96 = 0x60
	NSArray *rightGuides;	// 100 = 0x64
	NSArray *gutters;	// 104 = 0x68
	NSArray *spacers;	// 108 = 0x6c
	CPCharSequence *charactersInZone;	// 112 = 0x70
	NSMutableArray *textLinesInZone;	// 116 = 0x74
	NSArray *graphicsInZone;	// 120 = 0x78
	NSMutableArray *backgroundGraphics;	// 124 = 0x7c
	unsigned usedGraphicCount;	// 128 = 0x80
}
@property(retain) NSMutableArray *zoneBorders;	// G=0x227bd; S=0x23dcd; converted property
@property(retain) CPCharSequence *charactersInZone;	// G=0x227d1; S=0x22d31; converted property
@property(assign) BOOL isStraddleZone;	// G=0x227e1; S=0x227f1; converted property
@property(retain) CPZoneProfile *zoneProfile;	// G=0x22801; S=0x22aa1; converted property
@property(retain) NSArray *leftGuides;	// G=0x22811; S=0x22a59; converted property
@property(retain) NSArray *rightGuides;	// G=0x22821; S=0x22a11; converted property
@property(retain) NSArray *gutters;	// G=0x22831; S=0x229c9; converted property
@property(retain) NSArray *spacers;	// G=0x22841; S=0x22981; converted property
@property(readonly, assign) CGPoint *outerVertices;	// G=0x23491; converted property
@property(readonly, assign) CGPoint *swollenOuterVertices;	// G=0x233f1; converted property
@property(readonly, assign) double area;	// G=0x2336d; converted property
@property(readonly, retain) NSMutableArray *textLinesInZone;	// G=0x227a9; converted property
@property(readonly, retain) NSArray *graphicsInZone;	// G=0x242bd; converted property
@property(readonly, retain) NSMutableArray *backgroundGraphics;	// G=0x238e5; converted property
@property(readonly, assign) unsigned usedGraphicCount;	// G=0x22865; converted property
- (id)init;	// 0x22875
- (void)dealloc;	// 0x245a9
- (id)copyWithZone:(NSZone *)zone;	// 0x24329
// converted property getter: - (id)textLinesInZone;	// 0x227a9
// converted property getter: - (id)graphicsInZone;	// 0x242bd
- (unsigned)wordCount;	// 0x24245
- (BOOL)mapToWords:(/*function-pointer*/ void *)words passing:(void *)passing;	// 0x241c1
- (BOOL)mapToWordsWithIndex:(/*function-pointer*/ void *)index passing:(void *)passing;	// 0x240f1
- (BOOL)mapToWordPairs:(/*function-pointer*/ void *)wordPairs passing:(void *)passing;	// 0x23fed
- (BOOL)mapToWordPairsWithIndex:(/*function-pointer*/ void *)index passing:(void *)passing;	// 0x23ed9
- (BOOL)isZone;	// 0x227b9
- (BOOL)hasBorders;	// 0x23eb9
// converted property getter: - (id)zoneBorders;	// 0x227bd
// converted property setter: - (void)setZoneBorders:(id)borders;	// 0x23dcd
- (BOOL)bordersWindClockwise;	// 0x227cd
- (BOOL)hasNeighborShape:(id)shape;	// 0x23d5d
- (CGColorRef)createBackgroundColor;	// 0x23bb9
// converted property getter: - (id)backgroundGraphics;	// 0x238e5
- (void)removeUnfilledNeighborShapes;	// 0x2381d
- (unsigned)vertexCount;	// 0x237f1
- (long)borderZOrder;	// 0x236a9
- (long)neighborZOrder;	// 0x23519
// converted property getter: - (CGPoint *)outerVertices;	// 0x23491
- (void)accept:(id)accept;	// 0x23479
// converted property getter: - (CGPoint *)swollenOuterVertices;	// 0x233f1
// converted property getter: - (double)area;	// 0x2336d
- (CGRect)zoneBounds;	// 0x23265
- (CGRect)swollenZoneBounds;	// 0x23119
- (BOOL)isRectangular;	// 0x230f9
- (BOOL)rectangleBordersAtLeft:(id *)left top:(id *)top right:(id *)right bottom:(id *)bottom;	// 0x22fa1
- (BOOL)contains:(id)contains;	// 0x22e3d
- (BOOL)canContain:(CGRect)contain;	// 0x22de9
- (void)addPDFChar:(void *)aChar;	// 0x22d79
// converted property setter: - (void)setCharactersInZone:(id)zone;	// 0x22d31
// converted property getter: - (id)charactersInZone;	// 0x227d1
- (void)addContentFrom:(id)from;	// 0x22c35
- (int)compareArea:(id)area;	// 0x22ae9
// converted property getter: - (BOOL)isStraddleZone;	// 0x227e1
// converted property setter: - (void)setIsStraddleZone:(BOOL)zone;	// 0x227f1
// converted property getter: - (id)zoneProfile;	// 0x22801
// converted property setter: - (void)setZoneProfile:(id)profile;	// 0x22aa1
// converted property setter: - (void)setLeftGuides:(id)guides;	// 0x22a59
// converted property getter: - (id)leftGuides;	// 0x22811
// converted property setter: - (void)setRightGuides:(id)guides;	// 0x22a11
// converted property getter: - (id)rightGuides;	// 0x22821
// converted property setter: - (void)setGutters:(id)gutters;	// 0x229c9
// converted property getter: - (id)gutters;	// 0x22831
// converted property setter: - (void)setSpacers:(id)spacers;	// 0x22981
// converted property getter: - (id)spacers;	// 0x22841
- (void)incrementUsedGraphicCount;	// 0x22851
// converted property getter: - (unsigned)usedGraphicCount;	// 0x22865
@end
