/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import <iCalendar/ICSDuration.h>
#import <iCalendar/NSCoding.h>
#import <iCalendar/XXUnknownSuperclass.h>


@interface ICSDuration : XXUnknownSuperclass <NSCoding> {
	double _duration;	// 4 = 0x4
}
+ (id)durationFromICSString:(id)icsstring;	// 0x9e5d
- (id)initWithCoder:(id)coder;	// 0x9ef9
- (void)encodeWithCoder:(id)coder;	// 0x9eb9
- (id)ICSStringWithOptions:(unsigned)options;	// 0x9e79
- (BOOL)isNegative;	// 0x9e39
- (int)seconds;	// 0x9e11
- (int)minutes;	// 0x9ddd
- (int)hours;	// 0x9da5
- (int)days;	// 0x9d69
- (int)weeks;	// 0x9d39
- (double)timeInterval;	// 0x9d21
- (id)initWithWeeks:(int)weeks days:(int)days hours:(int)hours minutes:(int)minutes seconds:(int)seconds;	// 0x9ca1
@end

@interface ICSDuration (ICSWriter)
- (void)_ICSStringWithOptions:(unsigned)options appendingToString:(id)string;	// 0xde99
@end

@interface ICSDuration (iCalendarImport)
+ (id)durationFromICSString:(id)icsstring;	// 0x1ab79
+ (id)durationFromRFC2445UTF8String:(const char *)rfc2445UTF8String;	// 0x1a96d
@end
