/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MediaStream.framework/MediaStream
 */



@class NSString, CPDistributedMessagingCenter, NSTimer;

@interface MSClientSidePauseContext : NSObject {
@private
	CPDistributedMessagingCenter *_server;	// 4 = 0x4
	NSTimer *_timer;	// 8 = 0x8
	NSString *_UUID;	// 12 = 0xc
}
- (void)_ping;	// 0x3dcd
- (void)_timerDidFire:(id)_timer;	// 0x3dbd
- (void)resume;	// 0x3cbd
- (void)dealloc;	// 0x3c7d
- (id)initWithServer:(id)server;	// 0x3af9
@end
