/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMHTMLElement.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface DOMHTMLBRElement : DOMHTMLElement {
}
@property(copy) NSString *clear;	// G=0x30f769; S=0x30f849; 
// declared property getter: - (id)clear;	// 0x30f769
// declared property setter: - (void)setClear:(id)clear;	// 0x30f849
@end
