/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMHTMLElement.h>


__attribute__((visibility("hidden")))
@interface DOMHTMLPreElement : DOMHTMLElement {
}
@property(assign) BOOL wrap;	// G=0x3306b5; S=0x33077d; 
@property(assign) int width;	// G=0x330525; S=0x3305ed; 
// declared property getter: - (int)width;	// 0x330525
// declared property setter: - (void)setWidth:(int)width;	// 0x3305ed
// declared property getter: - (BOOL)wrap;	// 0x3306b5
// declared property setter: - (void)setWrap:(BOOL)wrap;	// 0x33077d
@end
