/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/WebCore-Structs.h>
#import <WebCore/DOMHTMLElement.h>
#import <WebCore/DOMHTMLInputElement.h>

@class NSURL, DOMHTMLFormElement, DOMFileList, NSString;

@interface DOMHTMLInputElement : DOMHTMLElement {
}
@property(readonly, retain) DOMFileList *files;	// G=0x324b49; 
@property(readonly, copy) NSURL *absoluteImageURL;	// G=0x324a61; 
@property(readonly, copy) NSString *altDisplayString;	// G=0x324871; 
@property(assign) int selectionEnd;	// G=0x3246f9; S=0x3247b5; 
@property(assign) int selectionStart;	// G=0x324581; S=0x32463d; 
@property(assign) BOOL indeterminate;	// G=0x320455; S=0x3244b5; 
@property(readonly, assign) BOOL willValidate;	// G=0x320395; 
@property(copy) NSString *value;	// G=0x3206ad; S=0x323ec5; 
@property(copy) NSString *useMap;	// G=0x3237a1; S=0x322afd; 
@property(copy) NSString *type;	// G=0x320489; S=0x323d8d; 
@property(copy) NSString *src;	// G=0x3216a9; S=0x322875; 
@property(copy) NSString *size;	// G=0x323ae9; S=0x323c41; 
@property(assign) BOOL readOnly;	// G=0x320c55; S=0x32120d; 
@property(copy) NSString *name;	// G=0x323421; S=0x3224a9; 
@property(assign) BOOL multiple;	// G=0x320b8d; S=0x321135; 
@property(assign) int maxLength;	// G=0x3202d5; S=0x323a1d; 
@property(assign) BOOL autofocus;	// G=0x320ac5; S=0x32105d; 
@property(assign) BOOL disabled;	// G=0x320145; S=0x320205; 
@property(assign) BOOL checked;	// G=0x320111; S=0x32394d; 
@property(copy) NSString *alt;	// G=0x323181; S=0x3220dd; 
@property(copy) NSString *align;	// G=0x3230a1; S=0x321f99; 
@property(copy) NSString *accessKey;	// G=0x322fc1; S=0x321e55; 
@property(copy) NSString *accept;	// G=0x322ee1; S=0x321d11; 
@property(readonly, retain) DOMHTMLFormElement *form;	// G=0x321495; 
@property(assign) BOOL defaultChecked;	// G=0x320935; S=0x320ead; 
@property(copy) NSString *defaultValue;	// G=0x320561; S=0x3207fd; 
@property(retain) id formAction;	// G=0x321551; S=0x321801; converted property
@property(retain) id formEnctype;	// G=0x322c41; S=0x321945; converted property
@property(retain) id formMethod;	// G=0x322d21; S=0x321a89; converted property
@property(assign) BOOL formNoValidate;	// G=0x3209fd; S=0x320f85; converted property
@property(retain) id formTarget;	// G=0x322e01; S=0x321bcd; converted property
@property(retain) id max;	// G=0x323261; S=0x322221; converted property
@property(retain) id min;	// G=0x323341; S=0x322365; converted property
@property(retain) id pattern;	// G=0x323501; S=0x3225ed; converted property
@property(retain) id placeholder;	// G=0x3235e1; S=0x322731; converted property
@property(assign) BOOL required;	// G=0x320d1d; S=0x3212e5; converted property
@property(retain) id step;	// G=0x3236c1; S=0x3229b9; converted property
@property(assign) double valueAsDate;	// G=0x323ffd; S=0x3240dd; converted property
@property(assign) double valueAsNumber;	// G=0x3241d1; S=0x324291; converted property
@property(assign) BOOL incremental;	// G=0x320de5; S=0x3213bd; converted property
@property(assign) BOOL autocorrect;	// G=0x324d55; S=0x324e11; converted property
@property(retain) id autocapitalize;	// G=0x324edd; S=0x324fb1; converted property
// declared property getter: - (id)defaultValue;	// 0x320561
// declared property setter: - (void)setDefaultValue:(id)value;	// 0x3207fd
// declared property getter: - (BOOL)defaultChecked;	// 0x320935
// declared property setter: - (void)setDefaultChecked:(BOOL)checked;	// 0x320ead
// declared property getter: - (id)form;	// 0x321495
// converted property getter: - (id)formAction;	// 0x321551
// converted property setter: - (void)setFormAction:(id)action;	// 0x321801
// converted property getter: - (id)formEnctype;	// 0x322c41
// converted property setter: - (void)setFormEnctype:(id)enctype;	// 0x321945
// converted property getter: - (id)formMethod;	// 0x322d21
// converted property setter: - (void)setFormMethod:(id)method;	// 0x321a89
// converted property getter: - (BOOL)formNoValidate;	// 0x3209fd
// converted property setter: - (void)setFormNoValidate:(BOOL)validate;	// 0x320f85
// converted property getter: - (id)formTarget;	// 0x322e01
// converted property setter: - (void)setFormTarget:(id)target;	// 0x321bcd
- (id)validity;	// 0x323881
// declared property getter: - (id)accept;	// 0x322ee1
// declared property setter: - (void)setAccept:(id)accept;	// 0x321d11
// declared property getter: - (id)accessKey;	// 0x322fc1
// declared property setter: - (void)setAccessKey:(id)key;	// 0x321e55
// declared property getter: - (id)align;	// 0x3230a1
// declared property setter: - (void)setAlign:(id)align;	// 0x321f99
// declared property getter: - (id)alt;	// 0x323181
// declared property setter: - (void)setAlt:(id)alt;	// 0x3220dd
// declared property getter: - (BOOL)checked;	// 0x320111
// declared property setter: - (void)setChecked:(BOOL)checked;	// 0x32394d
// declared property getter: - (BOOL)disabled;	// 0x320145
// declared property setter: - (void)setDisabled:(BOOL)disabled;	// 0x320205
// declared property getter: - (BOOL)autofocus;	// 0x320ac5
// declared property setter: - (void)setAutofocus:(BOOL)autofocus;	// 0x32105d
// converted property getter: - (id)max;	// 0x323261
// converted property setter: - (void)setMax:(id)max;	// 0x322221
// declared property getter: - (int)maxLength;	// 0x3202d5
// declared property setter: - (void)setMaxLength:(int)length;	// 0x323a1d
// converted property getter: - (id)min;	// 0x323341
// converted property setter: - (void)setMin:(id)min;	// 0x322365
// declared property getter: - (BOOL)multiple;	// 0x320b8d
// declared property setter: - (void)setMultiple:(BOOL)multiple;	// 0x321135
// declared property getter: - (id)name;	// 0x323421
// declared property setter: - (void)setName:(id)name;	// 0x3224a9
// converted property getter: - (id)pattern;	// 0x323501
// converted property setter: - (void)setPattern:(id)pattern;	// 0x3225ed
// converted property getter: - (id)placeholder;	// 0x3235e1
// converted property setter: - (void)setPlaceholder:(id)placeholder;	// 0x322731
// declared property getter: - (BOOL)readOnly;	// 0x320c55
// declared property setter: - (void)setReadOnly:(BOOL)only;	// 0x32120d
// converted property getter: - (BOOL)required;	// 0x320d1d
// converted property setter: - (void)setRequired:(BOOL)required;	// 0x3212e5
// declared property getter: - (id)size;	// 0x323ae9
// declared property setter: - (void)setSize:(id)size;	// 0x323c41
// declared property getter: - (id)src;	// 0x3216a9
// declared property setter: - (void)setSrc:(id)src;	// 0x322875
// converted property getter: - (id)step;	// 0x3236c1
// converted property setter: - (void)setStep:(id)step;	// 0x3229b9
// declared property getter: - (id)type;	// 0x320489
// declared property setter: - (void)setType:(id)type;	// 0x323d8d
// declared property getter: - (id)useMap;	// 0x3237a1
// declared property setter: - (void)setUseMap:(id)map;	// 0x322afd
// declared property getter: - (id)value;	// 0x3206ad
// declared property setter: - (void)setValue:(id)value;	// 0x323ec5
// converted property getter: - (double)valueAsDate;	// 0x323ffd
// converted property setter: - (void)setValueAsDate:(double)date;	// 0x3240dd
// converted property getter: - (double)valueAsNumber;	// 0x3241d1
// converted property setter: - (void)setValueAsNumber:(double)number;	// 0x324291
// converted property getter: - (BOOL)incremental;	// 0x320de5
// converted property setter: - (void)setIncremental:(BOOL)incremental;	// 0x3213bd
// declared property getter: - (BOOL)willValidate;	// 0x320395
- (id)validationMessage;	// 0x324369
// declared property getter: - (BOOL)indeterminate;	// 0x320455
// declared property setter: - (void)setIndeterminate:(BOOL)indeterminate;	// 0x3244b5
// declared property getter: - (int)selectionStart;	// 0x324581
// declared property setter: - (void)setSelectionStart:(int)start;	// 0x32463d
// declared property getter: - (int)selectionEnd;	// 0x3246f9
// declared property setter: - (void)setSelectionEnd:(int)end;	// 0x3247b5
// declared property getter: - (id)altDisplayString;	// 0x324871
// declared property getter: - (id)absoluteImageURL;	// 0x324a61
// declared property getter: - (id)files;	// 0x324b49
- (id)labels;	// 0x324c0d
// converted property getter: - (BOOL)autocorrect;	// 0x324d55
// converted property setter: - (void)setAutocorrect:(BOOL)autocorrect;	// 0x324e11
// converted property getter: - (id)autocapitalize;	// 0x324edd
// converted property setter: - (void)setAutocapitalize:(id)autocapitalize;	// 0x324fb1
- (void)stepUp:(int)up;	// 0x3250e9
- (void)stepDown:(int)down;	// 0x3251b5
- (BOOL)checkValidity;	// 0x325281
- (void)setCustomValidity:(id)validity;	// 0x325341
- (void)select;	// 0x325479
- (void)click;	// 0x325531
- (void)setValueForUser:(id)user;	// 0x3255e9
- (void)setSelectionRange:(int)range end:(int)end;	// 0x325721
@end

@interface DOMHTMLInputElement (AutocapitalizeAdditions)
- (int)_autocapitalizeType;	// 0x308579
@end

@interface DOMHTMLInputElement (FormPromptAdditions)
- (BOOL)_isEdited;	// 0x308559
@end

@interface DOMHTMLInputElement (FormAutoFillTransition)
- (BOOL)_isTextField;	// 0x3082ed
- (void)_replaceCharactersInRange:(NSRange)range withString:(id)string selectingFromIndex:(int)index;	// 0x3082fd
- (NSRange)_selectedRange;	// 0x3084b9
- (BOOL)_isAutofilled;	// 0x3082dd
- (void)_setAutofilled:(BOOL)autofilled;	// 0x3084e9
@end

@interface DOMHTMLInputElement (DOMUIKitComplexityExtensions)
- (int)structuralComplexityContribution;	// 0x34f5ad
@end
