/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMHTMLElement.h>


__attribute__((visibility("hidden")))
@interface DOMHTMLDetailsElement : DOMHTMLElement {
}
@property(assign) BOOL open;	// G=0x312019; S=0x3120e1; 
// declared property getter: - (BOOL)open;	// 0x312019
// declared property setter: - (void)setOpen:(BOOL)open;	// 0x3120e1
@end
