/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMObject.h>
#import <WebCore/DOMXPathNSResolver.h>


__attribute__((visibility("hidden")))
@interface DOMNativeXPathNSResolver : DOMObject <DOMXPathNSResolver> {
}
- (void)dealloc;	// 0x357699
- (void)finalize;	// 0x357895
- (id)lookupNamespaceURI:(id)uri;	// 0x3576f5
@end
