/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMEvent.h>


__attribute__((visibility("hidden")))
@interface DOMProgressEvent : DOMEvent {
}
@property(readonly, assign) unsigned long long total;	// G=0x347815; 
@property(readonly, assign) unsigned long long loaded;	// G=0x3477e5; 
@property(readonly, assign) BOOL lengthComputable;	// G=0x3477b5; 
// declared property getter: - (BOOL)lengthComputable;	// 0x3477b5
// declared property getter: - (unsigned long long)loaded;	// 0x3477e5
// declared property getter: - (unsigned long long)total;	// 0x347815
- (void)initProgressEvent:(id)event canBubbleArg:(BOOL)arg cancelableArg:(BOOL)arg3 lengthComputableArg:(BOOL)arg4 loadedArg:(unsigned long long)arg5 totalArg:(unsigned long long)arg6;	// 0x347845
@end
