/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMObject.h>

@class DOMNode;
@protocol DOMNodeFilter;

__attribute__((visibility("hidden")))
@interface DOMTreeWalker : DOMObject {
}
@property(retain) DOMNode *currentNode;	// G=0x34e851; S=0x34e6f5; 
@property(readonly, assign) BOOL expandEntityReferences;	// G=0x34e045; 
@property(readonly, retain) id<DOMNodeFilter> filter;	// G=0x34e90d; 
@property(readonly, assign) unsigned whatToShow;	// G=0x34e019; 
@property(readonly, retain) DOMNode *root;	// G=0x34e9c9; 
- (void)dealloc;	// 0x34e075
- (void)finalize;	// 0x34ea85
// declared property getter: - (id)root;	// 0x34e9c9
// declared property getter: - (unsigned)whatToShow;	// 0x34e019
// declared property getter: - (id)filter;	// 0x34e90d
// declared property getter: - (BOOL)expandEntityReferences;	// 0x34e045
// declared property getter: - (id)currentNode;	// 0x34e851
// declared property setter: - (void)setCurrentNode:(id)node;	// 0x34e6f5
- (id)parentNode;	// 0x34e619
- (id)firstChild;	// 0x34e53d
- (id)lastChild;	// 0x34e461
- (id)previousSibling;	// 0x34e385
- (id)nextSibling;	// 0x34e2a9
- (id)previousNode;	// 0x34e1cd
- (id)nextNode;	// 0x34e0f1
@end
