/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/DOMUIEvent.h>

@class DOMTouchList;

__attribute__((visibility("hidden")))
@interface DOMTouchEvent : DOMUIEvent {
}
@property(readonly, assign) BOOL metaKey;	// G=0x34d929; 
@property(readonly, assign) BOOL altKey;	// G=0x34d8f5; 
@property(readonly, assign) BOOL shiftKey;	// G=0x34d8c1; 
@property(readonly, assign) BOOL ctrlKey;	// G=0x34d88d; 
@property(readonly, assign) float rotation;	// G=0x34d85d; 
@property(readonly, assign) float scale;	// G=0x34d831; 
@property(readonly, retain) DOMTouchList *changedTouches;	// G=0x34dad5; 
@property(readonly, retain) DOMTouchList *targetTouches;	// G=0x34da19; 
@property(readonly, retain) DOMTouchList *touches;	// G=0x34d95d; 
// declared property getter: - (id)touches;	// 0x34d95d
// declared property getter: - (id)targetTouches;	// 0x34da19
// declared property getter: - (id)changedTouches;	// 0x34dad5
// declared property getter: - (float)scale;	// 0x34d831
// declared property getter: - (float)rotation;	// 0x34d85d
// declared property getter: - (BOOL)ctrlKey;	// 0x34d88d
// declared property getter: - (BOOL)shiftKey;	// 0x34d8c1
// declared property getter: - (BOOL)altKey;	// 0x34d8f5
// declared property getter: - (BOOL)metaKey;	// 0x34d929
- (void)initTouchEvent:(id)event canBubble:(BOOL)bubble cancelable:(BOOL)cancelable view:(id)view detail:(int)detail screenX:(int)x screenY:(int)y clientX:(int)x8 clientY:(int)y9 ctrlKey:(BOOL)key altKey:(BOOL)key11 shiftKey:(BOOL)key12 metaKey:(BOOL)key13 touches:(id)touches targetTouches:(id)touches15 changedTouches:(id)touches16 scale:(float)scale rotation:(float)rotation;	// 0x34db91
@end
