/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import <WebCore/WebCore-Structs.h>
#import <WebCore/XXUnknownSuperclass.h>


@interface WebFontCache : XXUnknownSuperclass {
}
+ (GSFontRef)createFontWithFamily:(id)family traits:(unsigned)traits weight:(int)weight size:(float)size;	// 0x89d69
+ (void)getTraits:(Vector<unsigned int,0ul> *)traits inFamily:(id)family;	// 0x6dc5bd
@end
