/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import <Symbolication/VMULoadCommand.h>

@class NSString;

@interface VMUDyLibLoadCommand : VMULoadCommand {
	NSString *_path;	// 16 = 0x10
	unsigned _currentVersion;	// 20 = 0x14
	unsigned _compatibilityVersion;	// 24 = 0x18
}
@property(readonly, retain) NSString *path;	// G=0x35760; converted property
@property(readonly, assign) unsigned currentVersion;	// G=0x35774; converted property
@property(readonly, assign) unsigned compatibilityVersion;	// G=0x35788; converted property
- (id)initWithMemory:(id)memory;	// 0x357a4
// converted property getter: - (id)path;	// 0x35760
// converted property getter: - (unsigned)currentVersion;	// 0x35774
// converted property getter: - (unsigned)compatibilityVersion;	// 0x35788
- (BOOL)isLoadDyLib;	// 0x3579c
- (id)description;	// 0x35954
- (void)dealloc;	// 0x358e0
@end
