/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import <Symbolication/VMUMachOHeader.h>


@interface VMUMachO32Header : VMUMachOHeader {
}
+ (id)machO32HeaderWithUniverse:(id)universe memory:(id)memory name:(id)name path:(id)path timestamp:(id)timestamp;	// 0x7f60
- (id)initWithUniverse:(id)universe memory:(id)memory name:(id)name path:(id)path timestamp:(id)timestamp;	// 0x7fd0
- (BOOL)isMachO32;	// 0x7f58
@end
