/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import <Foundation/NSObject.h>
#import <Symbolication/Symbolication-Structs.h>

@class NSMutableArray, NSMapTable;

@interface VMUVMRegionIdentifier : NSObject {
	NSMutableArray *_regions;	// 4 = 0x4
	NSMapTable *_mallocZoneStatisticsMap;	// 8 = 0x8
}
@property(readonly, retain) NSMutableArray *regions;	// G=0x373b4; converted property
- (id)initWithTask:(unsigned)task options:(unsigned)options;	// 0x3bb28
- (id)initWithTask:(unsigned)task;	// 0x38794
- (void)dealloc;	// 0x3ad18
// converted property getter: - (id)regions;	// 0x373b4
- (id)descriptionForRange:(VMURange)range;	// 0x387a8
- (id)descriptionForRange:(VMURange)range options:(unsigned)options;	// 0x3b888
- (id)descriptionForMallocZoneTotalsWithOptions:(unsigned)options;	// 0x3ad98
- (id)descriptionForRegionTotalsWithOptions:(unsigned)options;	// 0x39884
@end
