/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MediaToolbox.framework/MediaToolbox
 */

#import <MediaToolbox/MediaToolbox-Structs.h>



@interface FigVideoLayerInternal : NSObject {
	BOOL isPresentationLayer;	// 4 = 0x4
	BOOL visible;	// 5 = 0x5
	OpaqueFigSimpleMutex *serializationMutex;	// 8 = 0x8
	dispatch_queue_s *notificationSerialQueue;	// 12 = 0xc
}
@end
