/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MediaToolbox.framework/MediaToolbox
 */

#import <MediaToolbox/SSPlayInfoRequestDelegate.h>

#import <MediaToolbox/MediaToolbox-Structs.h>

@class SSPlayInfoRequest;

@interface FPAPSSPlayInfoRequestHandler : NSObject <SSPlayInfoRequestDelegate> {
@private
	OpaqueFigPlayer *_player;	// 4 = 0x4
	SSPlayInfoRequest *_playInfoRequest;	// 8 = 0x8
}
- (id)init;	// 0x167b4d
- (void)dealloc;	// 0x167d11
- (void)setPlayer:(OpaqueFigPlayer *)player;	// 0x167b39
- (void)setRequest:(id)request;	// 0x167cd1
- (void)playInfoRequest:(id)request didReceiveResponse:(id)response;	// 0x167b49
- (void)request:(id)request didFailWithError:(id)error;	// 0x167c41
- (void)requestDidFinish:(id)request;	// 0x167b99
@end
