/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CHBChart.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface CHBChart : XXUnknownSuperclass {
}
+ (void)readWithState:(id)state;	// 0x161fad
@end

@interface CHBChart (Private)
+ (int)readCHDDisplayBlanksAsEnumFrom:(int)from;	// 0x164669
+ (int)emptyCellsPlottedEnumsFrom:(int)from;	// 0x25e035
@end
