/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CHBPlotArea.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface CHBPlotArea : XXUnknownSuperclass {
}
+ (id)readWithState:(id)state;	// 0x167f1d
@end

@interface CHBPlotArea (Private)
+ (void)readAxisGroup:(int)group to:(id)to state:(id)state;	// 0x168839
@end
