/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface CHBTitle : XXUnknownSuperclass {
}
+ (id)readFrom:(const XlChartTextFrame *)from state:(id)state;	// 0x16b711
@end
