/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/XXUnknownSuperclass.h>

@class CHDTrendlineLabel, OADGraphicProperties, EDString;

__attribute__((visibility("hidden")))
@interface CHDTrendline : XXUnknownSuperclass {
@private
	bool mDisplayEquation;	// 4 = 0x4
	bool mDisplayRSquaredValue;	// 5 = 0x5
	double mBackward;	// 8 = 0x8
	double mForward;	// 16 = 0x10
	double mInterceptYAxis;	// 24 = 0x18
	int mPolynomialOrder;	// 32 = 0x20
	int mMovingAveragePeriod;	// 36 = 0x24
	int mType;	// 40 = 0x28
	OADGraphicProperties *mGraphicProperties;	// 44 = 0x2c
	CHDTrendlineLabel *mLabel;	// 48 = 0x30
	EDString *mName;	// 52 = 0x34
}
@property(assign, getter=isDisplayEquation) bool displayEquation;	// G=0x2664bd; S=0x1ed95d; converted property
@property(assign, getter=isDisplayRSquaredValue) bool displayRSquaredValue;	// G=0x2664cd; S=0x1ed96d; converted property
@property(assign) double backward;	// G=0x2664dd; S=0x1ed97d; converted property
@property(assign) double forward;	// G=0x2664f5; S=0x1ed991; converted property
@property(assign) double interceptYAxis;	// G=0x26650d; S=0x1ed9a5; converted property
@property(assign) int polynomialOrder;	// G=0x266525; S=0x266535; converted property
@property(assign) int movingAveragePeriod;	// G=0x266545; S=0x210ffd; converted property
@property(assign) int type;	// G=0x266555; S=0x1ed639; converted property
@property(retain) id label;	// G=0x266565; S=0x1ed915; converted property
@property(retain) id graphicProperties;	// G=0x266575; S=0x1eda65; converted property
@property(retain) id name;	// G=0x266585; S=0x2666f5; converted property
+ (id)trendline;	// 0x266595
- (id)init;	// 0x1ed559
- (void)dealloc;	// 0x1edd7d
// converted property getter: - (bool)isDisplayEquation;	// 0x2664bd
// converted property setter: - (void)setDisplayEquation:(bool)equation;	// 0x1ed95d
// converted property getter: - (bool)isDisplayRSquaredValue;	// 0x2664cd
// converted property setter: - (void)setDisplayRSquaredValue:(bool)value;	// 0x1ed96d
// converted property getter: - (double)backward;	// 0x2664dd
// converted property setter: - (void)setBackward:(double)backward;	// 0x1ed97d
// converted property getter: - (double)forward;	// 0x2664f5
// converted property setter: - (void)setForward:(double)forward;	// 0x1ed991
// converted property getter: - (double)interceptYAxis;	// 0x26650d
// converted property setter: - (void)setInterceptYAxis:(double)axis;	// 0x1ed9a5
// converted property getter: - (int)polynomialOrder;	// 0x266525
// converted property setter: - (void)setPolynomialOrder:(int)order;	// 0x266535
// converted property getter: - (int)movingAveragePeriod;	// 0x266545
// converted property setter: - (void)setMovingAveragePeriod:(int)period;	// 0x210ffd
// converted property getter: - (int)type;	// 0x266555
// converted property setter: - (void)setType:(int)type;	// 0x1ed639
// converted property getter: - (id)label;	// 0x266565
// converted property setter: - (void)setLabel:(id)label;	// 0x1ed915
// converted property getter: - (id)graphicProperties;	// 0x266575
// converted property setter: - (void)setGraphicProperties:(id)properties;	// 0x1eda65
// converted property getter: - (id)name;	// 0x266585
// converted property setter: - (void)setName:(id)name;	// 0x2666f5
- (id)defaultNameWithSeriesName:(id)seriesName;	// 0x2665dd
@end
