/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>
#import <OfficeImport/CHXErrorBar.h>


__attribute__((visibility("hidden")))
@interface CHXErrorBar : XXUnknownSuperclass {
}
+ (id)chdErrorBarFromXmlErrorBarElement:(xmlNode *)xmlErrorBarElement state:(id)state;	// 0x267459
@end

@interface CHXErrorBar (Private)
+ (int)chdErrorBarTypeFromXmlElement:(xmlNode *)xmlElement;	// 0x267759
+ (int)chdErrorBarValueTypeFromXmlElement:(xmlNode *)xmlElement;	// 0x2677fd
+ (int)chdErrorBarDirectionFromXmlElement:(xmlNode *)xmlElement;	// 0x2678f1
@end
