/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CHXLayout.h>
#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface CHXLayout : XXUnknownSuperclass {
}
+ (void)readFrom:(xmlNode *)from graphicProperties:(id)properties state:(id)state;	// 0x1e1b89
@end

@interface CHXLayout (Private)
+ (CGRect)boundsRectFromXmlManualLayoutElement:(xmlNode *)xmlManualLayoutElement;	// 0x1e7b0d
@end
