/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OCCancelDelegate.h>
#import <OfficeImport/XXUnknownSuperclass.h>

@class NSMutableSet, NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CMArchiveManager : XXUnknownSuperclass <OCCancelDelegate> {
@private
	BOOL mIsThumbnail;	// 4 = 0x4
	BOOL mIsOnPhone;	// 5 = 0x5
	unsigned mPageCount;	// 8 = 0x8
	NSMutableDictionary *mDrawableCache;	// 12 = 0xc
	NSString *mResourcePathPrefix;	// 16 = 0x10
	NSMutableSet *mPausedPaths;	// 20 = 0x14
	int mHeight;	// 24 = 0x18
	int mWidth;	// 28 = 0x1c
	float mCommitInterval;	// 32 = 0x20
	BOOL mAutoCommit;	// 36 = 0x24
}
@property(retain) id resourcePathPrefix;	// G=0x2f1321; S=0x2f1405; converted property
@property(assign) BOOL isThumbnail;	// G=0xa66dd; S=0x2f1331; converted property
@property(assign) unsigned pageCount;	// G=0x2f1341; S=0xc5339; converted property
+ (int)blipTypeToResourceType:(int)resourceType;	// 0x95931
+ (id)resourceTypeToMIME:(int)mime;	// 0x2f1359
+ (id)resourceTypeToExtension:(int)extension;	// 0x91625
- (id)init;	// 0xa5e1d
- (void)dealloc;	// 0x90ea5
- (id)createResourceWithName:(id)name;	// 0x2f12e9
- (id)createResourceWithType:(int)type;	// 0x915c5
- (void)pushData:(id)data toPath:(id)path;	// 0x2f12ed
- (void)pushText:(id)text toPath:(id)path;	// 0x2f12f1
- (void)pushCssToPath:(id)path;	// 0x2f12f5
- (void)closeResourceAtPath:(id)path;	// 0x2f12f9
- (void)commitDataAtPath:(id)path;	// 0x2f12fd
- (void)setCommitInterval:(float)interval;	// 0x2f1301
- (void)setAutoCommit:(BOOL)commit;	// 0xa66cd
- (id)_validateData:(id)data withType:(int *)type;	// 0x915c1
- (id)addResource:(id)resource withType:(int)type;	// 0x91551
- (id)addResource:(id)resource withName:(id)name;	// 0x100769
- (id)addResourceForDrawable:(id)drawable withType:(int)type drawable:(id)drawable3;	// 0xc6cf1
- (id)cachedPathForDrawable:(id)drawable;	// 0xc6989
- (void)pauseProgressiveMappingOnPath:(id)path;	// 0x9425d
- (void)restartProgressiveMappingOnPath:(id)path;	// 0x91d4d
- (BOOL)progressiveMappingIsPausedOnPath:(id)path;	// 0x7fb1
- (BOOL)setIsOnPhone:(BOOL)phone;	// 0xa5e9d
- (BOOL)isOnPhone;	// 0x135449
- (int)resourceCount;	// 0x2f1311
- (id)addCssStyle:(id)style;	// 0x2f1315
- (void)addCssStyle:(id)style withName:(id)name;	// 0x2f1319
- (id)cssStylesheetString;	// 0x2f131d
// converted property setter: - (void)setResourcePathPrefix:(id)prefix;	// 0x2f1405
// converted property getter: - (id)resourcePathPrefix;	// 0x2f1321
- (id)appendResourcePathToName:(id)name;	// 0x2f13d9
// converted property setter: - (void)setIsThumbnail:(BOOL)thumbnail;	// 0x2f1331
// converted property getter: - (BOOL)isThumbnail;	// 0xa66dd
// converted property setter: - (void)setPageCount:(unsigned)count;	// 0xc5339
// converted property getter: - (unsigned)pageCount;	// 0x2f1341
- (BOOL)isProgressive;	// 0x2f1351
- (void)setHTMLHeight:(int)height;	// 0x8c095
- (void)setHTMLWidth:(int)width;	// 0x8c085
- (BOOL)isCancelled;	// 0x2f1355
@end
