/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CMColorProperty.h>
#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/CMProperty.h>

@class NSColorStub;

__attribute__((visibility("hidden")))
@interface CMColorProperty : CMProperty {
@private
	NSColorStub *wdValue;	// 8 = 0x8
}
+ (CGColorRef)createCGColorFromOADColor:(id)oadcolor state:(id)state;	// 0x2f1c91
+ (CGColorRef)createCGColorFromOADFill:(id)oadfill state:(id)state;	// 0x177d0d
+ (id)cssStringFromOADGradientFill:(id)oadgradientFill state:(id)state;	// 0xce1b5
+ (id)nsColorFromOADFill:(id)oadfill state:(id)state;	// 0x660d
+ (id)nsColorFromOADColor:(id)oadcolor state:(id)state;	// 0x694d
+ (id)nsColorFromShading:(id)shading;	// 0x142d09
+ (id)cssStringFromRed:(float)red green:(float)green blue:(float)blue;	// 0x76a9
+ (id)cssStringFromNSColorStub:(id)nscolorStub;	// 0x7615
+ (id)cssStringFromOADColor:(id)oadcolor;	// 0x145339
+ (float)transformedAlphaFromOADColor:(id)oadcolor;	// 0xcf5cd
- (id)value;	// 0x2f1c81
- (id)initWithColor:(id)color;	// 0x143391
- (BOOL)isEqualTo:(id)to;	// 0x2f1d0d
- (id)cssString;	// 0x143401
- (id)cssStringForName:(id)name;	// 0x1433d1
@end

@interface CMColorProperty (Private)
+ (id)resolveStyleColorWithPercentage:(float)percentage shading:(id)shading;	// 0x14316d
+ (id)resolveStyleColorWithPercentage:(float)percentage foregroundColor:(id)color backgroundColor:(id)color3;	// 0x1431e9
+ (float)resolveColorValueWithPercentage:(float)percentage foregroundComponent:(float)component backgroundComponent:(float)component3;	// 0x143369
@end
