/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CMDiagramPointMapper.h>
#import <OfficeImport/OfficeImport-Structs.h>


__attribute__((visibility("hidden")))
@interface CMDiagramPointPyramidLayerMapper : CMDiagramPointMapper {
@private
	float mPyramidAspectRatio;	// 24 = 0x18
}
- (void)setPyramidAspectRatio:(float)ratio;	// 0x20433d
- (void)mapAt:(id)at withState:(id)state;	// 0x20434d
@end
