/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CMDiagramShapeMapper.h>
#import <OfficeImport/OfficeImport-Structs.h>


__attribute__((visibility("hidden")))
@interface CMDiagramArrowMapper : CMDiagramShapeMapper {
@private
	BOOL mIsVertical;	// 112 = 0x70
	BOOL mIsOutward;	// 113 = 0x71
	float mRadius;	// 116 = 0x74
}
+ (void)initialize;	// 0x1f39bd
- (id)initWithOddDiagram:(id)oddDiagram drawingContext:(id)context orientedBounds:(id)bounds identifier:(id)identifier parent:(id)parent;	// 0x1f3a35
- (void)mapChildrenAt:(id)at withState:(id)state;	// 0x1f3cd1
- (CGRect)circumscribedBounds;	// 0x1f3bf9
- (CGSize)sizeForNode:(id)node atIndex:(unsigned)index;	// 0x1f43a1
- (CGSize)textSizeForShapeSize:(CGSize)shapeSize;	// 0x1f445d
@end
