/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface CMTextFilter : XXUnknownSuperclass {
}
+ (id)filterHyperlinkField:(id)field;	// 0x151191
+ (id)covertFormatString:(id)string;	// 0x2f5859
+ (id)filterSpecialCodes:(id)codes;	// 0x2f573d
+ (id)convertLineBreaksToParagraphBreaks:(id)paragraphBreaks;	// 0x10703d
+ (id)filterToPreserveMultipleWhiteSpaces:(id)preserveMultipleWhiteSpaces;	// 0x2f5671
+ (id)convertToVericalString:(id)vericalString;	// 0x1b7621
- (id)init;	// 0x2f5641
@end
