/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OABReaderState.h>

@class EBReaderState;

__attribute__((visibility("hidden")))
@interface EBOfficeArtReaderState : OABReaderState {
@private
	EBReaderState *mReaderState;	// 24 = 0x18
}
- (id)initWithReaderState:(id)readerState;	// 0xd731d
- (id)readerState;	// 0x26b2f9
@end
