/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OADColorPalette.h>
#import <OfficeImport/EDColorsCollection.h>
#import <OfficeImport/EDCollection.h>


__attribute__((visibility("hidden")))
@interface EDColorsCollection : EDCollection <OADColorPalette> {
@private
	unsigned mDefaultColorsCount;	// 8 = 0x8
}
+ (bool)isSystemColorId:(unsigned)anId;	// 0xdc049
+ (int)systemColorIdFromIndex:(unsigned)index;	// 0xdc061
+ (unsigned)xlColorIndexFromCPSystemColorIDEnum:(int)cpsystemColorIDEnum;	// 0x24d1a5
+ (int)oadSchemeColorIdFromThemeIndex:(int)themeIndex;	// 0x1a2285
- (id)initWithDefaultSetup:(bool)defaultSetup;	// 0xd8a71
- (unsigned)defaultColorsCount;	// 0x24d195
- (id)colorWithIndex:(unsigned)index;	// 0xe6a29
- (unsigned)addOrEquivalentColorExcludingDefaults:(id)defaults;	// 0x167b91
- (void)addDefaultPalette;	// 0x24d1d5
- (void)addColors:(const unsigned *)colors count:(unsigned long)count defaultColors:(const unsigned *)colors3 defaultCount:(unsigned)count4;	// 0xe14f9
- (const unsigned *)defaultPalette;	// 0xe14ed
- (void)addPalette:(const unsigned *)palette paletteSize:(unsigned long)size paletteX:(const unsigned *)x paletteXSize:(unsigned)size4;	// 0xe13e1
@end

@interface EDColorsCollection (Private)
- (void)setupDefaults;	// 0xd8acd
@end
