/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/EDSortedCollection.h>

@class EDWorksheet, EDResources;

__attribute__((visibility("hidden")))
@interface EDColumnInfoCollection : EDSortedCollection {
@private
	EDResources *mResources;	// 12 = 0xc
	EDWorksheet *mWorksheet;	// 16 = 0x10
}
- (id)initWithResources:(id)resources worksheet:(id)worksheet;	// 0xe6e71
- (void)dealloc;	// 0x1114a9
- (id)columnInfoForColumnNumber:(int)columnNumber;	// 0xfadd1
- (id)columnInfoCreateIfNilForColumnNumber:(int)columnNumber;	// 0x24d2bd
@end
