/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/EDCollection.h>


__attribute__((visibility("hidden")))
@interface EDStylesCollection : EDCollection {
@private
	unsigned mDefaultWorkbookStyleIndex;	// 8 = 0x8
}
@property(assign) unsigned defaultWorkbookStyleIndex;	// G=0x25265d; S=0xded9d; converted property
- (id)init;	// 0xd8a31
- (unsigned)addObject:(id)object;	// 0xe0335
- (void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;	// 0x252659
- (void)removeObjectAtIndex:(unsigned)index;	// 0x252699
- (void)removeAllObjects;	// 0x25266d
- (id)defaultWorkbookStyle;	// 0xeb8ad
// converted property getter: - (unsigned)defaultWorkbookStyleIndex;	// 0x25265d
// converted property setter: - (void)setDefaultWorkbookStyleIndex:(unsigned)index;	// 0xded9d
@end
