/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/CMMapper.h>


__attribute__((visibility("hidden")))
@interface EMAxisMapper : CMMapper {
}
- (id)position;	// 0x2f650d
- (unsigned)type;	// 0x2f6511
- (id)label;	// 0x2f6515
- (float)minValue;	// 0x2f6519
- (float)maxValue;	// 0x2f651d
- (float)unit;	// 0x2f6521
- (bool)isLogarithmic;	// 0x2f6525
- (id)labels;	// 0x2f6529
- (bool)centerLabels;	// 0x2f652d
- (id)values;	// 0x2f6531
- (CGColorRef)strokeColor;	// 0x2f6535
- (float)strokeWidth;	// 0x2f6539
- (CGColorRef)textColor;	// 0x2f653d
@end
