/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface EXContentFormat : XXUnknownSuperclass {
}
+ (id)edContentFormatFromXmlContentFormatElement:(xmlNode *)xmlContentFormatElement;	// 0x1a237d
@end
