/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>
#import <OfficeImport/EXFill.h>


__attribute__((visibility("hidden")))
@interface EXFill : XXUnknownSuperclass {
}
+ (id)edFillFromXmlFillElement:(xmlNode *)xmlFillElement state:(id)state;	// 0x1a3091
+ (id)edFillFromXmlFillElement:(xmlNode *)xmlFillElement differentialFill:(bool)fill state:(id)state;	// 0x1a30b1
@end

@interface EXFill (Private)
+ (id)edPatternFillFromXmlElement:(xmlNode *)xmlElement differentialFill:(bool)fill state:(id)state;	// 0x1a3199
+ (int)edPatternTypeFromXmlPatternTypeString:(id)xmlPatternTypeString;	// 0x1a3391
+ (id)edGradientFillFromXmlElement:(xmlNode *)xmlElement state:(id)state;	// 0x25422d
+ (int)edGradientTypeFromXmlGradientTypeString:(id)xmlGradientTypeString state:(id)state;	// 0x2541dd
+ (id)edStopFromXmlGradientElement:(xmlNode *)xmlGradientElement state:(id)state;	// 0x254399
@end
