/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/EXPane.h>
#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface EXPane : XXUnknownSuperclass {
}
+ (id)edPaneFromXMLPaneElement:(xmlNode *)xmlpaneElement;	// 0x200e59
@end

@interface EXPane (Private)
+ (int)edActivePaneEnumFromString:(id)string;	// 0x200fcd
@end
