/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/EXPivotTable.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface EXPivotTable : XXUnknownSuperclass {
}
+ (id)edPivotTableFromXmlPivotTableElement:(xmlNode *)xmlPivotTableElement state:(id)state;	// 0x209df5
@end

@interface EXPivotTable (Private)
+ (void)readStyleInfoFrom:(xmlNode *)from toPivotTable:(id)pivotTable;	// 0x20af99
+ (void)readLocationFrom:(xmlNode *)from toPivotTable:(id)pivotTable;	// 0x20ada1
+ (void)readFieldsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20bc89
+ (void)readItemsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20bd55
+ (void)readPivotFieldsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20b1d9
+ (void)readFieldItemsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20b6f5
+ (void)readDataFieldsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20c149
+ (void)readConditionalFormatsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20c57d
+ (void)readPivotAreasFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20c72d
+ (void)readPivotAreaReferencesFrom:(xmlNode *)from toCollection:(id)collection;	// 0x25476d
+ (void)readPageFieldsFrom:(xmlNode *)from toCollection:(id)collection;	// 0x20c019
+ (int)edPivotItemTypeFrom:(id)from;	// 0x20bab5
+ (int)edPivotFieldAxisFrom:(id)from;	// 0x20b5f9
+ (int)edPivotDatFieldFormatFrom:(id)from;	// 0x20c451
+ (int)edPivotConditionalFormatTypeFrom:(id)from;	// 0x2545bd
+ (int)edPivotConditionalFormatScopeFrom:(id)from;	// 0x254645
+ (int)edPivotAreaTypeFrom:(id)from;	// 0x2546b1
@end
