/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/NSCopying.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface OADBevel : XXUnknownSuperclass <NSCopying> {
@private
	int mType;	// 4 = 0x4
	float mWidth;	// 8 = 0x8
	float mHeight;	// 12 = 0xc
}
@property(assign) int type;	// G=0x2ae1b1; S=0x1dc505; converted property
@property(assign) float width;	// G=0x2ae1c1; S=0x1cbf7d; converted property
@property(assign) float height;	// G=0x2ae1d1; S=0x1cbf8d; converted property
- (id)init;	// 0x1cbf1d
- (id)copyWithZone:(NSZone *)zone;	// 0x2ae38d
// converted property getter: - (int)type;	// 0x2ae1b1
// converted property setter: - (void)setType:(int)type;	// 0x1dc505
// converted property getter: - (float)width;	// 0x2ae1c1
// converted property setter: - (void)setWidth:(float)width;	// 0x1cbf7d
// converted property getter: - (float)height;	// 0x2ae1d1
// converted property setter: - (void)setHeight:(float)height;	// 0x1cbf8d
- (unsigned)hash;	// 0x2ae1e1
- (BOOL)isEqual:(id)equal;	// 0x2ae2a9
@end
