/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OADPattern.h>

@class OADBlipRef;

__attribute__((visibility("hidden")))
@interface OADCustomPattern : OADPattern {
@private
	OADBlipRef *mBlipRef;	// 12 = 0xc
	BOOL mIsBlipRefOverridden;	// 16 = 0x10
}
@property(retain) id blipRef;	// G=0x2a2601; S=0x1d92a9; converted property
+ (id)defaultProperties;	// 0x1d9219
- (id)copyWithZone:(NSZone *)zone;	// 0x2a2569
- (void)dealloc;	// 0x1d9541
- (id)initWithDefaults;	// 0x1d9261
// converted property getter: - (id)blipRef;	// 0x2a2601
// converted property setter: - (void)setBlipRef:(id)ref;	// 0x1d92a9
- (BOOL)isBlipRefOverridden;	// 0x2a2631
- (unsigned)hash;	// 0x2a2755
- (BOOL)isEqual:(id)equal;	// 0x2a2669
@end
