/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OADDash.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface OADCustomDash : OADDash {
@private
	NSMutableArray *mStops;	// 12 = 0xc
	unsigned mAreStopsOverridden : 1;	// 16 = 0x10
}
@property(retain) id stops;	// G=0x2a66bd; S=0x14ae99; converted property
+ (id)defaultProperties;	// 0x14ae09
- (id)copyWithZone:(NSZone *)zone;	// 0x2a6649
- (id)initWithDefaults;	// 0x14ae51
- (void)dealloc;	// 0x14e465
- (unsigned)stopCount;	// 0x14b03d
- (float)dashAtIndex:(unsigned)index;	// 0x14b05d
- (float)spaceAtIndex:(unsigned)index;	// 0x14b0a9
- (void)addStopWithDash:(float)dash space:(float)space;	// 0x14af0d
// converted property getter: - (id)stops;	// 0x2a66bd
// converted property setter: - (void)setStops:(id)stops;	// 0x14ae99
- (BOOL)areStopsOverridden;	// 0x2a66ed
- (unsigned)hash;	// 0x2a6729
- (BOOL)isEqual:(id)equal;	// 0x2a6769
@end
