/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/NSCopying.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface OADRelativeRect : XXUnknownSuperclass <NSCopying> {
@private
	float mLeft;	// 4 = 0x4
	float mTop;	// 8 = 0x8
	float mRight;	// 12 = 0xc
	float mBottom;	// 16 = 0x10
}
@property(assign) float left;	// G=0xc6825; S=0xc6e6d; converted property
@property(assign) float top;	// G=0xc6845; S=0xcf415; converted property
@property(assign) float right;	// G=0xc6835; S=0xc6e91; converted property
@property(assign) float bottom;	// G=0xc6855; S=0xcf439; converted property
- (id)init;	// 0xc6e35
- (id)initWithLeft:(float)left top:(float)top right:(float)right bottom:(float)bottom;	// 0xc2241
- (id)copyWithZone:(NSZone *)zone;	// 0x1e90e5
// converted property getter: - (float)left;	// 0xc6825
// converted property setter: - (void)setLeft:(float)left;	// 0xc6e6d
// converted property getter: - (float)top;	// 0xc6845
// converted property setter: - (void)setTop:(float)top;	// 0xcf415
// converted property getter: - (float)right;	// 0xc6835
// converted property setter: - (void)setRight:(float)right;	// 0xc6e91
// converted property getter: - (float)bottom;	// 0xc6855
// converted property setter: - (void)setBottom:(float)bottom;	// 0xcf439
- (unsigned)hash;	// 0x29c53d
- (BOOL)isEqual:(id)equal;	// 0x29c73d
@end
