/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OADEffect.h>


__attribute__((visibility("hidden")))
@interface OADReflectionEffect : OADEffect {
@private
	float mBlurRadius;	// 8 = 0x8
	float mStartOpacity;	// 12 = 0xc
	float mStartPosition;	// 16 = 0x10
	float mEndOpacity;	// 20 = 0x14
	float mEndPosition;	// 24 = 0x18
	float mDistance;	// 28 = 0x1c
	float mDirection;	// 32 = 0x20
	float mFadeDirection;	// 36 = 0x24
	float mXScale;	// 40 = 0x28
	float mYScale;	// 44 = 0x2c
	float mXSkew;	// 48 = 0x30
	float mYSkew;	// 52 = 0x34
	int mAlignment;	// 56 = 0x38
	BOOL mRotateWithShape;	// 60 = 0x3c
}
@property(assign) float blurRadius;	// G=0x2a5825; S=0x1d1411; converted property
@property(assign) float startOpacity;	// G=0x2a5835; S=0x1d1421; converted property
@property(assign) float startPosition;	// G=0x2a5845; S=0x2a5855; converted property
@property(assign) float endOpacity;	// G=0x2a5865; S=0x1d2e5d; converted property
@property(assign) float endPosition;	// G=0x2a5875; S=0x1d1431; converted property
@property(assign) float distance;	// G=0x2a5885; S=0x1d1441; converted property
@property(assign) float direction;	// G=0x2a5895; S=0x1d1451; converted property
@property(assign) float fadeDirection;	// G=0x2a58a5; S=0x2a58b5; converted property
@property(assign) float xScale;	// G=0x2a58c5; S=0x2a58d5; converted property
@property(assign) float yScale;	// G=0x2a58e5; S=0x1d1461; converted property
@property(assign) float xSkew;	// G=0x2a58f5; S=0x2a5905; converted property
@property(assign) float ySkew;	// G=0x2a5915; S=0x2a5925; converted property
@property(assign) int alignment;	// G=0x2a5935; S=0x1d1821; converted property
@property(assign) BOOL rotateWithShape;	// G=0x2a5945; S=0x1d1471; converted property
- (id)init;	// 0x1d0ed5
- (id)copyWithZone:(NSZone *)zone;	// 0x2a5e41
- (void)setStyleColor:(id)color;	// 0x2a5821
// converted property getter: - (float)blurRadius;	// 0x2a5825
// converted property setter: - (void)setBlurRadius:(float)radius;	// 0x1d1411
// converted property getter: - (float)startOpacity;	// 0x2a5835
// converted property setter: - (void)setStartOpacity:(float)opacity;	// 0x1d1421
// converted property getter: - (float)startPosition;	// 0x2a5845
// converted property setter: - (void)setStartPosition:(float)position;	// 0x2a5855
// converted property getter: - (float)endOpacity;	// 0x2a5865
// converted property setter: - (void)setEndOpacity:(float)opacity;	// 0x1d2e5d
// converted property getter: - (float)endPosition;	// 0x2a5875
// converted property setter: - (void)setEndPosition:(float)position;	// 0x1d1431
// converted property getter: - (float)distance;	// 0x2a5885
// converted property setter: - (void)setDistance:(float)distance;	// 0x1d1441
// converted property getter: - (float)direction;	// 0x2a5895
// converted property setter: - (void)setDirection:(float)direction;	// 0x1d1451
// converted property getter: - (float)fadeDirection;	// 0x2a58a5
// converted property setter: - (void)setFadeDirection:(float)direction;	// 0x2a58b5
// converted property getter: - (float)xScale;	// 0x2a58c5
// converted property setter: - (void)setXScale:(float)scale;	// 0x2a58d5
// converted property getter: - (float)yScale;	// 0x2a58e5
// converted property setter: - (void)setYScale:(float)scale;	// 0x1d1461
// converted property getter: - (float)xSkew;	// 0x2a58f5
// converted property setter: - (void)setXSkew:(float)skew;	// 0x2a5905
// converted property getter: - (float)ySkew;	// 0x2a5915
// converted property setter: - (void)setYSkew:(float)skew;	// 0x2a5925
// converted property getter: - (int)alignment;	// 0x2a5935
// converted property setter: - (void)setAlignment:(int)alignment;	// 0x1d1821
// converted property getter: - (BOOL)rotateWithShape;	// 0x2a5945
// converted property setter: - (void)setRotateWithShape:(BOOL)shape;	// 0x1d1471
- (unsigned)hash;	// 0x2a5c91
- (BOOL)isEqual:(id)equal;	// 0x2a5955
@end
