/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OADColor.h>


__attribute__((visibility("hidden")))
@interface OADSystemColor : OADColor {
@private
	int mSystemColorID;	// 8 = 0x8
}
- (id)initWithSystemColorID:(int)systemColorID;	// 0x187eb5
- (id)copyWithZone:(NSZone *)zone;	// 0x29fc75
- (int)systemColorID;	// 0x29f565
- (unsigned)hash;	// 0x29fc39
- (BOOL)isEqual:(id)equal;	// 0x29fb95
@end
