/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OADLinkedMediaFile.h>


__attribute__((visibility("hidden")))
@interface OADVideoFile : OADLinkedMediaFile {
}
@end
