/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OAICOrientedBounds.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface OAICOrientedBounds : XXUnknownSuperclass {
}
+ (id)absoluteOrientedBoundsOfDrawable:(id)drawable;	// 0x2bcde1
+ (id)adjustedOrientedBoundsWithOrientedBounds:(id)orientedBounds;	// 0x2bceed
+ (CGAffineTransform)transformFromBounds:(CGRect)bounds toOrientedBounds:(id)orientedBounds;	// 0x2bd391
+ (id)absoluteOrientedBoundsWithRelativeOrientedBounds:(id)relativeOrientedBounds parentOrientedBounds:(id)bounds parentLogicalBounds:(CGRect)bounds3;	// 0x2bd66d
+ (id)relativeOrientedBoundsOfDrawable:(id)drawable;	// 0x2bd03d
+ (CGRect)axisParallelBoundsOfOrientedBounds:(id)orientedBounds;	// 0x2bd9e9
@end

@interface OAICOrientedBounds (Private)
+ (float)scaleFactorFromLength:(float)length toLength:(float)length2;	// 0x2bcdb5
+ (id)adjustedOrientedBoundsWithOrientedBounds:(id)orientedBounds logicalBounds:(CGRect)bounds;	// 0x2bd205
@end
