/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OAXParagraph.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface OAXParagraph : XXUnknownSuperclass {
}
+ (void)readParagraph:(xmlNode *)paragraph paragraph:(id)paragraph2 drawingState:(id)state;	// 0x1ae9bd
@end

@interface OAXParagraph (Private)
@end
