/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OAXTextParaPropertyBag.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface OAXTextParaPropertyBag : XXUnknownSuperclass {
}
+ (void)readParagraphProperties:(xmlNode *)properties paragraphProperties:(id)properties2 drawingState:(id)state;	// 0x1ab371
@end

@interface OAXTextParaPropertyBag (Private)
+ (id)readSpacing:(xmlNode *)spacing;	// 0x1acca5
+ (void)readTabList:(xmlNode *)list paragraphProperties:(id)properties;	// 0x1c651d
+ (void)readAlign:(id)align paragraphProperties:(id)properties;	// 0x1abd4d
+ (void)readFontAlign:(id)align paragraphProperties:(id)properties;	// 0x1c55f9
+ (int)readBulletScheme:(id)scheme;	// 0x1cfc01
@end
