/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/ODICycle5.h>


__attribute__((visibility("hidden")))
@interface ODICycle3 : ODICycle5 {
}
+ (void)mapStyleForTransition:(id)transition shape:(id)shape state:(id)state;	// 0x2b22f1
@end
