/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface ODXFillColorList : XXUnknownSuperclass {
}
+ (id)hueDirectionMap;	// 0x1c84d5
+ (id)colorApplicationMethodMap;	// 0x1c85a1
+ (void)readNode:(xmlNode *)node list:(id)list;	// 0x1c8341
@end
