/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/XXUnknownSuperclass.h>
#import <OfficeImport/OfficeImport-Structs.h>

@class ESDRoot, NSMutableDictionary, PDPresentation, PBOfficeArtReaderState, NSMutableArray, PDSlideBase, PBSlideState, SFUNoCopyDictionary, PBOutlineBulletDictionary, OADTheme, ESDContainer, ESDObject;
@protocol OCCancelDelegate;

__attribute__((visibility("hidden")))
@interface PBPresentationReaderState : XXUnknownSuperclass {
@private
	PptBinaryReader *mPptBinaryReader;	// 4 = 0x4
	PDPresentation *mTgtPresentation;	// 8 = 0x8
	ESDRoot *mDocumentRoot;	// 12 = 0xc
	ESDContainer *mSrcSlideListHolder;	// 16 = 0x10
	ChVector<int> *mCurrentSlideTextBlockStartIndexVector;	// 20 = 0x14
	unsigned mSrcSlideId;	// 24 = 0x18
	NSMutableArray *mSlideIndexes;	// 28 = 0x1c
	SFUNoCopyDictionary *mSlideMasterToMasterStyles;	// 32 = 0x20
	CFDictionaryRef mHyperlinkMap;	// 36 = 0x24
	PBOfficeArtReaderState *mOfficeArtState;	// 40 = 0x28
	NSMutableArray *mFontEntities;	// 44 = 0x2c
	PDSlideBase *mTgtSlide;	// 48 = 0x30
	unsigned mTextLength;	// 52 = 0x34
	BOOL mHasCharacterPropertyBulletIndex;	// 56 = 0x38
	unsigned mBulletIndex;	// 60 = 0x3c
	PBOutlineBulletDictionary *mPlaceholderBulletStyles;	// 64 = 0x40
	PBOutlineBulletDictionary *mPlaceholderMacCharStyles;	// 68 = 0x44
	ESDObject *mCurrentBulletStyle;	// 72 = 0x48
	ESDObject *mCurrentMacCharStyle;	// 76 = 0x4c
	ChVector<PBReaderMasterStyleInfo> *mSrcDocMasterStyleInfoVector;	// 80 = 0x50
	ChVector<PBReaderMasterStyleInfo> *mSrcCurrentMasterStyleInfoVector;	// 84 = 0x54
	OADTheme *mDefaultTheme;	// 88 = 0x58
	PBSlideState *mSlideState;	// 92 = 0x5c
	id<OCCancelDelegate> mCancel;	// 96 = 0x60
	BOOL mHasSlideNumberPlaceholder;	// 100 = 0x64
	NSMutableDictionary *mTargetShapeToSourceTextBoxContainerHolderMap;	// 104 = 0x68
}
@property(assign) ESDContainer *sourceSlideListHolder;	// G=0x7e541; S=0xc5225; @synthesize=mSrcSlideListHolder
@property(retain, nonatomic) id<OCCancelDelegate> cancelDelegate;	// G=0x1b523d; S=0xac65d; @synthesize=mCancel
@property(assign) BOOL hasSlideNumberPlaceholder;	// G=0x89b6d; S=0x89b7d; @synthesize=mHasSlideNumberPlaceholder
@property(retain) id documentRoot;	// G=0x83761; S=0xba33d; converted property
@property(retain) id defaultTheme;	// G=0xbf40d; S=0xbeadd; converted property
@property(retain) id tgtSlide;	// G=0xc2919; S=0x9889; converted property
@property(assign) unsigned textLength;	// G=0xb6a79; S=0xb6941; converted property
@property(assign) BOOL hasCharacterPropertyBulletIndex;	// G=0x813a1; S=0x81fd5; converted property
@property(assign) unsigned bulletIndex;	// G=0x21e4dd; S=0x813b1; converted property
- (id)initWithReader:(PptBinaryReader *)reader tgtPresentation:(id)presentation;	// 0xac0d1
- (void)dealloc;	// 0x8c96d
- (PptBinaryReader *)reader;	// 0x83749
// converted property getter: - (id)documentRoot;	// 0x83761
// converted property setter: - (void)setDocumentRoot:(id)root;	// 0xba33d
- (id)tgtPresentation;	// 0xba701
- (int)numberOfSlideIndexes;	// 0xc2b9d
- (void)addSlideIndex:(int)index;	// 0x21e58d
- (int)getSlideIndexAt:(int)at;	// 0x21e5dd
- (id)slideIndexesRef;	// 0x21e4cd
- (id)officeArtState;	// 0x9899
- (unsigned)fontEntityCount;	// 0x21e619
- (void)addFontEntity:(id)entity charSet:(int)set type:(int)type family:(int)family;	// 0xba4b5
- (id)fontEntityAtIndex:(unsigned)index;	// 0x815dd
- (id)baseTextListStyle;	// 0x98a9
// converted property setter: - (void)setDefaultTheme:(id)theme;	// 0xbeadd
// converted property getter: - (id)defaultTheme;	// 0xbf40d
// converted property getter: - (id)tgtSlide;	// 0xc2919
// converted property setter: - (void)setTgtSlide:(id)slide;	// 0x9889
// converted property getter: - (unsigned)textLength;	// 0xb6a79
// converted property setter: - (void)setTextLength:(unsigned)length;	// 0xb6941
// converted property getter: - (BOOL)hasCharacterPropertyBulletIndex;	// 0x813a1
// converted property setter: - (void)setHasCharacterPropertyBulletIndex:(BOOL)index;	// 0x81fd5
// converted property getter: - (unsigned)bulletIndex;	// 0x21e4dd
// converted property setter: - (void)setBulletIndex:(unsigned)index;	// 0x813b1
- (void)setPlaceholderBulletStyles:(id)styles;	// 0x15b815
- (void)setPlaceholderMacCharStyles:(id)styles;	// 0x1b7e09
- (id)currentBulletStyle;	// 0x7ff3d
- (id)currentMacCharStyle;	// 0x81391
- (void)setCurrentTextType:(int)type placeholderIndex:(unsigned long)index;	// 0x7e905
- (void)setCurrentBulletStyle:(id)style macCharStyle:(id)style2;	// 0x7deed
- (void)setMasterStyles:(id)styles slideMaster:(id)master;	// 0xc0df9
- (id)masterStyles:(id)styles;	// 0xc46f5
- (id)slideState;	// 0x21e4ed
- (void)resetSlideState;	// 0x21e639
- (BOOL)hasCurrentSourceMasterStyleInfoVector;	// 0x7fefd
- (void)setCurrentSourceMasterStyleInfoVector:(ChVector<PBReaderMasterStyleInfo> *)vector;	// 0x9349
- (PBReaderMasterStyleInfo *)docSourceMasterStyleInfoOfType:(int)type;	// 0xba6ed
- (PBReaderMasterStyleInfo *)currentSourceMasterStyleInfoOfType:(int)type;	// 0x7ff15
- (ChVector<int> *)currentSlideTextBlockStartIndexVector;	// 0x7df61
- (void)setSourceSlideId:(unsigned long)anId;	// 0x8ca1
- (BOOL)isCancelled;	// 0x8cb1
- (id)hyperlinkInfoWithId:(unsigned long)anId createIfAbsent:(BOOL)absent;	// 0xbc7f5
- (id)sourceTextBoxContainerHolderForTargetShape:(id)targetShape;	// 0x83d7d
- (void)setSourceTextBoxContainerHolder:(id)holder forTargetShape:(id)targetShape;	// 0x14f0dd
// declared property getter: - (BOOL)hasSlideNumberPlaceholder;	// 0x89b6d
// declared property setter: - (void)setHasSlideNumberPlaceholder:(BOOL)placeholder;	// 0x89b7d
// declared property getter: - (id)cancelDelegate;	// 0x1b523d
// declared property setter: - (void)setCancelDelegate:(id)delegate;	// 0xac65d
// declared property getter: - (id)sourceSlideListHolder;	// 0x7e541
// declared property setter: - (void)setSourceSlideListHolder:(id)holder;	// 0xc5225
@end
