/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OCDDocument.h>
#import <OfficeImport/OfficeImport-Structs.h>

@class NSMutableArray, OADTextListStyle, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PDPresentation : OCDDocument {
@private
	NSMutableArray *mSlideMasters;	// 20 = 0x14
	NSMutableArray *mNotesMasters;	// 24 = 0x18
	NSMutableArray *mSlides;	// 28 = 0x1c
	NSMutableArray *mBulletBlips;	// 32 = 0x20
	CGSize mSlideSize;	// 36 = 0x24
	CGSize mNotesSize;	// 44 = 0x2c
	BOOL mIsAutoPlay;	// 52 = 0x34
	BOOL mIsCommentsVisible;	// 53 = 0x35
	BOOL mIsLooping;	// 54 = 0x36
	BOOL mIsKiosk;	// 55 = 0x37
	NSMutableDictionary *mCommentAuthors;	// 56 = 0x38
	OADTextListStyle *mDefaultTextStyle;	// 60 = 0x3c
}
@property(assign) CGSize slideSize;	// G=0x8a39; S=0xbd249; converted property
@property(assign) CGSize notesSize;	// G=0x219885; S=0xbd25d; converted property
@property(assign) BOOL isAutoPlay;	// G=0x21989d; S=0xaba81; converted property
@property(assign) BOOL isCommentsVisible;	// G=0x2198ad; S=0xbd271; converted property
@property(assign) BOOL isLooping;	// G=0x2198bd; S=0x1bea75; converted property
@property(assign) BOOL isKiosk;	// G=0x2198cd; S=0x1bea85; converted property
- (id)init;	// 0xaaa1d
- (void)dealloc;	// 0x8f28d
- (unsigned)slideMasterCount;	// 0x219cdd
- (id)slideMasterAtIndex:(unsigned)index;	// 0x219cb9
- (void)addSlideMaster:(id)master;	// 0xbf70d
- (unsigned)notesMasterCount;	// 0x219c99
- (id)notesMasterAtIndex:(unsigned)index;	// 0x219c75
- (void)addNotesMaster:(id)master;	// 0x1c5719
- (unsigned)slideCount;	// 0x219c55
- (id)slideAtIndex:(unsigned)index;	// 0x219c31
- (void)addSlide:(id)slide;	// 0x219c0d
- (unsigned)indexOfSlide:(id)slide;	// 0x219bbd
- (id)bulletBlipAtIndex:(long)index;	// 0x219b99
- (unsigned long)addBulletBlip:(id)blip;	// 0x17c8d5
- (unsigned long)bulletBlipCount;	// 0x17c911
- (id)bulletBlips;	// 0x1aadc5
// converted property getter: - (CGSize)slideSize;	// 0x8a39
// converted property setter: - (void)setSlideSize:(CGSize)size;	// 0xbd249
// converted property getter: - (CGSize)notesSize;	// 0x219885
// converted property setter: - (void)setNotesSize:(CGSize)size;	// 0xbd25d
// converted property getter: - (BOOL)isAutoPlay;	// 0x21989d
// converted property setter: - (void)setIsAutoPlay:(BOOL)play;	// 0xaba81
// converted property getter: - (BOOL)isCommentsVisible;	// 0x2198ad
// converted property setter: - (void)setIsCommentsVisible:(BOOL)visible;	// 0xbd271
// converted property getter: - (BOOL)isLooping;	// 0x2198bd
// converted property setter: - (void)setIsLooping:(BOOL)looping;	// 0x1bea75
// converted property getter: - (BOOL)isKiosk;	// 0x2198cd
// converted property setter: - (void)setIsKiosk:(BOOL)kiosk;	// 0x1bea85
- (id)commentAuthorForId:(unsigned)anId;	// 0x219b49
- (void)setCommentAuthor:(id)author forId:(unsigned)anId;	// 0x1d55a1
- (id)defaultTextStyle;	// 0xba711
- (void)flushUnusedMastersAndLayouts;	// 0x2198dd
@end
