/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface PXLegacyText : XXUnknownSuperclass {
}
+ (PptTextMasterStyleAtom *)textMasterStyleOfType:(int)type state:(id)state;	// 0x21a9b5
+ (void)readLegacyTextGlobalsFromData:(id)data state:(id)state;	// 0x21ae79
+ (void)readLegacyTextFromData:(id)data toShape:(id)shape state:(id)state;	// 0x21af91
@end
