/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OAXClient.h>
#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/PXOfficeArtClient.h>

@class PXPresentationState;

__attribute__((visibility("hidden")))
@interface PXOfficeArtClient : OAXClient {
@private
	PXPresentationState *mPresentationState;	// 4 = 0x4
}
- (id)initWithState:(id)state;	// 0x1aac61
- (id)presentationState;	// 0x21b7e9
- (void)readClientDataFromShapeNode:(xmlNode *)shapeNode toShape:(id)shape state:(id)state;	// 0x1aeead
- (void)readClientDataFromPictureNode:(xmlNode *)pictureNode toImage:(id)image state:(id)state;	// 0x1b20dd
- (void)readClientDataFromGraphicalFramePropertiesNode:(xmlNode *)graphicalFramePropertiesNode toDrawable:(id)drawable state:(id)state;	// 0x1c72e1
- (id)readClientTextField:(xmlNode *)field paragraph:(id)paragraph state:(id)state;	// 0x1af325
- (void)postprocessHyperlink:(id)hyperlink relationship:(id)relationship state:(id)state;	// 0x1d02b5
- (id)readOle:(xmlNode *)ole state:(id)state;	// 0x1c6e3d
@end

@interface PXOfficeArtClient (Private)
+ (int)readPlaceholderTypeFromNode:(xmlNode *)node;	// 0x1af0d1
+ (int)readPlaceholderBoundsTrackFromNode:(xmlNode *)node;	// 0x1af265
@end
