/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>
#import <OfficeImport/PXPresentation.h>


__attribute__((visibility("hidden")))
@interface PXPresentation : XXUnknownSuperclass {
}
+ (id)readFromArchive:(id)archive asThumbnail:(BOOL)thumbnail delegate:(id)delegate;	// 0x21b7f9
+ (id)readFromData:(id)data asThumbnail:(BOOL)thumbnail delegate:(id)delegate;	// 0x21ba45
+ (id)readFromPackage:(id)package fileName:(id)name reader:(id)reader cancel:(id)cancel asThumbnail:(BOOL)thumbnail delegate:(id)delegate;	// 0x1a9e59
@end

@interface PXPresentation (Private)
+ (CGSize)readSizeFromChildOfElement:(xmlNode *)element childName:(const char *)name;	// 0x1aae41
+ (void)readPresentationProperties:(id)properties to:(id)to;	// 0x1aaee9
+ (void)readSlideIndicesWithPresentationPart:(id)presentationPart presentationState:(id)state;	// 0x1aaff1
@end
