/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OAVState.h>

@class ESDObject, PBPresentationReaderState;

__attribute__((visibility("hidden")))
@interface PXVmlState : OAVState {
@private
	ESDObject *mLegacyTextGlobals;	// 28 = 0x1c
	PBPresentationReaderState *mLegacyPresentationState;	// 32 = 0x20
}
@property(retain) id legacyTextGlobals;	// G=0x21a90d; S=0x21a92d; converted property
@property(retain) id legacyPresentationState;	// G=0x21a91d; S=0x21a971; converted property
- (void)dealloc;	// 0x1b2309
// converted property getter: - (id)legacyTextGlobals;	// 0x21a90d
// converted property setter: - (void)setLegacyTextGlobals:(id)globals;	// 0x21a92d
// converted property getter: - (id)legacyPresentationState;	// 0x21a91d
// converted property setter: - (void)setLegacyPresentationState:(id)state;	// 0x21a971
@end
