/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface WBSymbol : XXUnknownSuperclass {
}
+ (void)readFrom:(id)from textRun:(WrdCharacterTextRun *)run paragraph:(id)paragraph symbol:(id)symbol;	// 0x1b8749
@end
