/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/XXUnknownSuperclass.h>
#import <OfficeImport/WDAContent.h>
#import <OfficeImport/OADClient.h>
#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/OADTextClient.h>

@class WDAAnchor, OADDrawable, WDATextBox;

__attribute__((visibility("hidden")))
@interface WDAContent : XXUnknownSuperclass <OADClient, OADTextClient> {
@private
	WDAAnchor *mAnchor;	// 4 = 0x4
	WDATextBox *mTextBox;	// 8 = 0x8
	OADDrawable *mDrawable;	// 12 = 0xc
	int mTextType;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) WDAAnchor *anchor;	// G=0x138cf5; @synthesize=mAnchor
@property(assign) CGRect bounds;	// G=0x94ffd; S=0x286a75; converted property
@property(retain) id textBox;	// G=0x145155; S=0x139449; converted property
@property(retain) id drawable;	// G=0x1394d5; S=0x138ac9; converted property
@property(assign) int textType;	// G=0x141e01; S=0x138ae9; converted property
- (id)init;	// 0x138a89
- (void)dealloc;	// 0xa2d79
- (id)createAnchor;	// 0x138b75
- (void)clearAnchor;	// 0x1bd955
- (id)createTextBoxWithDocument:(id)document textType:(int)type;	// 0x286aa1
- (BOOL)hasBounds;	// 0x2869a1
// converted property getter: - (CGRect)bounds;	// 0x94ffd
// converted property setter: - (void)setBounds:(CGRect)bounds;	// 0x286a75
// converted property getter: - (id)textBox;	// 0x145155
// converted property setter: - (void)setTextBox:(id)box;	// 0x139449
// converted property getter: - (id)drawable;	// 0x1394d5
// converted property setter: - (void)setDrawable:(id)drawable;	// 0x138ac9
- (bool)isShape;	// 0x144ac1
- (bool)isLine;	// 0x286a31
- (bool)isTopLevelObject;	// 0x286a01
// converted property getter: - (int)textType;	// 0x141e01
// converted property setter: - (void)setTextType:(int)type;	// 0x138ae9
- (BOOL)floating;	// 0x196761
- (BOOL)hasText;	// 0x2869b9
// declared property getter: - (id)anchor;	// 0x138cf5
@end

@interface WDAContent (Private)
+ (Class)classForType:(unsigned short)type;	// 0x286b81
@end
