/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/WDIterator.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface WDArrayIterator : WDIterator {
@private
	NSArray *mArray;	// 4 = 0x4
	unsigned mNextIndex;	// 8 = 0x8
}
- (id)initWithArray:(id)array;	// 0x28d245
- (BOOL)hasNext;	// 0x28d2fd
- (id)next;	// 0x28d295
@end
