/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/WDPicture.h>


__attribute__((visibility("hidden")))
@interface WDOleObject : WDPicture {
}
- (int)runType;	// 0x941f5
@end
