/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/XXUnknownSuperclass.h>

@class OADDrawable;

__attribute__((visibility("hidden")))
@interface WDStory : XXUnknownSuperclass {
@private
	OADDrawable *mHead;	// 4 = 0x4
	BOOL mOle;	// 8 = 0x8
}
@property(assign, getter=isOle) BOOL ole;	// G=0x295979; S=0x295969; converted property
- (id)initWithHead:(id)head;	// 0x295989
- (void)dealloc;	// 0x295a45
- (id)head;	// 0x295959
- (id)text;	// 0x2959e1
// converted property setter: - (void)setOle:(BOOL)ole;	// 0x295969
// converted property getter: - (BOOL)isOle;	// 0x295979
@end
