/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/CMBordersProperty.h>


__attribute__((visibility("hidden")))
@interface WMBordersProperty : CMBordersProperty {
@private
	unsigned mBorderCustomWidth[5];	// 72 = 0x48
}
- (id)init;	// 0x1428dd
- (void)setBorder:(id)border location:(int)location;	// 0x142991
@end
