/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/MFReader.h>
#import <OfficeImport/XXUnknownSuperclass.h>

@class WMFPlayer;

__attribute__((visibility("hidden")))
@interface WMFReader : XXUnknownSuperclass <MFReader> {
@private
	int m_recordsRead;	// 4 = 0x4
	WMFPlayer *m_player;	// 8 = 0x8
	unsigned m_length;	// 12 = 0xc
	char *m_pBuffer;	// 16 = 0x10
	unsigned m_cursor;	// 20 = 0x14
}
- (id)initWithWMFPlayer:(id)wmfplayer;	// 0x972f1
- (void)dealloc;	// 0x92049
- (oneway void)release;	// 0x9201d
- (int)play:(id)play;	// 0x9731d
- (int)playHeaders;	// 0x973f9
- (int)playRecord;	// 0x98049
- (int)checkBytesAvailable:(unsigned)available;	// 0x974c1
- (int)moveDataCursor:(unsigned)cursor;	// 0x9801d
@end
