/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <OfficeImport/OfficeImport-Structs.h>
#import <OfficeImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface WXTextBox : XXUnknownSuperclass {
}
+ (id)readFrom:(xmlNode *)from parent:(id)parent state:(id)state;	// 0x19f9b5
@end
