/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import <MIME/XXUnknownSuperclass.h>
#import <MIME/MFLockObject.h>

@class NSString;

@interface MFRecursiveLock : XXUnknownSuperclass <MFLockObject> {
	NSString *_name;	// 8 = 0x8
	id _delegate;	// 12 = 0xc
}
+ (void)initialize;	// 0x1f511
- (id)init;	// 0x1e8f1
- (id)initWithName:(id)name andDelegate:(id)delegate;	// 0x1f4a9
- (BOOL)isLockedByMe;	// 0x1f089
- (void)lock;	// 0x1f6f1
- (BOOL)tryLock;	// 0x1f68d
- (BOOL)lockBeforeDate:(id)date;	// 0x1f625
- (void)unlock;	// 0x1f5f1
- (id)description;	// 0x1f575
- (void)dealloc;	// 0x1f529
@end
