/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <AppSupport/XXUnknownSuperclass.h>

@class NSString;

@interface CPNotificationObservationHelper : XXUnknownSuperclass {
@private
	id _observer;	// 4 = 0x4
	id _object;	// 8 = 0x8
	id _block;	// 12 = 0xc
	NSString *_name;	// 16 = 0x10
}
- (id)initWithObserver:(id)observer name:(id)name object:(id)object block:(id)block;	// 0x20621
- (void)dealloc;	// 0x206e9
- (void)_notification:(id)notification;	// 0x205f9
@end
