/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import <MusicLibrary/NSCopying.h>
#import <MusicLibrary/XXUnknownSuperclass.h>
#import <MusicLibrary/MusicLibrary-Structs.h>

@class NSData, NSURL, NSString;

@interface MLTrackImportChapter : XXUnknownSuperclass <NSCopying> {
@private
	NSData *_imageData;	// 4 = 0x4
	NSString *_imageCacheKey;	// 8 = 0x8
	unsigned _startTimeInMilliseconds;	// 12 = 0xc
	NSString *_title;	// 16 = 0x10
	NSURL *_url;	// 20 = 0x14
	NSString *_urlTitle;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *URLTitle;	// G=0x398f9; S=0x39909; @synthesize=_urlTitle
@property(copy, nonatomic) NSURL *URL;	// G=0x398c5; S=0x398d5; @synthesize=_url
@property(copy, nonatomic) NSString *title;	// G=0x39891; S=0x398a1; @synthesize=_title
@property(assign, nonatomic) unsigned startTimeInMilliseconds;	// G=0x39871; S=0x39881; @synthesize=_startTimeInMilliseconds
@property(copy, nonatomic) NSString *imageCacheKey;	// G=0x3992d; S=0x3993d; @synthesize=_imageCacheKey
@property(copy, nonatomic) NSData *imageData;	// G=0x3983d; S=0x3984d; @synthesize=_imageData
// declared property setter: - (void)setImageCacheKey:(id)key;	// 0x3993d
// declared property getter: - (id)imageCacheKey;	// 0x3992d
// declared property setter: - (void)setURLTitle:(id)title;	// 0x39909
// declared property getter: - (id)URLTitle;	// 0x398f9
// declared property setter: - (void)setURL:(id)url;	// 0x398d5
// declared property getter: - (id)URL;	// 0x398c5
// declared property setter: - (void)setTitle:(id)title;	// 0x398a1
// declared property getter: - (id)title;	// 0x39891
// declared property setter: - (void)setStartTimeInMilliseconds:(unsigned)milliseconds;	// 0x39881
// declared property getter: - (unsigned)startTimeInMilliseconds;	// 0x39871
// declared property setter: - (void)setImageData:(id)data;	// 0x3984d
// declared property getter: - (id)imageData;	// 0x3983d
- (BOOL)isEqualIgnoringTimesAndTitle:(id)title;	// 0x39725
- (int)compare:(id)compare;	// 0x396ed
- (id)copyWithZone:(NSZone *)zone;	// 0x39601
- (id)description;	// 0x39225
- (void)dealloc;	// 0x39189
@end
