/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <PhotoLibrary/XXUnknownSuperclass.h>
#import <PhotoLibrary/PhotoLibrary-Structs.h>

@class UIView;

@interface PLCropOverlayLayer : XXUnknownSuperclass {
	CGRect _cropRect;	// 48 = 0x30
	UIView *_topOpaqueLayer;	// 64 = 0x40
	UIView *_bottomOpaqueLayer;	// 68 = 0x44
	UIView *_rightOpaqueLayer;	// 72 = 0x48
	UIView *_leftOpaqueLayer;	// 76 = 0x4c
	UIView *_topEdgeLayer;	// 80 = 0x50
	UIView *_bottomEdgeLayer;	// 84 = 0x54
	UIView *_rightEdgeLayer;	// 88 = 0x58
	UIView *_leftEdgeLayer;	// 92 = 0x5c
	UIView *_topLeftCornerLayer;	// 96 = 0x60
	UIView *_topRightCornerLayer;	// 100 = 0x64
	UIView *_bottomRightCornerLayer;	// 104 = 0x68
	UIView *_bottomLeftCornerLayer;	// 108 = 0x6c
	UIView *_topThirdLayer;	// 112 = 0x70
	UIView *_bottomThirdLayer;	// 116 = 0x74
	UIView *_rightThirdLayer;	// 120 = 0x78
	UIView *_leftThirdLayer;	// 124 = 0x7c
	UIView *_straightenHorizontalLayers[6];	// 128 = 0x80
	UIView *_straightenVerticalLayers[6];	// 152 = 0x98
	unsigned _showsCropRect : 1;	// 176 = 0xb0
	unsigned _showThirdsGrid : 1;	// 176 = 0xb0
	unsigned _showsStraightenGrid : 1;	// 176 = 0xb0
	unsigned _thirdsVisible : 1;	// 176 = 0xb0
	unsigned _highlighted : 1;	// 176 = 0xb0
}
@property(assign) CGRect cropRect;	// G=0x23471; S=0x22501; converted property
@property(assign, getter=isHighlighted) BOOL highlighted;	// G=0xd0c19; S=0xd0b5d; converted property
@property(assign) BOOL showsCropRect;	// G=0xd0a61; S=0x20ded; converted property
// converted property getter: - (CGRect)cropRect;	// 0x23471
// converted property setter: - (void)setCropRect:(CGRect)rect;	// 0x22501
// converted property getter: - (BOOL)isHighlighted;	// 0xd0c19
// converted property setter: - (void)setHighlighted:(BOOL)highlighted;	// 0xd0b5d
- (BOOL)showsStraightenGrid;	// 0xd0b49
- (void)showStraightenGrid:(BOOL)grid;	// 0xd0a89
- (BOOL)showsThirdsGrid;	// 0xd0a75
- (void)showThirdsGrid:(BOOL)grid;	// 0x29735
// converted property getter: - (BOOL)showsCropRect;	// 0xd0a61
// converted property setter: - (void)setShowsCropRect:(BOOL)rect;	// 0x20ded
- (void)_updateCropRectVisibility;	// 0x20b6d
- (void)_updateLayout;	// 0x225bd
- (void)dealloc;	// 0x2c1c1
- (id)initWithFrame:(CGRect)frame;	// 0x20009
@end
