/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <PhotoLibrary/XXUnknownSuperclass.h>


@interface PLStackedImageView : XXUnknownSuperclass {
}
+ (Class)layer;	// 0xd74fd
- (id)replicatorLayer;	// 0xd7519
@end
