/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

#import <PhotoLibrary/XXUnknownSuperclass.h>


@interface TrimVideoNavigationItem : XXUnknownSuperclass {
}
- (int)barStyle;	// 0x6f48d
@end
