/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <GMM/XXUnknownSuperclass.h>
#import <GMM/GMM-Structs.h>


@interface GMMClientCapabilities : XXUnknownSuperclass {
	BOOL _hasMaxImageWidth;	// 4 = 0x4
	int _maxImageWidth;	// 8 = 0x8
	BOOL _hasMaxImageHeight;	// 12 = 0xc
	int _maxImageHeight;	// 16 = 0x10
	BOOL _hasAvailableImageMemory;	// 20 = 0x14
	int _availableImageMemory;	// 24 = 0x18
	XXStruct_WmZAAA _preferredImageFormats;	// 28 = 0x1c
	BOOL _hasHtmlBodyOnly;	// 40 = 0x28
	BOOL _htmlBodyOnly;	// 41 = 0x29
	BOOL _hasEmbedImages;	// 42 = 0x2a
	BOOL _embedImages;	// 43 = 0x2b
}
@property(assign, nonatomic) BOOL embedImages;	// G=0x12395; S=0x123b9; @synthesize=_embedImages
@property(assign, nonatomic) BOOL hasEmbedImages;	// G=0x12a3d; S=0x12a4d; @synthesize=_hasEmbedImages
@property(assign, nonatomic) BOOL htmlBodyOnly;	// G=0x1234d; S=0x12371; @synthesize=_htmlBodyOnly
@property(assign, nonatomic) BOOL hasHtmlBodyOnly;	// G=0x12a1d; S=0x12a2d; @synthesize=_hasHtmlBodyOnly
@property(readonly, assign, nonatomic) int *preferredImageFormats;	// G=0x12259; 
@property(readonly, assign, nonatomic) unsigned preferredImageFormatsCount;	// G=0x12245; 
@property(assign, nonatomic) int availableImageMemory;	// G=0x12a0d; S=0x12221; @synthesize=_availableImageMemory
@property(assign, nonatomic) BOOL hasAvailableImageMemory;	// G=0x129ed; S=0x129fd; @synthesize=_hasAvailableImageMemory
@property(assign, nonatomic) int maxImageHeight;	// G=0x129dd; S=0x121fd; @synthesize=_maxImageHeight
@property(assign, nonatomic) BOOL hasMaxImageHeight;	// G=0x129bd; S=0x129cd; @synthesize=_hasMaxImageHeight
@property(assign, nonatomic) int maxImageWidth;	// G=0x129ad; S=0x121d9; @synthesize=_maxImageWidth
@property(assign, nonatomic) BOOL hasMaxImageWidth;	// G=0x1298d; S=0x1299d; @synthesize=_hasMaxImageWidth
// declared property setter: - (void)setHasEmbedImages:(BOOL)images;	// 0x12a4d
// declared property getter: - (BOOL)hasEmbedImages;	// 0x12a3d
// declared property setter: - (void)setHasHtmlBodyOnly:(BOOL)only;	// 0x12a2d
// declared property getter: - (BOOL)hasHtmlBodyOnly;	// 0x12a1d
// declared property getter: - (int)availableImageMemory;	// 0x12a0d
// declared property setter: - (void)setHasAvailableImageMemory:(BOOL)memory;	// 0x129fd
// declared property getter: - (BOOL)hasAvailableImageMemory;	// 0x129ed
// declared property getter: - (int)maxImageHeight;	// 0x129dd
// declared property setter: - (void)setHasMaxImageHeight:(BOOL)height;	// 0x129cd
// declared property getter: - (BOOL)hasMaxImageHeight;	// 0x129bd
// declared property getter: - (int)maxImageWidth;	// 0x129ad
// declared property setter: - (void)setHasMaxImageWidth:(BOOL)width;	// 0x1299d
// declared property getter: - (BOOL)hasMaxImageWidth;	// 0x1298d
- (void)writeTo:(id)to;	// 0x12841
- (BOOL)readFrom:(id)from;	// 0x12649
- (id)dictionaryRepresentation;	// 0x1244d
- (id)description;	// 0x123dd
// declared property setter: - (void)setEmbedImages:(BOOL)images;	// 0x123b9
// declared property getter: - (BOOL)embedImages;	// 0x12395
// declared property setter: - (void)setHtmlBodyOnly:(BOOL)only;	// 0x12371
// declared property getter: - (BOOL)htmlBodyOnly;	// 0x1234d
- (void)setPreferredImageFormats:(int *)formats count:(unsigned)count;	// 0x12335
- (int)preferredImageFormatAtIndex:(unsigned)index;	// 0x12291
- (void)addPreferredImageFormat:(int)format;	// 0x1227d
- (void)clearPreferredImageFormats;	// 0x12269
// declared property getter: - (int *)preferredImageFormats;	// 0x12259
// declared property getter: - (unsigned)preferredImageFormatsCount;	// 0x12245
// declared property setter: - (void)setAvailableImageMemory:(int)memory;	// 0x12221
// declared property setter: - (void)setMaxImageHeight:(int)height;	// 0x121fd
// declared property setter: - (void)setMaxImageWidth:(int)width;	// 0x121d9
- (void)dealloc;	// 0x12199
@end
