/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <GMM/XXUnknownSuperclass.h>
#import <GMM/GMM-Structs.h>

@class GMMClientCapabilities;

__attribute__((visibility("hidden")))
@interface GMMDirectionsIconRequest : XXUnknownSuperclass {
	GMMClientCapabilities *_capabilities;	// 4 = 0x4
	BOOL _hasCachedIconVersion;	// 8 = 0x8
	int _cachedIconVersion;	// 12 = 0xc
	XXStruct_19EQxD _cachedIconIDs;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) long long *cachedIconIDs;	// G=0x1cb21; 
@property(readonly, assign, nonatomic) unsigned cachedIconIDsCount;	// G=0x1cb0d; 
@property(assign, nonatomic) int cachedIconVersion;	// G=0x1cac5; S=0x1cae9; @synthesize=_cachedIconVersion
@property(assign, nonatomic) BOOL hasCachedIconVersion;	// G=0x1d101; S=0x1d111; @synthesize=_hasCachedIconVersion
@property(retain, nonatomic) GMMClientCapabilities *capabilities;	// G=0x1d0cd; S=0x1d0dd; @synthesize=_capabilities
@property(readonly, assign, nonatomic) BOOL hasCapabilities;	// G=0x1caad; 
// declared property setter: - (void)setHasCachedIconVersion:(BOOL)version;	// 0x1d111
// declared property getter: - (BOOL)hasCachedIconVersion;	// 0x1d101
// declared property setter: - (void)setCapabilities:(id)capabilities;	// 0x1d0dd
// declared property getter: - (id)capabilities;	// 0x1d0cd
- (void)writeTo:(id)to;	// 0x1cfad
- (BOOL)readFrom:(id)from;	// 0x1cd69
- (id)dictionaryRepresentation;	// 0x1cc8d
- (id)description;	// 0x1cc1d
- (void)setCachedIconIDs:(long long *)ids count:(unsigned)count;	// 0x1cc05
- (long long)cachedIconIDAtIndex:(unsigned)index;	// 0x1cb5d
- (void)addCachedIconID:(long long)anId;	// 0x1cb45
- (void)clearCachedIconIDs;	// 0x1cb31
// declared property getter: - (long long *)cachedIconIDs;	// 0x1cb21
// declared property getter: - (unsigned)cachedIconIDsCount;	// 0x1cb0d
// declared property setter: - (void)setCachedIconVersion:(int)version;	// 0x1cae9
// declared property getter: - (int)cachedIconVersion;	// 0x1cac5
// declared property getter: - (BOOL)hasCapabilities;	// 0x1caad
- (void)dealloc;	// 0x1ca59
@end
