/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <GMM/GMMTrip.h>
#import <GMM/XXUnknownSuperclass.h>

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface GMMTrip : XXUnknownSuperclass {
	NSMutableArray *_routes;	// 4 = 0x4
	NSString *_tripSummary;	// 8 = 0x8
	BOOL _hasDetailLevel;	// 12 = 0xc
	int _detailLevel;	// 16 = 0x10
}
@property(assign, nonatomic) int detailLevel;	// G=0x25ad5; S=0x25af9; @synthesize=_detailLevel
@property(assign, nonatomic) BOOL hasDetailLevel;	// G=0x25ff9; S=0x26009; @synthesize=_hasDetailLevel
@property(retain, nonatomic) NSString *tripSummary;	// G=0x25fc5; S=0x25fd5; @synthesize=_tripSummary
@property(readonly, assign, nonatomic) BOOL hasTripSummary;	// G=0x25abd; 
@property(retain, nonatomic) NSMutableArray *routes;	// G=0x25f91; S=0x25fa1; @synthesize=_routes
// declared property setter: - (void)setHasDetailLevel:(BOOL)level;	// 0x26009
// declared property getter: - (BOOL)hasDetailLevel;	// 0x25ff9
// declared property setter: - (void)setTripSummary:(id)summary;	// 0x25fd5
// declared property getter: - (id)tripSummary;	// 0x25fc5
// declared property setter: - (void)setRoutes:(id)routes;	// 0x25fa1
// declared property getter: - (id)routes;	// 0x25f91
- (void)writeTo:(id)to;	// 0x25e29
- (BOOL)readFrom:(id)from;	// 0x25c65
- (id)dictionaryRepresentation;	// 0x25b8d
- (id)description;	// 0x25b1d
// declared property setter: - (void)setDetailLevel:(int)level;	// 0x25af9
// declared property getter: - (int)detailLevel;	// 0x25ad5
// declared property getter: - (BOOL)hasTripSummary;	// 0x25abd
- (id)routeAtIndex:(unsigned)index;	// 0x25a9d
- (unsigned)routesCount;	// 0x25a7d
- (void)addRoute:(id)route;	// 0x25a19
- (void)dealloc;	// 0x259c1
@end

@interface GMMTrip (Descriptions)
- (id)description;	// 0xa74d
@end

@interface GMMTrip (GMMGEODirectionsProvider_Extras)
- (id)altDescription;	// 0x3e9a1
@end
