/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

#import <HomeSharing/HomeSharing-Structs.h>
#import <HomeSharing/XXUnknownSuperclass.h>


@interface HSResponseDataParser : XXUnknownSuperclass {
}
+ (id)_parseListingItemWithBytes:(const char *)bytes length:(unsigned)length usingHandler:(id)handler;	// 0x8bd9
+ (id)_parseItemIDArrayWithBytes:(const char *)bytes length:(unsigned)length;	// 0x8af1
+ (id)_parseBrowseListingWithBytes:(const char *)bytes length:(unsigned)length;	// 0x89ed
+ (id)_parseListingCollectionWithBytes:(const char *)bytes length:(unsigned)length usingHandler:(id)handler;	// 0x88f9
+ (id)_parseItemsResponseWithBytes:(const char *)bytes length:(unsigned)length usingHandler:(id)handler;	// 0x8601
+ (id)_parseEditCommandResponseWithBytes:(const char *)bytes length:(unsigned)length;	// 0x84a1
+ (id)_parseDictionaryCollectionWithBytes:(const char *)bytes length:(unsigned)length;	// 0x8329
+ (id)_parseDeletedIDListingWithBytes:(const char *)bytes length:(unsigned)length;	// 0x823d
+ (id)_parseCloudArtworkInfoResponseWithBytes:(const char *)bytes length:(unsigned)length;	// 0x815d
+ (id)_parseBulkCloudArtworkInfoResponseWithBytes:(const char *)bytes length:(unsigned)length;	// 0x80a5
+ (id)_parseAuthorizedAccountTokenWithBytes:(const char *)bytes length:(unsigned)length;	// 0x7e9d
+ (id)_parseUpdateResponseWithBytes:(const char *)bytes length:(unsigned)length;	// 0x7d15
+ (id)_parseLoginResponseWithBytes:(const char *)bytes length:(unsigned)length;	// 0x7b8d
+ (id)_parseResponseCode:(unsigned)code bytes:(const char *)bytes length:(unsigned)length usingHandler:(id)handler;	// 0x79ed
+ (unsigned)_parseItemPropertyCountWithBytes:(const char *)bytes length:(unsigned)length;	// 0x79ad
+ (void)enumerateDeletedItemsInResponseData:(id)responseData usingHandler:(id)handler;	// 0x781d
+ (void)enumerateItemsInResponseData:(id)responseData usingHandler:(id)handler;	// 0x7761
+ (void)parseItemWithBytes:(const char *)bytes length:(unsigned)length usingHandler:(id)handler;	// 0x76e9
+ (unsigned)parseItemWithBytes:(const char *)bytes length:(unsigned)length valuesOut:(XXStruct_LKnRFA *)anOut valuesCapacity:(unsigned)capacity;	// 0x7421
+ (id)enumerateRawItemsInResponseData:(id)responseData usingHandler:(id)handler;	// 0x7371
+ (id)parseResponseData:(id)data;	// 0x735d
@end
