/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SMSCTServer.framework/SMSCTServer
 */

#import <SMSCTServer/SMSCTServer-Structs.h>
#import <SMSCTServer/XXUnknownSuperclass.h>

@class NSThread, NSMutableDictionary;

@interface SMSCTServer : XXUnknownSuperclass {
	NSMutableDictionary *_associationSets;	// 4 = 0x4
	NSMutableDictionary *_associationForRecord;	// 8 = 0x8
	NSThread *_messageThread;	// 12 = 0xc
}
+ (id)sharedServer;	// 0x4259
- (void)dealloc;	// 0x6109
- (int)_associationIDForRecord:(int)record;	// 0x38c9
- (void)_removeAssociationSetForRecord:(int)record;	// 0x3929
- (BOOL)_removeRecordFromAssociations:(int)associations;	// 0x39b9
- (void)_addRecord:(int)record forAssociationID:(int)associationID;	// 0x3a9d
- (void)start;	// 0x5fc1
- (void)stop;	// 0x5f85
- (void)updateMMSCapability;	// 0x5de5
- (void)_registerForCTNotifications;	// 0x5c51
- (BOOL)_checkMMSEnablement;	// 0x5af5
- (unsigned char)_readMMSUserOverride;	// 0x5a55
- (void)playMessageSent;	// 0x5a3d
- (void)_acknowledgeMessageWithKey:(int)key;	// 0x40dd
- (void)_clearPendingIncomingMessageQueue;	// 0x5889
- (void)_processReceivedMessageWithInfo:(CFDictionaryRef)info;	// 0x56dd
- (void)_processReceivedMessageReceiptWithInfo:(CFDictionaryRef)info;	// 0x554d
- (void)_ingestIncomingCTMessage:(id)message;	// 0x4bfd
- (void)_reallySendSMSRequest:(CFDictionaryRef)request withProcessedParts:(CFArrayRef)processedParts recordID:(unsigned)anId;	// 0x4441
- (void)_sendCompleted:(unsigned char)completed forRecord:(unsigned)record;	// 0x438d
- (void)_checkAddressBook:(void *)book;	// 0x42a1
- (void)_checkAddressBookAfterQuiescence;	// 0x41d1
- (void)_significantTimeChanged;	// 0x4239
- (void)_mobileSMSDidResume;	// 0x4249
@end
