/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import <StoreServices/XXUnknownSuperclass.h>
#import <StoreServices/StoreServices-Structs.h>

@class NSLock, NSMutableDictionary;

@interface SSLockdown : XXUnknownSuperclass {
@private
	NSMutableDictionary *_dictionary;	// 4 = 0x4
	NSLock *_lock;	// 8 = 0x8
}
@property(readonly, assign) long long totalDiskCapacity;	// G=0x282e1; 
@property(readonly, assign) long long availableDiskSpace;	// G=0x28241; 
+ (id)sharedInstance;	// 0x28191
- (void)_setLocalValue:(void *)value forKey:(CFStringRef)key domain:(CFStringRef)domain;	// 0x28c31
- (BOOL)_ntsSaveLocalDictionary;	// 0x28b11
- (id)_ntsLocalDictionary;	// 0x289cd
- (id)_localDictionaryFileName;	// 0x28991
- (id)_localDictionaryDirectory;	// 0x28959
- (void *)_copyLocalValueForKey:(CFStringRef)key domain:(CFStringRef)domain;	// 0x288c1
- (void)setValue:(void *)value forKey:(CFStringRef)key domain:(CFStringRef)domain;	// 0x28891
- (void)removeAccountFromDomain:(CFStringRef)domain;	// 0x2879d
- (void *)copyValueForKey:(CFStringRef)key domain:(CFStringRef)domain;	// 0x28769
- (void *)copyITunesValueForKey:(CFStringRef)key usedDomain:(const CFStringRef *)domain;	// 0x2870d
- (CFStringRef)copyDeviceGUID;	// 0x286b1
- (id)copyAccountDictionaryForDomain:(CFStringRef)domain;	// 0x28381
// declared property getter: - (long long)totalDiskCapacity;	// 0x282e1
// declared property getter: - (long long)availableDiskSpace;	// 0x28241
- (void)dealloc;	// 0x28131
- (id)init;	// 0x280cd
@end
