/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
 */

#import <MobileBackup/MobileBackup-Structs.h>
#import <MobileBackup/XXUnknownSuperclass.h>

@class NSObject;
@protocol MBConnectionHandler;

@interface MBConnection : XXUnknownSuperclass {
	xpc_connection_s *_conn;	// 4 = 0x4
	dispatch_queue_s *_eventQueue;	// 8 = 0x8
	NSObject<MBConnectionHandler> *_handler;	// 12 = 0xc
}
@property(assign, nonatomic) NSObject<MBConnectionHandler> *messageHandler;	// G=0xfcf1; S=0xfd01; @synthesize=_handler
@property(readonly, assign) dispatch_queue_s *eventQueue;	// G=0x10121; converted property
- (id)initWithXPCConnection:(xpc_connection_s *)xpcconnection eventQueue:(dispatch_queue_s *)queue;	// 0x10081
- (id)initWithServiceName:(id)serviceName eventQueue:(dispatch_queue_s *)queue;	// 0x104ed
- (void)_setEventHandlerForXPCConnection;	// 0x10465
- (void)_handleXPCEvent:(void *)event;	// 0x103a5
- (void)_handleXPCError:(void *)error;	// 0xfd31
- (void)dealloc;	// 0x10339
- (void)sendMessage:(id)message;	// 0x102b9
- (id)sendMessageWithReplyAndSync:(id)replyAndSync;	// 0x10185
- (void)suspend;	// 0x10171
- (void)resume;	// 0x1015d
// converted property getter: - (dispatch_queue_s *)eventQueue;	// 0x10121
// declared property getter: - (id)messageHandler;	// 0xfcf1
// declared property setter: - (void)setMessageHandler:(id)handler;	// 0xfd01
@end
