/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <ImageCapture/XXUnknownSuperclass.h>

@class NSMutableArray;

@interface ICDeviceBrowserPrivateData : XXUnknownSuperclass {
	id _delegate;	// 4 = 0x4
	BOOL _browsing;	// 8 = 0x8
	NSMutableArray *_internalDevices;	// 12 = 0xc
}
@property(assign) id delegate;	// G=0x4739; S=0x4749; @synthesize=_delegate
@property(assign, getter=isBrowsing) BOOL browsing;	// G=0x4719; S=0x4729; @synthesize=_browsing
@property(retain) NSMutableArray *internalDevices;	// G=0x4919; S=0x48f5; @synthesize=_internalDevices
- (void)dealloc;	// 0x48a1
- (void)finalize;	// 0x4931
// declared property getter: - (id)internalDevices;	// 0x4919
// declared property setter: - (void)setInternalDevices:(id)devices;	// 0x48f5
// declared property getter: - (BOOL)isBrowsing;	// 0x4719
// declared property setter: - (void)setBrowsing:(BOOL)browsing;	// 0x4729
// declared property getter: - (id)delegate;	// 0x4739
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x4749
@end
