/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <ImageCapture/ImageCapture-Structs.h>
#import <ImageCapture/XXUnknownSuperclass.h>

@class NSString, NSDictionary, NSMutableArray;

@interface ICPTPIPBonjourServiceProperties : XXUnknownSuperclass {
	CFSocketRef _hostSocket;	// 4 = 0x4
	NSString *_hostName;	// 8 = 0x8
	unsigned short _hostPort;	// 12 = 0xc
	NSString *_hostGUID;	// 16 = 0x10
	unsigned _hostMaxConnections;	// 20 = 0x14
	int _hostSecuritylevel;	// 24 = 0x18
	NSString *_serviceType;	// 28 = 0x1c
	NSDictionary *_txtRecordsDict;	// 32 = 0x20
	CFNetServiceRef _publishedService;	// 36 = 0x24
	NSMutableArray *_clients;	// 40 = 0x28
	int _clientSpinLock;	// 44 = 0x2c
	id _delegate;	// 48 = 0x30
	int _clientsSpinLock;	// 52 = 0x34
}
@property(assign) CFSocketRef hostSocket;	// G=0x31ed5; S=0x31ee5; @synthesize=_hostSocket
@property(retain) NSString *hostName;	// G=0x32319; S=0x322f5; @synthesize=_hostName
@property(assign) unsigned short hostPort;	// G=0x31eb5; S=0x31ec5; @synthesize=_hostPort
@property(retain) NSString *hostGUID;	// G=0x32355; S=0x32331; @synthesize=_hostGUID
@property(assign) unsigned hostMaxConnections;	// G=0x31e95; S=0x31ea5; @synthesize=_hostMaxConnections
@property(assign) int hostSecurityLevel;	// G=0x31e75; S=0x31e85; @synthesize=_hostSecuritylevel
@property(retain) NSString *serviceType;	// G=0x32391; S=0x3236d; @synthesize=_serviceType
@property(retain) NSDictionary *txtRecordsDict;	// G=0x323cd; S=0x323a9; @synthesize=_txtRecordsDict
@property(assign) CFNetServiceRef publishedService;	// G=0x31e55; S=0x31e65; @synthesize=_publishedService
@property(retain) NSMutableArray *clients;	// G=0x32409; S=0x323e5; @synthesize=_clients
@property(assign) int clientsSpinLock;	// G=0x31e35; S=0x31e45; @synthesize=_clientsSpinLock
@property(assign) id delegate;	// G=0x31e15; S=0x31e25; @synthesize=_delegate
- (void)dealloc;	// 0x32251
- (void)finalize;	// 0x32421
// declared property getter: - (id)delegate;	// 0x31e15
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x31e25
// declared property getter: - (int)clientsSpinLock;	// 0x31e35
// declared property setter: - (void)setClientsSpinLock:(int)lock;	// 0x31e45
// declared property getter: - (id)clients;	// 0x32409
// declared property setter: - (void)setClients:(id)clients;	// 0x323e5
// declared property getter: - (CFNetServiceRef)publishedService;	// 0x31e55
// declared property setter: - (void)setPublishedService:(CFNetServiceRef)service;	// 0x31e65
// declared property getter: - (id)txtRecordsDict;	// 0x323cd
// declared property setter: - (void)setTxtRecordsDict:(id)dict;	// 0x323a9
// declared property getter: - (id)serviceType;	// 0x32391
// declared property setter: - (void)setServiceType:(id)type;	// 0x3236d
// declared property getter: - (int)hostSecurityLevel;	// 0x31e75
// declared property setter: - (void)setHostSecurityLevel:(int)level;	// 0x31e85
// declared property getter: - (unsigned long)hostMaxConnections;	// 0x31e95
// declared property setter: - (void)setHostMaxConnections:(unsigned long)connections;	// 0x31ea5
// declared property getter: - (id)hostGUID;	// 0x32355
// declared property setter: - (void)setHostGUID:(id)guid;	// 0x32331
// declared property getter: - (unsigned short)hostPort;	// 0x31eb5
// declared property setter: - (void)setHostPort:(unsigned short)port;	// 0x31ec5
// declared property getter: - (id)hostName;	// 0x32319
// declared property setter: - (void)setHostName:(id)name;	// 0x322f5
// declared property getter: - (CFSocketRef)hostSocket;	// 0x31ed5
// declared property setter: - (void)setHostSocket:(CFSocketRef)socket;	// 0x31ee5
@end
