/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import <ImageCapture/ImageCapture-Structs.h>
#import <ImageCapture/XXUnknownSuperclass.h>


@interface ICPTPIPClient : XXUnknownSuperclass {
@private
	id _clientProperties;	// 4 = 0x4
}
@property(assign) int pid;	// G=0x31efd; S=0x31f1d; converted property
@property(assign) BOOL registered;	// G=0x31f41; S=0x31f65; converted property
@property(assign) CFFileDescriptorRef fdref;	// G=0x31f89; S=0x31fa9; converted property
@property(assign) CFMessagePortRef remotePort;	// G=0x31fcd; S=0x31fed; converted property
@property(assign) int remoteAddress;	// G=0x32011; S=0x32031; converted property
@property(assign) int serverFD;	// G=0x32055; S=0x32075; converted property
- (id)init;	// 0x324c5
// converted property getter: - (int)pid;	// 0x31efd
// converted property setter: - (void)setPid:(int)pid;	// 0x31f1d
// converted property getter: - (BOOL)registered;	// 0x31f41
// converted property setter: - (void)setRegistered:(BOOL)registered;	// 0x31f65
// converted property getter: - (CFFileDescriptorRef)fdref;	// 0x31f89
// converted property setter: - (void)setFdref:(CFFileDescriptorRef)fdref;	// 0x31fa9
// converted property getter: - (CFMessagePortRef)remotePort;	// 0x31fcd
// converted property setter: - (void)setRemotePort:(CFMessagePortRef)port;	// 0x31fed
// converted property getter: - (int)remoteAddress;	// 0x32011
// converted property setter: - (void)setRemoteAddress:(int)address;	// 0x32031
// converted property getter: - (int)serverFD;	// 0x32055
// converted property setter: - (void)setServerFD:(int)fd;	// 0x32075
@end
