/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
 */

#import <GameKitServices/GameKitServices-Structs.h>
#import <GameKitServices/XXUnknownSuperclass.h>
#import <GameKitServices/GKTableCleanupWhenRemoved.h>

@class NSString, GKSessionInternal;

__attribute__((visibility("hidden")))
@interface GKPeerInternal : XXUnknownSuperclass <GKTableCleanupWhenRemoved> {
@private
	unsigned _pid;	// 4 = 0x4
	NSString *_displayName;	// 8 = 0x8
	NSString *_serviceName;	// 12 = 0xc
	BOOL _isBusy;	// 16 = 0x10
	GKSessionInternal *_session;	// 20 = 0x14
	int _serviceCount;	// 24 = 0x18
	DNSServiceRef_tRef _resolveService;	// 28 = 0x1c
	DNSServiceRef_tRef _txtRecordService;	// 32 = 0x20
	NSData **_addrList;	// 36 = 0x24
	unsigned *_interfaceList;	// 40 = 0x28
	unsigned _servicePort;	// 44 = 0x2c
	DNSServiceRef_tRef *_lookupServiceList;	// 48 = 0x30
	int _lookupServiceCount;	// 52 = 0x34
	int _lookupServiceSize;	// 56 = 0x38
	BOOL _moreResolvesComing;	// 60 = 0x3c
	double _connectTimeout;	// 64 = 0x40
	BOOL _needsToTimeout;	// 72 = 0x48
}
@property(readonly, assign) NSString *serviceName;	// G=0x21571; @synthesize=_serviceName
@property(readonly, assign) NSString *displayName;	// G=0x21561; @synthesize=_displayName
@property(readonly, assign) unsigned pid;	// G=0x21551; @synthesize=_pid
@property(assign, getter=isBusy) BOOL busy;	// G=0x21531; S=0x21541; @synthesize=_isBusy
@property(assign) int serviceCount;	// G=0x21521; S=0x23019; @synthesize=_serviceCount
@property(assign) DNSServiceRef_tRef resolveService;	// G=0x21501; S=0x21511; @synthesize=_resolveService
@property(assign) DNSServiceRef_tRef txtRecordService;	// G=0x214e1; S=0x214f1; @synthesize=_txtRecordService
@property(assign) unsigned servicePort;	// G=0x214c1; S=0x214d1; @synthesize=_servicePort
@property(assign) BOOL moreResolvesComing;	// G=0x214a1; S=0x214b1; @synthesize=_moreResolvesComing
@property(retain, nonatomic) GKSessionInternal *session;	// G=0x21491; S=0x223f1; @synthesize=_session
@property(assign) double connectTimeout;	// G=0x2244d; S=0x22419; @synthesize=_connectTimeout
@property(assign) BOOL needsToTimeout;	// G=0x21471; S=0x21481; @synthesize=_needsToTimeout
+ (void)freeLookupList:(DNSServiceRef_tRef *)list andAddrList:(id *)list2 andInterfaceList:(unsigned *)list3 count:(int)count;	// 0x2239d
- (id)initWithPID:(unsigned)pid displayName:(id)name serviceName:(id)name3;	// 0x222dd
- (void)dealloc;	// 0x23081
// declared property setter: - (void)setServiceCount:(int)count;	// 0x23019
- (BOOL)tryDetruncateDisplayName:(id)name;	// 0x22f5d
- (void)addLookup:(DNSServiceRef_tRef)lookup;	// 0x22c91
- (void)removeAndReturnLookupList:(DNSServiceRef_tRef **)list andAddrList:(id **)list2 andInterfaceList:(unsigned **)list3 count:(int *)count;	// 0x2136d
- (BOOL)containsLookupService:(DNSServiceRef_tRef)service;	// 0x22bd5
- (void)setAddr:(const sockaddr_in *)addr interface:(unsigned)interface forLookupService:(DNSServiceRef_tRef)lookupService;	// 0x22915
- (void)copyLookupList:(DNSServiceRef_tRef **)list count:(int *)count;	// 0x228b1
- (int)usableAddrs;	// 0x2141d
- (void)stopResolving;	// 0x22671
- (void)clearResolving;	// 0x22629
- (void)stopTXTRecordMonitoring;	// 0x2256d
- (void)cleanupForGKTable:(id)gktable;	// 0x22481
// declared property getter: - (BOOL)needsToTimeout;	// 0x21471
// declared property setter: - (void)setNeedsToTimeout:(BOOL)timeout;	// 0x21481
// declared property getter: - (double)connectTimeout;	// 0x2244d
// declared property setter: - (void)setConnectTimeout:(double)timeout;	// 0x22419
// declared property getter: - (id)session;	// 0x21491
// declared property setter: - (void)setSession:(id)session;	// 0x223f1
// declared property getter: - (BOOL)moreResolvesComing;	// 0x214a1
// declared property setter: - (void)setMoreResolvesComing:(BOOL)coming;	// 0x214b1
// declared property getter: - (unsigned)servicePort;	// 0x214c1
// declared property setter: - (void)setServicePort:(unsigned)port;	// 0x214d1
// declared property getter: - (DNSServiceRef_tRef)txtRecordService;	// 0x214e1
// declared property setter: - (void)setTxtRecordService:(DNSServiceRef_tRef)service;	// 0x214f1
// declared property getter: - (DNSServiceRef_tRef)resolveService;	// 0x21501
// declared property setter: - (void)setResolveService:(DNSServiceRef_tRef)service;	// 0x21511
// declared property getter: - (int)serviceCount;	// 0x21521
// declared property getter: - (BOOL)isBusy;	// 0x21531
// declared property setter: - (void)setBusy:(BOOL)busy;	// 0x21541
// declared property getter: - (unsigned)pid;	// 0x21551
// declared property getter: - (id)displayName;	// 0x21561
// declared property getter: - (id)serviceName;	// 0x21571
@end
