/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import <ManagedConfiguration/MCPayload.h>

@class NSNumber;

@interface MCPasswordPolicyPayload : MCPayload {
	NSNumber *_isSimplePasscodeAllowed;	// 40 = 0x28
	NSNumber *_isPasscodeRequired;	// 44 = 0x2c
	NSNumber *_isAlphanumericPasscodeRequired;	// 48 = 0x30
	NSNumber *_isManualFetchingWhenRoaming;	// 52 = 0x34
	NSNumber *_minLength;	// 56 = 0x38
	NSNumber *_maxFailedAttempts;	// 60 = 0x3c
	NSNumber *_maxGracePeriodMinutes;	// 64 = 0x40
	NSNumber *_maxInactivityMinutes;	// 68 = 0x44
	NSNumber *_maxPasscodeAgeDays;	// 72 = 0x48
	NSNumber *_passcodeHistoryCount;	// 76 = 0x4c
	NSNumber *_minComplexCharacters;	// 80 = 0x50
}
@property(readonly, assign) NSNumber *isSimplePasscodeAllowed;	// G=0x17335; @synthesize=_isSimplePasscodeAllowed
@property(readonly, assign) NSNumber *isPasscodeRequired;	// G=0x17325; @synthesize=_isPasscodeRequired
@property(readonly, assign) NSNumber *isAlphanumericPasscodeRequired;	// G=0x17315; @synthesize=_isAlphanumericPasscodeRequired
@property(readonly, assign) NSNumber *isManualFetchingWhenRoaming;	// G=0x17305; @synthesize=_isManualFetchingWhenRoaming
@property(readonly, assign) NSNumber *minLength;	// G=0x172f5; @synthesize=_minLength
@property(readonly, assign) NSNumber *maxFailedAttempts;	// G=0x172e5; @synthesize=_maxFailedAttempts
@property(readonly, assign) NSNumber *maxGracePeriodMinutes;	// G=0x172d5; @synthesize=_maxGracePeriodMinutes
@property(readonly, assign) NSNumber *maxInactivityMinutes;	// G=0x172c5; @synthesize=_maxInactivityMinutes
@property(readonly, assign) NSNumber *passcodeHistoryCount;	// G=0x172b5; @synthesize=_passcodeHistoryCount
@property(readonly, assign) NSNumber *maxPasscodeAgeDays;	// G=0x172a5; @synthesize=_maxPasscodeAgeDays
@property(readonly, assign) NSNumber *minComplexCharacters;	// G=0x17295; @synthesize=_minComplexCharacters
+ (id)typeStrings;	// 0x17509
+ (id)localizedDescriptionForPayloadCount:(unsigned)payloadCount;	// 0x174a9
- (id)initWithDictionary:(id)dictionary profile:(id)profile outError:(id *)error;	// 0x17c9d
- (void)dealloc;	// 0x17345
- (id)stubDictionary;	// 0x17b01
- (id)description;	// 0x17809
- (id)title;	// 0x177f9
- (id)subtitle1Description;	// 0x17531
// declared property getter: - (id)minComplexCharacters;	// 0x17295
// declared property getter: - (id)maxPasscodeAgeDays;	// 0x172a5
// declared property getter: - (id)passcodeHistoryCount;	// 0x172b5
// declared property getter: - (id)maxInactivityMinutes;	// 0x172c5
// declared property getter: - (id)maxGracePeriodMinutes;	// 0x172d5
// declared property getter: - (id)maxFailedAttempts;	// 0x172e5
// declared property getter: - (id)minLength;	// 0x172f5
// declared property getter: - (id)isManualFetchingWhenRoaming;	// 0x17305
// declared property getter: - (id)isAlphanumericPasscodeRequired;	// 0x17315
// declared property getter: - (id)isPasscodeRequired;	// 0x17325
// declared property getter: - (id)isSimplePasscodeAllowed;	// 0x17335
@end
