/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

#import <ManagedConfiguration/MCCertificatePayload.h>
#import <ManagedConfiguration/ManagedConfiguration-Structs.h>

@class NSArray, NSDictionary, NSString, NSData;

@interface MCSCEPPayload : MCCertificatePayload {
@private
	NSString *_URLString;	// 48 = 0x30
	NSString *_CAInstanceName;	// 52 = 0x34
	NSString *_challenge;	// 56 = 0x38
	NSArray *_subject;	// 60 = 0x3c
	unsigned _keySize;	// 64 = 0x40
	int _usageFlags;	// 68 = 0x44
	NSData *_CAFingerprint;	// 72 = 0x48
	NSArray *_CACaps;	// 76 = 0x4c
	NSDictionary *_subjectAltName;	// 80 = 0x50
	unsigned _retries;	// 84 = 0x54
	unsigned _retryDelay;	// 88 = 0x58
}
@property(readonly, assign) NSString *URLString;	// G=0x29eb1; @synthesize=_URLString
@property(readonly, assign) NSString *CAInstanceName;	// G=0x29ea1; @synthesize=_CAInstanceName
@property(readonly, assign) NSString *challenge;	// G=0x29e91; @synthesize=_challenge
@property(readonly, assign) NSArray *subject;	// G=0x29e81; @synthesize=_subject
@property(readonly, assign) unsigned keySize;	// G=0x29e71; @synthesize=_keySize
@property(readonly, assign) int usageFlags;	// G=0x29e61; @synthesize=_usageFlags
@property(readonly, assign) NSData *CAFingerprint;	// G=0x29e51; @synthesize=_CAFingerprint
@property(readonly, assign) NSArray *CACaps;	// G=0x29e41; @synthesize=_CACaps
@property(readonly, assign) NSDictionary *subjectAltName;	// G=0x29e31; @synthesize=_subjectAltName
@property(readonly, assign) unsigned retries;	// G=0x29e21; @synthesize=_retries
@property(readonly, assign) unsigned retryDelay;	// G=0x29e11; @synthesize=_retryDelay
+ (id)typeStrings;	// 0x29fe5
+ (id)localizedDescriptionForPayloadCount:(unsigned)payloadCount;	// 0x29f85
- (BOOL)isRoot;	// 0x29e09
- (BOOL)isIdentity;	// 0x29e0d
- (id)initWithDictionary:(id)dictionary profile:(id)profile outError:(id *)error;	// 0x2a341
- (void)dealloc;	// 0x29ec1
- (SecCertificate *)copyCertificate;	// 0x2a2f5
- (SecIdentity *)copyIdentityFromKeychain;	// 0x2a2a9
- (id)stubDictionary;	// 0x2a229
- (id)description;	// 0x2a00d
// declared property getter: - (unsigned)retryDelay;	// 0x29e11
// declared property getter: - (unsigned)retries;	// 0x29e21
// declared property getter: - (id)subjectAltName;	// 0x29e31
// declared property getter: - (id)CACaps;	// 0x29e41
// declared property getter: - (id)CAFingerprint;	// 0x29e51
// declared property getter: - (int)usageFlags;	// 0x29e61
// declared property getter: - (unsigned)keySize;	// 0x29e71
// declared property getter: - (id)subject;	// 0x29e81
// declared property getter: - (id)challenge;	// 0x29e91
// declared property getter: - (id)CAInstanceName;	// 0x29ea1
// declared property getter: - (id)URLString;	// 0x29eb1
@end
