/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
 */

#import <Foundation/NSMutableURLRequest.h>
#import <IMAP/IMAP-Structs.h>

@class NSMutableArray;

@interface MFIMAPDownloadCache : NSMutableURLRequest {
	NSMutableArray *_downloads;	// 4 = 0x4
}
- (void)dealloc;	// 0xc4d9
- (id)downloadForMessage:(id)message;	// 0xc829
- (id)downloadForUid:(unsigned long)uid section:(id)section length:(unsigned long)length;	// 0xc801
- (id)downloadForUid:(unsigned long)uid section:(id)section expectedLength:(unsigned long)length;	// 0xc7dd
- (id)downloadForUid:(unsigned long)uid section:(id)section range:(NSRange)range;	// 0xc7b5
- (void)handleFetchResponse:(id)response forUid:(unsigned long)uid;	// 0xc74d
- (void)handleFetchResponses:(id)responses;	// 0xc66d
- (void)processResultsForUid:(unsigned long)uid;	// 0xc5d9
- (void)cleanUpDownloadsForUid:(unsigned long)uid;	// 0xc525
- (void)addCommandsForDownload:(id)download toPipeline:(id)pipeline;	// 0xc491
@end
