/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP
 */



@protocol MFMessageDataSection
- (id)partName;
- (BOOL)isPartial;
- (BOOL)isComplete;
- (id)data;
@end

