/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ScreenReaderOutputServer.framework/ScreenReaderOutputServer
 */


#import <ScreenReaderOutputServer/NSCopying.h>


@protocol SCROIOElementProtocol <NSObject, NSCopying>
- (unsigned)ioObject;
- (int)transport;
- (long)identifier;
@end
