/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMAVCore.framework/IMAVCore
 */

#import <IMAVCore/IMExtendedOperation.h>

@class NSString, IMHandle;

__attribute__((visibility("hidden")))
@interface AVChatCancelInvitationOp : IMExtendedOperation {
	IMHandle *_imHandle;	// 36 = 0x24
	NSString *_conferenceID;	// 40 = 0x28
	unsigned _sessionID;	// 44 = 0x2c
}
- (void)didFinish;	// 0x571d
- (void)dealloc;	// 0x56bd
- (id)initWithIMHandle:(id)imhandle avChat:(id)chat;	// 0x5615
@end
