/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore
 */

#import <DataDetectorsCore/DataDetectorsCore-Structs.h>
#import <DataDetectorsCore/DDURLifier.h>
#import <DataDetectorsCore/DDLocation.h>
#import <DataDetectorsCore/NSCoding.h>
#import <DataDetectorsCore/DDURLMatch.h>
#import <DataDetectorsCore/DDCompilationNote.h>
