/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <iLifeSlideshow/MCObject.h>

@class NSSet, NSLock, MCPlug, NSMutableSet, MCAudioPlaylist;

@interface MCContainer : MCObject {
	MCAudioPlaylist *mAudioPlaylist;	// 12 = 0xc
	NSMutableSet *mReferencingPlugs;	// 16 = 0x10
	NSLock *mReferencingPlugsLock;	// 20 = 0x14
	int mSpecialRetainCount;	// 24 = 0x18
}
@property(readonly, assign) MCAudioPlaylist *audioPlaylist;	// G=0x8079; @synthesize=mAudioPlaylist
@property(readonly, assign) NSSet *referencingPlugs;	// G=0x8459; @synthesize=mReferencingPlugs
@property(readonly, assign) MCPlug *superplug;	// G=0x837d; 
@property(readonly, assign) unsigned numberOfReferencingPlugs;	// G=0x83fd; 
@property(readonly, assign) MCAudioPlaylist *audioPlaylistCreateIfNeeded;	// G=0x8509; 
- (id)init;	// 0x8089
- (id)initWithImprint:(id)imprint andMontage:(id)montage;	// 0x8755
- (void)demolish;	// 0x86b1
- (id)imprint;	// 0x8645
// declared property getter: - (id)audioPlaylistCreateIfNeeded;	// 0x8509
// declared property getter: - (id)referencingPlugs;	// 0x8459
// declared property getter: - (unsigned)numberOfReferencingPlugs;	// 0x83fd
// declared property getter: - (id)superplug;	// 0x837d
- (void)referenceByPlug:(id)plug;	// 0x831d
- (void)unreferenceByPlug:(id)plug;	// 0x8255
- (id)specialRetain;	// 0x81f1
- (void)specialRelease;	// 0x8135
// declared property getter: - (id)audioPlaylist;	// 0x8079
@end
