/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <iLifeSlideshow/iLifeSlideshow-Structs.h>
#import <iLifeSlideshow/XXUnknownSuperclass.h>


@interface MRCroppingSprite : XXUnknownSuperclass {
}
+ (void)renderDumbImage:(const XXStruct_ywZ0fB *)image atPosition:(CGPoint)position andSize:(CGSize)size;	// 0x77529
+ (void)renderImage:(const XXStruct_ywZ0fB *)image atPosition:(CGPoint)position andSize:(CGSize)size;	// 0x7761d
+ (void)renderImage:(const XXStruct_ywZ0fB *)image withMask:(const XXStruct_ywZ0fB *)mask atPosition:(CGPoint)position andSize:(CGSize)size;	// 0x77989
+ (void)renderImage:(const XXStruct_ywZ0fB *)image atPosition:(CGPoint)position andSize:(CGSize)size withReferenceAspectRatio:(float)referenceAspectRatio andJustifications:(CGPoint)justifications;	// 0x77731
@end
