/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iLifeSlideshow.framework/iLifeSlideshow
 */

#import <iLifeSlideshow/iLifeSlideshow-Structs.h>
#import <iLifeSlideshow/XXUnknownSuperclass.h>

@class EAGLContext, NSConditionLock, MCMontage, NSThread, NSLock, NSDictionary, MRLayerParallelizer;
@protocol MRLiveSlideshowDelegate;

@interface MRRenderer : XXUnknownSuperclass {
	MCMontage *mMontage;	// 4 = 0x4
	MRLayerParallelizer *mTopMRLayer;	// 8 = 0x8
	NSLock *mRenderLock;	// 12 = 0xc
	NSConditionLock *mWarmUpLock;	// 16 = 0x10
	CGSize mSize;	// 20 = 0x14
	int mOrientation;	// 28 = 0x1c
	BOOL mNeedsToUpdateSize;	// 32 = 0x20
	BOOL mIsPlaying;	// 33 = 0x21
	id mDisplayLink;	// 36 = 0x24
	NSDictionary *mParameters;	// 40 = 0x28
	EAGLContext *mContext;	// 44 = 0x2c
	EAGLContext *mPreloadContext;	// 48 = 0x30
	unsigned mFramebuffer;	// 52 = 0x34
	unsigned mRenderbuffer;	// 56 = 0x38
	BOOL mFramebufferIsSetup;	// 60 = 0x3c
	NSThread *mRenderThread;	// 64 = 0x40
	double mTimeOffset;	// 68 = 0x44
	double mLastRenderedTime;	// 76 = 0x4c
	float mFadeAlpha;	// 84 = 0x54
	BOOL mShowFPS;	// 88 = 0x58
	BOOL mPauseWhenStill;	// 89 = 0x59
	BOOL mIsWarmingUp;	// 90 = 0x5a
	BOOL mWasForcedPaused;	// 91 = 0x5b
	id<MRLiveSlideshowDelegate> mLiveSlideshowDelegate;	// 92 = 0x5c
}
@property(retain, nonatomic) MCMontage *montage;	// G=0x8a609; S=0x8bd35; @synthesize=mMontage
@property(readonly, assign) EAGLContext *context;	// G=0x8a5f9; @synthesize=mContext
@property(readonly, assign) EAGLContext *preloadContext;	// G=0x8a5e9; @synthesize=mPreloadContext
@property(assign, nonatomic) CGSize size;	// G=0x8a5d1; S=0x8a475; @synthesize=mSize
@property(assign, nonatomic) int orientation;	// G=0x8a5c1; S=0x8a4f9; @synthesize=mOrientation
@property(readonly, assign) BOOL isPlaying;	// G=0x8a5b1; @synthesize=mIsPlaying
@property(readonly, assign) BOOL isWarmingUp;	// G=0x8a5a1; @synthesize=mIsWarmingUp
@property(assign) BOOL showFPS;	// G=0x8a581; S=0x8a591; @synthesize=mShowFPS
@property(assign) float fadeAlpha;	// G=0x8a561; S=0x8a571; @synthesize=mFadeAlpha
@property(assign) id<MRLiveSlideshowDelegate> liveSlideshowDelegate;	// G=0x8a541; S=0x8a551; @synthesize=mLiveSlideshowDelegate
@property(assign) double time;	// G=0x8b959; S=0x8b8d5; 
- (id)init;	// 0x8a619
- (void)dealloc;	// 0x8c341
- (void)cleanup;	// 0x8c125
- (void)setContext:(id)context frameBuffer:(unsigned)buffer renderBuffer:(unsigned)buffer3;	// 0x8bf05
// declared property setter: - (void)setMontage:(id)montage;	// 0x8bd35
// declared property setter: - (void)setSize:(CGSize)size;	// 0x8a475
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x8a4f9
- (void)render;	// 0x8bcd5
- (void)warmup;	// 0x8bc99
- (void)warmupAndWhenDoneCallSelector:(SEL)selector withTarget:(id)target andObject:(id)object;	// 0x8bbb5
- (void)_warmupWithCallback:(id)callback;	// 0x8bb31
- (void)pause;	// 0x8baf5
- (void)pauseWhenStill;	// 0x8a519
- (void)resume;	// 0x8ba95
- (void)stepForward;	// 0x8ba3d
- (void)stepBackward;	// 0x8b9e5
// declared property getter: - (double)time;	// 0x8b959
// declared property setter: - (void)setTime:(double)time;	// 0x8b8d5
- (void)setForcedPaused;	// 0x8a52d
- (void)_startRenderThread;	// 0x8b749
- (void)_exitRenderThread;	// 0x8b739
- (void)_startRenderTimer;	// 0x8b699
- (void)_stopRenderTimer;	// 0x8b66d
- (void)_render;	// 0x8b659
- (void)_render:(id)render;	// 0x8af49
- (void)_postPlaybackOverNotification;	// 0x8af05
- (void)_displayFPS;	// 0x8ac29
- (void)_warmup;	// 0x8ab31
- (void)_armWarmingUp;	// 0x8aaf1
- (void)_warmingUpCompleted;	// 0x8aab1
- (void)_pause:(BOOL)pause;	// 0x8a9b1
- (void)_resume;	// 0x8a911
- (void)hackCheckIfNeedsAdditionalEffectsAtTime:(double)time;	// 0x8a875
// declared property getter: - (id)liveSlideshowDelegate;	// 0x8a541
// declared property setter: - (void)setLiveSlideshowDelegate:(id)delegate;	// 0x8a551
// declared property getter: - (float)fadeAlpha;	// 0x8a561
// declared property setter: - (void)setFadeAlpha:(float)alpha;	// 0x8a571
// declared property getter: - (BOOL)showFPS;	// 0x8a581
// declared property setter: - (void)setShowFPS:(BOOL)fps;	// 0x8a591
// declared property getter: - (BOOL)isWarmingUp;	// 0x8a5a1
// declared property getter: - (BOOL)isPlaying;	// 0x8a5b1
// declared property getter: - (int)orientation;	// 0x8a5c1
// declared property getter: - (CGSize)size;	// 0x8a5d1
// declared property getter: - (id)preloadContext;	// 0x8a5e9
// declared property getter: - (id)context;	// 0x8a5f9
// declared property getter: - (id)montage;	// 0x8a609
@end
