/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MailServices.framework/MailServices
 */

#import <MailServices/MSMailDefaultService.h>


@interface MSCreateDraft : MSMailDefaultService {
}
+ (id)createDraftWithHeaders:(id)headers body:(id)body delegate:(id)delegate;	// 0x2981
+ (id)smi_serverCommandName;	// 0x2975
- (void)_smi_notifyClientDidFinishWithError:(id)_smi_notifyClient;	// 0x2c81
- (id)_didCreateDraft:(id)draft userInfo:(id)info;	// 0x2b49
- (id)_createMailDraftWithHeaders:(id)headers body:(id)body delegate:(id)delegate;	// 0x2a25
@end
