/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/MDM.framework/MDM
 */

#import <MDM/SSRequestDelegate.h>


@protocol SSDownloadManifestRequestDelegate <SSRequestDelegate>
@optional
- (void)downloadManifestRequest:(id)request didReceiveResponse:(id)response;
@end
