/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <CoreDAV/CoreDAVContainerSyncTaskGroup.h>


@interface CardDAVFolderSyncTaskGroup : CoreDAVContainerSyncTaskGroup {
	BOOL _isInitialSync;	// 137 = 0x89
}
@property(assign) BOOL isInitialSync;	// G=0xbd15; S=0xbd25; @synthesize=_isInitialSync
// declared property setter: - (void)setIsInitialSync:(BOOL)sync;	// 0xbd25
// declared property getter: - (BOOL)isInitialSync;	// 0xbd15
- (Class)bulkChangeTaskClass;	// 0xbcf9
- (id)dataContentType;	// 0xbced
- (id)copyGetTaskWithURL:(id)url;	// 0xbcb5
- (id)copyMultiGetTaskWithURLs:(id)urls;	// 0xbc59
- (id)initWithFolderURL:(id)folderURL previousCTag:(id)tag previousSyncToken:(id)token actions:(id)actions context:(void *)context accountInfoProvider:(id)provider taskManager:(id)manager appSpecificDataItemClass:(Class)aClass;	// 0xbc09
- (id)initWithFolderURL:(id)folderURL previousCTag:(id)tag previousSyncToken:(id)token actions:(id)actions syncItemOrder:(BOOL)order context:(void *)context accountInfoProvider:(id)provider taskManager:(id)manager appSpecificDataItemClass:(Class)aClass;	// 0xbba5
@end
