/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <CoreDAV/CoreDAVTaskGroup.h>
#import <CoreDAV/CoreDAVTaskDelegate.h>

@class NSMutableSet, NSSet, NSURL;

@interface CoreDAVValidatePrincipalsTaskGroup : CoreDAVTaskGroup <CoreDAVTaskDelegate> {
	NSMutableSet *_urlsToExamine;	// 44 = 0x2c
	NSMutableSet *_principalURLs;	// 48 = 0x30
	NSURL *_urlBeingExamined;	// 52 = 0x34
	BOOL _authError;	// 56 = 0x38
}
@property(retain) NSURL *urlBeingExamined;	// G=0x33069; S=0x3307d; @synthesize=_urlBeingExamined
@property(retain) NSMutableSet *principalURLs;	// G=0x33031; S=0x33045; @synthesize=_principalURLs
@property(retain) NSMutableSet *urlsToExamine;	// G=0x32ff9; S=0x3300d; @synthesize=_urlsToExamine
@property(readonly, assign) BOOL didReceiveAuthenticationError;	// G=0x330a1; @synthesize=_authError
@property(readonly, assign) NSSet *resultPrincipalURLs;	// G=0x32ba9; 
// declared property getter: - (BOOL)didReceiveAuthenticationError;	// 0x330a1
// declared property setter: - (void)setUrlBeingExamined:(id)examined;	// 0x3307d
// declared property getter: - (id)urlBeingExamined;	// 0x33069
// declared property setter: - (void)setPrincipalURLs:(id)urls;	// 0x33045
// declared property getter: - (id)principalURLs;	// 0x33031
// declared property setter: - (void)setUrlsToExamine:(id)examine;	// 0x3300d
// declared property getter: - (id)urlsToExamine;	// 0x32ff9
- (void)cancelTaskGroup;	// 0x32fb5
- (void)startTaskGroup;	// 0x32fa5
- (void)task:(id)task didFinishWithError:(id)error;	// 0x32e1d
- (void)_fetchNextURL;	// 0x32bf1
- (void)_finishWithError:(id)error;	// 0x32be1
// declared property getter: - (id)resultPrincipalURLs;	// 0x32ba9
- (void)dealloc;	// 0x32b35
- (id)initWithAccountInfoProvider:(id)accountInfoProvider urls:(id)urls taskManager:(id)manager;	// 0x32a91
@end
