/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <CoreDAV/XXUnknownSuperclass.h>
#import <CoreDAV/CoreDAVResponseBodyParser.h>

@class CoreDAVErrorItem, NSError, CoreDAVItem, CoreDAVXMLElementGenerator, NSURL, NSSet;

@interface CoreDAVXMLParser : XXUnknownSuperclass <CoreDAVResponseBodyParser> {
@private
	CoreDAVXMLElementGenerator *_rootElementGenerator;	// 24 = 0x18
	CoreDAVXMLElementGenerator *_rootErrorGenerator;	// 28 = 0x1c
	NSSet *_parseHints;	// 32 = 0x20
	NSURL *_baseURL;	// 36 = 0x24
}
@property(retain) CoreDAVXMLElementGenerator *rootErrorGenerator;	// G=0x39e71; S=0x39e85; @synthesize=_rootErrorGenerator
@property(retain) CoreDAVXMLElementGenerator *rootElementGenerator;	// G=0x39e39; S=0x39e4d; @synthesize=_rootElementGenerator
@property(readonly, assign) NSError *parserError;	// @dynamic
@property(readonly, assign) CoreDAVErrorItem *rootError;	// G=0x39e11; 
@property(readonly, assign) CoreDAVItem *rootElement;	// G=0x39de9; 
@property(retain) NSURL *baseURL;	// G=0x39ee1; S=0x39ef5; @synthesize=_baseURL
@property(retain) NSSet *parseHints;	// G=0x39ea9; S=0x39ebd; @synthesize=_parseHints
// declared property setter: - (void)setBaseURL:(id)url;	// 0x39ef5
// declared property getter: - (id)baseURL;	// 0x39ee1
// declared property setter: - (void)setParseHints:(id)hints;	// 0x39ebd
// declared property getter: - (id)parseHints;	// 0x39ea9
// declared property setter: - (void)setRootErrorGenerator:(id)generator;	// 0x39e85
// declared property getter: - (id)rootErrorGenerator;	// 0x39e71
// declared property setter: - (void)setRootElementGenerator:(id)generator;	// 0x39e4d
// declared property getter: - (id)rootElementGenerator;	// 0x39e39
// declared property getter: - (id)rootError;	// 0x39e11
// declared property getter: - (id)rootElement;	// 0x39de9
- (void)dealloc;	// 0x39d61
- (BOOL)processData:(id)data forTask:(id)task;	// 0x39cfd
- (id)initWithRootElementNameSpace:(id)rootElementNameSpace name:(id)name parseClass:(Class)aClass baseURL:(id)url;	// 0x39b81
- (id)initWithData:(id)data;	// 0x39b49
@end
