/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <CoreDAV/CoreDAVItem.h>


@interface CoreDAVSetItem : CoreDAVItem {
	CoreDAVItem *_prop;	// 24 = 0x18
}
@property(retain) CoreDAVItem *prop;	// G=0x29e91; S=0x29ea5; @synthesize=_prop
// declared property setter: - (void)setProp:(id)prop;	// 0x29ea5
// declared property getter: - (id)prop;	// 0x29e91
- (id)copyParseRules;	// 0x29d95
- (id)description;	// 0x29ce1
- (void)dealloc;	// 0x29c95
- (id)init;	// 0x29c69
@end
