/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import <CoreDAV/XXUnknownSuperclass.h>
#import <CoreDAV/CoreDAV-Structs.h>
#import <CoreDAV/CoreDAVAccountInfoProvider.h>

@class NSData, NSDictionary, NSString, NSError, NSSet, NSURL;

@interface CoreDAVDiscoveryAccountInfo : XXUnknownSuperclass <CoreDAVAccountInfoProvider> {
	NSString *_scheme;	// 4 = 0x4
	NSString *_host;	// 8 = 0x8
	NSString *_serverRoot;	// 12 = 0xc
	int _port;	// 16 = 0x10
	NSString *_user;	// 20 = 0x14
	NSString *_password;	// 24 = 0x18
	NSData *_identityPersist;	// 28 = 0x1c
	NSURL *_principalURL;	// 32 = 0x20
	NSString *_accountID;	// 36 = 0x24
	NSDictionary *_serverHeaders;	// 40 = 0x28
	NSSet *_serverComplianceClasses;	// 44 = 0x2c
	NSString *_userAgentHeader;	// 48 = 0x30
	BOOL _shouldFailAllTasks;	// 52 = 0x34
	BOOL _started;	// 53 = 0x35
	BOOL _success;	// 54 = 0x36
	NSError *_error;	// 56 = 0x38
	id<CoreDAVAccountInfoProvider> _backingAccountInfoProvider;	// 60 = 0x3c
}
@property(retain) id<CoreDAVAccountInfoProvider> backingAccountInfoProvider;	// G=0xce61; S=0xce75; @synthesize=_backingAccountInfoProvider
@property(retain) NSError *error;	// G=0xced9; S=0xceed; @synthesize=_error
@property(assign) BOOL success;	// G=0xceb9; S=0xcec9; @synthesize=_success
@property(assign) BOOL started;	// G=0xce99; S=0xcea9; @synthesize=_started
@property(assign) BOOL shouldFailAllTasks;	// G=0xce41; S=0xce51; @synthesize=_shouldFailAllTasks
@property(retain) NSString *userAgentHeader;	// G=0xcf81; S=0xcf95; @synthesize=_userAgentHeader
@property(retain) NSSet *serverComplianceClasses;	// G=0xcf49; S=0xcf5d; @synthesize=_serverComplianceClasses
@property(retain) NSDictionary *serverHeaders;	// G=0xcf11; S=0xcf25; @synthesize=_serverHeaders
@property(retain) NSString *accountID;	// G=0xce09; S=0xce1d; @synthesize=_accountID
@property(retain) NSURL *principalURL;	// G=0xcdd1; S=0xcde5; @synthesize=_principalURL
@property(retain) NSString *scheme;	// G=0xcc61; S=0xcc75; @synthesize=_scheme
@property(retain) NSData *identityPersist;	// G=0xcd99; S=0xcdad; @synthesize=_identityPersist
@property(assign) int port;	// G=0xccd1; S=0xcce1; @synthesize=_port
@property(retain) NSString *user;	// G=0xcd29; S=0xcd3d; @synthesize=_user
@property(retain) NSString *password;	// G=0xcd61; S=0xcd75; @synthesize=_password
@property(retain) NSString *serverRoot;	// G=0xccf1; S=0xcd05; @synthesize=_serverRoot
@property(retain) NSString *host;	// G=0xcc99; S=0xccad; @synthesize=_host
// declared property setter: - (void)setUserAgentHeader:(id)header;	// 0xcf95
// declared property getter: - (id)userAgentHeader;	// 0xcf81
// declared property setter: - (void)setServerComplianceClasses:(id)classes;	// 0xcf5d
// declared property getter: - (id)serverComplianceClasses;	// 0xcf49
// declared property setter: - (void)setServerHeaders:(id)headers;	// 0xcf25
// declared property getter: - (id)serverHeaders;	// 0xcf11
// declared property setter: - (void)setError:(id)error;	// 0xceed
// declared property getter: - (id)error;	// 0xced9
// declared property setter: - (void)setSuccess:(BOOL)success;	// 0xcec9
// declared property getter: - (BOOL)success;	// 0xceb9
// declared property setter: - (void)setStarted:(BOOL)started;	// 0xcea9
// declared property getter: - (BOOL)started;	// 0xce99
// declared property setter: - (void)setBackingAccountInfoProvider:(id)provider;	// 0xce75
// declared property getter: - (id)backingAccountInfoProvider;	// 0xce61
// declared property setter: - (void)setShouldFailAllTasks:(BOOL)failAllTasks;	// 0xce51
// declared property getter: - (BOOL)shouldFailAllTasks;	// 0xce41
// declared property setter: - (void)setAccountID:(id)anId;	// 0xce1d
// declared property getter: - (id)accountID;	// 0xce09
// declared property setter: - (void)setPrincipalURL:(id)url;	// 0xcde5
// declared property getter: - (id)principalURL;	// 0xcdd1
// declared property setter: - (void)setIdentityPersist:(id)persist;	// 0xcdad
// declared property getter: - (id)identityPersist;	// 0xcd99
// declared property setter: - (void)setPassword:(id)password;	// 0xcd75
// declared property getter: - (id)password;	// 0xcd61
// declared property setter: - (void)setUser:(id)user;	// 0xcd3d
// declared property getter: - (id)user;	// 0xcd29
// declared property setter: - (void)setServerRoot:(id)root;	// 0xcd05
// declared property getter: - (id)serverRoot;	// 0xccf1
// declared property setter: - (void)setPort:(int)port;	// 0xcce1
// declared property getter: - (int)port;	// 0xccd1
// declared property setter: - (void)setHost:(id)host;	// 0xccad
// declared property getter: - (id)host;	// 0xcc99
// declared property setter: - (void)setScheme:(id)scheme;	// 0xcc75
// declared property getter: - (id)scheme;	// 0xcc61
- (BOOL)shouldUseOpportunisticSockets;	// 0xcc19
- (CFURLStorageSessionRef)copyStorageSession;	// 0xcbd1
- (BOOL)shouldSendClientInfoHeaderForURL:(id)url;	// 0xcb79
- (BOOL)shouldHandleHTTPCookiesForURL:(id)url;	// 0xcb21
- (BOOL)handleShouldUseCredentialStorage;	// 0xcad9
- (BOOL)handleAuthenticateAgainstProtectionSpace:(id)space withConnection:(id)connection;	// 0xca21
- (BOOL)handleAuthenticateAgainstProtectionSpace:(id)space;	// 0xc8fd
- (BOOL)shouldRetryUnauthorizedConnection:(id)connection;	// 0xc8a5
- (BOOL)shouldTurnModalOnBadPassword;	// 0xc8a1
- (BOOL)handleCertificateError:(id)error;	// 0xc87d
- (BOOL)handleTrustChallenge:(id)challenge withConnection:(id)connection;	// 0xc80d
- (BOOL)handleTrustChallenge:(id)challenge;	// 0xc7b5
- (id)additionalHeaderValues;	// 0xc76d
- (void)promptUserForNewCoreDAVPasswordWithCompletionBlock:(id)completionBlock;	// 0xc745
- (id)url;	// 0xc675
- (id)description;	// 0xc46d
- (void)dealloc;	// 0xc331
- (id)initWithAccountInfoProvider:(id)accountInfoProvider;	// 0xc1b5
@end
