/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQDGraphic.h>
#import <iWorkImport/iWorkImport-Structs.h>

@class GQDChartModel, GQDChartLegend, GQDSStyle;

__attribute__((visibility("hidden")))
@interface GQDChart : GQDGraphic {
@private
	GQDChartLegend *mLegend;	// 40 = 0x28
	BOOL mIsLegendRetained;	// 44 = 0x2c
	GQDChartModel *mModel;	// 48 = 0x30
	GQDSStyle *mStyle;	// 52 = 0x34
	long mType;	// 56 = 0x38
}
@property(retain) id legend;	// G=0x5dbd; S=0x5e41; converted property
+ (const StateSpec *)stateForReading;	// 0x5db1
- (void)dealloc;	// 0x6591
// converted property getter: - (id)legend;	// 0x5dbd
- (id)model;	// 0x5dcd
- (id)style;	// 0x5ddd
- (id)graphicStyle;	// 0x5ded
- (long)type;	// 0x5dfd
// converted property setter: - (void)setLegend:(id)legend;	// 0x5e41
@end
