/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/XXUnknownSuperclass.h>
#import <iWorkImport/GQDNameMappable.h>
#import <iWorkImport/iWorkImport-Structs.h>

@class GQDImageBinary;

__attribute__((visibility("hidden")))
@interface GQDFilteredImage : XXUnknownSuperclass <GQDNameMappable> {
@private
	GQDImageBinary *mOriginalImageBinary;	// 4 = 0x4
	GQDImageBinary *mFilteredImageBinary;	// 8 = 0x8
}
+ (const StateSpec *)stateForReading;	// 0x7a681
- (id)imageBinary;	// 0x7a65d
- (void)dealloc;	// 0x7a6d5
@end
