/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQDDrawable.h>

@class GQDSStyle;

__attribute__((visibility("hidden")))
@interface GQDGraphic : GQDDrawable {
@private
	GQDSStyle *mGraphicStyle;	// 36 = 0x24
}
- (void)dealloc;	// 0xabed
- (id)graphicStyle;	// 0xabdd
@end
