/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/XXUnknownSuperclass.h>
#import <iWorkImport/GQDRStroke.h>
#import <iWorkImport/GQDNameMappable.h>
#import <iWorkImport/iWorkImport-Structs.h>

@class GQDRStrokePattern, GQDColor;

__attribute__((visibility("hidden")))
@interface GQDRStroke : XXUnknownSuperclass <GQDNameMappable> {
@private
	float mMiterLimit;	// 4 = 0x4
	float mWidth;	// 8 = 0x8
	int mCap;	// 12 = 0xc
	int mJoin;	// 16 = 0x10
	GQDColor *mColor;	// 20 = 0x14
	GQDRStrokePattern *mPattern;	// 24 = 0x18
}
+ (const StateSpec *)stateForReading;	// 0xd759
- (void)dealloc;	// 0xd889
- (float)miterLimit;	// 0xd765
- (float)width;	// 0xd775
- (int)cap;	// 0xd785
- (int)join;	// 0xd795
- (id)color;	// 0xd7a5
- (id)pattern;	// 0xd7b5
@end

@interface GQDRStroke (Private)
- (int)readAttributesFromReader:(xmlTextReader *)reader;	// 0xd969
@end
