/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQDWPPadding.h>


__attribute__((visibility("hidden")))
@interface GQDSLPageMargins : GQDWPPadding {
@private
	float mHeader;	// 20 = 0x14
	float mFooter;	// 24 = 0x18
}
@property(assign) float header;	// G=0xf16d; S=0xf17d; converted property
@property(assign) float footer;	// G=0xf18d; S=0xf19d; converted property
// converted property getter: - (float)header;	// 0xf16d
// converted property setter: - (void)setHeader:(float)header;	// 0xf17d
// converted property getter: - (float)footer;	// 0xf18d
// converted property setter: - (void)setFooter:(float)footer;	// 0xf19d
- (void)setTop:(float)top;	// 0xf1ad
- (void)setBottom:(float)bottom;	// 0xf1c1
- (void)setLeft:(float)left;	// 0xf1d5
- (void)setRight:(float)right;	// 0xf1e9
@end
