/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/iWorkImport-Structs.h>
#import <iWorkImport/GQDTSpiceTableModel.h>
#import <iWorkImport/GQDTTableModel.h>


__attribute__((visibility("hidden")))
@interface GQDTSpiceTableModel : GQDTTableModel {
}
+ (const StateSpec *)stateForReading;	// 0x1b3a1
@end

@interface GQDTSpiceTableModel (Private)
- (int)readAttributesFromReader:(xmlTextReader *)reader;	// 0x1b835
- (int)setRowHeightsFromState:(id)state;	// 0x1b8ed
- (int)setColumnWidthsFromState:(id)state;	// 0x1b949
- (CFArrayRef)createSizeArrayFromPositionVector:(vector<float,std::allocator<float> > *)positionVector;	// 0x1b9a5
@end
