/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/XXUnknownSuperclass.h>
#import <iWorkImport/iWorkImport-Structs.h>
#import <iWorkImport/GQDTTableModel.h>
#import <iWorkImport/GQDNameMappable.h>


__attribute__((visibility("hidden")))
@interface GQDTTableModel : XXUnknownSuperclass <GQDNameMappable> {
@private
	unsigned short mColumnCount;	// 4 = 0x4
	unsigned short mRowCount;	// 6 = 0x6
	CFStringRef mName;	// 8 = 0x8
	BOOL mNameVisible;	// 12 = 0xc
	CFArrayRef mColumnWidths;	// 16 = 0x10
	CFArrayRef mRowHeights;	// 20 = 0x14
	CFArrayRef mColumnVisibilities;	// 24 = 0x18
	CFArrayRef mRowVisibilities;	// 28 = 0x1c
	unsigned short mHeaderRowCount;	// 32 = 0x20
	unsigned short mHeaderColumnCount;	// 34 = 0x22
	unsigned short mFooterRowCount;	// 36 = 0x24
	CFArrayRef mCells;	// 40 = 0x28
	CFArrayRef mColumnGroupDisplayTypes;	// 44 = 0x2c
	int mNumGroupLevels;	// 48 = 0x30
}
@property(assign) int numGroupLevels;	// G=0x1ca2d; S=0x1ca3d; converted property
+ (const StateSpec *)stateForReading;	// 0x1c831
- (void)dealloc;	// 0x1d271
- (unsigned short)columnCount;	// 0x1c83d
- (unsigned short)rowCount;	// 0x1c84d
- (CFStringRef)name;	// 0x1c85d
- (BOOL)isNameVisible;	// 0x1c86d
- (float)widthForColumn:(unsigned short)column;	// 0x1d559
- (float)heightForRow:(unsigned short)row;	// 0x1d511
- (bool)visibilityForColumn:(unsigned short)column;	// 0x1d4cd
- (bool)visibilityForRow:(unsigned short)row;	// 0x1d489
- (id)cellAt:(unsigned short)at;	// 0x1d475
- (CFArrayRef)cells;	// 0x1c87d
- (unsigned short)headerRowCount;	// 0x1c88d
- (unsigned short)headerColumnCount;	// 0x1c89d
- (unsigned short)footerRowCount;	// 0x1c8ad
- (int)typeOfVectorAlongGridline:(unsigned short)vectorAlongGridline offset:(unsigned short)offset length:(unsigned short)length vertical:(BOOL)vertical;	// 0x1c8bd
- (BOOL)hasGroupDisplayType:(unsigned short)type level:(int)level displayType:(int *)type3 isTypeVisible:(BOOL *)visible;	// 0x1d391
- (unsigned short)firstVisibleColumn;	// 0x1d339
// converted property getter: - (int)numGroupLevels;	// 0x1ca2d
// converted property setter: - (void)setNumGroupLevels:(int)levels;	// 0x1ca3d
@end

@interface GQDTTableModel (Private)
- (int)readAttributesForModel:(xmlTextReader *)model;	// 0x1d5a1
- (int)readAttributesForGrid:(xmlTextReader *)grid;	// 0x1d67d
- (int)addColumnWidthFrom:(xmlTextReader *)from;	// 0x1d8b1
- (int)addRowHeightFrom:(xmlTextReader *)from;	// 0x1d97d
- (int)addGroupLevelsFrom:(xmlTextReader *)from;	// 0x1da49
- (void)setCells:(CFArrayRef)cells;	// 0x1d24d
@end
