/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQDWPTextList.h>

@class GQDSStyle;

__attribute__((visibility("hidden")))
@interface GQDWPSpan : GQDWPTextList {
@private
	GQDSStyle *mCharStyle;	// 8 = 0x8
}
- (void)dealloc;	// 0x23e71
- (id)characterStyle;	// 0x23e11
@end
