/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQDWPParagraph.h>
#import <iWorkImport/GQDWPInlineList.h>
#import <iWorkImport/iWorkImport-Structs.h>

@class GQDSStyle;

__attribute__((visibility("hidden")))
@interface GQDWPParagraph : GQDWPInlineList {
@private
	GQDSStyle *mParaStyle;	// 8 = 0x8
	long mListLevel;	// 12 = 0xc
	BOOL mRestartList;	// 16 = 0x10
	BOOL mContinue;	// 17 = 0x11
	BOOL mIsHidden;	// 18 = 0x12
}
- (void)dealloc;	// 0x23481
- (id)paragraphStyle;	// 0x233e1
- (long)listLevel;	// 0x233f1
- (BOOL)restartList;	// 0x23401
- (BOOL)cont;	// 0x23411
- (BOOL)isBlank;	// 0x234cd
- (BOOL)isHidden;	// 0x23421
@end

@interface GQDWPParagraph (Private)
- (int)readAttributesFromReader:(xmlTextReader *)reader processor:(id)processor;	// 0x235d9
@end
