/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <iWorkImport/GQHChart.h>
#import <iWorkImport/iWorkImport-Structs.h>
#import <iWorkImport/XXUnknownSuperclass.h>


__attribute__((visibility("hidden")))
@interface GQHChart : XXUnknownSuperclass {
}
+ (char *)pdfId:(id)anId;	// 0x4dce1
+ (id)geometry:(id)geometry;	// 0x4dcf5
+ (int)handleFloatingChart:(id)chart state:(id)state;	// 0x4dd2d
+ (int)handleInlineChart:(id)chart state:(id)state;	// 0x4dd09
@end

@interface GQHChart (Private)
+ (CFDataRef)renderChart:(id)chart;	// 0x4e03d
+ (CFStringRef)createChartImageUrlString:(id)string state:(id)state;	// 0x4e045
+ (int)handleInlineChart:(id)chart state:(id)state imageUrl:(CFStringRef)url;	// 0x4dead
@end
