/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */




@protocol GQZArchiveInputStream <NSObject>
- (const char *)dataAtOffset:(long long)offset size:(unsigned long)size end:(long long)end readSize:(unsigned *)size4;
- (void)readFromOffset:(long long)offset size:(unsigned long)size buffer:(char *)buffer;
- (long long)size;
@end

