/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DAEAS.framework/DAEAS
 */

#import <DAEAS/ASSearchTask.h>


@interface ASMailboxSearchTask : ASSearchTask {
}
- (int)numDownloadedElements;	// 0x141bd
- (void)finishWithError:(id)error;	// 0x13c51
- (BOOL)processContext:(id)context;	// 0x13731
- (id)replacementObjectForEmailItem:(id)emailItem;	// 0x13689
- (BOOL)getTopLevelToken:(char *)token outStatusCodePage:(char *)page outStatusToken:(char *)token3;	// 0x13675
- (id)requestBody;	// 0x13585
- (void)_appendSearchOptions:(id)options;	// 0x13335
- (void)_appendSearchQuery:(id)query;	// 0x131c1
- (void)performTask;	// 0x130a1
- (BOOL)requiresEASVersionInformaton;	// 0x1309d
@end
