/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DAEAS.framework/DAEAS
 */

#import <DAEAS/XXUnknownSuperclass.h>
#import <DAEAS/ASPolicyManagerDelegate.h>

@class NSError, ASTask, ASGetOptionsTask, ASPolicyManager, NSMutableDictionary;

@interface ASTaskManager : XXUnknownSuperclass <ASPolicyManagerDelegate> {
@private
	ASPolicyManager *_policyManager;	// 56 = 0x38
	NSError *_versionError;	// 60 = 0x3c
	NSMutableDictionary *_taskIDToTask;	// 64 = 0x40
	ASTask *_modalGetOptionsTask;	// 68 = 0x44
	ASGetOptionsTask *_getOptionsTask;	// 72 = 0x48
	ASTask *_modalPolicyKeyUpdateTask;	// 76 = 0x4c
}
@property(readonly, retain) ASPolicyManager *policyManager;	// G=0x60e95; converted property
- (void)taskEndModal:(id)modal;	// 0x6197d
- (void)taskRequestModal:(id)modal;	// 0x61929
- (void)taskDidFinish:(id)task;	// 0x617b1
- (void)cancelTask:(id)task;	// 0x6170d
- (void)shutdown;	// 0x61595
- (void)cancelTaskWithID:(int)anId;	// 0x614bd
- (void)taskManagerWillRemoveTask:(id)taskManager;	// 0x613c5
- (void)taskManagerDidAddTask:(id)taskManager;	// 0x61219
- (id)stateString;	// 0x610a5
- (void)_finishAllTasksWithError:(id)error;	// 0x60fdd
- (void)cancelAllTasks;	// 0x60f49
- (void)finishTask:(id)task withError:(id)error;	// 0x60f35
- (id)policyKey;	// 0x60f0d
- (id)protocol;	// 0x60eed
- (id)easProtocolVersion;	// 0x60ec5
- (void)setEASProtocolVersion:(id)version;	// 0x60ea5
// converted property getter: - (id)policyManager;	// 0x60e95
- (void)policyManagerFailedToUpdatePolicy:(id)updatePolicy;	// 0x60e21
- (void)policyManagerUpdatedPolicy:(id)policy;	// 0x60d95
- (void)updatePolicyKeyWithDelegateTask:(id)delegateTask;	// 0x60c15
- (void)getOptionsTask:(id)task completedWithStatus:(int)status supportedCommands:(id)commands supportedVersions:(id)versions error:(id)error;	// 0x60851
- (void)requestEASVersionWithDelegateTask:(id)delegateTask;	// 0x60545
- (id)_version;	// 0x6051d
- (void)_populateVersionDescriptions;	// 0x604a9
- (void)dealloc;	// 0x60355
- (id)initWithAccount:(id)account policyManager:(id)manager;	// 0x60191
@end
