/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
 */

#import <PhotoBoothEffects/PBMirrorFilter.h>
#import <PhotoBoothEffects/PBFilter.h>
#import <PhotoBoothEffects/PhotoBoothEffects-Structs.h>


@interface PBMirrorFilter : PBFilter {
	CGPoint inputPoint;	// 8 = 0x8
	float inputOrientation;	// 16 = 0x10
}
@property(assign) CGPoint inputPoint;	// G=0x5201; S=0x51cd; @synthesize
@property(assign) float inputOrientation;	// G=0x50d1; S=0x50e1; @synthesize
- (void)setDefaults;	// 0x516d
- (const char *)_fragmentShaderSource;	// 0x50c1
- (id)_glesUniforms;	// 0x5105
- (void)renderWithContext:(id)context inputSize:(CGSize)size outputRect:(CGRect)rect mirrored:(BOOL)mirrored;	// 0x5225
// declared property getter: - (float)inputOrientation;	// 0x50d1
// declared property setter: - (void)setInputOrientation:(float)orientation;	// 0x50e1
// declared property getter: - (CGPoint)inputPoint;	// 0x5201
// declared property setter: - (void)setInputPoint:(CGPoint)point;	// 0x51cd
@end

@interface PBMirrorFilter (OpenCL)
- (void)setupKernelArguments:(id)arguments mirrored:(BOOL)mirrored;	// 0x5411
- (unsigned long)kernelArgCount;	// 0x50f1
- (/*function-pointer*/ void *)kernelWrapper;	// 0x50f5
@end
