/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import <AirPortAssistant/XXUnknownSuperclass.h>

@class UIPickerView;

__attribute__((visibility("hidden")))
@interface PoppablePickerViewController : XXUnknownSuperclass {
	UIPickerView *pickerView;	// 152 = 0x98
}
@property(retain, nonatomic) UIPickerView *pickerView;	// G=0x89e19; S=0x89e29; @synthesize
// declared property setter: - (void)setPickerView:(id)view;	// 0x89e29
// declared property getter: - (id)pickerView;	// 0x89e19
- (void)dealloc;	// 0x89dd1
- (void)viewDidLoad;	// 0x89c8d
@end
