/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
 */

#import <AirPortAssistant/StepByStepUIViewController.h>
#import <AirPortAssistant/TableViewManagerDelegate.h>
#import <AirPortAssistant/UIPickerViewDataSource.h>
#import <AirPortAssistant/UIPickerViewDelegate.h>

@class PoppablePickerViewController, UIPopoverController, NSString, NSDictionary, AnimatedPickerView, NSArray, RecommendationActionController;

__attribute__((visibility("hidden")))
@interface StepByStepUIViewController_DevicePicker : StepByStepUIViewController <UIPickerViewDataSource, UIPickerViewDelegate, TableViewManagerDelegate> {
	NSDictionary *_selectedDevice;	// 220 = 0xdc
	NSDictionary *_sourceNetwork;	// 224 = 0xe0
	NSDictionary *_sourceBase;	// 228 = 0xe4
	NSDictionary *_targetBase;	// 232 = 0xe8
	UIPopoverController *_popover;	// 236 = 0xec
	PoppablePickerViewController *_poppablePickerViewController;	// 240 = 0xf0
	AnimatedPickerView *_networkPickerView;	// 244 = 0xf4
	NSArray *sortedDevices;	// 248 = 0xf8
	NSString *connectionMedium;	// 252 = 0xfc
	RecommendationActionController *actionController;	// 256 = 0x100
	BOOL _showSingleBaseTopo;	// 260 = 0x104
}
@property(retain, nonatomic) RecommendationActionController *actionController;	// G=0x8f629; S=0x8f639; @synthesize
@property(assign, nonatomic) NSString *connectionMedium;	// G=0x8f609; S=0x8f619; @synthesize
@property(retain, nonatomic) NSArray *sortedDevices;	// G=0x8f5d5; S=0x8f5e5; @synthesize
// declared property setter: - (void)setActionController:(id)controller;	// 0x8f639
// declared property getter: - (id)actionController;	// 0x8f629
// declared property setter: - (void)setConnectionMedium:(id)medium;	// 0x8f619
// declared property getter: - (id)connectionMedium;	// 0x8f609
// declared property setter: - (void)setSortedDevices:(id)devices;	// 0x8f5e5
// declared property getter: - (id)sortedDevices;	// 0x8f5d5
- (void)updateSelections;	// 0x8f3d1
- (void)setupPickerTable;	// 0x8f035
- (void)touchInCellAtIndexPath:(id)indexPath;	// 0x8ee31
- (id)pickerView:(id)view titleForRow:(int)row forComponent:(int)component;	// 0x8edc5
- (int)pickerView:(id)view numberOfRowsInComponent:(int)component;	// 0x8eda1
- (int)numberOfComponentsInPickerView:(id)pickerView;	// 0x8ed9d
- (id)valueForItemOfType:(id)type atTypeIndex:(unsigned)typeIndex inCellWithTag:(int)tag;	// 0x8ed71
- (void)viewWillAppear:(BOOL)view;	// 0x8ec01
- (void)viewDidLoad;	// 0x8ea39
@end
