/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
 */

#import <ProtocolBuffer/NSURLConnectionDelegate.h>
#import <ProtocolBuffer/ProtocolBuffer-Structs.h>
#import <ProtocolBuffer/XXUnknownSuperclass.h>

@class NSMutableData, NSURL, NSURLConnection, NSMutableArray, NSDictionary, NSMutableDictionary, NSString, NSArray, PBDataReader;
@protocol PBRequesterDelegate;

@interface PBRequester : XXUnknownSuperclass <NSURLConnectionDelegate> {
	NSURL *_URL;	// 4 = 0x4
	id<PBRequesterDelegate> _delegate;	// 8 = 0x8
	NSURLConnection *_connection;	// 12 = 0xc
	NSMutableData *_data;	// 16 = 0x10
	PBDataReader *_dataReader;	// 20 = 0x14
	unsigned _lastGoodDataOffset;	// 24 = 0x18
	unsigned _uploadPayloadSize;	// 28 = 0x1c
	int _responseStatusCode;	// 32 = 0x20
	NSMutableArray *_requests;	// 36 = 0x24
	NSMutableArray *_responses;	// 40 = 0x28
	NSMutableArray *_internalRequests;	// 44 = 0x2c
	NSMutableArray *_internalResponses;	// 48 = 0x30
	NSDictionary *_httpResponseHeaders;	// 52 = 0x34
	NSMutableDictionary *_httpRequestHeaders;	// 56 = 0x38
	double _timeoutSeconds;	// 60 = 0x3c
	CFRunLoopTimerRef _timeoutTimer;	// 68 = 0x44
	NSString *_logRequestToFile;	// 72 = 0x48
	NSString *_logResponseToFile;	// 76 = 0x4c
	NSArray *_clientCertificates;	// 80 = 0x50
	BOOL _shouldHandleCookies;	// 84 = 0x54
	struct {
		unsigned ignoresResponse : 1;
		unsigned loading : 1;
		unsigned needsCancel : 1;
		unsigned responseStatusSet : 1;
		unsigned parsedResponseHeader : 1;
		unsigned delegateDidReceiveResponse : 1;
		unsigned delegateDidFinish : 1;
		unsigned delegateDidCancel : 1;
		unsigned delegateDidFailWithError : 1;
		unsigned paused : 1;
		unsigned resuming : 1;
	} _flags;	// 85 = 0x55
}
@property(assign) BOOL needsCancel;	// G=0x21fd; S=0x2211; 
@property(assign, nonatomic) BOOL shouldHandleCookies;	// G=0x4559; S=0x4569; @synthesize=_shouldHandleCookies
@property(retain, nonatomic) NSDictionary *httpResponseHeaders;	// G=0x444d; S=0x445d; @synthesize=_httpResponseHeaders
@property(copy, nonatomic) NSDictionary *httpRequestHeaders;	// G=0x245d; S=0x246d; 
@property(retain, nonatomic) NSArray *clientCertificates;	// G=0x4525; S=0x4535; @synthesize=_clientCertificates
@property(assign, nonatomic) double timeoutSeconds;	// G=0x4481; S=0x4499; @synthesize=_timeoutSeconds
@property(readonly, assign, nonatomic) unsigned uploadPayloadSize;	// G=0x4515; @synthesize=_uploadPayloadSize
@property(readonly, assign, nonatomic) NSArray *requests;	// G=0x2249; 
@property(retain, nonatomic) NSString *logResponseToFile;	// G=0x44e1; S=0x44f1; @synthesize=_logResponseToFile
@property(retain, nonatomic) NSString *logRequestToFile;	// G=0x44ad; S=0x44bd; @synthesize=_logRequestToFile
@property(assign, nonatomic) BOOL ignoresResponse;	// G=0x20e1; S=0x20f5; 
@property(retain, nonatomic) NSURLConnection *connection;	// G=0x4419; S=0x4429; @synthesize=_connection
@property(assign, nonatomic) id delegate;	// G=0x4409; S=0x2119; @synthesize=_delegate
@property(retain, nonatomic) NSURL *URL;	// G=0x43d5; S=0x43e5; @synthesize=_URL
@property(readonly, retain) NSMutableArray *internalRequests;	// G=0x2351; converted property
+ (BOOL)usesEncodedMessages;	// 0x43c1
// declared property setter: - (void)setShouldHandleCookies:(BOOL)handleCookies;	// 0x4569
// declared property getter: - (BOOL)shouldHandleCookies;	// 0x4559
// declared property setter: - (void)setClientCertificates:(id)certificates;	// 0x4535
// declared property getter: - (id)clientCertificates;	// 0x4525
// declared property getter: - (unsigned)uploadPayloadSize;	// 0x4515
// declared property setter: - (void)setLogResponseToFile:(id)file;	// 0x44f1
// declared property getter: - (id)logResponseToFile;	// 0x44e1
// declared property setter: - (void)setLogRequestToFile:(id)file;	// 0x44bd
// declared property getter: - (id)logRequestToFile;	// 0x44ad
// declared property setter: - (void)setTimeoutSeconds:(double)seconds;	// 0x4499
// declared property getter: - (double)timeoutSeconds;	// 0x4481
// declared property setter: - (void)setHttpResponseHeaders:(id)headers;	// 0x445d
// declared property getter: - (id)httpResponseHeaders;	// 0x444d
// declared property setter: - (void)setConnection:(id)connection;	// 0x4429
// declared property getter: - (id)connection;	// 0x4419
// declared property getter: - (id)delegate;	// 0x4409
// declared property setter: - (void)setURL:(id)url;	// 0x43e5
// declared property getter: - (id)URL;	// 0x43d5
- (id)decodeResponseData:(id)data;	// 0x43d1
- (void)encodeRequestData:(id)data startRequestCallback:(id)callback;	// 0x43c5
- (void)_timeoutTimerFired;	// 0x4369
- (void)_resetTimeoutTimer;	// 0x42ed
- (void)_removeTimeoutTimer;	// 0x42bd
- (void)_startTimeoutTimer;	// 0x41cd
- (void)connection:(id)connection didFailWithError:(id)error;	// 0x414d
- (void)connectionDidFinishLoading:(id)connection;	// 0x3e29
- (void)connection:(id)connection didReceiveData:(id)data;	// 0x3bb9
- (void)connection:(id)connection didReceiveResponse:(id)response;	// 0x39fd
- (BOOL)_tryParseData;	// 0x3581
- (id)tryReadResponseData:(id)data forRequest:(id)request forResponseClass:(Class)responseClass;	// 0x34f9
- (BOOL)readResponsePreamble:(id)preamble;	// 0x349d
- (void)cancelWithErrorCode:(int)errorCode;	// 0x3471
- (void)_cancelWithErrorDomain:(id)errorDomain errorCode:(int)code userInfo:(id)info;	// 0x33e5
- (void)_failWithErrorDomain:(id)errorDomain errorCode:(int)code userInfo:(id)info;	// 0x3375
- (void)_failWithError:(id)error;	// 0x3335
- (void)resume;	// 0x32e5
- (BOOL)isPaused;	// 0x32d1
- (void)pause;	// 0x3179
- (void)cancel;	// 0x30d9
- (void)start;	// 0x2d91
- (void)_sendPayload:(id)payload;	// 0x2931
- (void)writeRequest:(id)request into:(id)into;	// 0x2885
- (id)requestPreamble;	// 0x26f5
- (id)_osVersion;	// 0x2641
- (id)_applicationID;	// 0x260d
- (id)_languageLocale;	// 0x252d
- (void)setHttpRequestHeader:(id)header forKey:(id)key;	// 0x24b1
// declared property setter: - (void)setHttpRequestHeaders:(id)headers;	// 0x246d
// declared property getter: - (id)httpRequestHeaders;	// 0x245d
- (void)handleResponse:(id)response forInternalRequest:(id)internalRequest;	// 0x2459
- (id)responseForInternalRequest:(id)internalRequest;	// 0x23c9
- (void)addInternalRequest:(id)request;	// 0x2361
// converted property getter: - (id)internalRequests;	// 0x2351
- (id)responseForRequest:(id)request;	// 0x22c1
- (void)addRequest:(id)request;	// 0x2259
// declared property getter: - (id)requests;	// 0x2249
- (void)setNeedsCancel;	// 0x2235
// declared property setter: - (void)setNeedsCancel:(BOOL)cancel;	// 0x2211
// declared property getter: - (BOOL)needsCancel;	// 0x21fd
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x2119
// declared property setter: - (void)setIgnoresResponse:(BOOL)response;	// 0x20f5
// declared property getter: - (BOOL)ignoresResponse;	// 0x20e1
- (void)_cleanup;	// 0x2001
- (void)dealloc;	// 0x1e9d
- (id)initWithURL:(id)url andDelegate:(id)delegate;	// 0x1e19
@end
