/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/Frameworks/IMTranscoding.framework/IMTranscoding
 */

#import <IMTranscoding/IMTranscoding-Structs.h>
#import <IMTranscoding/IMTranscodeController.h>
