/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <GeoServices/XXUnknownSuperclass.h>

@class NSMapTable, NSLock;

@interface GEOLocationShiftRequester : XXUnknownSuperclass {
	NSMapTable *_pendingRequests;	// 4 = 0x4
	NSLock *_pendingRequestsLock;	// 8 = 0x8
	NSMapTable *_providers;	// 12 = 0xc
}
+ (id)sharedRequester;	// 0x286c9
- (Class)classForProviderID:(short)providerID;	// 0x28e09
- (void)registerProvider:(Class)provider;	// 0x28dc9
- (void)cancelRequest:(id)request;	// 0x28d11
- (void)startRequest:(id)request finished:(id)finished networkActivity:(id)activity error:(id)error;	// 0x28921
- (void)dealloc;	// 0x28811
- (id)init;	// 0x28735
@end
