/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <ProtocolBuffer/PBCodable.h>

@class GEOPlaceResult;

@interface GEOLocationResult : PBCodable {
	GEOPlaceResult *_placeResult;	// 4 = 0x4
}
@property(retain, nonatomic) GEOPlaceResult *placeResult;	// G=0x14f89; S=0x14f99; @synthesize=_placeResult
@property(readonly, assign, nonatomic) BOOL hasPlaceResult;	// G=0x14c85; 
// declared property setter: - (void)setPlaceResult:(id)result;	// 0x14f99
// declared property getter: - (id)placeResult;	// 0x14f89
- (void)writeTo:(id)to;	// 0x14ee9
- (BOOL)readFrom:(id)from;	// 0x14d75
- (id)dictionaryRepresentation;	// 0x14d0d
- (id)description;	// 0x14c9d
// declared property getter: - (BOOL)hasPlaceResult;	// 0x14c85
- (void)dealloc;	// 0x14c41
@end

