/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */




@protocol GEOSupportedTileSetsServerProxyDelegate <NSObject>
- (void)supportedTileSetsServerProxyUpdateDidFail:(id)supportedTileSetsServerProxyUpdate;
- (void)supportedTileSetsServerProxyReportedCacheIsCurrent:(id)current;
- (void)supportedTileSetsServerProxy:(id)proxy didReceiveDocumentData:(id)data;
@end

