/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <GeoServices/XXUnknownSuperclass.h>


@interface GEOTileAvailabilityProvider : XXUnknownSuperclass {
}
+ (unsigned short)providerID;	// 0x2d535
- (void)cancelRequest;	// 0x2d53d
- (void)startRequest:(id)request finished:(id)finished error:(id)error;	// 0x2d539
@end
