/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <GeoServices/GeoServices-Structs.h>
#import <GeoServices/XXUnknownSuperclass.h>

@class NSData;

__attribute__((visibility("hidden")))
@interface GEOVoltaireRasterTileImageData : XXUnknownSuperclass {
	NSData *_data;	// 4 = 0x4
}
+ (id)createWithData:(id)data;	// 0x1ff11
- (CGImageRef)newImage;	// 0x1ffa5
- (void)dealloc;	// 0x1ff59
- (id)initWithData:(id)data;	// 0x1feb9
@end
