/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsVoices.framework/SportsVoices
 */

#import <SportsVoices/XXUnknownSuperclass.h>

@class NSString;

@interface AttributeKey : XXUnknownSuperclass {
	int _index;	// 4 = 0x4
	NSString *_key;	// 8 = 0x8
}
@property(readonly, assign) int index;	// G=0xeb1; converted property
@property(readonly, retain) NSString *key;	// G=0xec1; converted property
+ (id)instanceFromPlist:(id)plist;	// 0x1095
- (void)dealloc;	// 0x1141
- (id)initWithIndex:(int)index attributeName:(id)name;	// 0x10dd
- (id)initFromPlist:(id)plist;	// 0xed1
// converted property getter: - (id)key;	// 0xec1
// converted property getter: - (int)index;	// 0xeb1
@end
