/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsVoices.framework/SportsVoices
 */

#import <SportsVoices/XXUnknownSuperclass.h>

@class NSBundle, NSMutableDictionary, NSArray;

@interface Decomposer : XXUnknownSuperclass {
	NSArray *_availableSoundFiles;	// 4 = 0x4
	NSMutableDictionary *_cache;	// 8 = 0x8
	int _iterations;	// 12 = 0xc
	bool _debugging;	// 16 = 0x10
	id _delegate;	// 20 = 0x14
	NSBundle *_bundle;	// 24 = 0x18
}
@property(assign, nonatomic) id delegate;	// G=0x2f91; S=0x2fa1; @synthesize=_delegate
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x2fa1
// declared property getter: - (id)delegate;	// 0x2f91
- (void)dealloc;	// 0x2f0d
- (id)optimalDecompositionOf:(id)of isSubsetOfWhole:(BOOL)whole;	// 0x2a89
- (id)optimalDecompositionOf:(id)of;	// 0x2a0d
- (id)initWithDirectory:(id)directory bundle:(id)bundle;	// 0x27e1
@end
