/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import <SportsWorkout/XXUnknownSuperclass.h>

@class SWVicFileLogger, NSString;

@interface SWAccessory : XXUnknownSuperclass {
	NSString *_transportType;	// 4 = 0x4
	NSString *_serialNumber;	// 8 = 0x8
	NSString *_linkState;	// 12 = 0xc
	NSString *_searchState;	// 16 = 0x10
	SWVicFileLogger *_vicFileLogger;	// 20 = 0x14
}
@property(retain, nonatomic) SWVicFileLogger *vicFileLogger;	// G=0x3765; S=0x3775; @synthesize=_vicFileLogger
@property(readonly, assign, nonatomic) NSString *searchState;	// G=0x3755; @synthesize=_searchState
@property(readonly, assign, nonatomic) NSString *linkState;	// G=0x3745; @synthesize=_linkState
@property(readonly, assign, nonatomic) NSString *serialNumber;	// G=0x3735; @synthesize=_serialNumber
@property(readonly, assign, nonatomic) NSString *transportType;	// G=0x3725; @synthesize=_transportType
// declared property setter: - (void)setVicFileLogger:(id)logger;	// 0x3775
// declared property getter: - (id)vicFileLogger;	// 0x3765
// declared property getter: - (id)searchState;	// 0x3755
// declared property getter: - (id)linkState;	// 0x3745
// declared property getter: - (id)serialNumber;	// 0x3735
// declared property getter: - (id)transportType;	// 0x3725
- (void)cancelSearching;	// 0x36cd
- (void)beginSearching;	// 0x3675
- (void)unlink;	// 0x3595
- (void)cancelLinking;	// 0x34e9
- (void)beginLinking;	// 0x3429
- (void)deactivate;	// 0x33ed
- (void)dealloc;	// 0x33a1
- (id)init;	// 0x3341
@end
