/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */

#import <SportsWorkout/SWRunWorkoutProxy.h>

@class NSTimer, NSString, NSDictionary;

@interface SWRemoteRunWorkoutProxyClient : SWRunWorkoutProxy {
	NSTimer *_updateTimer;	// 4 = 0x4
	NSString *_goalType;	// 8 = 0x8
	NSString *_presetGoal;	// 12 = 0xc
	float _goal;	// 16 = 0x10
	NSString *_sensorSearchState;	// 20 = 0x14
	NSString *_workoutState;	// 24 = 0x18
	NSDictionary *_workoutData;	// 28 = 0x1c
	BOOL _hasEverStarted;	// 32 = 0x20
	BOOL _hasPowerSong;	// 33 = 0x21
	NSString *_powerSongName;	// 36 = 0x24
	BOOL _shouldControlMusic;	// 40 = 0x28
	int _musicSelection;	// 44 = 0x2c
	NSString *_currentSongName;	// 48 = 0x30
}
@property(readonly, retain) NSString *goalType;	// G=0x28bd9; converted property
@property(readonly, retain) NSString *presetGoal;	// G=0x28be9; converted property
@property(readonly, assign) float goal;	// G=0x28bf9; converted property
@property(readonly, retain) NSString *sensorSearchState;	// G=0x28c09; converted property
@property(readonly, retain) NSString *workoutState;	// G=0x28c19; converted property
@property(readonly, retain) NSDictionary *workoutData;	// G=0x28c29; converted property
@property(readonly, assign) BOOL hasPowerSong;	// G=0x28c39; converted property
@property(readonly, retain) NSString *powerSongName;	// G=0x28c49; converted property
@property(readonly, assign) BOOL shouldControlMusic;	// G=0x28c59; converted property
@property(readonly, assign) int musicSelection;	// G=0x28c69; converted property
@property(readonly, retain) NSString *currentSongName;	// G=0x28c79; converted property
// converted property getter: - (id)currentSongName;	// 0x28c79
// converted property getter: - (int)musicSelection;	// 0x28c69
// converted property getter: - (BOOL)shouldControlMusic;	// 0x28c59
// converted property getter: - (id)powerSongName;	// 0x28c49
// converted property getter: - (BOOL)hasPowerSong;	// 0x28c39
// converted property getter: - (id)workoutData;	// 0x28c29
// converted property getter: - (id)workoutState;	// 0x28c19
// converted property getter: - (id)sensorSearchState;	// 0x28c09
// converted property getter: - (float)goal;	// 0x28bf9
// converted property getter: - (id)presetGoal;	// 0x28be9
// converted property getter: - (id)goalType;	// 0x28bd9
- (void)endSeeking;	// 0x28b59
- (void)beginSeekingBackward;	// 0x28ad9
- (void)beginSeekingForward;	// 0x28a59
- (void)selectNextSong;	// 0x289d9
- (void)selectPreviousSong;	// 0x28959
- (void)playMusic;	// 0x288d9
- (void)pauseMusic;	// 0x28859
- (void)goToNowPlaying;	// 0x287d9
- (void)playPowerSong;	// 0x28759
- (void)playOnDemandPrompt;	// 0x286d9
- (void)_nowPlayingChanged:(id)changed;	// 0x28675
- (void)endWorkout;	// 0x285f5
- (void)pauseWorkout;	// 0x28575
- (void)activateWorkout;	// 0x284f5
- (void)prepareToActivateWorkout;	// 0x28475
- (void)_checkinWithServer;	// 0x283f5
- (void)_workoutStateChanged:(id)changed;	// 0x28321
- (void)_sensorSearchStateChanged:(id)changed;	// 0x2824d
- (void)_handlePropertyUpdateNotification:(id)notification;	// 0x27ecd
- (void)dealloc;	// 0x27d71
- (id)init;	// 0x27b6d
@end
