/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsWorkout.framework/SportsWorkout
 */




@protocol SWRunSensorPacketObserver <NSObject>
- (void)sensor:(id)sensor didReceivePacketPayload:(const char *)payload timestamp:(unsigned long)timestamp;
@end

