/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/ChatKit-Structs.h>
#import <ChatKit/XXUnknownSuperclass.h>

@class CKService, NSMutableDictionary, UIActionSheet, NSError;

@interface CKComposeRecipientView : XXUnknownSuperclass {
	CKService *_preferredService;	// 128 = 0x80
	BOOL _canSend;	// 132 = 0x84
	NSError *_serviceError;	// 136 = 0x88
	BOOL _alreadyShowedAlertForTooManyRecipientsError;	// 140 = 0x8c
	NSMutableDictionary *_recipientAvailabilityTimeoutTimers;	// 144 = 0x90
	UIActionSheet *_actionSheet;	// 148 = 0x94
}
@property(retain, nonatomic) CKService *preferredService;	// G=0x7aa45; S=0x7aa81; @synthesize=_preferredService
@property(assign, nonatomic) BOOL canSend;	// G=0x7aa25; S=0x7aa35; @synthesize=_canSend
@property(retain, nonatomic) NSError *serviceError;	// G=0x7aa15; S=0x7aaa9; @synthesize=_serviceError
@property(retain, nonatomic) UIActionSheet *actionSheet;	// G=0x7aa05; S=0x7aad1; @synthesize=_actionSheet
- (id)initWithFrame:(CGRect)frame;	// 0x7ca5d
- (void)dealloc;	// 0x7c995
- (id)customOverlayContainer;	// 0x7c979
- (void)selectComposeRecipientAtom:(id)atom;	// 0x7c8f9
- (void)reflow;	// 0x7c735
- (int)atomStyleForRecipient:(id)recipient;	// 0x7c4c9
- (BOOL)_addable;	// 0x7aa01
- (void)removeRecipient:(id)recipient;	// 0x7c449
- (void)removeAddressAtIndex:(int)index;	// 0x7c3b1
- (void)removeAddresses;	// 0x7c361
- (void)_addRecipient:(id)recipient;	// 0x7aa55
- (void)_addRecipient:(id)recipient atIndex:(unsigned)index;	// 0x7c331
- (void)addRecipient:(id)recipient;	// 0x7c279
- (void)addRecipient:(id)recipient atIndex:(unsigned)index;	// 0x7c23d
- (BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void *)person property:(int)property identifier:(int)identifier;	// 0x7c181
- (void)handleMadridServiceActiveAccountsChangedNotification:(id)notification;	// 0x7c141
- (void)handlePreferredServiceChangedNotification:(id)notification;	// 0x7c101
- (id)_alternateAddressesForMFComposeRecipient:(id)mfcomposeRecipient onlyIMessageAble:(BOOL)able;	// 0x7be4d
- (void)_checkAvailabilityOfAlternateAddressesForMFComposeRecipient:(id)mfcomposeRecipient;	// 0x7bd5d
- (void)_refreshActionSheet;	// 0x7bce1
- (void)_showActionSheetForAtom:(id)atom animated:(BOOL)animated;	// 0x7b7f5
- (void)startAvailabilityTimeoutTimerForRecipient:(id)recipient;	// 0x7b69d
- (void)removeAvailabilityTimeoutTimerForRecipient:(id)recipient;	// 0x7b64d
- (void)handleRecipientAvailabilityTimeout:(id)timeout;	// 0x7b4e9
- (void)stopCheckingRecipientAvailabilityAndRemoveAllTimers;	// 0x7b4b1
- (void)reset;	// 0x7b431
- (void)stopCheckingRecipientAvailability;	// 0x7b375
- (void)updateRecipientLimit;	// 0x7b295
- (BOOL)canInsertMoreRecipients;	// 0x7b249
- (id)_recipientCausingTooManyRecipientsError;	// 0x7b111
- (void)_showOneTimeErrorAlertForTooManyRecipientsUponAddIfNecessary;	// 0x7b0bd
- (void)_showErrorAlertForTooManyRecipientsUponAdd;	// 0x7adad
- (void)showErrorAlertForTooManyRecipientsUponSendIfNecessary;	// 0x7ad59
- (void)_showErrorAlertForTooManyRecipientsUponSend;	// 0x7ab09
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x7aaf9
// declared property getter: - (id)actionSheet;	// 0x7aa05
// declared property setter: - (void)setActionSheet:(id)sheet;	// 0x7aad1
// declared property getter: - (id)serviceError;	// 0x7aa15
// declared property setter: - (void)setServiceError:(id)error;	// 0x7aaa9
// declared property getter: - (BOOL)canSend;	// 0x7aa25
// declared property setter: - (void)setCanSend:(BOOL)send;	// 0x7aa35
// declared property getter: - (id)preferredService;	// 0x7aa45
// declared property setter: - (void)setPreferredService:(id)service;	// 0x7aa81
@end
