/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/UIActionSheetDelegate.h>
#import <ChatKit/UITableViewDelegate.h>
#import <ChatKit/ChatKit-Structs.h>
#import <ChatKit/UITableViewDataSource.h>
#import <ChatKit/CKConversationSearcherDelegate.h>
#import <ChatKit/XXUnknownSuperclass.h>

@class NSIndexPath, CKMessagesController, UIToolbar, UITableView, CKConversationSearcher, CKConversationList;

@interface CKConversationListController : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate, CKConversationSearcherDelegate, UIActionSheetDelegate> {
	UITableView *_table;	// 152 = 0x98
	NSIndexPath *_previouslySelectedIndexPath;	// 156 = 0x9c
	UIToolbar *_buttonBar;	// 160 = 0xa0
	unsigned _willBeMarkedReadCount;	// 164 = 0xa4
	unsigned _dirty : 1;	// 168 = 0xa8
	unsigned _isVisible : 1;	// 168 = 0xa8
	unsigned _isUpdatingDisabled : 1;	// 168 = 0xa8
	unsigned _willRotate : 1;	// 168 = 0xa8
	CKMessagesController *_messagesController;	// 172 = 0xac
	CKConversationList *_conversationList;	// 176 = 0xb0
	CKConversationSearcher *_searcher;	// 180 = 0xb4
	BOOL _disableSMSFullDialog;	// 184 = 0xb8
}
@property(assign, nonatomic) CKConversationList *conversationList;	// G=0x2d931; S=0x2d941; @synthesize=_conversationList
@property(assign, nonatomic) CKMessagesController *messagesController;	// G=0x2d911; S=0x2d921; @synthesize=_messagesController
@property(retain, nonatomic) NSIndexPath *previouslySelectedIndexPath;	// G=0x2d901; S=0x2d9a1; @synthesize=_previouslySelectedIndexPath
- (id)init;	// 0x3038d
- (void)dealloc;	// 0x3028d
- (void)accessibilityLargeTextDidChange;	// 0x30251
- (void)_conversationWasMarkedAsRead:(id)read;	// 0x30225
- (void)_conversationReadItemsDidChange:(id)_conversationReadItems;	// 0x301f9
- (void)_conversationDidChange:(id)_conversation;	// 0x30171
- (void)_conversationListDidFinishLoadingConversations:(id)_conversationList;	// 0x30145
- (void)_conversationListDidChange:(id)_conversationList;	// 0x30135
- (void)_databaseFull:(id)full;	// 0x30125
- (void)_conversationMessageWasSent:(id)sent;	// 0x30115
- (void)_groupsChanged:(id)changed;	// 0x30105
- (void)updateTitle;	// 0x2fd8d
- (void)updateNavigationItems;	// 0x2fc4d
- (void)updateConversationSelection;	// 0x2faa1
- (void)conversationWillBeMarkedRead:(id)conversation;	// 0x2fa65
- (void)noteUnreadCountsChanged;	// 0x2fa45
- (void)significantTimeChange;	// 0x2fa09
- (void)reloadStaleConversations;	// 0x2f9bd
- (void)updateConversationList;	// 0x2f919
- (void)disableConversationListUpdates;	// 0x2d8d5
- (void)enableConversationListUpdates;	// 0x2f8c5
- (void)noteConversationListChanged;	// 0x2f87d
- (void)hideSearchUI;	// 0x2f841
- (void)loadView;	// 0x2f5d1
- (void)viewDidUnload;	// 0x2f52d
- (void)viewWillAppear:(BOOL)view;	// 0x2f3e1
- (void)viewDidAppear:(BOOL)view;	// 0x2f175
- (void)viewWillDisappear:(BOOL)view;	// 0x2f115
- (void)viewDidDisappear:(BOOL)view;	// 0x2f01d
- (void)applicationWillSuspend;	// 0x2efb1
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;	// 0x2ef79
- (void)_getRotationContentSettings:(XXStruct_3uUjXA *)settings;	// 0x2ef39
- (id)inputAccessoryView;	// 0x2ee85
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;	// 0x2ec75
- (void)composeButtonClicked:(id)clicked;	// 0x2ebd1
- (id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;	// 0x2eb91
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x2ea55
- (int)numberOfSectionsInTableView:(id)tableView;	// 0x2d8ed
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x2e9b5
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x2e7d5
- (void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;	// 0x2e7c1
- (void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;	// 0x2e7ad
- (void)deleteButtonPressedForIndexPath:(id)indexPath;	// 0x2e531
- (void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;	// 0x2e511
- (int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;	// 0x2e4ed
- (BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;	// 0x2e4c9
- (void)_displaySMSDatabaseFullWarning;	// 0x2e381
- (void)_checkIfDatabaseIsFull;	// 0x2e249
- (id)searcherContentsController:(id)controller;	// 0x2d8f1
- (id)searcher:(id)searcher conversationForGroupID:(id)groupID;	// 0x2e21d
- (void)searcher:(id)searcher userDidSelectConversationGroupID:(id)user messageRowID:(int)anId partRowID:(int)anId4;	// 0x2e159
- (void)searcher:(id)searcher didShowSearchResultsTableView:(id)view;	// 0x2e0f9
- (void)searcher:(id)searcher willHideSearchResultsTableView:(id)view;	// 0x2e099
- (void)searcherWillEndSearch:(id)searcher;	// 0x2e029
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x2d951
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x2dfdd
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x2df99
- (void)_keyboardWillShowOrHide:(id)_keyboard;	// 0x2dc7d
- (BOOL)_shouldUseKeyWindowStack;	// 0x2d8f5
- (BOOL)_shouldUseDefaultFirstResponder;	// 0x2d8f9
- (BOOL)_shouldUseNextFirstResponder;	// 0x2d8fd
- (unsigned)_indexOfConverationClosestToDeletedIndex:(unsigned)deletedIndex;	// 0x2dc1d
- (unsigned)_indexOfDefaultConversation;	// 0x2db95
- (void)_selectConversationAtIndex:(unsigned)index animated:(BOOL)animated;	// 0x2da71
- (void)selectDefaultConversationAnimated:(BOOL)animated;	// 0x2da11
- (void)selectConversationClosestToDeletedIndex:(unsigned)deletedIndex;	// 0x2d9c9
// declared property getter: - (id)previouslySelectedIndexPath;	// 0x2d901
// declared property setter: - (void)setPreviouslySelectedIndexPath:(id)path;	// 0x2d9a1
// declared property getter: - (id)messagesController;	// 0x2d911
// declared property setter: - (void)setMessagesController:(id)controller;	// 0x2d921
// declared property getter: - (id)conversationList;	// 0x2d931
// declared property setter: - (void)setConversationList:(id)list;	// 0x2d941
@end
