/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/ChatKit-Structs.h>
#import <ChatKit/CKEntity.h>

@class NSArray;

@interface CKMadridEntity : CKEntity {
@private
	NSArray *_imHandles;	// 36 = 0x24
	BOOL _shared;	// 40 = 0x28
}
@property(readonly, retain) NSArray *imHandles;	// G=0x6f9dd; converted property
+ (id)_sharedMadridEntities;	// 0x6ff0d
+ (id)copyAllEntities;	// 0x6fe91
+ (void)resetAllSharedEntityCaches;	// 0x6fdc9
- (id)initWithIMHandle:(id)imhandle;	// 0x702e5
- (void)dealloc;	// 0x70235
- (id)description;	// 0x701c5
- (void)_resetIMHandles;	// 0x6f9ed
- (void)_handleActiveMadridAccountsDidChange:(id)_handleActiveMadridAccounts;	// 0x6fa4d
- (void)_setOtherIMHandlesForIMHandle:(id)imhandle;	// 0x6fa5d
// converted property getter: - (id)imHandles;	// 0x6f9dd
- (id)defaultIMHandle;	// 0x6fb2d
- (void *)abRecord;	// 0x6fb89
- (int)identifier;	// 0x6fbc1
- (id)name;	// 0x6fbe9
- (int)propertyType;	// 0x70179
- (id)rawAddress;	// 0x6fc7d
- (BOOL)isEqual:(id)equal;	// 0x6fca5
- (unsigned)hash;	// 0x6fd29
- (CFPhoneNumberRef)phoneNumberRef;	// 0x6fd51
- (void)_addToShared;	// 0x70079
- (void)_removeFromShared;	// 0x6ff55
- (id)_existingEntityFromSharedForIMHandle:(id)imhandle;	// 0x6fd79
@end
