/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/XXUnknownSuperclass.h>

@class NSString, NSArray;

@interface CKMessageComposition : XXUnknownSuperclass {
}
@property(readonly, assign, nonatomic) BOOL hasContent;	// G=0x86841; 
@property(retain, nonatomic) NSArray *resources;	// G=0x867d1; S=0x867d5; 
@property(copy, nonatomic) NSString *textString;	// G=0x867c9; S=0x867cd; 
@property(copy, nonatomic) NSString *markupString;	// G=0x867c1; S=0x867c5; 
@property(copy, nonatomic) NSString *subject;	// G=0x867d9; S=0x867dd; 
@property(assign, nonatomic) BOOL isTextOnly;	// G=0x867b9; S=0x867bd; 
+ (id)newCompositionForText:(id)text;	// 0x8696d
+ (id)newCompositionForMessage:(id)message;	// 0x86a05
+ (id)newComposition;	// 0x86ac5
+ (void)deleteFileWithPrefix:(id)prefix path:(id)path;	// 0x86af9
+ (id)messageCompositionFromFileWithPrefix:(id)prefix path:(id)path;	// 0x86b65
// declared property getter: - (BOOL)hasContent;	// 0x86841
// declared property getter: - (BOOL)isTextOnly;	// 0x867b9
// declared property setter: - (void)setIsTextOnly:(BOOL)only;	// 0x867bd
// declared property getter: - (id)markupString;	// 0x867c1
// declared property setter: - (void)setMarkupString:(id)string;	// 0x867c5
// declared property getter: - (id)textString;	// 0x867c9
// declared property setter: - (void)setTextString:(id)string;	// 0x867cd
// declared property getter: - (id)resources;	// 0x867d1
// declared property setter: - (void)setResources:(id)resources;	// 0x867d5
// declared property getter: - (id)subject;	// 0x867d9
// declared property setter: - (void)setSubject:(id)subject;	// 0x867dd
- (id)messageParts;	// 0x868ed
- (void)writeToFileWithPrefix:(id)prefix path:(id)path;	// 0x86f11
@end
