/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/ChatKit-Structs.h>
#import <ChatKit/NSFastEnumeration.h>
#import <ChatKit/XXUnknownSuperclass.h>

@class CKService, CKSubConversation, NSNumber, NSString, NSCalendarDate;

@interface CKMessage : XXUnknownSuperclass <NSFastEnumeration> {
@private
	unsigned _height;	// 4 = 0x4
	float _cachedPercentComplete;	// 8 = 0x8
	unsigned _dateLoaded : 1;	// 12 = 0xc
	unsigned _heightAndFlagsLoaded : 1;	// 12 = 0xc
	unsigned _failedSendCountLoaded : 1;	// 12 = 0xc
	unsigned _outgoing : 1;	// 12 = 0xc
	unsigned _outgoingLoaded : 1;	// 12 = 0xc
	unsigned _hasLoadedIsFromDowngrading : 1;	// 12 = 0xc
	unsigned _hasLoadedIsRead : 1;	// 12 = 0xc
	unsigned _isFromDowngrading : 1;	// 12 = 0xc
	unsigned _isRead : 1;	// 13 = 0xd
	CKService *_service;	// 16 = 0x10
	NSString *_groupID;	// 20 = 0x14
	double _date;	// 24 = 0x18
	NSCalendarDate *_calendarDate;	// 32 = 0x20
	int _failedSendCount;	// 36 = 0x24
	unsigned _flags;	// 40 = 0x28
	NSString *_text;	// 44 = 0x2c
	CKSubConversation *_conversation;	// 48 = 0x30
}
@property(assign, nonatomic) CKSubConversation *conversation;	// G=0x31be1; S=0x31bf1; @synthesize=_conversation
@property(retain, nonatomic) NSString *groupID;	// G=0x31af5; S=0x31c59; @synthesize=_groupID
@property(readonly, assign, nonatomic) CKService *service;	// G=0x31bd1; @synthesize=_service
@property(assign, nonatomic) BOOL isFromDowngrading;	// G=0x3235d; S=0x31b59; 
@property(readonly, assign, nonatomic) int rowID;	// G=0x31b05; 
@property(readonly, assign, nonatomic) NSNumber *sequenceNumber;	// G=0x31ac5; 
@property(readonly, assign, nonatomic) NSString *guid;	// G=0x31ac1; 
@property(readonly, assign) int failedSendCount;	// G=0x32281; converted property
@property(readonly, retain) NSString *text;	// G=0x325d9; converted property
- (id)initWithService:(id)service;	// 0x31c01
// declared property getter: - (id)guid;	// 0x31ac1
// declared property getter: - (id)sequenceNumber;	// 0x31ac5
- (int)messageCount;	// 0x31ac9
- (BOOL)isEqual:(id)equal;	// 0x339f9
- (void)dealloc;	// 0x33985
- (void)_resetData;	// 0x338b9
- (void)resetHeightAndFlags;	// 0x31acd
// declared property getter: - (id)groupID;	// 0x31af5
// declared property getter: - (int)rowID;	// 0x31b05
- (double)_loadDate;	// 0x31b0d
- (double)timeIntervalSince1970;	// 0x33859
- (id)date;	// 0x337d5
- (void)markAsRead;	// 0x31b19
- (BOOL)isForward;	// 0x31b1d
- (BOOL)_loadOutgoing;	// 0x31b21
- (void)loadParts;	// 0x33741
- (id)parts;	// 0x31b25
- (unsigned)messagePartCount;	// 0x336a9
- (BOOL)hasAttachments;	// 0x33689
- (id)messagePartAtIndex:(unsigned)index;	// 0x335f1
- (id)messagePartWithRowID:(int)rowID;	// 0x3353d
- (void)_loadText;	// 0x31b29
- (BOOL)isOutgoing;	// 0x334d5
- (id)previewText;	// 0x333a1
- (id)attachmentText:(BOOL)text;	// 0x32609
- (id)subject;	// 0x31b2d
// converted property getter: - (id)text;	// 0x325d9
- (id)error;	// 0x31b31
- (unsigned long)height;	// 0x32599
- (void)_storeUIFlags:(unsigned long)flags;	// 0x31b35
- (void)_loadUIFlags;	// 0x31b39
- (BOOL)storesFlagsInDatabase;	// 0x31b3d
- (void)setUIHeight:(unsigned long)height flags:(unsigned long)flags;	// 0x3254d
- (void)getUIHeight:(unsigned *)height flags:(unsigned *)flags;	// 0x324ed
- (int)totalMessageCount;	// 0x31b41
- (int)pendingCount;	// 0x324a9
- (BOOL)pending;	// 0x32489
- (int)compare:(id)compare;	// 0x32451
- (BOOL)failedSend;	// 0x32415
- (BOOL)partiallyFailedSend;	// 0x323bd
- (BOOL)isDelivered;	// 0x31b45
- (BOOL)isWaitingForDelivery;	// 0x31b49
- (id)timeDelivered;	// 0x31b4d
- (BOOL)_loadIsFromDowngrading;	// 0x31b51
// declared property getter: - (BOOL)isFromDowngrading;	// 0x3235d
- (BOOL)_loadIsRead;	// 0x31b55
- (BOOL)isRead;	// 0x322fd
// declared property setter: - (void)setIsFromDowngrading:(BOOL)downgrading;	// 0x31b59
- (BOOL)isFromMe;	// 0x31b89
- (int)sentCount;	// 0x31b8d
- (BOOL)hasBeenSent;	// 0x322c5
- (id)timeRead;	// 0x31b95
- (BOOL)isPlaceholder;	// 0x31b99
- (BOOL)isTypingIndicator;	// 0x31b9d
- (void)_loadFailedSendCount;	// 0x31ba1
// converted property getter: - (int)failedSendCount;	// 0x32281
- (BOOL)completelyFailedSend;	// 0x32249
- (void)reloadFailedSendCount;	// 0x31ba5
- (float)percentComplete;	// 0x320ad
- (id)sender;	// 0x31bbd
- (id)address;	// 0x31bc1
- (id)alertImageData;	// 0x31fbd
- (BOOL)isFirstDisplayablePart:(id)part;	// 0x31efd
- (BOOL)isOnlyDisplayableMessagePart:(id)part;	// 0x31e4d
- (void)deleteMessagePart:(id)part;	// 0x31bc5
- (BOOL)smartForwardCapable;	// 0x31bc9
- (BOOL)getCharacterCountNumerator:(unsigned *)numerator denominator:(unsigned *)denominator;	// 0x31d61
- (void)send;	// 0x31d35
- (void)cancel;	// 0x31d09
- (unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA *)state objects:(id *)objects count:(unsigned)count;	// 0x31c81
- (BOOL)wantsSendStatus;	// 0x31bcd
// declared property getter: - (id)service;	// 0x31bd1
// declared property setter: - (void)setGroupID:(id)anId;	// 0x31c59
// declared property getter: - (id)conversation;	// 0x31be1
// declared property setter: - (void)setConversation:(id)conversation;	// 0x31bf1
@end
