/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

#import <ChatKit/XXUnknownSuperclass.h>

@class NSData, CKMediaObject;

@interface CKMediaPreviewGenerator : XXUnknownSuperclass {
@private
	BOOL _generateComposePreview;	// 12 = 0xc
	int _orientation;	// 16 = 0x10
	CKMediaObject *_mediaObject;	// 20 = 0x14
	id _delegate;	// 24 = 0x18
	NSData *_previewResult;	// 28 = 0x1c
	NSData *_composePreviewResult;	// 32 = 0x20
}
@property(assign, nonatomic) int orientation;	// G=0x51171; S=0x51181; @synthesize=_orientation
@property(assign, nonatomic) BOOL generateComposePreview;	// G=0x51151; S=0x51161; @synthesize=_generateComposePreview
@property(retain, nonatomic) CKMediaObject *mediaObject;	// G=0x51141; S=0x512c1; @synthesize=_mediaObject
@property(assign, nonatomic) id delegate;	// G=0x51121; S=0x51131; @synthesize=_delegate
@property(readonly, assign, nonatomic) NSData *previewResult;	// G=0x51111; @synthesize=_previewResult
@property(readonly, assign, nonatomic) NSData *composePreviewResult;	// G=0x51101; @synthesize=_composePreviewResult
- (void)main;	// 0x51191
- (void)dealloc;	// 0x5124d
// declared property getter: - (id)composePreviewResult;	// 0x51101
// declared property getter: - (id)previewResult;	// 0x51111
// declared property getter: - (id)delegate;	// 0x51121
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x51131
// declared property getter: - (id)mediaObject;	// 0x51141
// declared property setter: - (void)setMediaObject:(id)object;	// 0x512c1
// declared property getter: - (BOOL)generateComposePreview;	// 0x51151
// declared property setter: - (void)setGenerateComposePreview:(BOOL)preview;	// 0x51161
// declared property getter: - (int)orientation;	// 0x51171
// declared property setter: - (void)setOrientation:(int)orientation;	// 0x51181
@end
