/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

#import <IMCore/IMCore-Structs.h>
#import <IMCore/IMMessageChatItem.h>
#import <IMCore/IMHeaderChatItem.h>
#import <IMCore/IMTimestampChatItem.h>
#import <IMCore/IMChatItem.h>
#import <IMCore/IMChatRegistry.h>
#import <IMCore/IMPeopleCollection.h>
#import <IMCore/IMParentalControls.h>
#import <IMCore/IMServiceSessionProtocol.h>
#import <IMCore/IMHandleRegistrar.h>
#import <IMCore/IMMessage.h>
#import <IMCore/IMHandleRegistrarInternal.h>
#import <IMCore/IMDaemonListener.h>
#import <IMCore/FZDaemon.h>
#import <IMCore/IMServiceAgentCenter.h>
#import <IMCore/IMChat.h>
#import <IMCore/IMPersonRegistrar.h>

#import <IMCore/IMPerson.h>
#import <IMCore/IMActionsController.h>
#import <IMCore/IMFileTransferCenter.h>
#import <IMCore/IMAccountController.h>
#import <IMCore/NSCopying.h>
#import <IMCore/IMMe.h>
#import <IMCore/IMServiceAgentImpl.h>
#import <IMCore/IMPeople.h>
#import <IMCore/IMStatusChatItem.h>
#import <IMCore/NSCoding.h>
#import <IMCore/IMServiceAgent.h>
#import <IMCore/IMService.h>
#import <IMCore/IMAccount.h>
#import <IMCore/IMParentalControlsService.h>
#import <IMCore/IMMarkChatItem.h>
#import <IMCore/IMHandle.h>
#import <IMCore/IMDaemonController.h>
#import <IMCore/IMServiceImpl.h>
#import <IMCore/IMDaemonListenerProtocol.h>
#import <IMCore/IMDatestampChatItem.h>
#import <IMCore/IMSystemMonitorListener.h>
#import <IMCore/IMAddressBook.h>
