/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */



@class NSDictionary, NSArray;

@interface IMServiceAgent : NSObject {
	NSDictionary *_currentAVChatInfo;	// 4 = 0x4
}
@property(readonly, assign, nonatomic) unsigned requestAudioReflectorStop;	// G=0x2e301; 
@property(readonly, assign, nonatomic) unsigned requestAudioReflectorStart;	// G=0x2e2fd; 
@property(readonly, assign, nonatomic) NSDictionary *currentAVChatInfo;	// G=0x2e2f9; 
@property(readonly, assign, nonatomic) unsigned long long vcCapabilities;	// G=0x2e309; 
@property(retain, nonatomic) NSArray *myAwayMessages;	// G=0x2e2ed; S=0x2e2f5; 
@property(retain, nonatomic) NSArray *myAvailableMessages;	// G=0x2e2e9; S=0x2e2f1; 
+ (id)notificationCenter;	// 0x8095
+ (void)forgetStatusImageAppearance;	// 0x2e2a5
+ (id)imageNameForStatus:(unsigned)status;	// 0x348d
+ (id)imageURLForStatus:(unsigned)status;	// 0x2e289
+ (id)sharedAgent;	// 0x2e26d
+ (int)serviceAgentCapabilities;	// 0x2e22d
+ (void)setServiceAgentCapabilities:(int)capabilities;	// 0x2e1d5
- (void)dealloc;	// 0x2e389
- (id)myPictureData;	// 0x2e345
- (void)launchIfNecessary;	// 0x2e311
// declared property getter: - (unsigned long long)vcCapabilities;	// 0x2e309
- (unsigned)requestVideoStillForPerson:(id)person;	// 0x2e305
// declared property getter: - (unsigned)requestAudioReflectorStop;	// 0x2e301
// declared property getter: - (unsigned)requestAudioReflectorStart;	// 0x2e2fd
// declared property getter: - (id)currentAVChatInfo;	// 0x2e2f9
// declared property setter: - (void)setMyAwayMessages:(id)messages;	// 0x2e2f5
// declared property setter: - (void)setMyAvailableMessages:(id)messages;	// 0x2e2f1
// declared property getter: - (id)myAwayMessages;	// 0x2e2ed
// declared property getter: - (id)myAvailableMessages;	// 0x2e2e9
- (void)setMyStatus:(unsigned)status message:(id)message;	// 0x2e2e5
- (id)notificationCenter;	// 0x2e2c9
- (id)serviceWithNameNonBlocking:(id)nameNonBlocking;	// 0x2e2c5
- (id)serviceWithName:(id)name;	// 0x2e2c1
@end
