/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsTrainer.framework/SportsTrainer
 */

#import <SportsTrainer/XXUnknownSuperclass.h>
#import <SportsTrainer/SportsTrainer-Structs.h>

@protocol STAnimatableButtonSliceDelegate;

@interface STAnimatableButtonSlice : XXUnknownSuperclass {
	id<STAnimatableButtonSliceDelegate> _delegate;	// 48 = 0x30
}
@property(assign, nonatomic) id<STAnimatableButtonSliceDelegate> delegate;	// G=0xaea1; S=0xaeb1; @synthesize=_delegate
// declared property setter: - (void)setDelegate:(id)delegate;	// 0xaeb1
// declared property getter: - (id)delegate;	// 0xaea1
- (void)drawRect:(CGRect)rect;	// 0xaded
- (id)initWithFrame:(CGRect)frame;	// 0xad9d
@end
