/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SportsTrainer.framework/SportsTrainer
 */




@protocol STAnimatableButtonSliceDelegate <NSObject>
- (void)drawImageForSlice;
@end

