/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

#import <TextInput/TextInput-Structs.h>
#import <TextInput/XXUnknownSuperclass.h>


@interface TIMecabraCandidate : XXUnknownSuperclass {
@private
	void *_candidate;	// 4 = 0x4
}
- (id)candidate;	// 0xb7fd
- (id)input;	// 0xb811
- (id)initConversionCandidateWithSurface:(id)surface andInput:(id)input;	// 0xb825
- (id)initWithMecabraCandidate:(const void *)mecabraCandidate;	// 0xb931
- (void)dealloc;	// 0xb8f1
- (id)copyWithZone:(NSZone *)zone;	// 0xb8ad
- (void *)mecabraCandidate;	// 0xb7ed
- (BOOL)isExtensionCandidate;	// 0xb891
- (BOOL)isForShortcutConversion;	// 0xb875
@end
