/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

#import <TextInput/XXUnknownSuperclass.h>

@class TIWordSearch;

@interface TIWordSearchOperation : XXUnknownSuperclass {
	TIWordSearch *_kbws;	// 12 = 0xc
}
@property(readonly, retain, nonatomic) TIWordSearch *kbws;	// G=0x30e69; @synthesize=_kbws
- (id)initWithTIWordSearch:(id)tiwordSearch;	// 0x30fe9
- (void)dealloc;	// 0x310b5
- (void)perform;	// 0x30e65
- (void)main;	// 0x31041
// declared property getter: - (id)kbws;	// 0x30e69
@end
