/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import <Conference/XXUnknownSuperclass.h>
#import <Conference/Conference-Structs.h>

@class UIColor;

@interface CNFArrowView : XXUnknownSuperclass {
@private
	UIColor *_fillColor;	// 48 = 0x30
	UIColor *_strokeColor;	// 52 = 0x34
}
@property(retain, nonatomic) UIColor *strokeColor;	// G=0x1d619; S=0x1d67d; @synthesize=_strokeColor
@property(retain, nonatomic) UIColor *fillColor;	// G=0x1d609; S=0x1d6a5; @synthesize=_fillColor
- (id)initWithFrame:(CGRect)frame;	// 0x1d629
- (void)drawRect:(CGRect)rect;	// 0x1d72d
- (void)dealloc;	// 0x1d6cd
// declared property getter: - (id)fillColor;	// 0x1d609
// declared property setter: - (void)setFillColor:(id)color;	// 0x1d6a5
// declared property getter: - (id)strokeColor;	// 0x1d619
// declared property setter: - (void)setStrokeColor:(id)color;	// 0x1d67d
@end
