/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import <Conference/XXUnknownSuperclass.h>


@interface CNFInternalProcessListController : XXUnknownSuperclass {
}
- (id)specifiers;	// 0x4a2a5
- (id)bundle;	// 0x4a2f5
- (void)killJustIChatAgent:(id)agent;	// 0x4a311
- (void)killJustMediaServerD:(id)d;	// 0x4a32d
- (void)conferenceKillProcessesAndNukeKeychain:(id)keychain;	// 0x4a349
- (void)conferenceKillProcesses:(id)processes;	// 0x4a381
@end
