/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Conference.framework/Conference
 */

#import <Conference/CNFRegTableLabel.h>


@interface CNFRegTableFooterLabel : CNFRegTableLabel {
}
- (id)initWithSpecifier:(id)specifier;	// 0x34ed5
- (id)_labelText;	// 0x3500d
- (id)_URLText;	// 0x34fe5
- (id)_URLTarget;	// 0x34fbd
- (int)_labelTextAlignment;	// 0x34f4d
- (float)_topPadding;	// 0x341d9
- (float)_bottomPadding;	// 0x341e1
@end
