/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import <PhotoLibraryServices/PLManagedObject.h>


@interface _PLManagedAdjustment : PLManagedObject {
}
+ (id)entityInManagedObjectContext:(id)managedObjectContext;	// 0x4d921
+ (id)entityName;	// 0x4d915
+ (id)insertInManagedObjectContext:(id)managedObjectContext;	// 0x4d84d
- (id)objectID;	// 0x4d9dd
@end
