/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import <PhotoLibraryServices/XXUnknownSuperclass.h>
#import <PhotoLibraryServices/PLImageCache.h>

@class PLImageCacheList, PLImageLoadingThread;

@interface PLImageCache : XXUnknownSuperclass {
	PLImageLoadingThread *_loader;	// 4 = 0x4
@private
	PLImageCacheList *_cacheList;	// 8 = 0x8
}
- (id)newImageLoadingQueue;	// 0x1c8f1
- (void)_addImageToCache:(id)cache;	// 0x1c8b1
- (void)invalidateCachedImageForSource:(id)source asset:(id)asset;	// 0x1c869
- (id)cachedImageFromSource:(id)source forAsset:(id)asset loadIfNeeded:(BOOL)needed synchronously:(BOOL)synchronously priority:(int)priority forImageLoadingQueue:(id)imageLoadingQueue;	// 0x1c7f1
- (id)_cachedImageFromSource:(id)source asset:(id)asset;	// 0x1c7a9
- (void)_uncacheImage:(id)image;	// 0x1c76d
- (id)_imageLoader;	// 0x1c75d
- (void)dealloc;	// 0x1c6bd
- (id)init;	// 0x1c625
@end

@interface PLImageCache (Internal)
- (void)resumeLoading;	// 0x1cbbd
- (void)pauseLoading;	// 0x1cb95
- (void)cancelLoadFromSource:(id)source asset:(id)asset imageLoadingQueue:(id)queue;	// 0x1cb65
- (void)removeImageLoadingQueue:(id)queue;	// 0x1cb39
- (id)newCachedImageWithImageContents:(void *)imageContents orientation:(int)orientation metadata:(id)metadata fromSource:(id)source asset:(id)asset;	// 0x1c9c9
- (id)cachedImageFromSource:(id)source asset:(id)asset loadIfNeeded:(BOOL)needed synchronously:(BOOL)synchronously priority:(int)priority forImageLoadingQueue:(id)imageLoadingQueue completion:(id)completion;	// 0x1c951
@end
