/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import <PhotoLibraryServices/PLManagedAsset.h>
#import <PhotoLibraryServices/PhotoLibraryServices-Structs.h>
#import <PhotoLibraryServices/_PLManagedAsset.h>

@class NSMutableOrderedSet, UIImage, NSDictionary, NSMutableSet, NSURL, CLLocation, NSDate, NSData, NSSet, NSArray, NSString, NSNumber;

@interface PLManagedAsset : _PLManagedAsset {
@private
	BOOL _didPrepareForDeletion;	// 48 = 0x30
	UIImage *inflightImage;	// 52 = 0x34
	UIImage *inflightIndexSheetImage;	// 56 = 0x38
	NSDictionary *inflightMetadata;	// 60 = 0x3c
}
@property(assign) int thumbnailIndex;	// G=0x2e75d; S=0x2e7c9; 
@property(retain, nonatomic) NSDictionary *inflightMetadata;	// G=0x2fcb5; S=0x2fcc5; @synthesize
@property(retain, nonatomic) UIImage *inflightIndexSheetImage;	// G=0x2fc81; S=0x2fc91; @synthesize
@property(retain, nonatomic) UIImage *inflightImage;	// G=0x2fc4d; S=0x2fc5d; @synthesize
@property(assign, nonatomic) BOOL isInFlight;	// G=0x2fbf5; S=0x2fba9; 
@property(retain, nonatomic) PLManagedAsset *originalAsset;	// G=0x2faed; S=0x2fb59; 
@property(readonly, assign, nonatomic) NSMutableOrderedSet *adjustments;	// @dynamic
@property(assign) unsigned effectiveThumbnailIndex;	// G=0x2e839; S=0x2e859; 
@property(retain, nonatomic) CLLocation *location;	// G=0x2ed95; S=0x2eea1; 
@property(assign, nonatomic) int savedAssetTypeValue;	// G=0x2ec5d; S=0x2ec85; 
@property(assign, nonatomic) int highDynamicRangeTypeValue;	// G=0x2ebf9; S=0x2ec21; 
+ (id)keyPathsForValuesAffectingValueForKey:(id)key;	// 0x2e4a9
+ (id)assetWithObjectID:(id)objectID inLibrary:(id)library;	// 0x2e475
+ (id)assetWithUUID:(id)uuid inLibrary:(id)library;	// 0x2e441
// declared property setter: - (void)setInflightMetadata:(id)metadata;	// 0x2fcc5
// declared property getter: - (id)inflightMetadata;	// 0x2fcb5
// declared property setter: - (void)setInflightIndexSheetImage:(id)image;	// 0x2fc91
// declared property getter: - (id)inflightIndexSheetImage;	// 0x2fc81
// declared property setter: - (void)setInflightImage:(id)image;	// 0x2fc5d
// declared property getter: - (id)inflightImage;	// 0x2fc4d
// declared property getter: - (BOOL)isInFlight;	// 0x2fbf5
// declared property setter: - (void)setIsInFlight:(BOOL)flight;	// 0x2fba9
- (BOOL)hasGPS;	// 0x2fba5
// declared property setter: - (void)setOriginalAsset:(id)asset;	// 0x2fb59
// declared property getter: - (id)originalAsset;	// 0x2faed
- (void)updateAdjustmentsWithAdjustmentMetadata:(id)adjustmentMetadata;	// 0x2f919
- (void)updateAdjustmentsWithFiltersAndIdentifiers:(id)filtersAndIdentifiers;	// 0x2f01d
- (id)addAdjustment;	// 0x2ef9d
- (void)delete;	// 0x2ef6d
// declared property setter: - (void)setLocation:(id)location;	// 0x2eea1
// declared property getter: - (id)location;	// 0x2ed95
- (BOOL)isLocatedAtCoordinates:(XXStruct_UNJ7RC)coordinates;	// 0x2ecc1
// declared property setter: - (void)setSavedAssetTypeValue:(int)value;	// 0x2ec85
// declared property getter: - (int)savedAssetTypeValue;	// 0x2ec5d
// declared property setter: - (void)setHighDynamicRangeTypeValue:(int)value;	// 0x2ec21
// declared property getter: - (int)highDynamicRangeTypeValue;	// 0x2ebf9
- (void)prepareForDeletion;	// 0x2e879
// declared property setter: - (void)setEffectiveThumbnailIndex:(unsigned)index;	// 0x2e859
// declared property getter: - (unsigned)effectiveThumbnailIndex;	// 0x2e839
// declared property setter: - (void)setThumbnailIndex:(int)index;	// 0x2e7c9
// declared property getter: - (int)thumbnailIndex;	// 0x2e75d
- (void)willTurnIntoFault;	// 0x2e71d
- (void)awakeFromSnapshotEvents:(unsigned)snapshotEvents;	// 0x2e6cd
- (void)awakeFromFetch;	// 0x2e68d
- (void)awakeFromInsert;	// 0x2e5cd
- (void)dealloc;	// 0x2e589
@end

@interface PLManagedAsset (VideoAdditions)
- (id)previewFrameImageFromDatabase;	// 0x25ed
@end

@interface PLManagedAsset (Convenience)
@property(readonly, assign, nonatomic) NSArray *sortedSidecarFiles;	// G=0x659d; 
@property(readonly, assign, nonatomic) BOOL allowsWallpaperEditing;	// G=0x654d; 
@property(readonly, assign, nonatomic) BOOL isAudio;	// G=0x64f9; 
@property(readonly, assign, nonatomic) BOOL isPhoto;	// G=0x64b1; 
@property(readonly, assign, nonatomic) BOOL isHDVideo;	// G=0x641d; 
@property(readonly, assign, nonatomic) BOOL isVideo;	// G=0x63fd; 
@property(readonly, assign, nonatomic) BOOL isPhotoStreamPhoto;	// G=0x63b5; 
@property(readonly, assign, nonatomic) NSDate *date;	// G=0x637d; 
@property(readonly, assign, nonatomic) BOOL hasLocationInfo;	// G=0x6335; 
@property(assign, nonatomic) XXStruct_UNJ7RC gpsCoordinate;	// G=0x6225; S=0x6275; 
@property(assign, nonatomic) double recordModDate;	// G=0x615d; S=0x6185; 
@property(readonly, assign, nonatomic) BOOL allowsRotation;	// G=0x60ed; 
@property(assign, nonatomic) CGSize imageSize;	// G=0x5f89; S=0x603d; 
@property(assign, nonatomic) double captureTime;	// G=0x5ee5; S=0x5f0d; 
@property(assign, nonatomic) int assetKind;	// G=0x5e91; S=0x5ea9; 
+ (id)bestCreationDateForAssestAtURL:(id)url;	// 0x6731
+ (id)keyPathsForValuesAffectingIsAudio;	// 0x64d1
+ (id)keyPathsForValuesAffectingIsPhoto;	// 0x6489
+ (id)keyPathsForValuesAffectingIsVideo;	// 0x63d5
+ (id)keyPathsForValuesAffectingIsPhotoStreamPhoto;	// 0x638d
+ (id)keyPathsForValuesAffectingDate;	// 0x6355
+ (id)keyPathsForValuesAffectingHasLocationInfo;	// 0x630d
+ (id)keyPathsForValuesAffectingGpsCoordinate;	// 0x61fd
+ (id)keyPathsForValuesAffectingRecordModDate;	// 0x6135
+ (id)keyPathsForValuesAffectingImageSize;	// 0x5f49
+ (id)keyPathsForValuesAffectingCaptureTime;	// 0x5ebd
+ (id)keyPathsForValuesAffectingAssetKind;	// 0x5e69
// declared property getter: - (id)sortedSidecarFiles;	// 0x659d
- (BOOL)canPerformEditOperation:(int)operation;	// 0x6551
// declared property getter: - (BOOL)allowsWallpaperEditing;	// 0x654d
- (BOOL)isEditable;	// 0x6519
// declared property getter: - (BOOL)isAudio;	// 0x64f9
// declared property getter: - (BOOL)isPhoto;	// 0x64b1
// declared property getter: - (BOOL)isHDVideo;	// 0x641d
// declared property getter: - (BOOL)isVideo;	// 0x63fd
// declared property getter: - (BOOL)isPhotoStreamPhoto;	// 0x63b5
// declared property getter: - (id)date;	// 0x637d
// declared property getter: - (BOOL)hasLocationInfo;	// 0x6335
// declared property setter: - (void)setGpsCoordinate:(XXStruct_UNJ7RC)coordinate;	// 0x6275
// declared property getter: - (XXStruct_UNJ7RC)gpsCoordinate;	// 0x6225
- (void)setRecordModDate;	// 0x61c1
// declared property setter: - (void)setRecordModDate:(double)date;	// 0x6185
// declared property getter: - (double)recordModDate;	// 0x615d
// declared property getter: - (BOOL)allowsRotation;	// 0x60ed
// declared property setter: - (void)setImageSize:(CGSize)size;	// 0x603d
// declared property getter: - (CGSize)imageSize;	// 0x5f89
// declared property setter: - (void)setCaptureTime:(double)time;	// 0x5f0d
// declared property getter: - (double)captureTime;	// 0x5ee5
// declared property setter: - (void)setAssetKind:(int)kind;	// 0x5ea9
// declared property getter: - (int)assetKind;	// 0x5e91
@end

@interface PLManagedAsset (UniformTypeIdentifiers)
@property(readonly, assign, nonatomic) BOOL isJPEG;	// G=0x6ead; 
@property(readonly, assign, nonatomic) NSString *mimeType;	// G=0x6e49; 
@property(copy, nonatomic) NSString *utiType;	// G=0x6e01; S=0x6e11; 
+ (id)keyPathsForValuesAffectingIsJPEG;	// 0x6e85
+ (id)keyPathsForValuesAffectingMimeType;	// 0x6e21
+ (id)keyPathsForValuesAffectingUtiType;	// 0x6dd9
- (void)updateAssetKindFromUniformTypeIdentifier;	// 0x6fa1
- (void)setUniformTypeIdentifierFromPathExtension:(id)pathExtension assetKind:(int)kind;	// 0x6f6d
- (void)setUniformTypeIdentifierFromPathExtension:(id)pathExtension;	// 0x6ed9
// declared property getter: - (BOOL)isJPEG;	// 0x6ead
// declared property getter: - (id)mimeType;	// 0x6e49
// declared property setter: - (void)setUtiType:(id)type;	// 0x6e11
// declared property getter: - (id)utiType;	// 0x6e01
@end

@interface PLManagedAsset (FilePaths)
@property(readonly, assign, nonatomic) BOOL hasFullSizeImageData;	// G=0x8001; 
@property(readonly, assign, nonatomic) BOOL hasXMPFile;	// G=0x7f6d; 
@property(readonly, assign, nonatomic) NSString *pathForXMPFile;	// G=0x7f29; 
@property(readonly, assign, nonatomic) NSURL *fileURLForLargeDisplayableImage;	// G=0x7d49; 
@property(readonly, assign, nonatomic) NSString *pathForLargeDisplayableImageFile;	// G=0x7cb9; 
@property(readonly, assign, nonatomic) NSString *pathForVideoFile;	// G=0x7c81; 
@property(readonly, assign, nonatomic) NSString *pathForVideoPreviewFile;	// G=0x7c3d; 
@property(readonly, assign, nonatomic) NSString *pathForTrimmedVideoFile;	// G=0x7bf5; 
@property(readonly, assign, nonatomic) NSString *pathForLowResolutionFile;	// G=0x7f0d; 
@property(readonly, assign, nonatomic) NSString *pathForPrebakedWildcatThumbnailsFile;	// G=0x7bd9; 
@property(readonly, assign, nonatomic) NSURL *fileURLForPrebakedPortraitScrubberThumbnails;	// G=0x7ec9; 
@property(readonly, assign, nonatomic) NSString *pathForPrebakedPortraitScrubberThumbnails;	// G=0x7e85; 
@property(readonly, assign, nonatomic) NSURL *fileURLForPrebakedLandscapeScrubberThumbnails;	// G=0x7e41; 
@property(readonly, assign, nonatomic) NSString *pathForPrebakedLandscapeScrubberThumbnails;	// G=0x7dfd; 
@property(readonly, assign, nonatomic) NSString *pathForPrebakedThumbnail;	// G=0x7bbd; 
@property(readonly, assign, nonatomic) NSURL *fileURLForThumbnailFile;	// G=0x7ba1; 
@property(readonly, assign, nonatomic) NSURL *fileURLForMetadataDirectory;	// G=0x7a1d; 
@property(readonly, assign, nonatomic) NSString *pathForMetadataDirectory;	// G=0x79f5; 
@property(readonly, assign, nonatomic) NSString *fileExtension;	// G=0x79cd; 
@property(readonly, assign, nonatomic) NSArray *allUniformTypeIdentifiers;	// G=0x786d; 
@property(readonly, assign, nonatomic) NSURL *fileURLForLargeThumbnailFile;	// G=0x7669; 
@property(readonly, assign, nonatomic) NSString *pathForOriginalFile;	// G=0x7685; 
@property(readonly, assign, nonatomic) NSString *pathForLargeThumbnailFile;	// G=0x764d; 
@property(readonly, assign, nonatomic) NSSet *filePathsWithoutThumbs;	// G=0x7361; 
@property(readonly, assign, nonatomic) NSSet *allFileURLs;	// G=0x7491; 
@property(readonly, assign, nonatomic) NSString *pathForImageFile;	// G=0x7159; 
@property(readonly, assign, nonatomic) NSURL *mainFileURL;	// G=0x7119; 
+ (id)pathForMetadataWithExtension:(id)extension forMediaInMainDirectory:(id)mainDirectory withFilename:(id)filename;	// 0x7269
+ (id)abbreviatedMetadataDirectoryForDirectory:(id)directory;	// 0x7169
// declared property getter: - (BOOL)hasFullSizeImageData;	// 0x8001
- (void)save;	// 0x7fb9
// declared property getter: - (BOOL)hasXMPFile;	// 0x7f6d
// declared property getter: - (id)pathForXMPFile;	// 0x7f29
// declared property getter: - (id)pathForLowResolutionFile;	// 0x7f0d
// declared property getter: - (id)fileURLForPrebakedPortraitScrubberThumbnails;	// 0x7ec9
// declared property getter: - (id)pathForPrebakedPortraitScrubberThumbnails;	// 0x7e85
// declared property getter: - (id)fileURLForPrebakedLandscapeScrubberThumbnails;	// 0x7e41
// declared property getter: - (id)pathForPrebakedLandscapeScrubberThumbnails;	// 0x7dfd
// declared property getter: - (id)fileURLForLargeDisplayableImage;	// 0x7d49
// declared property getter: - (id)pathForLargeDisplayableImageFile;	// 0x7cb9
// declared property getter: - (id)pathForVideoFile;	// 0x7c81
// declared property getter: - (id)pathForVideoPreviewFile;	// 0x7c3d
// declared property getter: - (id)pathForTrimmedVideoFile;	// 0x7bf5
// declared property getter: - (id)pathForPrebakedWildcatThumbnailsFile;	// 0x7bd9
// declared property getter: - (id)pathForPrebakedThumbnail;	// 0x7bbd
// declared property getter: - (id)fileURLForThumbnailFile;	// 0x7ba1
- (id)fileULRForMetadataWithExtension:(id)extension;	// 0x7af5
- (id)pathForMetadataWithExtension:(id)extension;	// 0x7a89
// declared property getter: - (id)fileURLForMetadataDirectory;	// 0x7a1d
// declared property getter: - (id)pathForMetadataDirectory;	// 0x79f5
// declared property getter: - (id)fileExtension;	// 0x79cd
- (void)addExtension:(id)extension;	// 0x79c9
// declared property getter: - (id)allUniformTypeIdentifiers;	// 0x786d
- (id)allFileExtensions;	// 0x771d
- (id)fileURLForSidecarFile:(id)sidecarFile;	// 0x7709
// declared property getter: - (id)pathForOriginalFile;	// 0x7685
// declared property getter: - (id)fileURLForLargeThumbnailFile;	// 0x7669
// declared property getter: - (id)pathForLargeThumbnailFile;	// 0x764d
// declared property getter: - (id)allFileURLs;	// 0x7491
// declared property getter: - (id)filePathsWithoutThumbs;	// 0x7361
// declared property getter: - (id)pathForImageFile;	// 0x7159
// declared property getter: - (id)mainFileURL;	// 0x7119
- (BOOL)isSavedPhotosAsset;	// 0x7039
@end

@interface PLManagedAsset (Additions)
@property(readonly, assign, nonatomic) UIImage *wallpaperFullScreenImage;	// G=0x8ec5; 
@property(readonly, assign, nonatomic) NSString *textBadgeString;	// G=0x8b0d; 
@property(readonly, assign, nonatomic) BOOL hasFullSizeImage;	// G=0x8981; 
+ (CGImageRef)newUnrotatedImageWithSize:(CGSize)size originalImage:(CGImageRef)image imageOrientation:(int)orientation;	// 0x8355
+ (int)landscapeScrubberThumbnailFormat;	// 0x8331
+ (int)portraitScrubberThumbnailFormat;	// 0x830d
+ (int)indexSheetFormat;	// 0x82e9
+ (int)posterThumbnailFormat;	// 0x82c5
+ (int)thumbnailFormat;	// 0x82a1
+ (int)fullSizeImageFormat;	// 0x81ad
+ (id)preferredFileExtensionForType:(id)type;	// 0x8005
// declared property getter: - (id)wallpaperFullScreenImage;	// 0x8ec5
// declared property getter: - (id)textBadgeString;	// 0x8b0d
- (void)copyToPasteboard;	// 0x8ad5
- (id)largestAvailableDataRepresentationAndType:(id *)type;	// 0x8985
// declared property getter: - (BOOL)hasFullSizeImage;	// 0x8981
- (id)newLowResolutionFullScreenImage;	// 0x894d
- (id)newFullSizeImage;	// 0x8939
- (id)newFullSizeImageForImagePickerClient;	// 0x88e1
- (id)newFullScreenImage:(const CFDictionaryRef *)image;	// 0x8881
- (id)indexSheetImage;	// 0x8739
- (id)imageWithFormat:(int)format outImageProperties:(const CFDictionaryRef *)properties;	// 0x8671
- (id)imageWithFormat:(int)format;	// 0x85f5
- (id)mimeTypeForService:(id)service;	// 0x8141
- (id)fileExtensionForService:(id)service;	// 0x80d5
@end

@interface PLManagedAsset (AssetURLs)
@property(readonly, assign, nonatomic) NSURL *assetURL;	// G=0x9329; 
+ (id)fileURLFromAssetURL:(id)assetURL photoLibrary:(id)library;	// 0x9729
+ (id)photoFromAssetURL:(id)assetURL photoLibrary:(id)library sidecar:(id *)sidecar;	// 0x937d
+ (id)photoFromAssetURL:(id)assetURL photoLibrary:(id)library;	// 0x9359
// declared property getter: - (id)assetURL;	// 0x9329
- (id)assetURLForSidecarFile:(id)sidecarFile;	// 0x9195
- (id)assetURLWithExtension:(id)extension;	// 0x9015
@end

@interface PLManagedAsset (Private)
- (BOOL)_isValidUTI:(id)uti forService:(id)service;	// 0x9925
@end

@interface PLManagedAsset (CopyingAssets)
+ (void)copyAssets:(id)assets toAlbum:(NSObject *)album;	// 0x2fce9
@end

@interface PLManagedAsset (Private)
+ (void)_copyAssets:(id)assets toCameraRollAndAddToAlbum:(id)album;	// 0x3009d
+ (id)_findExistingAssetWithMatchingDate:(id)matchingDate inAlbum:(NSObject *)album;	// 0x2ff25
- (BOOL)_isSavedAssetTypeValueValid:(int)valid;	// 0x2ff0d
@end

@interface PLManagedAsset (ContextChanges)
- (void)unregisterForChanges;	// 0x30389
- (void)registerForChanges;	// 0x30385
@end

@interface PLManagedAsset (Debugging)
- (id)_prettyDescription;	// 0x30499
- (id)_kindDesription;	// 0x3044d
- (id)_savedAssetTypeDesription;	// 0x303e5
- (id)_highDynamicRangeTypeDesription;	// 0x3038d
@end

@interface PLManagedAsset (FileSystemPersistence)
- (void)setPersistedFileSystemAttributes;	// 0x308ed
- (void)updateFromPersistedFileSystemAttributes;	// 0x30839
- (void)persistMetadataToFilesystem;	// 0x306d9
@end

@interface PLManagedAsset (Faces)
@property(retain, nonatomic) NSMutableSet *faces;	// @dynamic
- (id)addFaceWithRelativeRect:(CGRect)relativeRect identifier:(short)identifier albumUUID:(id)uuid;	// 0x30bb1
- (id)faceWithIdentifier:(short)identifier;	// 0x30af5
@end

@interface PLManagedAsset (EmbeddedThumbnails)
@property(assign) short embeddedThumbnailHeightValue;	// G=0x31061; S=0x31089; 
@property(retain, nonatomic) NSNumber *embeddedThumbnailHeight;	// G=0x30ff5; S=0x31029; 
@property(assign) short embeddedThumbnailWidthValue;	// G=0x30f91; S=0x30fb9; 
@property(retain, nonatomic) NSNumber *embeddedThumbnailWidth;	// G=0x30f25; S=0x30f59; 
@property(assign) int embeddedThumbnailLengthValue;	// G=0x30ec1; S=0x30ee9; 
@property(retain, nonatomic) NSNumber *embeddedThumbnailLength;	// G=0x30e55; S=0x30e89; 
@property(assign) int embeddedThumbnailOffsetValue;	// G=0x30df1; S=0x30e19; 
@property(retain, nonatomic) NSNumber *embeddedThumbnailOffset;	// G=0x30d85; S=0x30db9; 
@property(readonly, assign, nonatomic) NSData *embeddedThumbnailData;	// G=0x30c79; 
@property(readonly, assign, nonatomic) BOOL hasEmbeddedThumbnail;	// G=0x30c59; 
// declared property setter: - (void)setEmbeddedThumbnailHeightValue:(short)value;	// 0x31089
// declared property getter: - (short)embeddedThumbnailHeightValue;	// 0x31061
// declared property setter: - (void)setEmbeddedThumbnailHeight:(id)height;	// 0x31029
// declared property getter: - (id)embeddedThumbnailHeight;	// 0x30ff5
// declared property setter: - (void)setEmbeddedThumbnailWidthValue:(short)value;	// 0x30fb9
// declared property getter: - (short)embeddedThumbnailWidthValue;	// 0x30f91
// declared property setter: - (void)setEmbeddedThumbnailWidth:(id)width;	// 0x30f59
// declared property getter: - (id)embeddedThumbnailWidth;	// 0x30f25
// declared property setter: - (void)setEmbeddedThumbnailLengthValue:(int)value;	// 0x30ee9
// declared property getter: - (int)embeddedThumbnailLengthValue;	// 0x30ec1
// declared property setter: - (void)setEmbeddedThumbnailLength:(id)length;	// 0x30e89
// declared property getter: - (id)embeddedThumbnailLength;	// 0x30e55
// declared property setter: - (void)setEmbeddedThumbnailOffsetValue:(int)value;	// 0x30e19
// declared property getter: - (int)embeddedThumbnailOffsetValue;	// 0x30df1
// declared property setter: - (void)setEmbeddedThumbnailOffset:(id)offset;	// 0x30db9
// declared property getter: - (id)embeddedThumbnailOffset;	// 0x30d85
// declared property getter: - (id)embeddedThumbnailData;	// 0x30c79
// declared property getter: - (BOOL)hasEmbeddedThumbnail;	// 0x30c59
@end

@interface PLManagedAsset (Import)
+ (id)insertAssetIntoPhotoLibrary:(id)library mainFileURL:(id)url savedAssetType:(int)type replacementUUID:(id)uuid imageSource:(CGImageSourceRef *)source imageData:(id *)data;	// 0x310c5
- (BOOL)setAttributesFromMainFileURL:(id)mainFileURL savedAssetType:(int)type imageSource:(CGImageSourceRef *)source imageData:(id *)data;	// 0x31179
@end

@interface PLManagedAsset (PLPhotoLibrary)
+ (id)assetWithObjectID:(id)objectID inManagedObjectContext:(id)managedObjectContext;	// 0x45b39
+ (id)assetWithUUID:(id)uuid inManagedObjectContext:(id)managedObjectContext;	// 0x459e9
+ (id)pathsForAllIncompleteAssetsInManagedObjectContext:(id)managedObjectContext;	// 0x45799
+ (id)incompleteAssetsInManagedObjectContext:(id)managedObjectContext;	// 0x4568d
+ (id)pathsForAssetsWithKind:(int)kind inManagedObjectContext:(id)managedObjectContext;	// 0x454a9
+ (id)_pathsByAssetUUIDFromFetchResults:(id)fetchResults absolute:(BOOL)absolute;	// 0x45231
+ (id)assetsWithKind:(int)kind inManagedObjectContext:(id)managedObjectContext;	// 0x45101
+ (unsigned)countUsedAssetsWithKind:(int)kind inManagedObjectContext:(id)managedObjectContext;	// 0x4500d
+ (unsigned)countAssetsWithKind:(int)kind inManagedObjectContext:(id)managedObjectContext;	// 0x44f19
@end

@interface PLManagedAsset (Metadata)
- (void)generateThumbnailsWithPreviewImage:(id)previewImage thumbnailImage:(id)image existingThumbnailIndex:(unsigned)index fromImageSource:(CGImageSourceRef)imageSource imageData:(id)data thumbnailDataByFormatID:(CFDictionaryRef)anId;	// 0x506b9
- (BOOL)setVideoInfoFromFileAtURL:(id)url;	// 0x503a1
- (void)setSavedAssetTypeFromImageProperties:(id)imageProperties;	// 0x50315
- (void)setSizeAndOrientationFromImageProperties:(id)imageProperties;	// 0x5019d
- (void)setHDRFlagFromImageProperties:(id)imageProperties;	// 0x50125
- (void)setThumbnailDataFromImageProperties:(id)imageProperties;	// 0x5003d
- (void)setLocationFromImageProperties:(id)imageProperties;	// 0x4fed1
- (id)pictureTransferProtocolInformationWithAlbumsObjectIDs:(id)albumsObjectIDs;	// 0x4f44d
@end
