/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

#import <PhotoLibraryServices/PhotoLibraryServices-Structs.h>
#import <PhotoLibraryServices/XXUnknownSuperclass.h>
#import <PhotoLibraryServices/PLPhotoLibrary.h>

@class NSDictionary, PLFetchingAlbum, PLGenericAlbum, PLWStackedImageCache, PLThumbnailManager, PLManagedAlbum, NSCalendar, NSMutableDictionary, NSMutableArray, NSSet, NSArray, NSString, NSObject, PLManagedObjectContext;
@protocol PLAssetContainer;

@interface PLPhotoLibrary : XXUnknownSuperclass {
	BOOL _listeningForITunesSyncing;	// 4 = 0x4
	BOOL _canTriggerDatabaseUpdate;	// 5 = 0x5
	CFDictionaryRef _allPhotos;	// 8 = 0x8
	double _lastRemoteDataModification;	// 12 = 0xc
	int _databaseMigrationKind;	// 20 = 0x14
	PLThumbnailManager *_thumbnailManager;	// 24 = 0x18
	NSDictionary *_existingThumbnailEntries;	// 28 = 0x1c
	PLGenericAlbum *_allImportedPhotosAlbum;	// 32 = 0x20
	PLGenericAlbum *_lastImportedPhotosAlbum;	// 36 = 0x24
	NSCalendar *_exifConversionCalendar;	// 40 = 0x28
	NSMutableDictionary *_photoStreamAlbumsByStreamID;	// 44 = 0x2c
	NSMutableArray *_photoStreamAlbums;	// 48 = 0x30
	NSObject *_allPhotoStreamPhotosAlbum;	// 52 = 0x34
	id _ptpDelegate;	// 56 = 0x38
	PLWStackedImageCache *_stackedImageCache;	// 60 = 0x3c
	NSSet *_imageFileExtensions;	// 64 = 0x40
	NSSet *_rawImageFileExtensions;	// 68 = 0x44
	NSSet *_audioFileExtensions;	// 72 = 0x48
	NSSet *_extraVideoExtensions;	// 76 = 0x4c
	unsigned _lastFetchedGPSCount;	// 80 = 0x50
	unsigned _insertedCountSinceLastFetchedGPSCount;	// 84 = 0x54
	unsigned _deletedCountSinceLastFetchedGPSCount;	// 88 = 0x58
	unsigned _newlyCompleteWithGPS;	// 92 = 0x5c
@private
	PLManagedAlbum *_cameraRollAlbum;	// 96 = 0x60
	PLFetchingAlbum *_cameraSessionAlbum;	// 100 = 0x64
	PLManagedAlbum *_savedAndInFlightAlbum;	// 104 = 0x68
	PLManagedObjectContext *managedObjectContext;	// 108 = 0x6c
}
@property(retain, nonatomic) PLManagedObjectContext *managedObjectContext;	// G=0x3c5d; S=0x3c6d; @synthesize
@property(readonly, assign, nonatomic) PLThumbnailManager *thumbnailManager;	// G=0x2f9d; 
+ (void)_doFilesystemImportIfNeeded;	// 0x3249
+ (BOOL)isApplicationWildcat;	// 0x2691
+ (void)setApplicationIsWildcat:(BOOL)wildcat;	// 0x2681
+ (id)sharedPhotoLibrary;	// 0x2665
// declared property setter: - (void)setManagedObjectContext:(id)context;	// 0x3c6d
// declared property getter: - (id)managedObjectContext;	// 0x3c5d
- (void)updateThumbnailsForPhoto:(id)photo previewImage:(id)image thumbnailImage:(id)image3;	// 0x3c21
- (void)deleteAllImages;	// 0x3b19
- (void)_compactThumbnailTablesIfNecessary;	// 0x3b15
- (void)_deleteFilesAndEmptyDirectoriesAtPaths:(id)paths;	// 0x385d
- (BOOL)rotateCameraPhoto:(id)photo byDegrees:(int)degrees;	// 0x3859
- (void)deleteImages:(id)images;	// 0x3705
- (BOOL)hasAtLeastOnePhoto;	// 0x36ed
- (BOOL)hasAtLeastOneItem;	// 0x36d5
- (id)iTunesFaceImageForRecordID:(int)recordID faceIndex:(int)index size:(CGSize)size returnLocationInImage:(CGRect *)image;	// 0x36d1
- (void)pictureWasChanged;	// 0x3691
- (void)pictureWasDeletedNotification;	// 0x368d
- (void)photoLibraryAvailableNotification;	// 0x35dd
- (void)photoLibraryRebuildingNotification;	// 0x35c9
- (void)photoLibraryCorruptNotification;	// 0x356d
- (void)_notifyPhotoLibraryIsNoLongerAvailableOnMainThread;	// 0x34fd
- (void)_loadPhotoLibraryAfterMigration;	// 0x34dd
- (id)_iTunesPhotos;	// 0x34d9
- (void)addPhotoToCameraRoll:(id)cameraRoll completionBlock:(id)block;	// 0x3485
- (void)applicationWillEnterForeground:(id)application;	// 0x335d
- (id)countOfAllPhotosAndVideos;	// 0x3139
- (void)flushAlbums;	// 0x310d
- (void)flushPhotoStreamAlbums;	// 0x30bd
- (void)flushDCIMAlbums;	// 0x306d
- (BOOL)libraryIsAvailable;	// 0x3035
- (void)_releaseThumbnailManager;	// 0x2ff1
// declared property getter: - (id)thumbnailManager;	// 0x2f9d
- (void)dealloc;	// 0x2ddd
- (id)initWithPath:(id)path canTriggerDatabaseUpdate:(BOOL)update;	// 0x274d
- (id)init;	// 0x2709
@end

@interface PLPhotoLibrary (Queue)
- (void)withDispatchGroup:(dispatch_group_s *)dispatchGroup performBlock:(id)block completionHandler:(id)handler;	// 0x4085
- (void)withDispatchGroup:(dispatch_group_s *)dispatchGroup performBlock:(id)block;	// 0x4061
- (void)withDispatchGroup:(dispatch_group_s *)dispatchGroup performTransaction:(id)transaction completionHandler:(id)handler;	// 0x3d45
- (void)withDispatchGroup:(dispatch_group_s *)dispatchGroup performTransaction:(id)transaction;	// 0x3d21
- (void)performBlock:(id)block completionHandler:(id)handler;	// 0x3cfd
- (void)performBlock:(id)block;	// 0x3cd9
- (void)performTransaction:(id)transaction completionHandler:(id)handler;	// 0x3cb5
- (void)performTransaction:(id)transaction;	// 0x3c91
@end

@interface PLPhotoLibrary (Albums)
@property(readonly, assign, nonatomic) NSArray *photoStreamAlbumsForPreferences;	// G=0x4925; 
@property(readonly, assign, nonatomic) NSArray *photoStreamAlbums;	// G=0x48e9; 
@property(readonly, assign, nonatomic) NSArray *placeAlbums;	// G=0x48ad; 
@property(readonly, assign, nonatomic) NSArray *faceAlbums;	// G=0x4871; 
@property(readonly, assign, nonatomic) NSArray *eventAlbums;	// G=0x4829; 
@property(readonly, assign, nonatomic) NSArray *wallpaperAlbums;	// G=0x46d1; 
@property(readonly, assign, nonatomic) NSArray *imagePickerAlbums;	// G=0x4581; 
@property(readonly, assign, nonatomic) NSArray *userAlbums;	// G=0x4539; 
@property(readonly, assign, nonatomic) NSArray *albums;	// G=0x44f1; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *savedPhotosAlbum;	// G=0x41ed; 
+ (NSObject *)savedPhotosAlbum;	// 0x41b9
- (id)objectWithObjectID:(id)objectID;	// 0x4ecd
- (id)assetWithUUID:(id)uuid inAlbum:(NSObject *)album;	// 0x4d71
- (id)assetWithUUID:(id)uuid;	// 0x4d5d
- (unsigned)countOfAlbumsContainingItems:(id)albumsContainingItems includeInFlightAlbum:(BOOL)flightAlbum;	// 0x4d35
- (id)_albumsContainingItems:(id)items includeInFlightAlbum:(BOOL)flightAlbum;	// 0x4ab1
- (NSObject *)eventAlbumContainingPhoto:(id)photo;	// 0x4a35
// declared property getter: - (id)photoStreamAlbumsForPreferences;	// 0x4925
// declared property getter: - (id)photoStreamAlbums;	// 0x48e9
// declared property getter: - (id)placeAlbums;	// 0x48ad
// declared property getter: - (id)faceAlbums;	// 0x4871
// declared property getter: - (id)eventAlbums;	// 0x4829
// declared property getter: - (id)wallpaperAlbums;	// 0x46d1
// declared property getter: - (id)imagePickerAlbums;	// 0x4581
// declared property getter: - (id)userAlbums;	// 0x4539
// declared property getter: - (id)albums;	// 0x44f1
- (NSObject *)albumWithUuid:(id)uuid;	// 0x4485
- (NSObject *)eventWithName:(id)name andImportSessionIdentifier:(id)identifier;	// 0x4415
- (NSObject *)cameraSessionAlbumFromTimeInterval:(double)timeInterval;	// 0x4285
- (NSObject *)savedAndInFlightPhotosAlbum;	// 0x4239
// declared property getter: - (NSObject *)savedPhotosAlbum;	// 0x41ed
@end

@interface PLPhotoLibrary (PhotoStream)
+ (void)setPhotoStreamEnabled:(BOOL)enabled;	// 0x536d
- (void)setPhotoStreamEnabled:(BOOL)enabled;	// 0x502d
- (void)saveToSavedPhotosAllPhotoInPhotoStreamAlbums:(id)photoStreamAlbums;	// 0x4f01
@end

@interface PLPhotoLibrary (Import)
@property(copy, nonatomic) NSString *lastImportSessionUUID;	// G=0x53ed; S=0x545d; 
// declared property setter: - (void)setLastImportSessionUUID:(id)uuid;	// 0x545d
// declared property getter: - (id)lastImportSessionUUID;	// 0x53ed
@end

@interface PLPhotoLibrary (Utilities)
+ (void)moveDatabasesAside;	// 0x1a89d
+ (id)calculatedDisplayableIndexesForAlbum:(NSObject *)album count:(unsigned)count;	// 0x1a679
- (BOOL)getPhotoCount:(unsigned *)count videoCount:(unsigned *)count2;	// 0x1aa19
- (id)albumListForContentMode:(int)contentMode;	// 0x1a809
- (id)albumsForContentMode:(int)contentMode;	// 0x1a759
- (BOOL)multiplePhotoStreamsAvailable;	// 0x1a755
@end

@interface PLPhotoLibrary (ALAssetLibraryMethods)
- (NSObject *)albumFromGroupURL:(id)groupURL;	// 0x33809
- (id)messagesPhotoFromAssetURL:(id)assetURL;	// 0x337e9
- (id)photoFromAssetURL:(id)assetURL;	// 0x337c9
- (id)assetURLForManagedPhoto:(id)managedPhoto;	// 0x337b5
- (id)assetURLForPhoto:(id)photo;	// 0x337a1
- (id)assetURLForPhoto:(id)photo extension:(id)extension;	// 0x3378d
@end

@interface PLPhotoLibrary (InMemoryLibrary)
+ (id)sharedInMemoryLibrary;	// 0x33a1d
@end

@interface PLPhotoLibrary (CoreData)
@property(readonly, assign, nonatomic) PLManagedObjectContext *managedObjectContext;	// @dynamic
- (id)managedObjectWithObjectID:(id)objectID;	// 0x33a39
@end

@interface PLPhotoLibrary (Internal)
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *filesystemImportProgressAlbum;	// G=0x34f6d; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *otaRestoreProgressAlbum;	// G=0x34f4d; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *syncProgressAlbum;	// G=0x34f2d; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *iPadAllPhotosAlbumIfExists;	// G=0x34f1d; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *iPadAllPhotosAlbum;	// G=0x34efd; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *allPhotosAlbumIfExists;	// G=0x34eed; 
@property(readonly, assign, nonatomic) NSObject<PLAssetContainer> *allPhotosAlbum;	// G=0x34ecd; 
@property(readonly, assign, nonatomic) unsigned editableAlbumCount;	// G=0x34d9d; 
@property(readonly, assign, nonatomic) NSArray *editableAlbums;	// G=0x34d81; 
@property(readonly, assign, nonatomic) NSArray *syncedAlbums;	// G=0x34c61; 
@property(readonly, assign, nonatomic) BOOL hasAtLeastOnePhotoWithGPS;	// G=0x34885; 
+ (void)initializeGraphicsServices;	// 0x350ad
+ (BOOL)processCanWriteSandboxForPath:(id)path;	// 0x34c21
+ (BOOL)processCanReadSandboxForPath:(id)path;	// 0x34be1
+ (id)persistedAlbumDataDirectoryURL;	// 0x34171
+ (id)iTunesSyncedFaceAlbumThumbnailsDirectory;	// 0x3413d
+ (id)iTunesSyncedAssetsDirectory;	// 0x34109
+ (id)simpleDCIMDirectory;	// 0x33fc9
+ (id)dcimDirectory;	// 0x33ef1
+ (id)dcimDirectoryURL;	// 0x33ea9
+ (id)iTunesPhotosDirectory;	// 0x33e81
+ (id)photoDataMiscDirectory;	// 0x33df1
+ (id)videosPath;	// 0x33dbd
+ (id)photoMetadataDirectoryURL;	// 0x33ccd
+ (id)photoDataDirectory;	// 0x33ca5
+ (id)photoDataDirectoryURL;	// 0x33c09
+ (id)mediaFilesDirectoryURL;	// 0x33bd9
+ (BOOL)needsToBeSyncedWithiTunesBecauseFormatIDsChanged;	// 0x33bb9
+ (void)setVideoCaptureIsBusy:(BOOL)busy;	// 0x33b8d
+ (void)setImageWriterIsBusy:(BOOL)busy;	// 0x33b61
+ (void)setMigratorIsBusy:(BOOL)busy;	// 0x33a89
- (BOOL)isPhotoInSavedPhotosAlbum:(id)savedPhotosAlbum;	// 0x37e91
- (void)_detachAuxDatabase;	// 0x37e8d
- (void)_attachAuxDatabase;	// 0x37e89
- (id)fileExtensionsForPhoto:(id)photo;	// 0x37e85
- (void)_notifyChangedPhotos:(id)photos;	// 0x37809
- (void)pictureWasTakenOrChanged;	// 0x37805
- (void)processSyncSaveJob:(id)job albumMap:(id)map;	// 0x369fd
- (BOOL)hasPhotoWithFileCreationDate:(id)fileCreationDate fileName:(id)name fileSize:(int)size;	// 0x36751
- (int)priorityForFileExtension:(id)fileExtension;	// 0x366b9
- (BOOL)isAudioFileExtension:(id)extension;	// 0x36669
- (BOOL)isVideoFileExtension:(id)extension;	// 0x36585
- (BOOL)isNonRawImageFileExtension:(id)extension;	// 0x364fd
- (BOOL)isRawImageFileExtension:(id)extension;	// 0x364ad
- (BOOL)isImageFileExtension:(id)extension;	// 0x3645d
- (void)_loadFileExtensionInformation;	// 0x36305
- (id)masterFilenameFromSidecarFileInfo:(id)sidecarFileInfo;	// 0x361c9
- (id)masterURLFromSidecarURLs:(id)sidecarURLs;	// 0x36131
- (id)addDCIMEntryAtFileURL:(id)fileURL toEvent:(NSObject *)event sidecarFileInfo:(id)info progress:(XXStruct_pqCwAA *)progress importSessionIdentifier:(id)identifier isImported:(BOOL)imported previewImage:(id)image thumbnailImage:(id)image8 savedAssetType:(int)type replacementUUID:(id)uuid extendedInfo:(id)info11 thumbnailsData:(CFDictionaryRef)data;	// 0x3549d
- (void)modifyDCIMEntryForVideo:(id)video progress:(XXStruct_pqCwAA *)progress previewImage:(id)image thumbnailImage:(id)image4;	// 0x3536d
- (void)modifyDCIMEntryForPhoto:(id)photo;	// 0x350ed
- (id)photoWithPath:(id)path;	// 0x350e9
- (void)migrateSavedPhotoCaptureTimes;	// 0x350a9
- (void)setSqliteErrorAndExitIfNecessary;	// 0x350a5
- (id)newImageForDulcimerPhoto:(id)dulcimerPhoto format:(int)format;	// 0x35081
- (id)newImageForDulcimerPhoto:(id)dulcimerPhoto format:(int)format outImageProperties:(const CFDictionaryRef *)properties;	// 0x35051
- (id)dataForPhoto:(id)photo format:(int)format width:(int *)width height:(int *)height bytesPerRow:(int *)row dataWidth:(int *)width6 dataHeight:(int *)height7 imageDataOffset:(int *)offset;	// 0x35021
- (id)imageForFormat:(int)format forAsset:(id)asset;	// 0x34fbd
- (void)preheatImageDataForAssets:(id)assets format:(int)format;	// 0x34f8d
// declared property getter: - (NSObject *)filesystemImportProgressAlbum;	// 0x34f6d
// declared property getter: - (NSObject *)otaRestoreProgressAlbum;	// 0x34f4d
// declared property getter: - (NSObject *)syncProgressAlbum;	// 0x34f2d
// declared property getter: - (NSObject *)iPadAllPhotosAlbumIfExists;	// 0x34f1d
// declared property getter: - (NSObject *)iPadAllPhotosAlbum;	// 0x34efd
// declared property getter: - (NSObject *)allPhotosAlbumIfExists;	// 0x34eed
// declared property getter: - (NSObject *)allPhotosAlbum;	// 0x34ecd
// declared property getter: - (unsigned)editableAlbumCount;	// 0x34d9d
// declared property getter: - (id)editableAlbums;	// 0x34d81
// declared property getter: - (id)syncedAlbums;	// 0x34c61
- (void)_updateWithInsertedAssetsCount:(unsigned)insertedAssetsCount deletedCount:(unsigned)count updatedAssets:(id)assets;	// 0x34bd1
- (void)_updateHasAtLeastOnePhotoWithGPSWithInsertedCount:(unsigned)insertedCount deletedCount:(unsigned)count updatedAssets:(id)assets;	// 0x34ac9
// declared property getter: - (BOOL)hasAtLeastOnePhotoWithGPS;	// 0x34885
- (id)lastImportedPhotosAlbum;	// 0x347a9
- (id)allImportedPhotosAlbum;	// 0x346cd
- (void)recreateAlbumsFromMetadata;	// 0x342a1
- (BOOL)needsMigration;	// 0x33bbd
@end

@interface PLPhotoLibrary (PhotoStreams)
+ (id)assetsDataDirectory;	// 0x37f25
+ (id)photoStreamsDataDirectory;	// 0x37eb9
- (void)removeFromKnownPhotoStreamAlbums:(id)knownPhotoStreamAlbums;	// 0x38179
- (void)addToKnownPhotoStreamAlbums:(id)knownPhotoStreamAlbums;	// 0x38029
- (NSObject *)allPhotoStreamPhotosAlbumIfItExists;	// 0x38015
- (NSObject *)allPhotoStreamPhotosAlbum;	// 0x37ff5
@end

@interface PLPhotoLibrary (Protected)
@property(readonly, assign, nonatomic) unsigned concurrencyType;	// G=0x3a04d; 
+ (id)pathToAssetsToAlbumsMapping;	// 0x38f15
+ (id)allIndicatorFilePaths;	// 0x38491
+ (id)migrationIndicatorFilePath;	// 0x3845d
+ (id)sqliteErrorIndicatorFilePath;	// 0x38429
+ (id)imageWriterIndicatorFilePath;	// 0x383f5
+ (id)takingVideoIndicatorFilePath;	// 0x383c1
+ (void)_presentSqliteCorruptionErrorDialog;	// 0x383bd
// declared property getter: - (unsigned)concurrencyType;	// 0x3a04d
- (void)loadDatabase;	// 0x39ddd
- (void)cleanupModelAfterRestoreFromiTunesBackup;	// 0x39bc5
- (void)prepareDatabaseForOTAAssetsPhase;	// 0x395d1
- (id)_allAssetsForDeletion:(id)deletion;	// 0x394e9
- (void)_batchDeleteAssets:(id)assets inManagedObjectContext:(id)managedObjectContext;	// 0x392c5
- (void)_safeSave:(id)save;	// 0x3917d
- (void)_calculatePendingItemCountsAfterOTARestoreWithMangedObjectContext:(id)mangedObjectContext;	// 0x3906d
- (void)_removeSyncedAlbumsInTransactionWithManagedObjectContext:(id)managedObjectContext;	// 0x38f99
- (int)_orientationOfFileAtPath:(id)path;	// 0x38dfd
- (int)_orientationAfterRotatingOrientation:(int)orientation clockwiseByDegrees:(int)degrees transposeCoordinatesOut:(BOOL *)anOut;	// 0x38d8d
- (BOOL)_hasAtLeastOneItem:(BOOL)leastOneItem;	// 0x38af1
- (void)_migrationDidFinish;	// 0x38ab1
- (void)_deleteObsoleteMetadataFiles;	// 0x38645
- (void)_notifyProgress:(float)progress;	// 0x3852d
- (void)prepareToMigrateDcimToDatabase;	// 0x38529
- (id)_init;	// 0x38391
@end

@interface PLPhotoLibrary (ThumbnailsProtected)
- (void)_unloadExistingThumbnailEntries;	// 0x3a0a9
- (void)_loadExistingThumbnailEntries;	// 0x3a055
- (void)_removeOrphanedThumbnailEntries;	// 0x3a051
@end

@interface PLPhotoLibrary (AlbumsProtected)
- (void)_addPhoto:(id)photo toEvent:(NSObject *)event;	// 0x3a0dd
- (void)removePhotosFromAllAlbums:(id)allAlbums;	// 0x3a0d9
@end

@interface PLPhotoLibrary (Globals)
- (void)setGlobalValue:(id)value forKey:(id)key;	// 0x3a10d
- (id)globalValueForKey:(id)key;	// 0x3a0e1
@end
