/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CalDAV/XXUnknownSuperclass.h>

@class NSString, NSMutableSet;

@interface CalDAVCalendarServerChangedPropertyItem : XXUnknownSuperclass {
	NSMutableSet *_changedParameters;	// 24 = 0x18
	NSString *_nameAttribute;	// 28 = 0x1c
}
@property(retain) NSMutableSet *changedParameters;	// G=0xd4dd; S=0xd4b9; @synthesize=_changedParameters
@property(retain) NSString *nameAttribute;	// G=0xd519; S=0xd4f5; @synthesize=_nameAttribute
- (id)initWithNameSpace:(id)nameSpace andName:(id)name;	// 0xd435
- (void)dealloc;	// 0xd751
- (void)parserFoundAttributes:(id)attributes;	// 0xd669
- (void)addChangedParameter:(id)parameter;	// 0xd63d
- (id)copyParseRules;	// 0xd531
// declared property getter: - (id)nameAttribute;	// 0xd519
// declared property setter: - (void)setNameAttribute:(id)attribute;	// 0xd4f5
// declared property getter: - (id)changedParameters;	// 0xd4dd
// declared property setter: - (void)setChangedParameters:(id)parameters;	// 0xd4b9
@end
