/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CalDAV/XXUnknownSuperclass.h>


@interface CalDAVUtils : XXUnknownSuperclass {
}
+ (id)dropBoxLocationForUID:(id)uid dropBoxPath:(id)path;	// 0x19239
+ (id)stringFromUIDWithPathSafeCharacters:(id)pathSafeCharacters;	// 0x192ad
@end
