/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CalDAV/XXUnknownSuperclass.h>

@class NSMutableSet;
@protocol CalDAVPrincipal;

@interface CalDAVOperation : XXUnknownSuperclass {
	id<CalDAVPrincipal> _principal;	// 44 = 0x2c
	BOOL _isCancellingTaskGroups;	// 48 = 0x30
	NSMutableSet *_outstandingTaskGroups;	// 52 = 0x34
}
@property(readonly, assign) id<CalDAVPrincipal> principal;	// G=0x13821; @synthesize=_principal
@property(readonly, assign) NSMutableSet *outstandingTaskGroups;	// G=0x13811; @synthesize=_outstandingTaskGroups
- (id)init;	// 0x13831
- (id)initWithPrincipal:(id)principal;	// 0x138e5
- (void)dealloc;	// 0x13b45
- (void)_tearDownAllTaskGroupsWithBlock:(id)block;	// 0x13a51
- (void)cancelTaskGroup;	// 0x13a09
- (void)bailWithError:(id)error;	// 0x1398d
// declared property getter: - (id)outstandingTaskGroups;	// 0x13811
// declared property getter: - (id)principal;	// 0x13821
@end
