/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CalDAV/XXUnknownSuperclass.h>

@class NSMutableSet;

@interface CalDAVCalendarServerShareItem : XXUnknownSuperclass {
	NSMutableSet *_shareesToRemove;	// 24 = 0x18
	NSMutableSet *_shareesToSet;	// 28 = 0x1c
}
@property(readonly, retain) NSMutableSet *shareesToRemove;	// G=0x11885; @synthesize=_shareesToRemove
@property(readonly, retain) NSMutableSet *shareesToSet;	// G=0x1186d; @synthesize=_shareesToSet
// declared property getter: - (id)shareesToSet;	// 0x1186d
// declared property getter: - (id)shareesToRemove;	// 0x11885
@end
