/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */


@class NSString;

@protocol AdSheetSessionDelegate
@property(readonly, assign, nonatomic) int clientStatusBarOrientation;
@property(readonly, assign, nonatomic) NSString *bundleId;
// declared property getter: - (int)clientStatusBarOrientation;
// declared property getter: - (id)bundleId;
- (void)sessionDidClose:(id)session;
- (void)sessionDidOpen:(id)session;
@end

