/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

#import <iAdCore/ADJavaScriptObject.h>
#import <iAdCore/iAdCore-Structs.h>

@class NSArray, WebScriptObject, NSString, NSMutableArray;
@protocol ADJSODelegate;

@interface ADTwitterJSO : ADJavaScriptObject {
@private
	id<ADJSODelegate> _delegate;	// 4 = 0x4
	WebScriptObject *_listener;	// 8 = 0x8
	NSString *_text;	// 12 = 0xc
	NSMutableArray *_tweetImages;	// 16 = 0x10
	NSArray *_imageURLs;	// 20 = 0x14
	NSArray *_tweetURLs;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *text;	// G=0x4d229; S=0x4d235; @synthesize=_text
@property(copy, nonatomic) NSArray *tweetURLs;	// G=0x4e479; S=0x4e489; @synthesize=_tweetURLs
@property(retain, nonatomic) NSArray *imageURLs;	// G=0x4e445; S=0x4e455; @synthesize=_imageURLs
@property(retain, nonatomic) NSMutableArray *tweetImages;	// G=0x4e411; S=0x4e421; @synthesize=_tweetImages
@property(retain, nonatomic) WebScriptObject *listener;	// G=0x4e3dd; S=0x4e3ed; @synthesize=_listener
@property(assign, nonatomic) id<ADJSODelegate> delegate;	// G=0x4e3bd; S=0x4e3cd; @synthesize=_delegate
@property(retain) id images;	// G=0x4d5d9; S=0x4d5dd; converted property
@property(retain) id URLs;	// G=0x4d3ad; S=0x4d3b1; converted property
+ (void)initializeInContext:(OpaqueJSContext *)context;	// 0x4d109
+ (id)scriptSelectors;	// 0x4d0cd
+ (id)scriptingKeys;	// 0x4d04d
// declared property setter: - (void)setTweetURLs:(id)urls;	// 0x4e489
// declared property getter: - (id)tweetURLs;	// 0x4e479
// declared property setter: - (void)setImageURLs:(id)urls;	// 0x4e455
// declared property getter: - (id)imageURLs;	// 0x4e445
// declared property setter: - (void)setTweetImages:(id)images;	// 0x4e421
// declared property getter: - (id)tweetImages;	// 0x4e411
// declared property setter: - (void)setListener:(id)listener;	// 0x4e3ed
// declared property getter: - (id)listener;	// 0x4e3dd
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x4e3cd
// declared property getter: - (id)delegate;	// 0x4e3bd
- (void)present;	// 0x4df11
// converted property setter: - (void)setImages:(id)images;	// 0x4d5dd
// converted property getter: - (id)images;	// 0x4d5d9
// converted property setter: - (void)setURLs:(id)urls;	// 0x4d3b1
// converted property getter: - (id)URLs;	// 0x4d3ad
// declared property setter: - (void)setText:(id)text;	// 0x4d235
// declared property getter: - (id)text;	// 0x4d229
- (id)init;	// 0x4d1c1
- (void)dealloc;	// 0x4cfb1
@end
