/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
 */

#import <iAdCore/ADDateStringNormalizer.h>


@interface ADW3CDateParser : ADDateStringNormalizer {
}
- (id)normalize:(id)normalize;	// 0x36c31
- (id)init;	// 0x36bbd
@end
