/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
 */



@class NSURL, NSString, ALCity, NSDictionary, NSNumber;

@interface WorldClockCity : NSObject {
	ALCity *_alCity;	// 4 = 0x4
	NSString *_timeZone;	// 8 = 0x8
	NSString *_name;	// 12 = 0xc
	NSString *_countryName;	// 16 = 0x10
	NSString *_countryCode;	// 20 = 0x14
	NSString *_unlocalizedName;	// 24 = 0x18
	NSString *_unlocalizedCountryName;	// 28 = 0x1c
}
@property(readonly, assign, nonatomic) NSURL *idUrl;	// G=0x9ab5; 
@property(readonly, assign, nonatomic) NSString *countryCode;	// G=0x9c1d; 
@property(readonly, assign, nonatomic) NSString *unlocalizedCountryName;	// G=0x9c55; 
@property(readonly, assign, nonatomic) NSString *unlocalizedCityName;	// G=0x9c8d; 
@property(readonly, assign, nonatomic) NSString *countryName;	// G=0x9cc5; 
@property(readonly, assign, nonatomic) NSString *name;	// G=0x9cfd; 
@property(readonly, assign, nonatomic) NSString *timeZone;	// G=0x9d35; 
@property(readonly, assign, nonatomic) NSNumber *alCityId;	// G=0x9d6d; 
@property(readonly, assign, nonatomic) NSDictionary *properties;	// G=0x9dbd; 
+ (BOOL)isWorldClockCityProperties:(id)properties;	// 0x9a85
- (id)initWithALCity:(id)alcity;	// 0x9a29
- (id)initWithALCityIdentifier:(int)alcityIdentifier;	// 0xa629
- (id)initWithTimeZone:(id)timeZone countryCode:(id)code name:(id)name countryName:(id)name4 unlocalizedName:(id)name5 unlocalizedCountryName:(id)name6;	// 0xa545
- (id)initWithProperties:(id)properties;	// 0xa35d
- (void)dealloc;	// 0xa2ad
- (id)description;	// 0xa181
- (BOOL)isEqual:(id)equal;	// 0xa049
- (unsigned)hash;	// 0x9fe9
// declared property getter: - (id)properties;	// 0x9dbd
// declared property getter: - (id)alCityId;	// 0x9d6d
// declared property getter: - (id)timeZone;	// 0x9d35
// declared property getter: - (id)name;	// 0x9cfd
// declared property getter: - (id)countryName;	// 0x9cc5
// declared property getter: - (id)unlocalizedCityName;	// 0x9c8d
// declared property getter: - (id)unlocalizedCountryName;	// 0x9c55
// declared property getter: - (id)countryCode;	// 0x9c1d
// declared property getter: - (id)idUrl;	// 0x9ab5
@end
