/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/MFDAMailAccountRequest.h>
#import <Message/XXUnknownSuperclass.h>


@interface _MFDAMessageStoreGetUpdatesRequest : XXUnknownSuperclass <MFDAMailAccountRequest> {
}
- (unsigned long long)generationNumber;	// 0x62c49
- (BOOL)shouldSend;	// 0x62c51
- (id)deferredOperation;	// 0x62c55
- (BOOL)mf_alwaysReportFailures;	// 0x62c59
@end
