/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/MFSASLAuthenticator.h>


@interface _MFLoginAuthenticator : MFSASLAuthenticator {
	BOOL _justSentPassword;	// 20 = 0x14
}
- (id)saslName;	// 0x41279
- (id)responseForServerData:(id)serverData;	// 0x414fd
- (BOOL)justSentPlainTextPassword;	// 0x41285
@end
