/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/MessageCriterion.h>
#import <Message/Message-Structs.h>
#import <Message/XXUnknownSuperclass.h>

@class NSArray, NSString;

@interface MessageCriterion : XXUnknownSuperclass {
	NSString *_uniqueId;	// 4 = 0x4
	NSString *_criterionIdentifier;	// 8 = 0x8
	NSString *_expression;	// 12 = 0xc
	int _qualifier;	// 16 = 0x10
	NSArray *_criteria;	// 20 = 0x14
	int _dateUnitType;	// 24 = 0x18
	NSString *_name;	// 28 = 0x1c
	unsigned _allCriteriaMustBeSatisfied : 1;	// 32 = 0x20
	unsigned _dateIsRelative : 1;	// 32 = 0x20
	int _type;	// 36 = 0x24
	NSArray *_requiredHeaders;	// 40 = 0x28
}
@property(assign) int criterionType;	// G=0xbd61; S=0x96e1; converted property
@property(retain) NSString *criterionIdentifier;	// G=0x1f071; S=0x992d; converted property
@property(assign) int qualifier;	// G=0x155ad; S=0x99b5; converted property
@property(retain) NSString *expression;	// G=0xc0fd; S=0x99c5; converted property
@property(retain) NSString *name;	// G=0x45aad; S=0x46d0d; converted property
@property(retain) NSArray *criteria;	// G=0x13a3d; S=0x13415; converted property
@property(assign) BOOL allCriteriaMustBeSatisfied;	// G=0x155bd; S=0x13471; converted property
@property(assign) int dateUnits;	// G=0x1577d; S=0x133e5; converted property
@property(assign) BOOL dateIsRelative;	// G=0x15761; S=0x133f5; converted property
+ (id)criteriaFromDefaultsArray:(id)defaultsArray;	// 0x45e35
+ (id)criteriaFromDefaultsArray:(id)defaultsArray removingRecognizedKeys:(BOOL)keys;	// 0x45d65
+ (id)defaultsArrayFromCriteria:(id)criteria;	// 0x45cc9
+ (void)_updateAddressComments:(id)comments;	// 0x45ba9
+ (int)criterionTypeForString:(id)string;	// 0xbdb1
+ (id)stringForCriterionType:(int)criterionType;	// 0x9735
+ (id)criterionForMailboxURL:(id)mailboxURL;	// 0x95a1
+ (id)messageIsDeletedCriterion:(BOOL)criterion;	// 0x18749
+ (id)messageIsServerSearchResultCriterion:(BOOL)criterion;	// 0x45b41
- (id)init;	// 0x965d
- (id)initWithCriterion:(id)criterion expression:(id)expression;	// 0x479a5
- (id)initWithType:(int)type qualifier:(int)qualifier expression:(id)expression;	// 0x95f1
- (id)initWithDictionary:(id)dictionary;	// 0x47991
- (id)initWithDictionary:(id)dictionary andRemoveRecognizedKeysIfMutable:(BOOL)aMutable;	// 0x47539
- (void)dealloc;	// 0x16e65
- (BOOL)isEqual:(id)equal;	// 0x47491
- (id)descriptionWithDepth:(unsigned)depth;	// 0x471c1
- (id)description;	// 0x471ad
- (id)dictionaryRepresentation;	// 0x46d6d
// converted property getter: - (int)criterionType;	// 0xbd61
// converted property setter: - (void)setCriterionType:(int)type;	// 0x96e1
// converted property getter: - (id)criterionIdentifier;	// 0x1f071
// converted property setter: - (void)setCriterionIdentifier:(id)identifier;	// 0x992d
- (id)_qualifierString;	// 0x46d4d
// converted property getter: - (int)qualifier;	// 0x155ad
// converted property setter: - (void)setQualifier:(int)qualifier;	// 0x99b5
// converted property getter: - (id)expression;	// 0xc0fd
// converted property setter: - (void)setExpression:(id)expression;	// 0x99c5
// converted property getter: - (id)name;	// 0x45aad
// converted property setter: - (void)setName:(id)name;	// 0x46d0d
- (id)_headersRequiredForEvaluation;	// 0x46ab5
- (BOOL)_evaluateHeaderCriterion:(id)criterion;	// 0x46795
- (BOOL)_evaluateAddressBookCriterion:(id)criterion;	// 0x46775
- (BOOL)_evaluateFullNameCriterion:(id)criterion;	// 0x464c5
- (BOOL)_evaluateIsDigitallySignedCriterion:(id)criterion;	// 0x4647d
- (BOOL)_evaluateIsEncryptedCriterion:(id)criterion;	// 0x46435
- (BOOL)_evaluatePriorityIsNormalCriterion:(id)criterion;	// 0x46411
- (BOOL)_evaluatePriorityIsHighCriterion:(id)criterion;	// 0x463ed
- (BOOL)_evaluatePriorityIsLowCriterion:(id)criterion;	// 0x463c9
- (BOOL)_evaluateAttachmentCriterion:(id)criterion;	// 0x461b1
- (BOOL)_evaluateAccountCriterion:(id)criterion;	// 0x4615d
- (BOOL)_evaluateAddressHistoryCriterion:(id)criterion;	// 0x4613d
- (BOOL)_evaluateDateCriterion:(id)criterion;	// 0x46015
- (BOOL)doesMessageSatisfyCriterion:(id)criterion;	// 0x45f31
- (int)messageRuleQualifierForString:(id)string;	// 0x45e49
- (id)stringForMessageRuleQualifier:(int)messageRuleQualifier;	// 0x45abd
// converted property getter: - (id)criteria;	// 0x13a3d
// converted property setter: - (void)setCriteria:(id)criteria;	// 0x13415
// converted property getter: - (BOOL)allCriteriaMustBeSatisfied;	// 0x155bd
// converted property setter: - (void)setAllCriteriaMustBeSatisfied:(BOOL)satisfied;	// 0x13471
// converted property getter: - (int)dateUnits;	// 0x1577d
// converted property setter: - (void)setDateUnits:(int)units;	// 0x133e5
// converted property getter: - (BOOL)dateIsRelative;	// 0x15761
// converted property setter: - (void)setDateIsRelative:(BOOL)relative;	// 0x133f5
- (id)simplifyOnce;	// 0x13b41
- (id)simplifiedCriterion;	// 0x13ae9
- (id)emailAddressesForGroupCriterion;	// 0x45b3d
@end

@interface MessageCriterion (PrivateLibraryAdditions)
- (id)criterionByAddingEmailCriteria;	// 0x1f681
- (id)criterionByExpandingAddressCriteria;	// 0x1381d
- (id)fixOnce;	// 0x13e79
- (id)SQLExpressionWithContext:(XXStruct_05f3rD *)context depth:(unsigned)depth;	// 0x1418d
- (BOOL)hasNumberCriterion;	// 0x14071
@end

@interface MessageCriterion (LibraryAdditions)
- (id)_criterionForSQL;	// 0x13a75
- (id)criterionForSQL;	// 0x137f5
- (id)SQLExpressionWithTables:(unsigned *)tables baseTable:(unsigned)table;	// 0x14029
- (unsigned)bestBaseTable;	// 0x17df1
- (BOOL)includesCriterionSatisfyingPredicate:(/*function-pointer*/ void *)predicate restrictive:(BOOL)restrictive;	// 0x14095
@end
