/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/MFMailDelivery.h>

@class NSString, DAMailAccount;

@interface MFDADelivery : MFMailDelivery {
	DAMailAccount *_DAMailAccount;	// 52 = 0x34
	NSString *_folderId;	// 56 = 0x38
	NSString *_accountId;	// 60 = 0x3c
	NSString *_repliedMessageId;	// 64 = 0x40
	NSString *_forwardedMessageId;	// 68 = 0x44
	NSString *_repliedLongId;	// 72 = 0x48
	NSString *_forwardedLongId;	// 76 = 0x4c
}
- (id)initWithHeaders:(id)headers mixedContent:(id)content textPartsAreHTML:(BOOL)html;	// 0x69a21
- (id)initWithHeaders:(id)headers HTML:(id)html plainTextAlternative:(id)alternative other:(id)other;	// 0x6989d
- (void)dealloc;	// 0x697d9
- (void)setDAMailAccount:(id)account;	// 0x69791
- (id)newMessageWriter;	// 0x6974d
- (int)deliverSynchronously;	// 0x69509
@end
