/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/DAMessageMoveRequestConsumer.h>
#import <Message/MFDAMailAccountConsumer.h>

@class NSMutableSet, NSSet, NSMutableDictionary, MFError;

@interface MFDAMoveResponseConsumer : MFDAMailAccountConsumer <DAMessageMoveRequestConsumer> {
	NSSet *_messagesIDs;	// 12 = 0xc
	NSMutableDictionary *_newRemoteIDsByMessageID;	// 16 = 0x10
	NSMutableSet *_failures;	// 20 = 0x14
	MFError *_error;	// 24 = 0x18
}
@property(retain, nonatomic) MFError *error;	// G=0x7cb05; S=0x7cbad; @synthesize=_error
- (id)initWithMessageIDs:(id)messageIDs newRemoteIDsByMessageID:(id)anId failures:(id)failures;	// 0x7cb15
- (void)dealloc;	// 0x7ce1d
- (void)taskFailed:(id)failed withStatusCode:(int)statusCode;	// 0x7cd65
- (void)resultsForMessageMove:(id)messageMove;	// 0x7cbd5
// declared property getter: - (id)error;	// 0x7cb05
// declared property setter: - (void)setError:(id)error;	// 0x7cbad
@end
