/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/XXUnknownSuperclass.h>


@interface MFLocalizedMessageHeaders : XXUnknownSuperclass {
}
+ (id)localizedHeaders;	// 0x77f9d
+ (id)localizedHeadersFromEnglishHeaders:(id)englishHeaders;	// 0x77ebd
+ (id)englishHeadersFromLocalizedHeaders:(id)localizedHeaders;	// 0x77dc1
- (id)copyFormattedHeaderValueFromAddressList:(id)addressList;	// 0x77d21
- (void)appendHeaderMarkupForKey:(id)key value:(id)value toString:(id)string;	// 0x782e5
- (id)markupString;	// 0x78185
@end
