/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/AuthScheme.h>


@interface MFNTLMAuthScheme : AuthScheme {
}
+ (void)initialize;	// 0x4811
- (Class)authenticatorClass;	// 0x48c0d
- (id)name;	// 0x4859
- (id)humanReadableName;	// 0x48f6d
- (BOOL)sendsPlainTextPasswords;	// 0x48c05
- (BOOL)hasEncryption;	// 0x48c09
@end
