/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/XXUnknownSuperclass.h>


@interface MFSparseMutable64IndexSet : XXUnknownSuperclass {
	unsigned _count;	// 4 = 0x4
	unsigned _storageSize;	// 8 = 0x8
	unsigned _cursor;	// 12 = 0xc
	unsigned long long *_storage;	// 16 = 0x10
}
@property(readonly, assign) unsigned count;	// G=0x7c599; converted property
+ (id)indexSet;	// 0x7c6f9
- (void)dealloc;	// 0x7c6b5
- (void)_incrementStorageIfNecessaryForCount:(unsigned)count;	// 0x7ca59
- (void)_garbageCollectStorageIfNecessary;	// 0x7c531
- (void)addIndex:(unsigned long long)index;	// 0x7c999
- (void)addIndexes:(id)indexes;	// 0x7c8f1
- (void)removeIndex:(unsigned long long)index;	// 0x7c82d
- (BOOL)containsIndex:(unsigned long long)index;	// 0x7c535
// converted property getter: - (unsigned)count;	// 0x7c599
- (unsigned long long)firstIndex;	// 0x7c5a9
- (unsigned long long)indexGreaterThanIndex:(unsigned long long)index;	// 0x7c5e5
- (id)description;	// 0x7c731
@end
