/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/Message-Structs.h>
#import <Message/NSStreamDelegate.h>
#import <Message/XXUnknownSuperclass.h>

@class NSOutputStream, NSError, NSMutableDictionary, NSInputStream;

@interface MFStream : XXUnknownSuperclass <NSStreamDelegate> {
	NSInputStream *_rStream;	// 4 = 0x4
	NSOutputStream *_wStream;	// 8 = 0x8
	NSMutableDictionary *_properties;	// 12 = 0xc
	id _callback;	// 16 = 0x10
	dispatch_queue_s *_location;	// 20 = 0x14
	unsigned _capacity;	// 24 = 0x18
	unsigned _length;	// 28 = 0x1c
	char *_buffer;	// 32 = 0x20
	NSError *_error;	// 36 = 0x24
	BOOL _canRead;	// 40 = 0x28
	BOOL _canWrite;	// 41 = 0x29
	BOOL _sentCanRead;	// 42 = 0x2a
}
@property(readonly, assign, nonatomic) NSError *streamError;	// G=0x6cbb9; @synthesize=_error
@property(readonly, assign, nonatomic) BOOL isOpen;	// G=0x6ca99; 
+ (id)networkThread;	// 0x9f15
+ (void)setNetworkThread:(id)thread;	// 0x6d40d
+ (dispatch_queue_s *)_networkDispatchQueue;	// 0x6d1cd
- (id)init;	// 0x6cc29
- (id)initCallBack:(id)back onDispatchQueue:(dispatch_queue_s *)queue;	// 0x6d359
- (void)dealloc;	// 0x6eb21
// declared property getter: - (BOOL)isOpen;	// 0x6ca99
- (id)_copyPropertyForKey:(id)key;	// 0x6cc3d
- (id)propertyForKey:(id)key;	// 0x6cded
- (BOOL)setProperty:(id)property forKey:(id)key;	// 0x6e8dd
- (void)openToHostName:(id)hostName port:(int)port;	// 0x6e51d
- (int)read:(char *)read maxLength:(unsigned)length;	// 0x6e1d5
- (int)write:(const char *)write maxLength:(unsigned)length;	// 0x6de19
- (void)close;	// 0x6db55
- (void)_readBytesFromStream;	// 0x6d749
- (void)stream:(id)stream handleEvent:(unsigned)event;	// 0x6d459
// declared property getter: - (id)streamError;	// 0x6cbb9
@end
