/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Message.framework/Message
 */

#import <Message/DeliveryAccount.h>
#import <Message/Message-Structs.h>

@class NSTimer, MFSMTPConnection;

@interface SMTPAccount : DeliveryAccount {
	Class _deliveryClass;	// 28 = 0x1c
	MFSMTPConnection *_connection;	// 32 = 0x20
	NSTimer *_timer;	// 36 = 0x24
	int _lastTimerSetTime;	// 40 = 0x28
	unsigned _supportsPipelining : 1;	// 44 = 0x2c
	unsigned _supportsOutboxCopy : 1;	// 44 = 0x2c
	unsigned _useCellDataOnly : 1;	// 44 = 0x2c
}
@property(assign) Class deliveryClass;	// G=0x3d411; S=0x3d379; converted property
@property(retain) id preferredAuthScheme;	// G=0x3e0d5; S=0x3e089; converted property
@property(assign) BOOL supportsPipelining;	// G=0x3d3ad; S=0x3d3c1; converted property
@property(assign) BOOL supportsOutboxCopy;	// G=0x3d3dd; S=0x3d3f1; converted property
+ (id)accountTypeString;	// 0x200ed
+ (void *)keychainProtocol;	// 0x3d355
+ (id)displayedAccountTypeString;	// 0x200dd
+ (id)displayedShortAccountTypeString;	// 0x200f9
+ (id)newDefaultInstance;	// 0x3d375
+ (void)registerAppleServiceDeliveryHostname:(id)hostname;	// 0x3d95d
+ (id)saslProfileName;	// 0x3d39d
- (id)certUIService;	// 0x3d365
// converted property getter: - (Class)deliveryClass;	// 0x3d411
// converted property setter: - (void)setDeliveryClass:(Class)aClass;	// 0x3d379
- (unsigned)defaultPortNumber;	// 0x3d389
- (id)serviceName;	// 0x3d391
- (BOOL)isCommonPortNumber:(unsigned)number;	// 0x3d911
- (unsigned)keychainPortNumber;	// 0x3d3a9
- (Class)connectionClass;	// 0x3e1c5
- (id)_defaultSettingsWithPort:(unsigned)port useSSL:(BOOL)ssl directSSL:(BOOL)ssl3;	// 0x3d449
- (id)connectionSettingsForAuthentication:(BOOL)authentication secure:(id)secure insecure:(id)insecure;	// 0x3d4a1
- (id)secureConnectionSettings;	// 0x3d77d
- (id)insecureConnectionSettings;	// 0x3d801
- (id)alternateConnectionSettings;	// 0x3d885
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned)port;	// 0x3e14d
// converted property getter: - (id)preferredAuthScheme;	// 0x3e0d5
// converted property setter: - (void)setPreferredAuthScheme:(id)scheme;	// 0x3e089
- (id)customAuthenticationErrorStringForError:(id)error authScheme:(id)scheme;	// 0x3e035
// converted property getter: - (BOOL)supportsPipelining;	// 0x3d3ad
// converted property setter: - (void)setSupportsPipelining:(BOOL)pipelining;	// 0x3d3c1
// converted property getter: - (BOOL)supportsOutboxCopy;	// 0x3d3dd
// converted property setter: - (void)setSupportsOutboxCopy:(BOOL)copy;	// 0x3d3f1
- (CFStringRef)connectionServiceType;	// 0x3dfe1
- (id)authenticatedConnection:(BOOL)connection;	// 0x3de71
- (void)disconnect:(id)disconnect;	// 0x3d8a5
- (void)connectionExpired:(id)expired;	// 0x3dddd
- (void)setTimer;	// 0x3dd5d
- (void)checkInConnection:(id)connection;	// 0x3dc99
- (void)releaseAllConnections;	// 0x3dc09
- (void)releaseAllForcedConnections;	// 0x3dbdd
- (BOOL)_isAppleServiceDeliveryHostname:(id)hostname;	// 0x3db9d
- (BOOL)canBeFallbackAccount;	// 0x3d8d5
- (void)setPasswordInKeychain:(id)keychain;	// 0x3dadd
- (id)passwordFromKeychain;	// 0x3da45
- (void)dealloc;	// 0x3d9d1
@end
