/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MMCSServices.framework/MMCSServices
 */

#import <MMCSServices/MMCSServices-Structs.h>
#import <MMCSServices/MMCSPutFile.h>
#import <MMCSServices/MMCSGetFile.h>
#import <MMCSServices/MMCSController.h>
#import <MMCSServices/MMCSSimpleFile.h>
