/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

#import <AppStoreUI/AppStoreUI-Structs.h>
#import <AppStoreUI/ASIconCellConfiguration.h>


@interface ASUpdateCellConfiguration : ASIconCellConfiguration {
}
+ (id)copyDefaultContext;	// 0x840d
- (void)reloadStrings;	// 0x8841
- (void)reloadLayoutInformation;	// 0x85dd
- (BOOL)getShadowColor:(id *)color offset:(CGSize *)offset forLabelAtIndex:(unsigned)index withModifiers:(unsigned)modifiers;	// 0x8569
- (id)fontForLabelAtIndex:(unsigned)index;	// 0x84f9
- (id)colorForLabelAtIndex:(unsigned)index withModifiers:(unsigned)modifiers;	// 0x8479
- (id)init;	// 0x83f9
@end
