/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/AppStoreUI.framework/AppStoreUI
 */

#import <AppStoreUI/SSRequestDelegate.h>


@protocol SSSoftwareUpdatesRequestDelegate <SSRequestDelegate>
@optional
- (void)updateQueueRequest:(id)request didReceiveResponse:(id)response;
@end
