/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <iTunesStore/ISOperation.h>

@class NSDictionary;

@interface ISSoftwareCapabilitiesDialogOperation : ISOperation {
@private
	NSDictionary *_mismatches;	// 60 = 0x3c
	id _requiredCapabilities;	// 64 = 0x40
}
@property(readonly, assign) id requiredCapabilities;	// G=0x2807d; 
@property(readonly, assign) NSDictionary *mismatches;	// G=0x28045; 
- (void)_postDefaultDialog;	// 0x2851d
- (void)run;	// 0x280b5
// declared property getter: - (id)requiredCapabilities;	// 0x2807d
// declared property getter: - (id)mismatches;	// 0x28045
- (void)dealloc;	// 0x27fe5
- (id)initWithRequiredCapabilities:(id)requiredCapabilities mismatches:(id)mismatches;	// 0x27f85
@end
