/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
 */

#import <CoreMediaStream/XXUnknownSuperclass.h>

@class NSDate;

@interface MSBackoffManager : XXUnknownSuperclass {
@private
	double _initialInterval;	// 4 = 0x4
	double _backoffFactor;	// 12 = 0xc
	double _randomizeFactor;	// 20 = 0x14
	double _maxBackoffInterval;	// 28 = 0x1c
	double _currentInterval;	// 36 = 0x24
	NSDate *_nextExpiryDate;	// 44 = 0x2c
	NSDate *_retryAfterDate;	// 48 = 0x30
}
@property(retain, nonatomic) NSDate *retryAfterDate;	// G=0x21a95; S=0x21aa5; @synthesize=_retryAfterDate
@property(retain, nonatomic) NSDate *nextExpiryDate;	// G=0x21685; S=0x21a71; @synthesize=_nextExpiryDate
@property(assign, nonatomic) double currentInterval;	// G=0x21a59; S=0x215a5; @synthesize=_currentInterval
@property(assign, nonatomic) double maxBackoffInterval;	// G=0x21a2d; S=0x21a45; @synthesize=_maxBackoffInterval
@property(assign, nonatomic) double randomizeFactor;	// G=0x21a01; S=0x21a19; @synthesize=_randomizeFactor
@property(assign, nonatomic) double backoffFactor;	// G=0x219d5; S=0x219ed; @synthesize=_backoffFactor
@property(assign, nonatomic) double initialInterval;	// G=0x219a9; S=0x219c1; @synthesize=_initialInterval
// declared property setter: - (void)setRetryAfterDate:(id)date;	// 0x21aa5
// declared property getter: - (id)retryAfterDate;	// 0x21a95
// declared property setter: - (void)setNextExpiryDate:(id)date;	// 0x21a71
// declared property getter: - (double)currentInterval;	// 0x21a59
// declared property setter: - (void)setMaxBackoffInterval:(double)interval;	// 0x21a45
// declared property getter: - (double)maxBackoffInterval;	// 0x21a2d
// declared property setter: - (void)setRandomizeFactor:(double)factor;	// 0x21a19
// declared property getter: - (double)randomizeFactor;	// 0x21a01
// declared property setter: - (void)setBackoffFactor:(double)factor;	// 0x219ed
// declared property getter: - (double)backoffFactor;	// 0x219d5
// declared property setter: - (void)setInitialInterval:(double)interval;	// 0x219c1
// declared property getter: - (double)initialInterval;	// 0x219a9
- (void)backoff;	// 0x21849
- (void)reset;	// 0x217cd
- (void)didReceiveRetryAfterDate:(id)date;	// 0x21709
// declared property getter: - (id)nextExpiryDate;	// 0x21685
// declared property setter: - (void)setCurrentInterval:(double)interval;	// 0x215a5
- (void)dealloc;	// 0x21545
- (id)initWithInitialInterval:(double)initialInterval backoffFactor:(double)factor randomizeFactor:(double)factor3 maxBackoffInterval:(double)interval retryAfterDate:(id)date;	// 0x21481
@end
