/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
 */

#import <ToneLibrary/TLVibrationPickerViewControllerDelegate.h>
#import <ToneLibrary/UITableViewDataSource.h>
#import <ToneLibrary/XXUnknownSuperclass.h>
#import <ToneLibrary/ToneLibrary-Structs.h>
#import <ToneLibrary/UITableViewDelegate.h>

@class NSMutableArray, NSIndexPath, UITableView, TLVibrationPickerViewController, NSString, TLToneManager;

@interface TLToneTableController : XXUnknownSuperclass <TLVibrationPickerViewControllerDelegate, UITableViewDataSource, UITableViewDelegate> {
@private
	id _delegate;	// 4 = 0x4
	NSMutableArray *_ringtoneGroupLists;	// 8 = 0x8
	NSMutableArray *_ringtoneGroupNames;	// 12 = 0xc
	NSIndexPath *_selectedRingtoneIndexPath;	// 16 = 0x10
	BOOL _showsNone;	// 20 = 0x14
	BOOL _showsDefault;	// 21 = 0x15
	NSString *_noneString;	// 24 = 0x18
	NSString *_noneIdentifier;	// 28 = 0x1c
	NSString *_defaultIdentifier;	// 32 = 0x20
	BOOL _showsNothingSelected;	// 36 = 0x24
	BOOL _showsRingtonesStore;	// 37 = 0x25
	BOOL _noneAtTop;	// 38 = 0x26
	UITableView *_tableView;	// 40 = 0x28
	BOOL _showsVibrations;	// 44 = 0x2c
	BOOL _showsVibrationsAlongsideTones;	// 45 = 0x2d
	BOOL _showsDefaultVibration;	// 46 = 0x2e
	BOOL _showsUserGeneratedVibrations;	// 47 = 0x2f
	BOOL _showsNoneVibration;	// 48 = 0x30
	BOOL _showsNoVibrationSelected;	// 49 = 0x31
	NSString *_selectedVibrationIdentifier;	// 52 = 0x34
	TLVibrationPickerViewController *_vibrationPickerViewController;	// 56 = 0x38
	TLToneManager *_ringtoneManager;	// 60 = 0x3c
	id _avController;	// 64 = 0x40
	BOOL _startedInteruption;	// 68 = 0x44
	BOOL _customAVController;	// 69 = 0x45
	BOOL _tonePicker;	// 70 = 0x46
	unsigned _filter;	// 72 = 0x48
	unsigned _systemRingtoneStartIndex;	// 76 = 0x4c
}
@property(retain, nonatomic, setter=setDefaultIdentifier:) id defaultIdentifier;	// G=0xafb5; S=0xafc5; @synthesize=_defaultIdentifier
@property(retain) NSString *selectedVibrationIdentifier;	// G=0x8ced; S=0x8db1; converted property
@property(retain) id selectedRingtoneIdentifier;	// G=0x86d1; S=0x8539; converted property
@property(readonly, retain) TLToneManager *ringtoneManager;	// G=0x86f1; converted property
@property(readonly, retain) id avController;	// G=0xa7d9; converted property
// declared property setter: - (void)setDefaultIdentifier:(id)identifier;	// 0xafc5
// declared property getter: - (id)defaultIdentifier;	// 0xafb5
- (void)_setRingtoneManager:(id)manager;	// 0xaf75
- (void)_switchValueDidChange:(id)_switchValue;	// 0xaeb9
- (void)vibrationPickerViewController:(id)controller selectedVibrationWithIdentifier:(id)identifier;	// 0xae41
- (void)finishedWithPicker;	// 0xadb9
- (void)stopPlaying;	// 0xada5
- (void)_stopPlayingButKeepVibrating:(BOOL)vibrating;	// 0xad91
- (void)stopPlayingWithFadeOut:(BOOL)fadeOut;	// 0xad7d
- (void)_stopPlayingWithFadeOut:(BOOL)fadeOut shouldKeepVibrating:(BOOL)vibrating;	// 0xac51
- (void)playRingtoneWithIdentifier:(id)identifier;	// 0xa9c5
- (void)togglePlayWithRingtoneWithIdentifier:(id)identifier;	// 0xa961
// converted property getter: - (id)avController;	// 0xa7d9
- (void)setAVController:(id)controller;	// 0xa6c5
- (id)tableView:(id)view titleForHeaderInSection:(int)section;	// 0xa465
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x9fb1
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x9f55
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x9d81
- (int)numberOfSectionsInTableView:(id)tableView;	// 0x9c95
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x9535
- (id)copyCurrentPhoneTextToneIdentifier;	// 0x9515
- (id)copyCurrentPhoneTextToneName;	// 0x94f5
- (id)copyCurrentPhoneRingtoneIdentifier;	// 0x94d5
- (id)copyCurrentPhoneRingtoneName;	// 0x94b5
- (void)processNewRingtoneSelected:(id)selected;	// 0x943d
- (id)_vibrationPickerViewController;	// 0x9281
- (BOOL)_showsNoneVibration;	// 0x9255
- (BOOL)_showsUserGeneratedVibrations;	// 0x9245
- (BOOL)_showsDefaultVibration;	// 0x9235
- (BOOL)_showsVibrationsSwitchIsOn;	// 0x91d1
- (BOOL)_showsVibrations;	// 0x9181
// converted property setter: - (void)setSelectedVibrationIdentifier:(id)identifier;	// 0x8db1
- (void)_setSelectedVibrationIdentifierTableViewUpdateDidComplete:(id)_setSelectedVibrationIdentifierTableViewUpdate;	// 0x8cfd
// converted property getter: - (id)selectedVibrationIdentifier;	// 0x8ced
- (void)setShowsNoVibrationSelected:(BOOL)selected;	// 0x8c89
- (void)setShowsNoneVibration:(BOOL)vibration;	// 0x8c79
- (void)setShowsUserGeneratedVibrations:(BOOL)vibrations;	// 0x8b2d
- (void)setShowsDefaultVibration:(BOOL)vibration;	// 0x8b1d
- (void)setShowsVibrationsAlongsideTones:(BOOL)tones;	// 0x8b0d
- (void)setShowsVibrations:(BOOL)vibrations;	// 0x8afd
- (void)setShowsNothingSelected:(BOOL)selected;	// 0x8aed
- (void)setNoneString:(id)string;	// 0x8aa9
- (void)setNoneAtTop:(BOOL)top;	// 0x89fd
- (void)setShowsNone:(BOOL)none;	// 0x8955
- (void)setShowsDefault:(BOOL)aDefault;	// 0x87c5
- (void)setShowsRingtonesStore:(BOOL)store;	// 0x8701
// converted property getter: - (id)ringtoneManager;	// 0x86f1
// converted property getter: - (id)selectedRingtoneIdentifier;	// 0x86d1
// converted property setter: - (void)setSelectedRingtoneIdentifier:(id)identifier;	// 0x8539
- (void)setTableView:(id)view;	// 0x84f5
- (void)setDelegate:(id)delegate;	// 0x84e5
- (void)reloadRingtones;	// 0x7bb5
- (id)loadTextTonesFromPlist;	// 0x79e1
- (id)indexPathForSelectedRingtone;	// 0x79d1
- (id)indexPathForVibrationGroup;	// 0x791d
- (id)indexPathForNoneGroup;	// 0x787d
- (id)indexPathForFirstRingtoneGroup;	// 0x77d1
- (id)indexPathForDefaultGroup;	// 0x7751
- (id)indexPathForRingtonesStoreGroup;	// 0x7715
- (id)indexPathForRingtoneWithIdentifier:(id)identifier;	// 0x7619
- (id)identifierOfRingtoneAtIndexPath:(id)indexPath;	// 0x74bd
- (BOOL)isDividerAtIndexPath:(id)indexPath;	// 0x748d
- (BOOL)isOtherVibrationGroupWithSection:(int)section;	// 0x7411
- (BOOL)isVibrationGroupAtIndexPath:(id)indexPath;	// 0x733d
- (BOOL)isNoneGroupAtIndexPath:(id)indexPath;	// 0x7279
- (BOOL)isDefaultGroupAtIndexPath:(id)indexPath;	// 0x71e5
- (BOOL)isRingtonesStoreGroupAtIndexPath:(id)indexPath;	// 0x7195
- (int)compareRingtoneWithIdentifier:(id)identifier toRingtoneWithIdentifier:(id)identifier2;	// 0x7111
- (void)addRingtonesInDirectory:(id)directory toArray:(id)array fileExtension:(id)extension;	// 0x6fe1
- (void)dealloc;	// 0x6e69
- (id)initWithAVController:(id)avcontroller filter:(unsigned)filter tonePicker:(BOOL)picker;	// 0x6c79
- (id)initWithAVController:(id)avcontroller;	// 0x6c59
- (id)init;	// 0x6c45
@end
