/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
 */




@protocol TLVibrationRecorderControlsViewDelegate <NSObject>
- (void)vibrationRecorderControlsView:(id)view buttonTappedAtIndex:(unsigned)index;
@end

