/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import <FTServices/FTMessage.h>
#import <FTServices/NSCopying.h>
#import <FTServices/FTServices-Structs.h>

@class NSDictionary, NSData, NSString, NSArray;

@interface FTProvisionMessage : FTMessage <NSCopying> {
	NSString *_service;	// 4 = 0x4
	NSString *_realm;	// 8 = 0x8
	NSData *_csr;	// 12 = 0xc
	NSDictionary *_authenticationInfo;	// 16 = 0x10
	NSString *_userID;	// 20 = 0x14
	NSArray *_URIs;	// 24 = 0x18
	NSData *_responseCertificate;	// 28 = 0x1c
	NSArray *_responseBindings;	// 32 = 0x20
	NSString *_protocolVersion;	// 36 = 0x24
}
@property(copy) NSArray *responseBindings;	// G=0x2c009; S=0x2c01d; @synthesize=_responseBindings
@property(copy) NSData *responseCertificate;	// G=0x2bfd1; S=0x2bfe5; @synthesize=_responseCertificate
@property(copy) NSArray *URIs;	// G=0x2bf99; S=0x2bfad; @synthesize=_URIs
@property(copy) NSDictionary *authenticationInfo;	// G=0x2bf29; S=0x2bf3d; @synthesize=_authenticationInfo
@property(copy) NSString *userID;	// G=0x2bf61; S=0x2bf75; @synthesize=_userID
@property(copy) NSString *protocolVersion;	// G=0x2c041; S=0x2c055; @synthesize=_protocolVersion
@property(copy) NSData *csr;	// G=0x2bef1; S=0x2bf05; @synthesize=_csr
@property(copy) NSString *realm;	// G=0x2beb9; S=0x2becd; @synthesize=_realm
@property(copy) NSString *service;	// G=0x2be81; S=0x2be95; @synthesize=_service
// declared property setter: - (void)setProtocolVersion:(id)version;	// 0x2c055
// declared property getter: - (id)protocolVersion;	// 0x2c041
// declared property setter: - (void)setResponseBindings:(id)bindings;	// 0x2c01d
// declared property getter: - (id)responseBindings;	// 0x2c009
// declared property setter: - (void)setResponseCertificate:(id)certificate;	// 0x2bfe5
// declared property getter: - (id)responseCertificate;	// 0x2bfd1
// declared property setter: - (void)setURIs:(id)uris;	// 0x2bfad
// declared property getter: - (id)URIs;	// 0x2bf99
// declared property setter: - (void)setUserID:(id)anId;	// 0x2bf75
// declared property getter: - (id)userID;	// 0x2bf61
// declared property setter: - (void)setAuthenticationInfo:(id)info;	// 0x2bf3d
// declared property getter: - (id)authenticationInfo;	// 0x2bf29
// declared property setter: - (void)setCsr:(id)csr;	// 0x2bf05
// declared property getter: - (id)csr;	// 0x2bef1
// declared property setter: - (void)setRealm:(id)realm;	// 0x2becd
// declared property getter: - (id)realm;	// 0x2beb9
// declared property setter: - (void)setService:(id)service;	// 0x2be95
// declared property getter: - (id)service;	// 0x2be81
- (void)handleResponseDictionary:(id)dictionary;	// 0x2bdc9
- (id)additionalMessageHeaders;	// 0x2bcc9
- (id)messageBody;	// 0x2b929
- (id)requiredKeys;	// 0x2b87d
- (id)bagKey;	// 0x2b83d
- (int)responseCommand;	// 0x2b839
- (int)command;	// 0x2b835
- (BOOL)wantsBinaryPush;	// 0x2b831
- (BOOL)wantsCompressedBody;	// 0x2b82d
- (BOOL)wantsHTTPHeaders;	// 0x2b829
- (BOOL)wantsBagKey;	// 0x2b825
- (id)copyWithZone:(NSZone *)zone;	// 0x2b69d
- (void)dealloc;	// 0x2b5b1
- (id)init;	// 0x2b531
@end
