/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

#import <FTServices/FTServices-Structs.h>
#import <FTServices/NSCopying.h>
#import <FTServices/FTProfileMessage.h>

@class NSString;

@interface FTProfileConfirmEmailsMessage : FTProfileMessage <NSCopying> {
	NSString *_vettingToken;	// 4 = 0x4
	NSString *_emailAddress;	// 8 = 0x8
}
@property(copy) NSString *vettingToken;	// G=0x1acd1; S=0x1ace5; @synthesize=_vettingToken
@property(copy) NSString *emailAddress;	// G=0x1ad09; S=0x1ad1d; @synthesize=_emailAddress
// declared property setter: - (void)setEmailAddress:(id)address;	// 0x1ad1d
// declared property getter: - (id)emailAddress;	// 0x1ad09
// declared property setter: - (void)setVettingToken:(id)token;	// 0x1ace5
// declared property getter: - (id)vettingToken;	// 0x1acd1
- (id)messageBody;	// 0x1ab9d
- (id)requiredKeys;	// 0x1ab25
- (id)bagKey;	// 0x1ab19
- (void)dealloc;	// 0x1aab9
- (id)copyWithZone:(NSZone *)zone;	// 0x1aa39
@end
