/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MobileWirelessSync.framework/MobileWirelessSync
 */




@protocol BasicAccountSyncing <NSObject>
- (id)defaultContainerIdentifierForDataclass:(id)dataclass;
@optional
- (BOOL)refreshContainerWithIdentifier:(id)identifier forDataclass:(id)dataclass isUserRequested:(BOOL)requested;
- (BOOL)refreshContainersForDataclass:(id)dataclass isUserRequested:(BOOL)requested;
- (BOOL)refreshContainerListForDataclass:(id)dataclass isUserRequested:(BOOL)requested;
- (BOOL)refreshContainerWithIdentifier:(id)identifier forDataclass:(id)dataclass;
- (BOOL)refreshContainersForDataclass:(id)dataclass;
- (BOOL)refreshContainerListForDataclass:(id)dataclass;
@end

