/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/MobileSoftwareUpdate.framework/MobileSoftwareUpdate
 */

#import <MobileSoftwareUpdate/MobileSoftwareUpdate-Structs.h>
