/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>


@interface EmbeddedStoreViewControllerFactory : XXUnknownSuperclass {
}
- (void)_setDefaultValuesForScriptProperties:(id)scriptProperties;	// 0x61ae9
- (id)newViewControllerForPage:(id)page ofType:(int)type;	// 0x61a69
- (id)newStorePageViewControllerWithSection:(id)section;	// 0x619dd
- (id)newPlaceholderViewController;	// 0x61949
@end
