/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>

@class IUMusicCoverFlowController;

@interface IUCoverFlowViewController : XXUnknownSuperclass {
	IUMusicCoverFlowController *_coverFlowController;	// 192 = 0xc0
	unsigned _swappedCoverflow : 1;	// 196 = 0xc4
}
@property(readonly, assign, nonatomic) IUMusicCoverFlowController *coverFlowController;	// G=0x7459; @synthesize=_coverFlowController
- (BOOL)musicCoverFlowHandlePendingRotations:(id)rotations;	// 0x74b1
- (void)musicCoverFlowFlipDidEnd:(id)musicCoverFlowFlip;	// 0x74ad
// declared property getter: - (id)coverFlowController;	// 0x7459
- (void)viewDidDisappear:(BOOL)view;	// 0x7351
- (void)setOrientation:(int)orientation animate:(BOOL)animate;	// 0x7295
- (void)loadView;	// 0x71f9
- (BOOL)canDisplayItem:(id)item withInterfaceOrientation:(int)interfaceOrientation;	// 0x71c5
- (void)willSwapCoverFlow;	// 0x71ad
- (void)dealloc;	// 0x712d
- (id)initWithCoverFlowController:(id)coverFlowController;	// 0x70d9
@end
