/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>


@interface IUMediaNavigationItem : XXUnknownSuperclass {
	int _barStyle;	// 68 = 0x44
	int _statusBarStyle;	// 72 = 0x48
	BOOL _statusBarHidden;	// 76 = 0x4c
}
@property(assign, nonatomic, getter=isStatusBarHidden) BOOL statusBarHidden;	// G=0xa3315; S=0xa3325; @synthesize=_statusBarHidden
@property(assign, nonatomic) int statusBarStyle;	// G=0xa32f5; S=0xa3305; @synthesize=_statusBarStyle
@property(assign, nonatomic) int barStyle;	// G=0xa32d5; S=0xa32e5; @synthesize=_barStyle
// declared property setter: - (void)setStatusBarHidden:(BOOL)hidden;	// 0xa3325
// declared property getter: - (BOOL)isStatusBarHidden;	// 0xa3315
// declared property setter: - (void)setStatusBarStyle:(int)style;	// 0xa3305
// declared property getter: - (int)statusBarStyle;	// 0xa32f5
// declared property setter: - (void)setBarStyle:(int)style;	// 0xa32e5
// declared property getter: - (int)barStyle;	// 0xa32d5
@end
