/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>


@interface IUMediaActionSheet : XXUnknownSuperclass {
}
- (void)showInView:(id)view;	// 0xa0749
- (void)showFromTabBar:(id)tabBar;	// 0xa0711
- (void)showFromToolbar:(id)toolbar;	// 0xa06d9
- (void)dismissWithClickedButtonIndex:(int)clickedButtonIndex animated:(BOOL)animated;	// 0xa069d
- (void)dealloc;	// 0xa0669
@end
