/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>
#import <iPodUI/iPodUI-Structs.h>

@class IUPropertyLayoutStorage, MPMediaItem, UIImage, IUMediaListDataSource;

@interface IUMediaListAggregateViewConfiguration : XXUnknownSuperclass {
@private
	MPMediaItem *_aggregateItem;	// 4 = 0x4
	IUMediaListDataSource *_dataSource;	// 8 = 0x8
	IUPropertyLayoutStorage *_labelStorage;	// 12 = 0xc
	IUPropertyLayoutStorage *_buttonStorage;	// 16 = 0x10
	BOOL _showsShuffleButton;	// 20 = 0x14
	BOOL _shuffleButtonEnabled;	// 21 = 0x15
	CGSize _layoutSize;	// 24 = 0x18
}
@property(readonly, assign, nonatomic) unsigned numberOfButtons;	// G=0xefa1; 
@property(retain, nonatomic) IUPropertyLayoutStorage *buttonStorage;	// G=0xf1b9; S=0xf1c9; @synthesize=_buttonStorage
@property(readonly, assign, nonatomic) unsigned numberOfLabels;	// G=0xee1d; 
@property(retain, nonatomic) IUPropertyLayoutStorage *labelStorage;	// G=0xf185; S=0xf195; @synthesize=_labelStorage
@property(readonly, assign, nonatomic) BOOL canDisplayShuffleButton;	// G=0xf0e1; 
@property(assign, nonatomic) BOOL shuffleButtonEnabled;	// G=0xf1fd; S=0xf20d; @synthesize=_shuffleButtonEnabled
@property(assign, nonatomic) BOOL showsShuffleButton;	// G=0xf1ed; S=0xf0e5; @synthesize=_showsShuffleButton
@property(readonly, assign, nonatomic) UIImage *backgroundImage;	// G=0xf08d; 
@property(retain, nonatomic) MPMediaItem *aggregateItem;	// G=0xf11d; S=0xf12d; @synthesize=_aggregateItem
@property(retain, nonatomic) IUMediaListDataSource *dataSource;	// G=0xf151; S=0xf161; @synthesize=_dataSource
@property(assign, nonatomic) CGSize layoutSize;	// G=0xee01; S=0xedad; 
+ (id)newConfigurationForDataSource:(id)dataSource;	// 0xe9e9
// declared property setter: - (void)setShuffleButtonEnabled:(BOOL)enabled;	// 0xf20d
// declared property getter: - (BOOL)shuffleButtonEnabled;	// 0xf1fd
// declared property getter: - (BOOL)showsShuffleButton;	// 0xf1ed
// declared property setter: - (void)setButtonStorage:(id)storage;	// 0xf1c9
// declared property getter: - (id)buttonStorage;	// 0xf1b9
// declared property setter: - (void)setLabelStorage:(id)storage;	// 0xf195
// declared property getter: - (id)labelStorage;	// 0xf185
// declared property setter: - (void)setDataSource:(id)source;	// 0xf161
// declared property getter: - (id)dataSource;	// 0xf151
// declared property setter: - (void)setAggregateItem:(id)item;	// 0xf12d
// declared property getter: - (id)aggregateItem;	// 0xf11d
// declared property setter: - (void)setShowsShuffleButton:(BOOL)button;	// 0xf0e5
// declared property getter: - (BOOL)canDisplayShuffleButton;	// 0xf0e1
- (id)artworkImageWithLoadingCompletionHandler:(id)loadingCompletionHandler;	// 0xf0dd
// declared property getter: - (id)backgroundImage;	// 0xf08d
- (id)viewForButtonAtIndex:(unsigned)index;	// 0xf04d
- (CGRect)frameForButtonAtIndex:(unsigned)index;	// 0xefdd
// declared property getter: - (unsigned)numberOfButtons;	// 0xefa1
- (id)stringForLabelAtIndex:(unsigned)index;	// 0xef6d
- (int)textAlignmentForLabelAtIndex:(unsigned)index;	// 0xef69
- (BOOL)getShadowColor:(id *)color offset:(CGSize *)offset forLabelAtIndex:(unsigned)index withModifiers:(unsigned)modifiers;	// 0xef65
- (float)minFontPointSizeForLabelAtIndex:(unsigned)index;	// 0xef3d
- (id)fontForLabelAtIndex:(unsigned)index;	// 0xef19
- (CGRect)frameForLabelAtIndex:(unsigned)index;	// 0xeea9
- (id)backgroundColorWithModifiers:(unsigned)modifiers;	// 0xee8d
- (id)colorForLabelAtIndex:(unsigned)index withModifiers:(unsigned)modifiers;	// 0xee59
// declared property getter: - (unsigned)numberOfLabels;	// 0xee1d
// declared property getter: - (CGSize)layoutSize;	// 0xee01
// declared property setter: - (void)setLayoutSize:(CGSize)size;	// 0xedad
- (void)reloadLayoutInformation;	// 0xeda9
- (void)reloadDisplayValues;	// 0xeda5
- (void)reloadData;	// 0xed15
- (BOOL)useLabelStorage;	// 0xed11
- (void)dealloc;	// 0xec9d
- (id)newViewWithDelegate:(id)delegate;	// 0xec45
- (Class)viewClass;	// 0xeba1
- (id)initWithDataSource:(id)dataSource;	// 0xeaa5
- (void)initStorage;	// 0xeaa1
@end
