/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/XXUnknownSuperclass.h>
#import <iPodUI/iPodUI-Structs.h>

@class UIImageView, MPMediaQuery, NSString, UIImage, MPAVItem, UILabel;

@interface IUNowPlayingAlbumBackHeaderView : XXUnknownSuperclass {
	MPAVItem *_item;	// 72 = 0x48
	MPMediaQuery *_query;	// 76 = 0x4c
	int _style;	// 80 = 0x50
	NSString *_subtitle;	// 84 = 0x54
	NSString *_title;	// 88 = 0x58
	UIImageView *_artworkImageView;	// 92 = 0x5c
	UIImageView *_backgroundImageView;	// 96 = 0x60
	UILabel *_subtitleLabel;	// 100 = 0x64
	UILabel *_titleLabel;	// 104 = 0x68
	UILabel *_infoLabel;	// 108 = 0x6c
}
@property(retain, nonatomic) NSString *title;	// G=0x58f75; S=0x57b65; @synthesize=_title
@property(retain, nonatomic) NSString *subtitle;	// G=0x58f65; S=0x57b0d; @synthesize=_subtitle
@property(assign, nonatomic) int style;	// G=0x58f55; S=0x57ae1; @synthesize=_style
@property(retain, nonatomic) MPMediaQuery *query;	// G=0x58f85; S=0x57bbd; @synthesize=_query
@property(retain, nonatomic) MPAVItem *item;	// G=0x58f45; S=0x57a89; @synthesize=_item
@property(retain, nonatomic) UIImage *artworkImage;	// G=0x579c1; S=0x579e1; 
+ (CGSize)thumbnailSize;	// 0x578f5
// declared property getter: - (id)query;	// 0x58f85
// declared property getter: - (id)title;	// 0x58f75
// declared property getter: - (id)subtitle;	// 0x58f65
// declared property getter: - (int)style;	// 0x58f55
// declared property getter: - (id)item;	// 0x58f45
- (id)_infoTitle;	// 0x58b7d
- (void)_reloadViews;	// 0x58475
- (void)_layoutForWildcatGridStyle;	// 0x5824d
- (void)_layoutForGridStyle;	// 0x580c1
- (void)_layoutForDefaultStyle;	// 0x57e55
- (id)_artworkImageView;	// 0x57e05
- (id)_infoLabel;	// 0x57d89
- (id)_titleLabel;	// 0x57d0d
- (id)_subtitleLabel;	// 0x57c91
- (id)_backgroundImageView;	// 0x57c15
// declared property setter: - (void)setQuery:(id)query;	// 0x57bbd
// declared property setter: - (void)setTitle:(id)title;	// 0x57b65
// declared property setter: - (void)setSubtitle:(id)subtitle;	// 0x57b0d
// declared property setter: - (void)setStyle:(int)style;	// 0x57ae1
// declared property setter: - (void)setItem:(id)item;	// 0x57a89
// declared property setter: - (void)setArtworkImage:(id)image;	// 0x579e1
// declared property getter: - (id)artworkImage;	// 0x579c1
- (void)layoutSubviews;	// 0x57975
- (void)dealloc;	// 0x577c5
@end
