/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/IUPlaybackViewController.h>

@class UIImageView, UIImage, UIBarButtonItem;

@interface IUVideoPlaybackViewController : IUPlaybackViewController {
	UIBarButtonItem *_scaleModeButton;	// 248 = 0xf8
	double _currentTimeOnAppear;	// 252 = 0xfc
	double _restoredTimeOnAppear;	// 260 = 0x104
	UIImageView *_fillerImageView;	// 268 = 0x10c
	unsigned _fakeIsCurrentControllerToEnableOrientationNotifications : 1;	// 272 = 0x110
	unsigned _firstVideoFrameDisplayed : 1;	// 272 = 0x110
	unsigned _isDisappearingAndWillEndPlayback : 1;	// 272 = 0x110
	unsigned _showControlsWithFirstFrame : 1;	// 272 = 0x110
}
@property(readonly, assign, nonatomic) UIImage *videoSnapshot;	// G=0x9c1cd; 
@property(assign, nonatomic) BOOL showControlsWithFirstFrame;	// G=0x9e375; S=0x9e38d; @synthesize=_showControlsWithFirstFrame
@property(assign, nonatomic) double restoredTimeOnAppear;	// G=0x9e349; S=0x9e361; @synthesize=_restoredTimeOnAppear
@property(assign, nonatomic) double currentTimeOnAppear;	// G=0x9e31d; S=0x9e335; @synthesize=_currentTimeOnAppear
@property(retain, nonatomic) UIImage *fillerImage;	// G=0x9c169; S=0x9c189; 
// declared property setter: - (void)setShowControlsWithFirstFrame:(BOOL)firstFrame;	// 0x9e38d
// declared property getter: - (BOOL)showControlsWithFirstFrame;	// 0x9e375
// declared property setter: - (void)setRestoredTimeOnAppear:(double)appear;	// 0x9e361
// declared property getter: - (double)restoredTimeOnAppear;	// 0x9e349
// declared property setter: - (void)setCurrentTimeOnAppear:(double)appear;	// 0x9e335
// declared property getter: - (double)currentTimeOnAppear;	// 0x9e31d
- (id)_scaleModeButton;	// 0x9e239
- (void)_endPlayback;	// 0x9e1ed
- (void)_endPlaybackByPausing;	// 0x9e1a1
- (void)_validateInterfaceOrientation:(int *)orientation;	// 0x9e121
- (void)_removeFillerImageView;	// 0x9e0c5
- (void)_showFillerImageView;	// 0x9df2d
- (BOOL)_usingPhoneVideoOutMode;	// 0x9ded9
- (void)_serverDiedNotification:(id)notification;	// 0x9dec5
- (void)_firstVideoFrameDisplayedNotification:(id)notification;	// 0x9dd95
- (void)_applicationDidEnterBackgroundNotification:(id)_application;	// 0x9dd1d
- (void)_scaleModeButtonAction:(id)action;	// 0x9dcf9
- (void)viewControllerRequestsExit:(id)exit;	// 0x9dc89
- (BOOL)videoController:(id)controller tappedButtonPart:(unsigned)part;	// 0x9dba5
- (void)videoController:(id)controller scaleModeDidChange:(unsigned)scaleMode;	// 0x9db65
- (BOOL)_isSupportedInterfaceOrientation:(int)orientation;	// 0x9db1d
- (BOOL)restoreArchivedContexts:(id)contexts;	// 0x9d79d
- (id)copyArchivableContexts;	// 0x9d49d
- (BOOL)shouldArchiveCreateVideoSnapshot;	// 0x9d499
- (void)viewDidDisappear:(BOOL)view;	// 0x9d335
- (void)viewWillDisappear:(BOOL)view;	// 0x9cf81
- (void)_endOrPausePlayback;	// 0x9ceb9
- (void)viewDidAppear:(BOOL)view;	// 0x9cbf9
- (void)viewWillAppear:(BOOL)view;	// 0x9c9ad
- (BOOL)requireHUDVisible;	// 0x9c979
- (BOOL)isCurrentController;	// 0x9c931
- (id)title;	// 0x9c8d9
- (void)setOrientation:(int)orientation animated:(BOOL)animated;	// 0x9c86d
- (int)modalTransition;	// 0x9c849
- (void)loadView;	// 0x9c7c5
- (void)exitPlayerAnimated:(BOOL)animated;	// 0x9c631
- (id)createViewControllerForItem:(id)item interfaceOrientation:(int)orientation reusingController:(id)controller;	// 0x9c34d
// declared property getter: - (id)videoSnapshot;	// 0x9c1cd
// declared property setter: - (void)setFillerImage:(id)image;	// 0x9c189
// declared property getter: - (id)fillerImage;	// 0x9c169
- (void)dealloc;	// 0x9c065
- (id)init;	// 0x9be19
@end
