/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/IUModalContext.h>

@class NSMutableArray, NSString, NSMutableSet, IUiPodTabBarController;
@protocol IUModalContextDelegate, MediaPickerModalContextDelegate;

@interface MediaPickerModalContext : IUModalContext {
	NSString *_prompt;	// 24 = 0x18
	NSMutableArray *_pickedTracks;	// 28 = 0x1c
	int _mediaTypes;	// 32 = 0x20
	IUiPodTabBarController *_tabBarController;	// 36 = 0x24
	NSMutableSet *_pickedDataSourceActionRowSet;	// 40 = 0x28
	NSMutableSet *_pickedPersistentIDSet;	// 44 = 0x2c
	unsigned _allowsPickingMultipleItems : 1;	// 48 = 0x30
	unsigned _wantsNavigationButtons : 1;	// 48 = 0x30
}
@property(assign, nonatomic) id<IUModalContextDelegate, MediaPickerModalContextDelegate> delegate;	// @dynamic
@property(copy, nonatomic) NSString *prompt;	// G=0xbf3c1; S=0xbf365; 
@property(assign, nonatomic) BOOL wantsNavigationButtons;	// G=0xbf351; S=0xbf185; 
@property(assign, nonatomic) BOOL allowsPickingMultipleItems;	// G=0xbf171; S=0xbf14d; 
- (void)_cancelAction:(id)action;	// 0xc01ad
- (void)_doneAction:(id)action;	// 0xc0169
- (void)_addTracksForActionRowAtIndex:(unsigned)index dataSource:(id)source;	// 0xc0049
- (void)_addTrackAtIndex:(unsigned)index dataSource:(id)source;	// 0xbfff5
- (void)_addTracks:(id)tracks ignoringPickedEntities:(BOOL)entities;	// 0xbfdd1
- (id)_availableIdentifiersForMediaTypes:(int)mediaTypes;	// 0xbfd21
- (id)copyQueryForQuery:(id)query;	// 0xbfb75
- (void)dismissWithSuccess:(BOOL)success;	// 0xbfa01
- (void)handleSelectionForIndex:(unsigned)index dataSource:(id)source;	// 0xbf979
- (BOOL)canHandleSelectionForIndex:(unsigned)index dataSource:(id)source;	// 0xbf8f9
- (void)configureNavigationItem:(id)item;	// 0xbf7ad
- (BOOL)hideIndexBar;	// 0xbf799
- (void)configureCell:(id)cell forIndex:(unsigned)index dataSource:(id)source;	// 0xbf561
- (id)viewController;	// 0xbf43d
- (void)orderOut;	// 0xbf3d1
// declared property getter: - (id)prompt;	// 0xbf3c1
// declared property setter: - (void)setPrompt:(id)prompt;	// 0xbf365
// declared property getter: - (BOOL)wantsNavigationButtons;	// 0xbf351
// declared property setter: - (void)setWantsNavigationButtons:(BOOL)buttons;	// 0xbf185
// declared property getter: - (BOOL)allowsPickingMultipleItems;	// 0xbf171
// declared property setter: - (void)setAllowsPickingMultipleItems:(BOOL)items;	// 0xbf14d
- (void)dealloc;	// 0xbf079
- (id)initWithMediaTypes:(int)mediaTypes;	// 0xbf025
@end
