/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */

#import <iPodUI/IUMediaQueryNowPlayingItem.h>
#import <iPodUI/iPodUI-Structs.h>


@interface MediaQueryFakeNowPlayingItem : IUMediaQueryNowPlayingItem {
@private
	unsigned _countForQueueFeeder;	// 84 = 0x54
	double _currentTimeDisplayOverride;	// 88 = 0x58
}
@property(assign, nonatomic) double currentTimeDisplayOverride;	// G=0x554c5; S=0x554dd; @synthesize=_currentTimeDisplayOverride
@property(assign, nonatomic) unsigned countForQueueFeeder;	// G=0x554a5; S=0x554b5; @synthesize=_countForQueueFeeder
// declared property setter: - (void)setCurrentTimeDisplayOverride:(double)override;	// 0x554dd
// declared property getter: - (double)currentTimeDisplayOverride;	// 0x554c5
// declared property setter: - (void)setCountForQueueFeeder:(unsigned)queueFeeder;	// 0x554b5
// declared property getter: - (unsigned)countForQueueFeeder;	// 0x554a5
- (BOOL)isPlaceholderForItem:(id)item;	// 0x5541d
- (BOOL)isValidPlayerSubstituteForItem:(id)item;	// 0x55419
@end
