/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iPodUI.framework/iPodUI
 */




@protocol MPVideoTransferViewController <NSObject>
@optional
@property(assign, nonatomic) BOOL inhibitOverlay;
@required
- (id)videoView;
- (void)displayVideoView;
@optional
// declared property setter: - (void)setInhibitOverlay:(BOOL)overlay;
// declared property getter: - (BOOL)inhibitOverlay;
- (void)showOverlayAnimated:(BOOL)animated;
@end

