/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/BookmarkDAV.framework/BookmarkDAV
 */




@protocol CoreDAVTaskDelegate <NSObject>
@optional
- (void)task:(id)task didFinishWithError:(id)error;
@end

