/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PrintKit.framework/PrintKit
 */



@class NSMutableDictionary, PKPaper;

@interface PKPrintSettings : NSObject {
@private
	NSMutableDictionary *_dict;	// 4 = 0x4
	PKPaper *paper;	// 8 = 0x8
}
@property(retain, nonatomic) NSMutableDictionary *dict;	// G=0xb310; S=0xb6b4; @synthesize=_dict
@property(retain, nonatomic) PKPaper *paper;	// G=0xb2fc; S=0xb6e8; @synthesize
+ (id)default;	// 0xb404
+ (id)photo;	// 0xb5c4
+ (id)printSettingsForPrinter:(id)printer;	// 0xb4c0
- (void)dealloc;	// 0xb71c
- (id)init;	// 0xb324
- (id)settingsDict;	// 0xb2e8
- (void)setObject:(id)object forKey:(id)key;	// 0xb3a4
- (void)removeObjectForKey:(id)key;	// 0xb3c4
- (id)objectForKey:(id)key;	// 0xb3e4
// declared property getter: - (id)paper;	// 0xb2fc
// declared property setter: - (void)setPaper:(id)paper;	// 0xb6e8
// declared property getter: - (id)dict;	// 0xb310
// declared property setter: - (void)setDict:(id)dict;	// 0xb6b4
@end
