/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DABookmarkDAV.framework/DABookmarkDAV
 */




@protocol CoreDAVTaskGroupDelegate <NSObject>
@optional
- (void)taskGroup:(id)group didFinishWithError:(id)error;
@end

