/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/SoftwareUpdateServices.framework/SoftwareUpdateServices
 */

#import <SoftwareUpdateServices/XXUnknownSuperclass.h>

@class NSString;

@interface SUActivationStatusResponse : XXUnknownSuperclass {
@private
	BOOL _alive;	// 4 = 0x4
	int _messageType;	// 8 = 0x8
	NSString *_message;	// 12 = 0xc
}
@property(retain, nonatomic) NSString *message;	// G=0x15d21; S=0x15d31; @synthesize=_message
@property(assign, nonatomic) int messageType;	// G=0x15d55; S=0x15d65; @synthesize=_messageType
@property(assign, nonatomic, getter=isAlive) BOOL alive;	// G=0x15d01; S=0x15d11; @synthesize=_alive
// declared property setter: - (void)setMessageType:(int)type;	// 0x15d65
// declared property getter: - (int)messageType;	// 0x15d55
// declared property setter: - (void)setMessage:(id)message;	// 0x15d31
// declared property getter: - (id)message;	// 0x15d21
// declared property setter: - (void)setAlive:(BOOL)alive;	// 0x15d11
// declared property getter: - (BOOL)isAlive;	// 0x15d01
- (id)description;	// 0x15c75
- (void)dealloc;	// 0x15c29
@end
