/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PSListController.h>

@class PSSpecifier;

@interface PSListItemsController : PSListController {
	int _rowToSelect;	// 240 = 0xf0
	BOOL _deferItemSelection;	// 244 = 0xf4
	BOOL _restrictionList;	// 245 = 0xf5
	PSSpecifier *_lastSelectedSpecifier;	// 248 = 0xf8
}
@property(assign) BOOL isRestrictionList;	// G=0xa809; S=0xa819; converted property
- (void)viewWillAppear:(BOOL)view;	// 0xa829
- (void)scrollToSelectedCell;	// 0xb69d
- (void)setRowToSelect;	// 0xb529
- (void)setValueForSpecifier:(id)specifier defaultValue:(id)value;	// 0xb449
- (void)dealloc;	// 0xb3fd
- (void)viewWillDisappear:(BOOL)view;	// 0xb295
- (void)suspend;	// 0xb221
- (void)didLock;	// 0xb1ad
- (void)prepareSpecifiersMetadata;	// 0xb16d
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0xb0b1
- (void)listItemSelected:(id)selected;	// 0xaf45
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0xaf11
- (void)_addStaticText:(id)text;	// 0xae91
- (id)itemsFromParent;	// 0xac95
- (id)itemsFromDataSource;	// 0xa9a1
- (id)specifiers;	// 0xa901
// converted property getter: - (BOOL)isRestrictionList;	// 0xa809
// converted property setter: - (void)setIsRestrictionList:(BOOL)list;	// 0xa819
@end
