/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */




@protocol ISOperationDelegate <NSObject>
@optional
- (void)operationWillStart:(id)operation;
- (void)operationFinished:(id)finished;
- (void)operation:(id)operation updatedProgress:(id)progress;
- (void)operation:(id)operation failedWithError:(id)error;
@end

