/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/iTunesStoreUI-Structs.h>
#import <iTunesStoreUI/SUItemCellConfiguration.h>


@interface SUBannerCellConfiguration : SUItemCellConfiguration {
}
+ (float)rowHeightForContext:(id)context representedObject:(id)object;	// 0x224c1
+ (float)minimumRowHeight;	// 0x224b9
+ (id)copyDefaultContext;	// 0x221fd
- (CGSize)_imageSizeForLayoutSize:(CGSize)layoutSize;	// 0x22811
- (void)reloadStrings;	// 0x2280d
- (void)reloadLayoutInformation;	// 0x226f5
- (void)reloadImages;	// 0x225d5
- (void)reloadData;	// 0x225d1
- (void)reloadAfterArtworkLoad;	// 0x22591
- (id)copyImageDataProvider;	// 0x224ed
- (id)init;	// 0x221e9
@end
