/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */




@protocol SUCellConfigurationView <NSObject>
@property(assign, getter=isHighlighted) BOOL highlighted;	// converted property
- (void)reloadView;
// converted property setter: - (void)setHighlighted:(BOOL)highlighted;
// converted property getter: - (BOOL)isHighlighted;
- (BOOL)highlightsOnlyContentView;
@end

