/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/iTunesStoreUI-Structs.h>
#import <iTunesStoreUI/NSCopying.h>
#import <iTunesStoreUI/XXUnknownSuperclass.h>

@class SUImageModifier, UIColor;

@interface SUImageDataProvider : XXUnknownSuperclass <NSCopying> {
	UIColor *_fillColor;	// 36 = 0x24
	CGSize _finalSize;	// 40 = 0x28
	float _inputImageScale;	// 48 = 0x30
	SUImageModifier *_modifier;	// 52 = 0x34
}
@property(retain) SUImageModifier *modifier;	// G=0x20c9d; S=0x20cb1; @synthesize=_modifier
@property(assign) float inputImageScale;	// G=0x20c7d; S=0x20c8d; @synthesize=_inputImageScale
@property(assign) CGSize finalSize;	// G=0x20c4d; S=0x20c69; @synthesize=_finalSize
@property(retain) UIColor *fillColor;	// G=0x20c15; S=0x20c29; @synthesize=_fillColor
// declared property setter: - (void)setModifier:(id)modifier;	// 0x20cb1
// declared property getter: - (id)modifier;	// 0x20c9d
// declared property setter: - (void)setInputImageScale:(float)scale;	// 0x20c8d
// declared property getter: - (float)inputImageScale;	// 0x20c7d
// declared property setter: - (void)setFinalSize:(CGSize)size;	// 0x20c69
// declared property getter: - (CGSize)finalSize;	// 0x20c4d
// declared property setter: - (void)setFillColor:(id)color;	// 0x20c29
// declared property getter: - (id)fillColor;	// 0x20c15
- (void)_getFinalSize:(CGSize *)size imageFrame:(CGRect *)frame forImage:(id)image withModifier:(id)modifier;	// 0x209e5
- (BOOL)parseData:(id)data returningError:(id *)error;	// 0x208c5
- (id)newImageFromImage:(id)image;	// 0x2051d
- (BOOL)isEqual:(id)equal;	// 0x203f1
- (unsigned)hash;	// 0x203c5
- (id)copyWithZone:(NSZone *)zone;	// 0x20311
- (void)dealloc;	// 0x202b9
@end
