/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/XXUnknownSuperclass.h>

@class CLLocation, SUSectionsResponse;

@interface SULocationSectionsOperation : XXUnknownSuperclass {
	CLLocation *_location;	// 60 = 0x3c
	SUSectionsResponse *_sectionsResponse;	// 64 = 0x40
	int _updateDistance;	// 68 = 0x44
}
@property(readonly, assign) int updateDistance;	// G=0x3da19; 
@property(readonly, assign) SUSectionsResponse *sectionsResponse;	// G=0x3d951; 
@property(retain) CLLocation *location;	// G=0x3d8f1; S=0x3d9b1; 
- (void)_setUpdateDistance:(int)distance;	// 0x3e031
- (void)_setSectionsResponse:(id)response;	// 0x3dfc9
- (id)_copyBaseOperation;	// 0x3dcc1
- (void)run;	// 0x3da55
// declared property getter: - (int)updateDistance;	// 0x3da19
// declared property setter: - (void)setLocation:(id)location;	// 0x3d9b1
// declared property getter: - (id)sectionsResponse;	// 0x3d951
// declared property getter: - (id)location;	// 0x3d8f1
- (void)dealloc;	// 0x3d891
@end
