/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/SUScriptObject.h>
#import <iTunesStoreUI/iTunesStoreUI-Structs.h>

@class NSString, NSArray, NSNumber, SUScriptABRecord;

@interface SUScriptAddressBook : SUScriptObject {
	BOOL _databaseAccess;	// 36 = 0x24
	void *_observedAddressBook;	// 40 = 0x28
}
@property(readonly, assign) int sourceTypeMobileMe;	// G=0xa4a8d; 
@property(readonly, assign) int sourceTypeLocal;	// G=0xa4a89; 
@property(readonly, assign) int sourceTypeLDAP;	// G=0xa4a81; 
@property(readonly, assign) int sourceTypeExchangeGAL;	// G=0xa4a79; 
@property(readonly, assign) int sourceTypeExchange;	// G=0xa4a75; 
@property(readonly, assign) int sourceTypeCardDAVSearch;	// G=0xa4a6d; 
@property(readonly, assign) int sourceTypeCardDAV;	// G=0xa4a69; 
@property(readonly, assign) int sortOrderByLastName;	// G=0xa4a65; 
@property(readonly, assign) int sortOrderByFirstName;	// G=0xa4a61; 
@property(readonly, assign) int searchScopeRemote;	// G=0xa4a5d; 
@property(readonly, assign) int searchScopeRecent;	// G=0xa4a59; 
@property(readonly, assign) int searchScopeLocal;	// G=0xa4a55; 
@property(readonly, assign) int recordTypeSource;	// G=0xa4a51; 
@property(readonly, assign) int recordTypePerson;	// G=0xa4a4d; 
@property(readonly, assign) int recordTypeGroup;	// G=0xa4a49; 
@property(readonly, assign) unsigned propertyTypeString;	// G=0xa4a21; 
@property(readonly, assign) unsigned propertyTypeReal;	// G=0xa4a1d; 
@property(readonly, assign) unsigned propertyTypeMultiString;	// G=0xa4a15; 
@property(readonly, assign) unsigned propertyTypeMultiReal;	// G=0xa4a0d; 
@property(readonly, assign) unsigned propertyTypeMultiInteger;	// G=0xa4a05; 
@property(readonly, assign) unsigned propertyTypeMultiDictionary;	// G=0xa49fd; 
@property(readonly, assign) unsigned propertyTypeMultiDateTime;	// G=0xa49f5; 
@property(readonly, assign) unsigned propertyTypeInvalid;	// G=0xa49f1; 
@property(readonly, assign) unsigned propertyTypeInteger;	// G=0xa49ed; 
@property(readonly, assign) unsigned propertyTypeDictionary;	// G=0xa49e9; 
@property(readonly, assign) unsigned propertyTypeDateTime;	// G=0xa49e5; 
@property(readonly, assign) int propertySourceType;	// G=0xa499d; 
@property(readonly, assign) int propertySourceName;	// G=0xa4979; 
@property(readonly, assign) int propertyGroupName;	// G=0xa47ed; 
@property(readonly, assign) int propertyURL;	// G=0xa4a25; 
@property(readonly, assign) int propertySuffix;	// G=0xa49c1; 
@property(readonly, assign) int propertyRelatedNames;	// G=0xa4955; 
@property(readonly, assign) int propertyPhoneNumber;	// G=0xa490d; 
@property(readonly, assign) int propertyPrefix;	// G=0xa4931; 
@property(readonly, assign) int propertyOrganization;	// G=0xa48e9; 
@property(readonly, assign) int propertyNickname;	// G=0xa48c5; 
@property(readonly, assign) int propertyMiddleName;	// G=0xa48a1; 
@property(readonly, assign) int propertyLastName;	// G=0xa487d; 
@property(readonly, assign) int propertyKind;	// G=0xa4835; 
@property(readonly, assign) int propertyJobTitle;	// G=0xa4859; 
@property(readonly, assign) int propertyInstantMessage;	// G=0xa4811; 
@property(readonly, assign) int propertyFirstName;	// G=0xa47c9; 
@property(readonly, assign) int propertyEmail;	// G=0xa47a5; 
@property(readonly, assign) int propertyDepartment;	// G=0xa4781; 
@property(readonly, assign) int propertyBirthday;	// G=0xa475d; 
@property(readonly, assign) int propertyAddress;	// G=0xa4721; 
@property(readonly, assign) NSString *labelWork;	// G=0xa4701; 
@property(readonly, assign) NSString *labelSpouse;	// G=0xa46e1; 
@property(readonly, assign) NSString *labelSister;	// G=0xa46c1; 
@property(readonly, assign) NSString *labelPartner;	// G=0xa46a1; 
@property(readonly, assign) NSString *labelOther;	// G=0xa4681; 
@property(readonly, assign) NSString *labelPhoneWorkFAX;	// G=0xa4661; 
@property(readonly, assign) NSString *labelPhonePager;	// G=0xa4641; 
@property(readonly, assign) NSString *labelPhoneMobile;	// G=0xa4621; 
@property(readonly, assign) NSString *labelPhoneMain;	// G=0xa4601; 
@property(readonly, assign) NSString *labelPhoneIPhone;	// G=0xa45e1; 
@property(readonly, assign) NSString *labelPhoneHomeFAX;	// G=0xa45c1; 
@property(readonly, assign) NSString *labelParent;	// G=0xa45a1; 
@property(readonly, assign) NSString *labelMother;	// G=0xa4581; 
@property(readonly, assign) NSString *labelManager;	// G=0xa4561; 
@property(readonly, assign) NSString *labelHomePage;	// G=0xa4541; 
@property(readonly, assign) NSString *labelHome;	// G=0xa4521; 
@property(readonly, assign) NSString *labelFriend;	// G=0xa4501; 
@property(readonly, assign) NSString *labelFather;	// G=0xa44e1; 
@property(readonly, assign) NSString *labelChild;	// G=0xa44c1; 
@property(readonly, assign) NSString *labelBrother;	// G=0xa44a1; 
@property(readonly, assign) NSString *labelAssistant;	// G=0xa4481; 
@property(readonly, assign) NSString *kindPerson;	// G=0xa4461; 
@property(readonly, assign) NSString *kindOrganization;	// G=0xa4441; 
@property(readonly, assign) NSString *instantMessageServiceYahoo;	// G=0xa4421; 
@property(readonly, assign) NSString *instantMessageServiceMSN;	// G=0xa4401; 
@property(readonly, assign) NSString *instantMessageServiceJabber;	// G=0xa43e1; 
@property(readonly, assign) NSString *instantMessageServiceICQ;	// G=0xa43c1; 
@property(readonly, assign) NSString *instantMessageServiceAIM;	// G=0xa43a1; 
@property(readonly, assign) NSString *instantMessageKeyUsername;	// G=0xa4381; 
@property(readonly, assign) NSString *instantMessageKeyService;	// G=0xa4361; 
@property(readonly, assign) int imageFormatThumbnail;	// G=0xa435d; 
@property(readonly, assign) int imageFormatOriginal;	// G=0xa4359; 
@property(readonly, assign) NSString *addressKeyZipCode;	// G=0xa4339; 
@property(readonly, assign) NSString *addressKeyStreet;	// G=0xa4319; 
@property(readonly, assign) NSString *addressKeyState;	// G=0xa42f9; 
@property(readonly, assign) NSString *addressKeyCountryCode;	// G=0xa42d9; 
@property(readonly, assign) NSString *addressKeyCountry;	// G=0xa42b9; 
@property(readonly, assign) NSString *addressKeyCity;	// G=0xa4281; 
@property(readonly, assign) NSArray *sources;	// G=0xa4149; 
@property(readonly, assign) NSArray *people;	// G=0xa407d; 
@property(readonly, assign) NSNumber *numberOfPeopleInAddressBook;	// G=0xa3fd9; 
@property(readonly, assign) NSNumber *numberOfGroupsInAddressBook;	// G=0xa3f35; 
@property(readonly, assign) NSArray *groups;	// G=0xa3e69; 
@property(readonly, assign) SUScriptABRecord *defaultSource;	// G=0xa3d95; 
@property(readonly, assign) int defaultSortOrder;	// G=0xa3d91; 
+ (void)initialize;	// 0xa4bed
+ (id)webScriptNameForSelector:(SEL)selector;	// 0xa4b35
+ (id)webScriptNameForKey:(const char *)key;	// 0xa4a91
+ (void *)threadAddressBook;	// 0xa3325
+ (id)newScriptValueForNativeValue:(void *)nativeValue propertyType:(unsigned)type;	// 0xa327d
+ (id)newScriptRecordsForNativeRecords:(CFArrayRef)nativeRecords;	// 0xa31c1
- (id)scriptAttributeKeys;	// 0xa4b8d
- (id)attributeKeys;	// 0xa4b7d
// declared property getter: - (int)sourceTypeMobileMe;	// 0xa4a8d
// declared property getter: - (int)sourceTypeLocal;	// 0xa4a89
// declared property getter: - (int)sourceTypeLDAP;	// 0xa4a81
// declared property getter: - (int)sourceTypeExchangeGAL;	// 0xa4a79
// declared property getter: - (int)sourceTypeExchange;	// 0xa4a75
// declared property getter: - (int)sourceTypeCardDAVSearch;	// 0xa4a6d
// declared property getter: - (int)sourceTypeCardDAV;	// 0xa4a69
// declared property getter: - (int)sortOrderByLastName;	// 0xa4a65
// declared property getter: - (int)sortOrderByFirstName;	// 0xa4a61
// declared property getter: - (int)searchScopeRemote;	// 0xa4a5d
// declared property getter: - (int)searchScopeRecent;	// 0xa4a59
// declared property getter: - (int)searchScopeLocal;	// 0xa4a55
// declared property getter: - (int)recordTypeSource;	// 0xa4a51
// declared property getter: - (int)recordTypePerson;	// 0xa4a4d
// declared property getter: - (int)recordTypeGroup;	// 0xa4a49
// declared property getter: - (int)propertyURL;	// 0xa4a25
// declared property getter: - (unsigned)propertyTypeString;	// 0xa4a21
// declared property getter: - (unsigned)propertyTypeReal;	// 0xa4a1d
// declared property getter: - (unsigned)propertyTypeMultiString;	// 0xa4a15
// declared property getter: - (unsigned)propertyTypeMultiReal;	// 0xa4a0d
// declared property getter: - (unsigned)propertyTypeMultiInteger;	// 0xa4a05
// declared property getter: - (unsigned)propertyTypeMultiDictionary;	// 0xa49fd
// declared property getter: - (unsigned)propertyTypeMultiDateTime;	// 0xa49f5
// declared property getter: - (unsigned)propertyTypeInvalid;	// 0xa49f1
// declared property getter: - (unsigned)propertyTypeInteger;	// 0xa49ed
// declared property getter: - (unsigned)propertyTypeDictionary;	// 0xa49e9
// declared property getter: - (unsigned)propertyTypeDateTime;	// 0xa49e5
// declared property getter: - (int)propertySuffix;	// 0xa49c1
// declared property getter: - (int)propertySourceType;	// 0xa499d
// declared property getter: - (int)propertySourceName;	// 0xa4979
// declared property getter: - (int)propertyRelatedNames;	// 0xa4955
// declared property getter: - (int)propertyPrefix;	// 0xa4931
// declared property getter: - (int)propertyPhoneNumber;	// 0xa490d
// declared property getter: - (int)propertyOrganization;	// 0xa48e9
// declared property getter: - (int)propertyNickname;	// 0xa48c5
// declared property getter: - (int)propertyMiddleName;	// 0xa48a1
// declared property getter: - (int)propertyLastName;	// 0xa487d
// declared property getter: - (int)propertyJobTitle;	// 0xa4859
// declared property getter: - (int)propertyKind;	// 0xa4835
// declared property getter: - (int)propertyInstantMessage;	// 0xa4811
// declared property getter: - (int)propertyGroupName;	// 0xa47ed
// declared property getter: - (int)propertyFirstName;	// 0xa47c9
// declared property getter: - (int)propertyEmail;	// 0xa47a5
// declared property getter: - (int)propertyDepartment;	// 0xa4781
// declared property getter: - (int)propertyBirthday;	// 0xa475d
// declared property getter: - (int)propertyAddress;	// 0xa4721
// declared property getter: - (id)labelWork;	// 0xa4701
// declared property getter: - (id)labelSpouse;	// 0xa46e1
// declared property getter: - (id)labelSister;	// 0xa46c1
// declared property getter: - (id)labelPartner;	// 0xa46a1
// declared property getter: - (id)labelOther;	// 0xa4681
// declared property getter: - (id)labelPhoneWorkFAX;	// 0xa4661
// declared property getter: - (id)labelPhonePager;	// 0xa4641
// declared property getter: - (id)labelPhoneMobile;	// 0xa4621
// declared property getter: - (id)labelPhoneMain;	// 0xa4601
// declared property getter: - (id)labelPhoneIPhone;	// 0xa45e1
// declared property getter: - (id)labelPhoneHomeFAX;	// 0xa45c1
// declared property getter: - (id)labelParent;	// 0xa45a1
// declared property getter: - (id)labelMother;	// 0xa4581
// declared property getter: - (id)labelManager;	// 0xa4561
// declared property getter: - (id)labelHomePage;	// 0xa4541
// declared property getter: - (id)labelHome;	// 0xa4521
// declared property getter: - (id)labelFriend;	// 0xa4501
// declared property getter: - (id)labelFather;	// 0xa44e1
// declared property getter: - (id)labelChild;	// 0xa44c1
// declared property getter: - (id)labelBrother;	// 0xa44a1
// declared property getter: - (id)labelAssistant;	// 0xa4481
// declared property getter: - (id)kindPerson;	// 0xa4461
// declared property getter: - (id)kindOrganization;	// 0xa4441
// declared property getter: - (id)instantMessageServiceYahoo;	// 0xa4421
// declared property getter: - (id)instantMessageServiceMSN;	// 0xa4401
// declared property getter: - (id)instantMessageServiceJabber;	// 0xa43e1
// declared property getter: - (id)instantMessageServiceICQ;	// 0xa43c1
// declared property getter: - (id)instantMessageServiceAIM;	// 0xa43a1
// declared property getter: - (id)instantMessageKeyUsername;	// 0xa4381
// declared property getter: - (id)instantMessageKeyService;	// 0xa4361
// declared property getter: - (int)imageFormatThumbnail;	// 0xa435d
// declared property getter: - (int)imageFormatOriginal;	// 0xa4359
// declared property getter: - (id)addressKeyZipCode;	// 0xa4339
// declared property getter: - (id)addressKeyStreet;	// 0xa4319
// declared property getter: - (id)addressKeyState;	// 0xa42f9
// declared property getter: - (id)addressKeyCountryCode;	// 0xa42d9
// declared property getter: - (id)addressKeyCountry;	// 0xa42b9
// declared property getter: - (id)addressKeyCity;	// 0xa4281
// declared property getter: - (id)sources;	// 0xa4149
// declared property getter: - (id)people;	// 0xa407d
// declared property getter: - (id)numberOfPeopleInAddressBook;	// 0xa3fd9
// declared property getter: - (id)numberOfGroupsInAddressBook;	// 0xa3f35
// declared property getter: - (id)groups;	// 0xa3e69
// declared property getter: - (id)defaultSource;	// 0xa3d95
// declared property getter: - (int)defaultSortOrder;	// 0xa3d91
- (id)_className;	// 0xa3d85
- (id)sourceWithRecordID:(id)recordID;	// 0xa3c59
- (id)searchResultsViewControllerWithOptions:(id)options;	// 0xa3bb9
- (id)personWithRecordID:(id)recordID;	// 0xa3a8d
- (id)peopleWithName:(id)name;	// 0xa3959
- (id)peopleInSource:(id)source withSortOrder:(id)sortOrder;	// 0xa3769
- (id)peoplePickerWithOptions:(id)options;	// 0xa36c9
- (id)localizedLabelForLabel:(id)label;	// 0xa3625
- (id)groupWithRecordID:(id)recordID;	// 0xa34f9
- (id)groupsInSource:(id)source;	// 0xa33ad
- (void)dealloc;	// 0xa2fed
- (id)initWithDatabaseAccess:(BOOL)databaseAccess;	// 0xa2e89
- (id)init;	// 0xa2e75
@end
