/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/SUScriptMediaItemCollection.h>

@class MPMediaPlaylist;

@interface SUScriptMediaPlaylist : SUScriptMediaItemCollection {
}
@property(readonly, assign, nonatomic) MPMediaPlaylist *nativePlaylist;	// G=0x7c84d; 
+ (void)initialize;	// 0x7ccdd
+ (id)webScriptNameForSelector:(SEL)selector;	// 0x7cc95
+ (id)scriptPropertyForNativeProperty:(id)nativeProperty;	// 0x7c7f9
+ (id)scriptPlaylistAttributesForNativePlaylistAttributes:(int)nativePlaylistAttributes;	// 0x7c771
+ (id)nativePropertyForScriptProperty:(id)scriptProperty;	// 0x7c71d
+ (int)nativePlaylistAttributesForScriptPlaylistAttributes:(id)scriptPlaylistAttributes;	// 0x7c651
- (id)_valueForProperty:(id)property;	// 0x7cb79
- (id)_className;	// 0x7cb6d
- (id)valueForProperty:(id)property;	// 0x7c875
// declared property getter: - (id)nativePlaylist;	// 0x7c84d
@end
