/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/SUScriptNativeObject.h>
#import <iTunesStoreUI/iTunesStoreUI-Structs.h>
#import <iTunesStoreUI/SUScriptTextFieldDelegate.h>

@class UITextField, SUScriptTextFieldDelegate;

@interface SUScriptTextFieldNativeObject : SUScriptNativeObject <SUScriptTextFieldDelegate> {
	SUScriptTextFieldDelegate *_textFieldDelegate;	// 20 = 0x14
}
@property(readonly, assign, nonatomic) UITextField *textField;	// G=0x4cb0d; 
- (void)_textDidEndEditingOnExit:(id)_text;	// 0x4cea1
- (void)_textDidChange:(id)_text;	// 0x4ce6d
- (BOOL)textFieldShouldBeginEditing:(id)textField;	// 0x4ce45
- (void)textFieldDidEndEditing:(id)textField;	// 0x4ce11
- (void)textFieldDidBeginEditing:(id)textField;	// 0x4cddd
- (void)setupNativeObject;	// 0x4cc59
- (void)destroyNativeObject;	// 0x4cb71
// declared property getter: - (id)textField;	// 0x4cb0d
- (void)dealloc;	// 0x4caa9
@end
