/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/XXUnknownSuperclass.h>
#import <iTunesStoreUI/SUScriptTextFieldDelegate.h>
#import <iTunesStoreUI/UITableViewDataSource.h>
#import <iTunesStoreUI/UITableViewDelegate.h>
#import <iTunesStoreUI/iTunesStoreUI-Structs.h>
#import <iTunesStoreUI/UISearchDisplayDelegate.h>
#import <iTunesStoreUI/ISStoreURLOperationDelegate.h>

@class NSArray, SUScriptTextFieldDelegate, SUSearchDisplayController, ISStoreURLOperation, UISearchBar, UIViewController, SUSearchFieldConfiguration;

@interface SUSearchFieldController : XXUnknownSuperclass <ISStoreURLOperationDelegate, SUScriptTextFieldDelegate, UISearchDisplayDelegate, UITableViewDataSource, UITableViewDelegate> {
@private
	NSArray *_completions;	// 4 = 0x4
	ISStoreURLOperation *_completionsOperation;	// 8 = 0x8
	SUSearchFieldConfiguration *_configuration;	// 12 = 0xc
	UIViewController *_dimmerViewController;	// 16 = 0x10
	UISearchBar *_searchBar;	// 20 = 0x14
	SUSearchDisplayController *_searchController;	// 24 = 0x18
	int _searchFieldStyle;	// 28 = 0x1c
	SUScriptTextFieldDelegate *_textFieldDelegate;	// 32 = 0x20
}
@property(assign, nonatomic) int searchFieldStyle;	// G=0x9bb85; S=0x9a1e9; @synthesize=_searchFieldStyle
@property(copy, nonatomic) SUSearchFieldConfiguration *searchFieldConfiguration;	// G=0x9bb75; S=0x9a191; @synthesize=_configuration
@property(readonly, assign, nonatomic) UISearchBar *searchBar;	// G=0x9a149; 
@property(readonly, assign, nonatomic, getter=isActive) BOOL active;	// G=0x9a125; 
// declared property getter: - (int)searchFieldStyle;	// 0x9bb85
// declared property getter: - (id)searchFieldConfiguration;	// 0x9bb75
- (void)_tearDownDimmerView;	// 0x9ba81
- (id)_targetViewController;	// 0x9b929
- (void)_showDimmerView;	// 0x9b599
- (void)_saveSearchTermToDefaults:(id)defaults;	// 0x9b4cd
- (void)_reloadSearchBar;	// 0x9b319
- (void)_reloadCompletionsForSearchString:(id)searchString;	// 0x9b28d
- (id)_newTransientViewController;	// 0x9b1f9
- (id)_newSearchDisplayControllerWithContentsController:(id)contentsController;	// 0x9b119
- (id)_newSearchBar;	// 0x9b0a5
- (id)_newBlankStorePageViewController;	// 0x9b03d
- (BOOL)_focusTransientViewController;	// 0x9af0d
- (void)_fetchResultsForURLRequestProperties:(id)urlrequestProperties;	// 0x9ae59
- (void)_fetchResultsForURL:(id)url;	// 0x9ade9
- (void)_fetchResultsForTerm:(id)term;	// 0x9ad59
- (void)_fetchCompletions;	// 0x9ab95
- (id)_defaultSearchTerm;	// 0x9ab39
- (void)_cancelCompletionsOperation;	// 0x9aab1
- (id)_cancelButtonView;	// 0x9a9e9
- (void)_savedSearchTermChangedNotification:(id)notification;	// 0x9a949
- (void)_dimmerViewAction:(id)action;	// 0x9a929
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x9a909
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x9a81d
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x9a735
- (BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;	// 0x9a6fd
- (void)searchBarTextDidEndEditing:(id)searchBarText;	// 0x9a6c1
- (BOOL)searchBarShouldEndEditing:(id)searchBar;	// 0x9a571
- (BOOL)searchBarShouldBeginEditing:(id)searchBar;	// 0x9a501
- (void)searchBarSearchButtonClicked:(id)clicked;	// 0x9a46d
- (void)scriptDidChangeTextForTextField:(id)script;	// 0x9a431
- (void)operationDidFinish:(id)operation;	// 0x9a3ed
- (void)operation:(id)operation finishedWithOutput:(id)output;	// 0x9a36d
- (void)operation:(id)operation failedWithError:(id)error;	// 0x9a329
// declared property setter: - (void)setSearchFieldStyle:(int)style;	// 0x9a1e9
// declared property setter: - (void)setSearchFieldConfiguration:(id)configuration;	// 0x9a191
// declared property getter: - (id)searchBar;	// 0x9a149
// declared property getter: - (BOOL)isActive;	// 0x9a125
- (void)handleSearchURL:(id)url;	// 0x99f9d
- (void)dealloc;	// 0x99dd5
- (id)initWithContentsController:(id)contentsController;	// 0x99c69
- (id)init;	// 0x99c55
@end
