/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/iTunesStoreUI-Structs.h>
#import <iTunesStoreUI/SUStorePageViewController.h>


@interface SUSearchRootStorePageViewController : SUStorePageViewController {
}
- (void)viewWillDisappear:(BOOL)view;	// 0xd39d5
- (void)setSection:(id)section;	// 0xd3981
- (void)setParentViewController:(id)controller;	// 0xd38ed
- (void)resetNavigationItem:(id)item;	// 0xd38ad
- (id)copyArchivableContext;	// 0xd3869
- (void)reloadCancelBarButtonItem;	// 0xd36bd
@end
