/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/XXUnknownSuperclass.h>

@class SUNavigationItem, UIBarButtonItem, UIView;

@interface SUSecondaryButtonTitleView : XXUnknownSuperclass {
	UIBarButtonItem *_buttonItem;	// 48 = 0x30
	UIView *_buttonItemView;	// 52 = 0x34
	SUNavigationItem *_navigationItem;	// 56 = 0x38
	UIView *_titleView;	// 60 = 0x3c
	BOOL _titleViewIsCustom;	// 64 = 0x40
}
@property(retain, nonatomic) UIView *titleView;	// G=0x9d701; S=0x9d2bd; @synthesize=_titleView
@property(assign, nonatomic, getter=isCustomTitleView) BOOL customTitleView;	// G=0x9d6c1; S=0x9d6d1; @synthesize=_titleViewIsCustom
@property(retain, nonatomic) UIBarButtonItem *buttonItem;	// G=0x9d6b1; S=0x9d155; @synthesize=_buttonItem
@property(assign, nonatomic) SUNavigationItem *navigationItem;	// G=0x9d6e1; S=0x9d6f1; @synthesize=_navigationItem
// declared property getter: - (id)titleView;	// 0x9d701
// declared property setter: - (void)setNavigationItem:(id)item;	// 0x9d6f1
// declared property getter: - (id)navigationItem;	// 0x9d6e1
// declared property setter: - (void)setCustomTitleView:(BOOL)view;	// 0x9d6d1
// declared property getter: - (BOOL)isCustomTitleView;	// 0x9d6c1
// declared property getter: - (id)buttonItem;	// 0x9d6b1
- (void)sizeToFit;	// 0x9d5e5
- (void)layoutSubviews;	// 0x9d345
// declared property setter: - (void)setTitleView:(id)view;	// 0x9d2bd
// declared property setter: - (void)setButtonItem:(id)item;	// 0x9d155
- (void)dealloc;	// 0x9d0e1
- (id)initWithNavigationItem:(id)navigationItem;	// 0x9d06d
- (id)init;	// 0x9d059
@end
