/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/SUScriptNativeObject.h>
#import <iTunesStoreUI/ISOperationDelegate.h>
#import <iTunesStoreUI/XXUnknownSuperclass.h>

@class UIViewController, SUViewControllerFactory, SUNavigationItem, SURotationController, SUViewControllerContext, NSString, SUViewControllerScriptProperties, NSMutableArray;

@interface SUViewController : XXUnknownSuperclass <SUScriptNativeObject, ISOperationDelegate> {
	SUViewControllerScriptProperties *_cachedScriptProperties;	// 152 = 0x98
	BOOL _canBeWeakScriptReference;	// 156 = 0x9c
	NSMutableArray *_cancelOnDeallocOperations;	// 160 = 0xa0
	BOOL _excludeFromNavigationHistory;	// 164 = 0xa4
	UIViewController *_footerViewController;	// 168 = 0xa8
	UIViewController *_inputAccessoryViewController;	// 172 = 0xac
	BOOL _isEnteringForeground;	// 176 = 0xb0
	BOOL _loading;	// 177 = 0xb1
	SUViewControllerContext *_memoryPurgeContext;	// 180 = 0xb4
	NSMutableArray *_operations;	// 184 = 0xb8
	NSMutableArray *_pendingDialogs;	// 188 = 0xbc
	SUViewControllerContext *_restoredContext;	// 192 = 0xc0
	SURotationController *_rotationController;	// 196 = 0xc4
	int _rotationState;	// 200 = 0xc8
	BOOL _shouldInvalidateForMemoryPurge;	// 204 = 0xcc
	int _transitionSafetyCount;	// 208 = 0xd0
}
@property(readonly, assign, nonatomic) SUViewControllerFactory *viewControllerFactory;	// G=0xd6f1; 
@property(readonly, assign, nonatomic) SUNavigationItem *navigationItem;	// G=0xda51; @dynamic
@property(readonly, assign, nonatomic) NSString *defaultPNGName;	// G=0xc8bd; 
@property(readonly, assign, nonatomic) double defaultPNGExpirationTime;	// G=0xc889; 
@property(readonly, assign, nonatomic, getter=isVisibleAndFrontmost) BOOL visibleAndFrontmost;	// G=0xcda5; 
@property(readonly, assign, nonatomic, getter=isVisible) BOOL visible;	// G=0xccd1; 
@property(assign, nonatomic) BOOL shouldInvalidateForMemoryPurge;	// G=0xd5cd; S=0xf40d; @synthesize=_shouldInvalidateForMemoryPurge
@property(assign, nonatomic) BOOL shouldExcludeFromNavigationHistory;	// G=0xf3ed; S=0xf3fd; @synthesize=_excludeFromNavigationHistory
@property(retain, nonatomic) UIViewController *inputAccessoryViewController;	// G=0xf3cd; S=0xd2fd; @synthesize=_inputAccessoryViewController
@property(readonly, assign, nonatomic) UIViewController *footerViewController;	// G=0xf3bd; @synthesize=_footerViewController
@property(assign, nonatomic, getter=isLoading) BOOL loading;	// G=0xf3dd; S=0xd3b1; @synthesize=_loading
// declared property setter: - (void)setShouldInvalidateForMemoryPurge:(BOOL)invalidateForMemoryPurge;	// 0xf40d
// declared property setter: - (void)setShouldExcludeFromNavigationHistory:(BOOL)excludeFromNavigationHistory;	// 0xf3fd
// declared property getter: - (BOOL)shouldExcludeFromNavigationHistory;	// 0xf3ed
// declared property getter: - (BOOL)isLoading;	// 0xf3dd
// declared property getter: - (id)inputAccessoryViewController;	// 0xf3cd
// declared property getter: - (id)footerViewController;	// 0xf3bd
- (void)_keyboardWillShowNotification:(id)_keyboard;	// 0xf341
- (void)_keyboardWillHideNotification:(id)_keyboard;	// 0xf2c5
- (void)_keyboardDidShowNotification:(id)_keyboard;	// 0xf249
- (void)_keyboardDidHideNotification:(id)_keyboard;	// 0xf1cd
- (void)_dialogFinishedNotification:(id)notification;	// 0xf13d
- (void)_applicationWillEnterForegroundNotification:(id)_application;	// 0xf09d
- (void)_applicationDidEnterBackgroundNotification:(id)_application;	// 0xf05d
- (void)operationFinished:(id)finished;	// 0xf005
- (void)operation:(id)operation failedWithError:(id)error;	// 0xefad
- (void)_presentFooterAnimationDidStop;	// 0xef59
- (void)_dismissFooterAnimationDidStop:(id)_dismissFooterAnimation;	// 0xee4d
- (BOOL)clearsWeakScriptReferences;	// 0xee3d
- (BOOL)_shouldUseDefaultFirstResponder;	// 0xedf1
- (id)inputAccessoryView;	// 0xed89
- (BOOL)canBecomeFirstResponder;	// 0xed3d
- (BOOL)becomeFirstResponder;	// 0xecf1
- (BOOL)window:(id)window shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;	// 0xeaa1
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xe971
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xe829
- (id)_rotationController;	// 0xe7f1
- (void)_performScheduledRotation:(id)rotation;	// 0xe73d
- (BOOL)_isSupportedInterfaceOrientation:(int)orientation;	// 0xe6f5
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0xe595
- (void)viewWillDisappear:(BOOL)view;	// 0xe435
- (void)viewWillAppear:(BOOL)view;	// 0xe2ad
- (void)viewDidDisappear:(BOOL)view;	// 0xe14d
- (void)viewDidAppear:(BOOL)view;	// 0xdf31
- (void)storePageProtocolDidChange;	// 0xdec9
- (void)setTitle:(id)title;	// 0xde1d
- (void)setParentViewController:(id)controller;	// 0xdd1d
- (void)_setExistingNavigationItem:(id)item;	// 0xdcf1
- (void)restoreArchivableContext:(id)context;	// 0xdc75
- (void)resetRestoredContext;	// 0xdc21
- (void)purgeMemoryForReason:(int)reason;	// 0xdba1
- (int)_preferredInterfaceOrientationGivenCurrentOrientation:(int)orientation;	// 0xdae9
// declared property getter: - (id)navigationItem;	// 0xda51
- (id)moreListSelectedImage;	// 0xda29
- (id)moreListImage;	// 0xda01
- (void)loadView;	// 0xd939
- (int)interfaceOrientation;	// 0xd8b1
- (id)_existingNavigationItem;	// 0xd885
- (id)copyArchivableContext;	// 0xd7cd
- (BOOL)_canReloadView;	// 0xd779
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;	// 0xd775
- (void)applicationWillSuspend;	// 0xd771
- (void)applicationDidResume;	// 0xd76d
// declared property getter: - (id)viewControllerFactory;	// 0xd6f1
- (void)trackOperation:(id)operation cancelOnDealloc:(BOOL)dealloc;	// 0xd611
// declared property getter: - (BOOL)shouldInvalidateForMemoryPurge;	// 0xd5cd
- (void)setTitle:(id)title changeTabBarItem:(BOOL)item;	// 0xd535
- (void)setScriptProperties:(id)properties;	// 0xd4f1
- (void)setSection:(id)section;	// 0xd409
// declared property setter: - (void)setLoading:(BOOL)loading;	// 0xd3b1
// declared property setter: - (void)setInputAccessoryViewController:(id)controller;	// 0xd2fd
- (void)reloadContentSizeForViewInPopover;	// 0xd265
- (void)reload;	// 0xd261
- (void)presentFooterViewController:(id)controller animated:(BOOL)animated;	// 0xcf95
- (BOOL)presentDialogForError:(id)error pendUntilVisible:(BOOL)visible;	// 0xcf21
- (BOOL)presentDialog:(id)dialog pendUntilVisible:(BOOL)visible;	// 0xce45
- (id)newRotationController;	// 0xce41
// declared property getter: - (BOOL)isVisibleAndFrontmost;	// 0xcda5
// declared property getter: - (BOOL)isVisible;	// 0xccd1
- (void)invalidateForMemoryPurge;	// 0xcccd
- (void)invalidate;	// 0xcbdd
- (void)handleApplicationURL:(id)url;	// 0xcbd9
- (void)enqueueOperation:(id)operation cancelOnDealloc:(BOOL)dealloc;	// 0xcb8d
- (void)dismissFooterViewControllerAnimated:(BOOL)animated;	// 0xc989
- (void)dismissAfterDialogs;	// 0xc8c1
// declared property getter: - (id)defaultPNGName;	// 0xc8bd
// declared property getter: - (double)defaultPNGExpirationTime;	// 0xc889
- (id)copyScriptProperties;	// 0xc851
- (id)copyDefaultScriptProperties;	// 0xc735
- (void)cancelOperations;	// 0xc571
- (id)copyChildViewControllersForReason:(int)reason;	// 0xc519
- (void)applicationWillEnterForeground;	// 0xc515
- (void)applicationDidEnterBackground;	// 0xc511
- (void)dealloc;	// 0xc111
- (id)initWithSection:(id)section;	// 0xc0dd
- (id)init;	// 0xbf09
@end
