/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

#import <iTunesStoreUI/XXUnknownSuperclass.h>


@interface SUWebThreadMainThreadInvocationRecorder : XXUnknownSuperclass {
}
- (void)invokeInvocation:(id)invocation;	// 0x47299
@end
