/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

#import <RemoteUI/XXUnknownSuperclass.h>

@class UIWebView;

@interface WebContainerView : XXUnknownSuperclass {
	UIWebView *_webView;	// 48 = 0x30
	BOOL _highlighted;	// 52 = 0x34
	BOOL _reallyHighlighted;	// 53 = 0x35
}
@property(retain, nonatomic) UIWebView *webView;	// G=0xa6ad; S=0xcdf1; @synthesize=_webView
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;	// G=0xa69d; S=0xa7dd; @synthesize=_highlighted
- (void)dealloc;	// 0xcdb1
- (void)layoutSubviews;	// 0xc6bd
- (void)_setHighlightedNow;	// 0xce19
// declared property setter: - (void)setHighlighted:(BOOL)highlighted;	// 0xa7dd
// declared property getter: - (BOOL)isHighlighted;	// 0xa69d
// declared property getter: - (id)webView;	// 0xa6ad
// declared property setter: - (void)setWebView:(id)view;	// 0xcdf1
@end
