/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

#import <Celestial/XXUnknownSuperclass.h>

@class NSDictionary;

@interface AVItemErrorLogEventInternal : XXUnknownSuperclass {
	NSDictionary *dict;	// 4 = 0x4
}
@end
