/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <VoiceServices/XXUnknownSuperclass.h>

@class PCPersistentTimer;

@interface VSAssetUpdateListener : XXUnknownSuperclass {
	BOOL _isListening;	// 4 = 0x4
	PCPersistentTimer *_assetCleanupTimer;	// 8 = 0x8
}
+ (id)sharedListener;	// 0x113d9
- (id)init;	// 0x11389
- (id)_initShared;	// 0x1138d
- (void)dealloc;	// 0x11a7d
- (void)_rescheduleAssetCleanup;	// 0x11a09
- (void)startListening;	// 0x1193d
- (void)stopListening;	// 0x11865
- (void)_flushLanguageChanges;	// 0x11751
- (void)_cleanupAssets;	// 0x116f5
- (void)_spokenLanguageChanged:(id)changed;	// 0x11679
- (void)_updateNextCleanupDate;	// 0x115d5
- (void)_scheduleNextCleanupForDate:(id)date;	// 0x1144d
- (void)_cancelAssetCleanupTimer;	// 0x11405
@end
