/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <VoiceServices/VSRecognitionAction.h>

@class NSString, NSAttributedString, NSURL;

@interface VSRecognitionURLAction : VSRecognitionAction {
	NSURL *_url;	// 24 = 0x18
}
@property(retain) id URL;	// G=0xcf69; S=0xcf79; converted property
- (void)dealloc;	// 0xcfc1
- (int)completionType;	// 0xcf65
// converted property setter: - (void)setURL:(id)url;	// 0xcf79
// converted property getter: - (id)URL;	// 0xcf69
- (id)perform;	// 0xd00d
@end
