/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <YouTube/YouTube-Structs.h>
#import <YouTube/XMLSAXHTTPRequest.h>

@class YTVideo, NSMutableURLRequest, NSMutableArray;
@protocol YTCaptionsRequestDelegate;

@interface YTCaptionsRequest : XMLSAXHTTPRequest {
	id<YTCaptionsRequestDelegate> _delegate;	// 148 = 0x94
	BOOL _isLoading;	// 152 = 0x98
	NSMutableArray *_captions;	// 156 = 0x9c
	NSMutableURLRequest *_deferredRequest;	// 160 = 0xa0
	YTVideo *_video;	// 164 = 0xa4
}
@property(readonly, assign) BOOL isLoading;	// G=0x16b59; converted property
@property(readonly, retain) YTVideo *video;	// G=0x16631; converted property
- (void)_requestCaptionsFromURL:(id)url;	// 0x16641
- (id)initRequestingCaptionsForVideo:(id)video withDelegate:(id)delegate;	// 0x16a5d
- (void)_listenForAuthenticationNotifications:(BOOL)authenticationNotifications;	// 0x166e5
- (void)dealloc;	// 0x16e19
// converted property getter: - (id)video;	// 0x16631
- (int)parseData:(id)data;	// 0x16da1
- (void)didParseData;	// 0x16c95
- (void)_didAuthenticate:(id)authenticate;	// 0x16ba9
- (void)_failedToAuthenticate:(id)authenticate;	// 0x167c1
// converted property getter: - (BOOL)isLoading;	// 0x16b59
- (void)loadRequest:(id)request;	// 0x16845
- (void)failWithError:(id)error;	// 0x16919
@end
