/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <YouTube/YTVideoDataSource.h>

@class NSString;

@interface YTSubscriptionsVideoDataSource : YTVideoDataSource {
	NSString *_subscriptionURL;	// 28 = 0x1c
	BOOL _requiresAuth;	// 32 = 0x20
}
- (void)setSubscriptionURL:(id)url requiresAuthentication:(BOOL)authentication;	// 0xc659
- (void)reloadData;	// 0xc6d9
@end
