/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <WebKit/XXUnknownSuperclass.h>
#import <WebKit/WebKit-Structs.h>

@class NSArray, WebResource;

__attribute__((visibility("hidden")))
@interface WebArchivePrivate : XXUnknownSuperclass {
@private
	WebResource *cachedMainResource;	// 4 = 0x4
	NSArray *cachedSubresources;	// 8 = 0x8
	NSArray *cachedSubframeArchives;	// 12 = 0xc
	RefPtr<WebCore::LegacyWebArchive> coreArchive;	// 16 = 0x10
}
+ (void)initialize;	// 0x346fd
- (id)init;	// 0x345a5
- (id)initWithCoreArchive:(PassRefPtr<WebCore::LegacyWebArchive>)coreArchive;	// 0x347cd
- (LegacyWebArchive *)coreArchive;	// 0x34541
- (void)setCoreArchive:(PassRefPtr<WebCore::LegacyWebArchive>)archive;	// 0x34565
- (void)dealloc;	// 0x34735
- (id).cxx_construct;	// 0x34551
- (void).cxx_destruct;	// 0x34701
@end
