/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */




@protocol WebDocumentDOM <NSObject>
- (id)DOMDocument;
- (BOOL)canSaveAsWebArchive;
@end

