/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <WebKit/XXUnknownSuperclass.h>

@class WebGeolocationPositionInternal;

@interface WebGeolocationPosition : XXUnknownSuperclass {
@private
	WebGeolocationPositionInternal *_internal;	// 4 = 0x4
}
- (id)initWithTimestamp:(double)timestamp latitude:(double)latitude longitude:(double)longitude accuracy:(double)accuracy;	// 0x5d575
- (void)dealloc;	// 0x5d5d9
@end
