/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import <WebKit/WebKit-Structs.h>
#import <WebKit/XXUnknownSuperclass.h>
#import <WebKit/WebGeolocation.h>

@class WebGeolocationPrivate;

__attribute__((visibility("hidden")))
@interface WebGeolocation : XXUnknownSuperclass {
@private
	WebGeolocationPrivate *_private;	// 4 = 0x4
}
- (BOOL)shouldClearCache;	// 0x5d4a5
- (void)setIsAllowed:(BOOL)allowed;	// 0x5d559
- (void)dealloc;	// 0x5d4fd
@end

@interface WebGeolocation (WebInternal)
- (id)_initWithWebCoreGeolocation:(Geolocation *)webCoreGeolocation;	// 0x5d4b9
@end
