/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/VisualAlert.framework/VisualAlert
 */

#import <VisualAlert/XXUnknownSuperclass.h>


@interface SBBulletinSoundControllerSafeCategory : XXUnknownSuperclass {
}
- (void)_AX_playSoundForBulletin:(id)bulletin;	// 0x1781
@end
