/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

#import <Notes/Notes-Structs.h>


@class NSNumber, NSManagedObjectModel, NSManagedObjectContext, NSPersistentStoreCoordinator, NSPredicate, CPExclusiveLock, NoteStoreObject, NoteAccountObject, NSMutableDictionary, NSString;

@interface NoteContext : NSObject {
@private
	NSManagedObjectModel *_managedObjectModel;	// 4 = 0x4
	NSManagedObjectContext *_managedObjectContext;	// 8 = 0x8
	NSPersistentStoreCoordinator *_persistentStoreCoordinator;	// 12 = 0xc
	NSPredicate *_searchPredicate;	// 16 = 0x10
	NoteStoreObject *_localStore;	// 20 = 0x14
	NoteAccountObject *_localAccount;	// 24 = 0x18
	CXIndexRef __SharedNoteStoreSearchIndex;	// 28 = 0x1c
	CPExclusiveLock *__SharedNoteStoreSearchIndexLock;	// 32 = 0x20
	int __SharedNoteStoreSearchIndexCount;	// 36 = 0x24
	BOOL _isIndexing;	// 40 = 0x28
	NSManagedObjectContext *_nextIdContext;	// 44 = 0x2c
	CPExclusiveLock *_nextIdLock;	// 48 = 0x30
	NSNumber *_nextId;	// 52 = 0x34
	CPExclusiveLock *_objectCreationLock;	// 56 = 0x38
	unsigned _notificationCount;	// 60 = 0x3c
	BOOL _logChanges;	// 64 = 0x40
	BOOL _indexInBatches;	// 65 = 0x41
	BOOL _hasPriorityInSaveConflicts;	// 66 = 0x42
	BOOL _inMigrator;	// 67 = 0x43
	NSString *_testingFilePrefix;	// 68 = 0x44
	NSString *_testingFilePath;	// 72 = 0x48
	NSMutableDictionary *_notePropertyObjectsRealized;	// 76 = 0x4c
}
@property(readonly, assign, nonatomic) NSManagedObjectContext *managedObjectContext;	// G=0x750d; 
@property(readonly, assign, nonatomic) BOOL isIndexing;	// G=0xaef5; @synthesize=_isIndexing
@property(readonly, retain) NSManagedObjectModel *managedObjectModel;	// G=0x7621; converted property
@property(readonly, retain) NSPersistentStoreCoordinator *persistentStoreCoordinator;	// G=0x7719; converted property
@property(readonly, retain) NoteStoreObject *localStore;	// G=0x53ed; converted property
@property(readonly, retain) NoteAccountObject *localAccount;	// G=0x5455; converted property
+ (BOOL)databaseIsCorrupt:(id)corrupt;	// 0x14f9
+ (BOOL)shouldLogIndexing;	// 0x1489
// declared property getter: - (BOOL)isIndexing;	// 0xaef5
/* iOSOpenDev: commented-out (since bad name)
- (void).cxx_destruct;	// 0xaf05
*/
- (BOOL)deleteIndexFile;	// 0xae89
- (BOOL)noteIsSafeToAccess:(id)access;	// 0xad2d
- (void)cleanUpLocks;	// 0xacdd
- (id)findNotesWithText:(id)text betweenDate:(id)date andDate:(id)date3;	// 0xa865
- (id)copyNotesForSearch:(void *)search predicate:(id)predicate complete:(char *)complete;	// 0xa5c9
- (id)copyNotesForSearch:(void *)search complete:(char *)complete;	// 0xa5a9
- (void *)newSearchContextWithText:(id)text;	// 0xa545
- (void)trackChanges:(id)changes;	// 0x975d
- (id)noteChangeWithType:(int)type store:(id)store;	// 0x95f1
- (void)updateSearchIndex:(id)index;	// 0x8c69
- (void)resetNotificationCount;	// 0x8c55
- (void)receiveDarwinNotificationWithChangeLogging:(BOOL)changeLogging;	// 0x8b79
- (void)indexInBatches:(BOOL)batches;	// 0x8b69
- (void)resumeIndexing;	// 0x8a69
- (void)wrapUpIndexing;	// 0x8821
- (void)destroySearchIndex;	// 0x878d
- (CXIndexRef)searchIndex:(char *)index;	// 0x8315
- (void)indexNotes:(id)notes;	// 0x7d35
- (id)notesToResumeIndexing;	// 0x7c69
- (BOOL)shouldResumeIndexing;	// 0x7c05
- (void)saveNotesToResumeIndexing:(id)resumeIndexing;	// 0x7a65
// converted property getter: - (id)persistentStoreCoordinator;	// 0x7719
// converted property getter: - (id)managedObjectModel;	// 0x7621
// declared property getter: - (id)managedObjectContext;	// 0x750d
- (void)setHasPriorityInSaveConflicts:(BOOL)saveConflicts;	// 0x7471
- (id)urlForPersistentStore;	// 0x741d
- (id)pathForIndex;	// 0x733d
- (id)pathForPersistentStore;	// 0x725d
- (id)rootDirectory;	// 0x723d
- (id)nextIndex;	// 0x6e75
- (id)getNextIdObject;	// 0x690d
- (void)handleMigration;	// 0x5de9
- (id)propertyValueForKey:(id)key;	// 0x5da1
- (void)setPropertyValue:(id)value forKey:(id)key;	// 0x5c99
- (id)_notePropertyObjectForKey:(id)key;	// 0x59e9
- (BOOL)hasMultipleEnabledStores;	// 0x5985
- (BOOL)shouldDisableLocalStore;	// 0x5925
- (BOOL)deleteStore:(id)store;	// 0x57e9
- (BOOL)deleteAccount:(id)account;	// 0x578d
- (BOOL)forceDeleteAccount:(id)account;	// 0x567d
// converted property getter: - (id)localAccount;	// 0x5455
// converted property getter: - (id)localStore;	// 0x53ed
- (id)defaultStoreForNewNote;	// 0x52dd
- (id)accountForAccountId:(id)accountId;	// 0x5085
- (id)newlyAddedAccount;	// 0x5025
- (id)allAccounts;	// 0x4df9
- (unsigned)countOfStores;	// 0x4c75
- (id)allStores;	// 0x4a49
- (id)newlyAddedStore;	// 0x49e9
- (id)collectionForInfo:(id)info;	// 0x48bd
- (id)allNotesWithoutBodiesInCollection:(id)collection;	// 0x47cd
- (id)notesForIntegerIds:(id)integerIds;	// 0x46b5
- (id)noteForObjectID:(id)objectID;	// 0x464d
- (unsigned)countOfNotesMatchingPredicate:(id)notesMatchingPredicate;	// 0x45cd
- (id)allNotesMatchingPredicate:(id)predicate;	// 0x4541
- (unsigned)countOfNotesInCollection:(id)collection;	// 0x4501
- (id)allNotesInCollection:(id)collection;	// 0x44b5
- (unsigned)countOfNotes;	// 0x4459
- (id)allNotes;	// 0x43f1
- (id)visibleNotesForIntegerIds:(id)integerIds;	// 0x4255
- (id)visibleNoteForObjectID:(id)objectID;	// 0x4179
- (unsigned)countOfVisibleNotesMatchingPredicate:(id)visibleNotesMatchingPredicate;	// 0x4041
- (id)allVisibleNotesMatchingPredicate:(id)predicate;	// 0x3efd
- (unsigned)countOfVisibleNotesInCollection:(id)collection;	// 0x3ebd
- (id)allVisibleNotesInCollection:(id)collection;	// 0x3e71
- (unsigned)countOfVisibleNotes;	// 0x3e5d
- (id)allVisibleNotes;	// 0x3e49
- (BOOL)saveSilently:(id *)silently;	// 0x3d1d
- (BOOL)handleSaveErrors:(id)errors;	// 0x3915
- (BOOL)save:(id *)save;	// 0x382d
- (BOOL)saveOutsideApp:(id *)app;	// 0x3815
- (void)invalidate;	// 0x3799
- (void)enableChangeLogging:(BOOL)logging;	// 0x3789
- (void)deleteChanges:(id)changes;	// 0x36b1
- (void)deleteNoteRegardlessOfConstraints:(id)constraints;	// 0x3661
- (void)deleteNote:(id)note;	// 0x3471
- (id)storeForObjectID:(id)objectID;	// 0x3409
- (id)collectionForObjectID:(id)objectID;	// 0x33a1
- (id)newlyAddedNote;	// 0x32ad
- (void)sortNotes:(id)notes;	// 0x3209
- (void)clearCaches;	// 0x31e9
- (id)newFetchRequestForNotes;	// 0x30bd
- (id)newFRCForCollection:(id)collection delegate:(id)delegate;	// 0x2df5
- (id)liveNotesNeedingBodiesPredicate;	// 0x2d89
- (id)visibleNotesPredicate;	// 0x2cf5
- (void)dealloc;	// 0x2cb5
- (id)init;	// 0x2c8d
- (id)initWithTestingFilePrefix:(id)testingFilePrefix atPath:(id)path inMigrator:(BOOL)migrator;	// 0x2aad
- (id)initWithTestingFilePrefix:(id)testingFilePrefix;	// 0x2a85
- (id)initForMigrator;	// 0x2a59
- (id)initWithTestingFilePrefix:(id)testingFilePrefix inMigrator:(BOOL)migrator;	// 0x2a29
- (void)tearDownCoreDataStack;	// 0x2945
- (void)setUpCoreDataStack;	// 0x2775
- (void)removeConflictingSqliteAndIdxFiles;	// 0x268d
- (void)removeSqliteAndIdxFiles;	// 0x24bd
- (void)setUpUniqueObjects;	// 0x2025
- (void)forceSetUpUniqueObjects;	// 0x1f05
- (BOOL)setUpLastIndexTid;	// 0x1b79
- (BOOL)setUpLocalAccountAndStore;	// 0x17e9
- (void)_createLocalAccount:(id *)account andStore:(id *)store;	// 0x16d9
- (id)storeOptions;	// 0x15e9
@end
