/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
 */

#ifndef __IONotificationPortRef__
#define __IONotificationPortRef__ 1
typedef struct IONotificationPort *IONotificationPortRef;
#endif


